RasaHQ/rasa

- src/training_data.py
- added section for common examples into json format, allows to define samples to be used for both, intent classification and entity recognition.
> Allow user to define common samples in json example

- .travis.yml
- _pytest/test_featurizers.py
- _pytest/test_tokenizers.py
- _pytest/trainers/test_mitie_trainer.py
- requirements.txt
- src/train.py
- src/trainers/__init__.py
- src/trainers/mitie_trainer.py
- src/trainers/spacy_sklearn_trainer.py
- src/trainers/trainer.py
- src/util.py
- added tests for supported language using spacy
- test mitie rejects invalid language parameters
TODO:
- update spacy vectors in tests
> Multi lang test improvements

- _pytest/test_interpreter.py
- src/interpreters/simple_interpreter.py
- src/server.py
> issues 24 and 20

- _pytest/test_tokenizers.py
- data/demo-restaurants.json
- src/emulators/api.py
- src/tokenizers/spacy_tokenizer.py
- src/training_data.py
> unicode api.ai

- data/examples/luis/demo-restaurants.json
- data/examples/rasa/demo-rasa.json
- src/visualization/__init__.py
> visualizer groups examples by intent

- README.md
- src/visualization/__init__.py
> visualize overlapping entities

- setup.py
- src/featurizers/mitie_featurizer.py
- src/trainers/mitie_trainer.py
> conditional import of numpy

- README.md
- _pytest/test_config.py
- setup.cfg
- src/classifiers/sklearn_intent_classifier.py
- src/config.py
- src/emulators/wit.py
- src/featurizers/mitie_featurizer.py
- src/persistor.py
- src/server.py
- src/train.py
- src/trainers/mitie_sklearn_trainer.py
- src/trainers/mitie_trainer.py
- src/visualize.py
replace `print()` calls with calls to logger. Add two config params for setting logfile (default None, e.g. stdout) and loglevel (default INFO)
> use python logger

- Dockerfile
- LICENSE.txt
- README.md
- docker-cloud.yml
- entrypoint.sh
- requirements.txt
- setup.py
- src/download.py
- src/featurizers/mitie_featurizer.py
1. build the image or pull it from Docker Hub.
a. use the image you can find from docker Hub: `docker pull rasa/rasa_nlu`
b. build the image from this repository `docker build -t rasa/rasa_nlu .`
2. choose to download either spacy (en/de) or mitie:
```
docker run --rm -it \
-v "${PWD}/rasa-docker/config:/config" \
-v "${PWD}/rasa-docker/data/mitie:/app/data" \
-v "${PWD}/rasa-docker/data/spacy:/usr/local/lib/python2.7/site-packages/spacy/data" \
rasa/rasa_nlu download spacy en
```
```
docker run --rm -it \
-v "${PWD}/rasa-docker/config:/config" \
-v "${PWD}/rasa-docker/data/mitie:/app/data" \
-v "${PWD}/rasa-docker/data/spacy:/usr/local/lib/python2.7/site-packages/spacy/data" \
rasa/rasa_nlu download mitie
```
3. Run it! (replace --rm with -d for detached mode)
```
docker run --rm -it \ …
```
> rasa-docker

- README.md
Hi there,
A first pull request to update the readme.md.
Goals:
* Clarify the intent of the library.
* Add simple installation explanation both locally and through docker.
> Updated readme to clarify intent and installation steps

- README.md
- docs/index.rst
- docs/python.rst
> fix to docs & readme

- src/trainers/training_utils.py
> bugfix: corrected name of language field in model metadata

- src/trainers/spacy_sklearn_trainer.py
Small fix to
- fix external persistence (used wrong var name)
- allow models to be stored in the passed path without the creation of a unique sub directory
> Aadd parameter to allow the model to be stored in the same folder

- _pytest/test_emulators.py
- _pytest/test_interpreter.py
- _pytest/test_server.py
- docs/migrating.rst
- docs/tutorial.rst
- setup.py
- src/classifiers/sklearn_intent_classifier.py
- src/emulators/luis.py
- src/emulators/wit.py
- src/interpreters/mitie_interpreter.py
- src/interpreters/mitie_sklearn_interpreter.py
- src/interpreters/simple_interpreter.py
- src/interpreters/spacy_sklearn_interpreter.py
- src/trainers/spacy_sklearn_trainer.py
- added confidence for mitie and spacy
- corrected missing `text` attribute in simple interpreter
- spacy classifier can also be trained without probabilities in which case the resulting intents will get a uniform probability assigned
- related to #64
TODO: double check that loading previously trained spacy models still works (change might break loading dumped spacy classifiers)
> Added confidence of intent classification to result

- src/trainers/mitie_trainer.py
Before: If the start and stop location of an entity are wrong, the training aborts with a meaningless index exception.
After: Invalid entity examples are ignored, a warning is echoed to inform about invalid start / end indices.
> Don't fail if an entity can not be found, echo warning instead

- src/server.py
- src/training_data.py
- src/util.py
- Post warning if default interpreter is used instead of specified one
- error if no training data is specified
> Added error / warn messages if wrong configuration is provided

- src/training_data.py
small fix concerning logging of non ascii examples
> Fixed small encoding issue on warning logging

- src/server.py
> fixed merge issue starting training twice #130

- .gitignore
- src/data_router.py
- src/interpreters/mitie_interpreter.py
Share the same feature extractor between interpreters
> Multitenancy

- _pytest/test_interpreter.py
- _pytest/test_synonyms.py
- _pytest/test_train.py
- _pytest/utilities.py
- data/examples/wit/demo-flights.json
- src/trainers/__init__.py
- src/trainers/sklearn_trainer_utils.py
> Added more tests

- _pytest/test_config.py
- rasa_nlu/components.py
- rasa_nlu/config.py
- raise proper exception if json can not be read from configuration file
- added test to check exception is in fact raised
> Improved error handling

- _pytest/test_server.py
- rasa_nlu/model.py
> Return default output when parsing an empty text

- CHANGELOG.rst
- config_defaults.json
- docs/config.rst
- docs/pipeline.rst
- rasa_nlu/config.py
- rasa_nlu/extractors/duckling_extractor.py
- rasa_nlu/registry.py
- requirements.txt
- adds duckling support to pipelines (found entities will be normalized (e.g. dates or numbers) if they are found as an entity)
- new config value `duckling_processing_mode` (either duckling entities `replace` only value of already found entities or new entities only found by duckling will be `append`ed to the list returned entities)
**Status**:
> Duckling Component

- data/examples/rasa/demo-rasa.json
- rasa_nlu/classifiers/sklearn_intent_classifier.py
- removed duplicates from rasa example training data
- added some more examples
- changed calculation of sklearn folds (won't matter for training sets with >25 examples per intent, for smaller datasets we will now choose fewer folds to avoid sklearn warnings)
- fixes #288 
**Status**:
> removed duplicated training samples, fixed fold calculation

- README.md
> Minor README update: remember to pip install, #295

- rasa_nlu/featurizers/ngram_featurizer.py
- added max_ngrams parameter to _create_bow_vecs in the train function
**Status**:
> bug fix on training

- _pytest/utilities.py
- dev-requirements.txt
- rasa_nlu/extractors/crf_entity_extractor.py
- rasa_nlu/train.py
- requirements.txt
- properly persist CRF model (fixes unicode issues). fixes #307 
- properly predict during parse
**Status**:
> Fixed CRF persistence

- rasa_nlu/server.py
- removed auth from the main route to allow health checks
**Status**:
> default route requires no auth

- docs/http.rst
- rasa_nlu/version.py
- rasa_nlu/wsgi.py
- provide proper app object when running on gunicorn
**Status**:
> Fix failure to run rasa on gunicorn

- _pytest/test_training_data.py
- data/examples/luis/demo-restaurants.json
- rasa_nlu/converters.py
> updated luis example data with new format

- docs/entities.rst
- docs/http.rst
- docs/index.rst
> Entity docs

- rasa_nlu/extractors/entity_synonyms.py
- rasa_nlu/train.py
> for entity synonyms, keys should be lowercased, values not

- rasa_nlu/extractors/spacy_entity_extractor.py
- Minor change to enhance the error message when using a SpaCy model without a POS tagger properly trained.
**Status**:
> Enhanced error msg when using a model with POS tagger not trained

- _pytest/test_server.py
- docs/http.rst
- rasa_nlu/server.py
See issue #334 
Adds additional API endpoints: 
Rasa version
Current loaded configuration
Server log
The root response now includes the rasa version (rather than just hello)
**Status**:
> Add additional API endpoints, issue #334

- docs/dataformat.rst
- docs/entities.rst
- Updating training data and entity docs
**Status**:
> Update Training and Entity Docs

- rasa_nlu/model.py
- rasa_nlu/utils/__init__.py
- setup.cfg
- Don't fail training if persistence directory already exists
**Status**:
> Don't fail training if persistence directory already exists

- CHANGELOG.rst
- rasa_nlu/data_router.py
- status endpoint shows all models instead of only those starting with *model*
**Status**:
> status endpoint showing all models

- rasa_nlu/registry.py
Pull request referenced to issue #383 
Minor typo in rasa_nlu/registry.py
> typo in rasa_nlu/registry.py fixed

- .travis.yml
- CHANGELOG.rst
- README.md
- app.json
- docs/contribute.rst
- docs/faq.rst
- docs/index.rst
- docs/installation.rst
- docs/tutorial.rst
- setup.py
- Renamed occurrences of golastmile to rasahq 
**Status**:
> Renamed occurrences of golastmile to rasahq

- CHANGELOG.rst
- data/examples/rasa/demo-rasa.json
- dev-requirements.txt
- docs/entities.rst
- rasa_nlu/extractors/crf_entity_extractor.py
- rasa_nlu/version.py
- due to incompatibilities - due to temporary file creation - `python-crfsuite` doesn't work to well with windows
- allows to use grid optimization of features now (haven't added it - should check with a large dataset first how much of a time tradeoff that is)
- fixes #357
**Status**:
> Replace python-crfsuite with sklearn-crfsuite

- docs/python.rst
added example training code using ComponentBuilder
> Update rasa_nlu from Python doc

- rasa_nlu/data_router.py
Adding some necessary logging content: see  #335 
- Extended the logged object by adding timestamp and model information
**Status**:
> Added timestamp and model alias to logging

- rasa_nlu/extractors/duckling_extractor.py
return the full duckling JSON information
> Duckling JSON output

- .gitignore
- CHANGELOG.rst
- rasa_nlu/__init__.py
- rasa_nlu/classifiers/sklearn_intent_classifier.py
- rasa_nlu/components.py
- rasa_nlu/config.py
- rasa_nlu/converters.py
- rasa_nlu/data_router.py
- rasa_nlu/download.py
- rasa_nlu/emulators/api.py
- rasa_nlu/extractors/__init__.py
- rasa_nlu/extractors/crf_entity_extractor.py
- rasa_nlu/extractors/duckling_extractor.py
- rasa_nlu/extractors/spacy_entity_extractor.py
- rasa_nlu/featurizers/mitie_featurizer.py
- rasa_nlu/featurizers/ngram_featurizer.py
- rasa_nlu/model.py
- rasa_nlu/persistor.py
- rasa_nlu/server.py
- rasa_nlu/train.py
- rasa_nlu/training_data.py
- rasa_nlu/utils/mitie_utils.py
- rasa_nlu/utils/spacy_utils.py
- rasa_nlu/wsgi.py
- proper instantiation of logger objects where needed (instead of using the root logger)
- some type fixes
**Status**:
> Proper logging

- CHANGELOG.rst
- rasa_nlu/classifiers/sklearn_intent_classifier.py
- rasa_nlu/featurizers/ngram_featurizer.py
- weight examples based on class balance during SVM / linear model training in crf and sklearn intent classifier
**Status**:
> Train models weighted

- docs/installation.rst
fixing rst
test
**Proposed changes**: 
- add explicit install of sklearn-crfsuite ( see issue #442 )
**Status**:
> add sklearn-crfsuite install instructions

- rasa_nlu/components.py
- rasa_nlu/model.py
- allow a component to cal the processing pipeline during training (e.g. to process external examples).
**Status**:
> Partial processing

- docs/faq.rst
Changed the gitter link from ```https://gitter.im/golastmile/rasa_nlu``` to ```https://gitter.im/RasaHQ/rasa_nlu``` in faq.rst in reference to issue #396
> gitter link changes in docs/faq.rst

- docs/config.rst
- docs/contribute.rst
- docs/http.rst
- docs/installation.rst
Many thanks for putting this together.
- Fix config's duckling_dimensions example
- Use public URL to clone repo
- Fix some rst formatting
**Status**:
> Fix some docs examples and formatting

- CHANGELOG.rst
- _pytest/test_sanity.py
- rasa_nlu/model.py
- rasa_nlu/training_data.py
- Properly persist training data (fixes #510)
**Status**:
> Fixed training data persistence

- setup.py
- print welcome message after install
**Status**:
> print welcome message after pip install

- CHANGELOG.rst
- _pytest/utilities.py
- docs/python.rst
- rasa_nlu/data_router.py
- rasa_nlu/evaluate.py
- rasa_nlu/model.py
- simplifies interpreter loading by passing the model directory directly to the interpreter
**Status**:
> Improvements to interpreter creation

- README.md
see https://github.com/RasaHQ/rasa_nlu/issues/575
It looks like the following is not working:
```
curl 'https://raw.githubusercontent.com/RasaHQ/rasa_nlu/master/data/examples/rasa/demo-rasa.md'
curl --request POST --data-binary @demo-rasa.md --url localhost:5000/train?name=test_model
```
- ...
**Status**:
> Add Post /train with markdown example

- .gitignore
- README.md
- app.json
- docker/Dockerfile_bare
- docker/Dockerfile_full
- docker/Dockerfile_mitie
- docker/Dockerfile_spacy_sklearn
- docker/Dockerfile_test
- docker/docker-cloud.yml
- docs/config.rst
- docs/python.rst
- docs/tutorial.rst
- rasa_nlu/config.py
- sample_configs/config_crf.json
- sample_configs/config_defaults.json
- sample_configs/config_mitie.json
- sample_configs/config_mitie_sklearn.json
- sample_configs/config_spacy.json
- sample_configs/config_spacy_duckling.json
- tests/base/test_server.py
- Renamed default model folder from `./models` to `./projects`
- Fixes #595
> Renamed models occurrences to projects

- CHANGELOG.rst
- docs/migrations.rst
- rasa_nlu/model.py
- rasa_nlu/persistor.py
- rasa_nlu/project.py
- rasa_nlu/train.py
- Adapted persistor to work with projects
> Adapted persistor to work with projects

- Makefile
- docs/_templates/layout.html
- docs/installation.rst
- setup.py
- added ga tags
- added makefile
- fixed setup py strings
> added ga and minor setup improvements

- docs/tutorial.rst
just working through the tutorial i noticed that with the given query, no entities are found. since "italian food" is used in the tests, i figured that it will do the trick.
> wont work without food

- rasa_nlu/config.py
- rasa_nlu/converters.py
- rasa_nlu/evaluate.py
- rasa_nlu/featurizers/ngram_featurizer.py
- rasa_nlu/featurizers/spacy_featurizer.py
- tests/base/test_featurizers.py
- some code cleanups ported from an obsolete branch
> Minor code cleanups

- rasa_nlu/config.py
- rasa_nlu/extractors/duckling_http_extractor.py
- rasa_nlu/model.py
- rasa_nlu/registry.py
- rasa_nlu/utils/__init__.py
- sample_configs/config_defaults.json
- can only handle the "new" duckling (so the haskell version, NOT the clojure one)
- needs docs - but lets first decide if we add it this way
> Added component to connect to a running duckling server

- docker/Dockerfile_full
- docker/Dockerfile_mitie
- docker/Dockerfile_spacy_sklearn
- docker/Dockerfile_test
- fix java install in dockerfiles
> Java dockerhub build

- docs/dataformat.rst
Adding a note that entity_synonyms doesn't impact classification.
Docs only change
> Add entity synonym note

- rasa_nlu/training_data.py
- add validation for empty intent - closes #695 
> added validation for empty intent

- rasa_nlu/data_router.py
- Fixed emulation command for dialogflow not working
> Fixed dialogflow emulation command not working

- docs/pipeline.rst
Just popping in to fix a repeated word in the docs.
> Fix repeated word in documentation

- cloudbuild.yaml
- add cloudbild to build main container on google container engine
> Lucid ntr cloudbuild

- rasa_nlu/utils/md_to_json.py
Fixes the bugs left unfixed in #726 
- Change the regex for Markdown comments to ''
- Use raw strings in all regex
- Support multi-line and in-line comments
- Read the file first, removing comments and splitting into lines
- Also strip extra-whitespace which might have been introduced due to comments
Will add tests in a couple of days
> Fixes the bugs unfixed in PR #726

- README.md
- I update the README file to include more instructions on how ton install the dev requirements for NLU.
Not applicable:
> Updated Readme to Include Dev Installation Instructions

- rasa_nlu/server.py
- I noticed in my json pull request there was this one odd change to the server.py. Removed it again
> Removed odd change

- docs/faq.rst
- docs/tutorial.rst
added an faq to address the how much data question. 
Fixes #780
> How much data

- alt_requirements/requirements_dev.txt
- alt_requirements/requirements_spacy_sklearn.txt
- Update spacy to 1.9.0 which fixes an issue occurring with several languages: https://github.com/explosion/spaCy/issues/1052
> Spacy update to 1.9.0

- docs/dataformat.rst
- Chatito is a simple tool that is compatible with rasa dataset format. https://github.com/rodrigopivi/Chatito
> Link a dataset generator compatible with RASA

- rasa_nlu/extractors/crf_entity_extractor.py
* allow ner_crf to use variable feature spans. Instead of just using the token to the left and right, we might also want to allow to use the second or third token to the left and right.
* added word1 function, which makes sense for Chinese where the average word is only two characters long and the last token of a word sometimes can indicate certain characteristics of that word.
Any thoughts or improvements? :-) 
> allow crf to use flexible field width

- CHANGELOG.rst
- docs/evaluation.rst
- rasa_nlu/evaluate.py
- tests/evaluation.py
- ...
apologies for the inconvenience. We can delete the other request.
> update docs, add crossvalidation to evaluation script

- docs/evaluation.rst
- docs/tutorial.rst
- in docs/tutorial.rst changed the phrase for running the model to "I am looking for Mexican food", which produces better results. Left the old phrase in the note with some explanation
- changed the output of applying mitie pipeline to a correct one
- in docs/evaluation.rst fixed the typo
> Fixed docs according to issue #800

- rasa_nlu/data_router.py
- ... _list_projects(path) method will return project names instead of absolute path of projects.
> fix #788 Project not found error while searching for project

- setup.py
- added the new training data packages to `setup.py` ... Ran into the problem that they were not included when I used pip to install a github branch version. Might give other people problems too!
> TIME-SENSITIVE: added training_data packages to setup.py

- rasa_nlu/evaluate.py
- tests/evaluation.py
**Proposed Changes**
- fixes issue #814 
supersedes PR #817 
manually tested the functionality for now - enabling the test suite would require more changes, coming in the next PR
> label O to no_entity on output

- rasa_nlu/extractors/crf_entity_extractor.py
- rasa_nlu/training_data/formats/rasa.py
- rasa_nlu/training_data/message.py
- previously the crf was trained on all examples, recent changes to the data loading led to the crf being trained on positive examples only. fixed by explicitly using all examples.
> train crf on all data

- rasa_nlu/classifiers/mitie_intent_classifier.py
- rasa_nlu/classifiers/sklearn_intent_classifier.py
- rasa_nlu/utils/mitie_utils.py
- rasa_nlu/utils/spacy_utils.py
Changed components `load` method to allow easy inheritance using the `cls` argument from the object instead of hardcoded class names.
> Using cls argument on component loading to avoid inheritance issues

- CHANGELOG.rst
- data/test/markdown_single_sections/regex_only.md
- data/test/markdown_single_sections/synonyms_only.md
- rasa_nlu/training_data/loading.py
- tests/base/test_training_data.py
- minor refactoring: introduced reader factory
- made markdown loading heuristic more robust, supporting files that only contain synonyms or regex features
> Reader factory

- rasa_nlu/extractors/spacy_entity_extractor.py
- rasa_nlu/utils/spacy_utils.py
- tests/base/test_extractors.py
- spacy NER needs capitalization --> can't use doc generated by spacy component as we lower case words there
> fixed capitalization issues during spacy NER

- rasa_nlu/components.py
- rasa_nlu/config.py
- rasa_nlu/extractors/duckling_extractor.py
- rasa_nlu/extractors/duckling_http_extractor.py
- rasa_nlu/extractors/entity_synonyms.py
- rasa_nlu/featurizers/regex_featurizer.py
- rasa_nlu/model.py
- rasa_nlu/utils/__init__.py
- tests/base/test_server.py
- fixed sig issues and unified file loading
> fixed sig issues and unified file loading

- docs/_static/css/custom.css
- docs/_static/css/rasa_theme.css
- docs/poll.html
- docs/tutorial.rst
> tutorial polling for nlu docs

- .travis.yml
- Makefile
- rasa_nlu/extractors/duckling_extractor.py
- rasa_nlu/run.py
- setup.py
- added a small script to load a model to test it on the command line
> Added run script and changed setup

- .gitignore
- .travis.yml
- alt_requirements/requirements_dev.txt
- rasa_nlu/persistor.py
- tests/base/test_config.py
- tests/base/test_data_router.py
- tests/base/test_emulators.py
- tests/base/test_extractors.py
- tests/base/test_featurizers.py
- tests/base/test_interpreter.py
- tests/base/test_multitenancy.py
- tests/base/test_persistor.py
- tests/base/test_project.py
- tests/base/test_server.py
- tests/base/test_synonyms.py
- tests/base/test_tokenizers.py
- tests/base/test_training_data.py
- tests/base/test_utils.py
- use moto mocking for s3 persistor tests
> cleaned up tests and used moto mocking for s3

- docs/community.rst
- docs/index.rst
- Adding a page to the docs for sharing customer written documentation
> Create community.rst for sharing community docs and software for Rasa NLU

- CHANGELOG.rst
- rasa_nlu/data_router.py
- rasa_nlu/project.py
- rasa_nlu/training_data/loading.py
- rasa_nlu/utils/__init__.py
- tests/base/test_utils.py
- Ignore hidden files when loading training data
> Ignore hidden files when loading training data

- docs/_templates/layout.html
> support script

- docs/dataformat.rst
Since I have worked on a side project to ease the creation of training datasets, I want to share it with the community and as so, added a link in the rasa's documentation.
- Added [Tracy](https://github.com/YuukanOO/tracy) as a tool to generate datasets in `dataformat.rst`
> Added Tracy as a tool to generate datasets

- README.md
> update README urls

- .travis.yml
- CHANGELOG.rst
- README.md
- rasa_nlu/data_router.py
- rasa_nlu/project.py
- rasa_nlu/server.py
- tests/base/test_multitenancy.py
- tests/base/test_server.py
> Config enhancements merge master

- alt_requirements/requirements_bare.txt
- new yaml config requires pyyaml but that's not in the requirements
> add pyyaml requirement

- setup.py
> add pyyaml to setup.py

- rasa_nlu/train.py
> fix exception raising - project no longer part of config

- rasa_nlu/run.py
- Add the missing loglevel argument to run.py
> added loglevel arg

- CHANGELOG.rst
- alt_requirements/requirements_full.txt
- alt_requirements/requirements_tensorflow_sklearn.txt
- docs/pipeline.rst
- rasa_nlu/classifiers/embedding_intent_classifier.py
- rasa_nlu/featurizers/count_vectors_featurizer.py
- rasa_nlu/featurizers/ngram_featurizer.py
- rasa_nlu/registry.py
- sample_configs/config_embedding.yml
- tests/base/test_featurizers.py
- add count vectors featurizer
- add embedding intent classifier
> Add emebedding classifier to rasa nlu

- rasa_nlu/classifiers/embedding_intent_classifier.py
- import tensorflow globally but with `try` statement:
```
try:
import tensorflow as tf
except ImportError:
logger.debug("No module named tensorflow")
```
> import tensorflow with try statement

- rasa_nlu/extractors/crf_entity_extractor.py
> train ner_crf on all examples

- rasa_nlu/classifiers/embedding_intent_classifier.py
- reset tf.Graph in train method
> FIX: reset tf.Graph in train method

- alt_requirements/requirements_bare.txt
- docker/Dockerfile_full
- docker/Dockerfile_spacy_sklearn
Added path to Docker commands. Temporarily added Tensorflow to basic requirements.
@tmbo NLU is failing to install for me, asking for Tensorflow, even when I am not using the tensor flow pipeline. I've temporarily added Tensorflow to the base requirements, but can merge in a real fix if you can point me to it.
- Add `, "--path", "/app/projects/"` to the Docker commands for spacy and full.
> Fix Docker Builds

- rasa_nlu/classifiers/embedding_intent_classifier.py
> Cosmetic changes: added types

- rasa_nlu/classifiers/embedding_intent_classifier.py
- actually load persisted config of tf embedding classifier
> fix loading of tf embed classifier

- CHANGELOG.rst
- rasa_nlu/data_router.py
- rasa_nlu/server.py
- Fix data router not taking values from arguments
- Fix json log generation without record separator
Issue #954 #952 #939
> Fix data_router to support storage and emulate through args

- CHANGELOG.rst
- rasa_nlu/server.py
- Make the `/evaluate` endpoint asynchronous
> Asynchronous /evaluate endpoint

- docs/languages.rst
> add comment about more languages

- .travis.yml
- rasa_nlu/version.py
- setup.cfg
- setup.py
- distribute packages as wheels as well as source distributions
- optimize for new pypi.org (markdown readme, classifiers, project links)
TODO:
- change .travis.yml from test to prod pypi & build from master 
> Wheel & pypi.org

- rasa_nlu/persistor.py
> properly use temp dir in persistor. fixes #991

- docs/config.rst
- docs/migrations.rst
- docs/pipeline.rst
- sample_configs/config_crf.yml
- some fixes around configuration and docs
> some doc fixes around configuration

- rasa_nlu/classifiers/embedding_intent_classifier.py
- use comprehentions for dict creation
> use comprehentions for dict creation

- README.md
> update comment about language support in README

- rasa_nlu/train.py
- sample_configs/config_jieba_mitie_sklearn.yml
- set default value of `num_threads` to 1 (from None)
- fix incorrect settings in `config_jieba_mitie_sklearn.yml`
This PR try to fix #1024 
> bugfix for Chinese pipeline related issues

- rasa_nlu/model.py
- tests/base/test_interpreter.py
- fix typo: `UnsuportedModelError` => `UnsupportedModelError`
> fix typo: UnsuportedModelError => UnsupportedModelError

- docs/community.rst
> Add Articulate to Community Software

- README.md
- Fixed a broken link in readme
> fix broken md link

- docs/python.rst
> remove non essential import

- CHANGELOG.rst
- docs/community.rst
> Doc link for Rasa NLU in Chinese

- docs/conf.py
- Update copyright year from 2017 to 2018
> Update copyright year in documentation

- rasa_nlu/train.py
- fixes #1101 
- model now gets saved to default location if no output path is provided
> add default path

- CHANGELOG.rst
- docs/pipeline.rst
- rasa_nlu/featurizers/count_vectors_featurizer.py
- tests/base/test_featurizers.py
- `count_vectors_featurizer` will looking for `tokens` for getting message text
> New feature: component `count_vectors_featurizer` can use `tokens` provide by tokenizers

- .travis.yml
- better YAML style for reading and maintenance
> Better YAML code style for .travis.yml

- CHANGELOG.rst
- docs/pipeline.rst
- rasa_nlu/classifiers/embedding_intent_classifier.py
- rasa_nlu/classifiers/sklearn_intent_classifier.py
- rasa_nlu/evaluate.py
- rasa_nlu/featurizers/count_vectors_featurizer.py
- rasa_nlu/featurizers/regex_featurizer.py
- rasa_nlu/model.py
- tests/base/test_featurizers.py
- tests/base/test_server.py
- visualize training progress with tqdm
- persist learned embedding tensors (**breaking compatibility**)
- predict empty intent with 0 confidence, if all of words have never been seen during training
- do not override completely `text_features` in `intent_featurizer_count_vectors`
- add basic OOV support to `intent_featurizer_count_vectors` (**breaking compatibility**)
> Update tensorflow pipeline, add basic OOV handling

- docs/http.rst
- rasa_nlu/training_data/formats/rasa.py
Update link to documentation that was broken,
> Documentation updates for Incorrect formats and HTTP requests.

- CHANGELOG.rst
- docs/dataformat.rst
- docs/pipeline.rst
- rasa_nlu/extractors/crf_entity_extractor.py
- rasa_nlu/featurizers/regex_featurizer.py
- rasa_nlu/model.py
- rasa_nlu/version.py
- tests/base/test_featurizers.py
- tests/base/test_interpreter.py
- Fixes 1128.  For each regex in training set, adds feature to crf entity extrator.
- To Do: check whether this adds features to intent classifier and fix if not.
> first go at fixing issue 1128

- CHANGELOG.rst
- rasa_nlu/extractors/crf_entity_extractor.py
- rasa_nlu/tokenizers/whitespace_tokenizer.py
- tests/base/test_tokenizers.py
- replace punctuation with spaces
> replace punctuation with space

- docs/installation.rst
> Adding  VC++ build tool pre-requisite Windows

- alt_requirements/conda-requirements.txt
- alt_requirements/requirements_bare.txt
- alt_requirements/requirements_spacy_sklearn.txt
- alt_requirements/requirements_tensorflow_sklearn.txt
Update python dependencies to latest version:
* **spacy**:
- Version: 2.0.11
- Release date: Apr 4, 2018
- PyPi link: https://pypi.org/project/spacy/#history
* **scipy**: 
- Version: 1.1.0
- Release date: May 5, 2018
- PyPi link: https://pypi.org/project/scipy/#history
* **scipy**: 
- Version: 1.1.0
- Release date: 25 days and 11 hours ago
- Anaconda link: https://anaconda.org/anaconda/scipy
* **tensorflow**:
- Version: 1.8.0
- Release date: Apr 28, 2018
- PyPi link: https://pypi.org/project/tensorflow/#history
* **numpy**:
- Version: 1.14.4
- Release date: 5 days ago
- PyPi link: https://pypi.org/project/numpy/#history
> Update python modules (dependencies) to latest version

- .travis.yml
- alt_requirements/requirements_dev.txt
- docs/entities.rst
- docs/fallback.rst
- docs/pipeline.rst
- fixes https://github.com/RasaHQ/rasa_nlu/issues/1198
- use publicly available docs package hosted on gcs
- some small docs improvements
> Docs theme gcs

- .travis.yml
> only build and push docs for master and PRs with master base

- CHANGELOG.rst
- docs/http.rst
- rasa_nlu/model.py
- rasa_nlu/server.py
- tests/base/test_server.py
- adds the minimum compatible NLU model version to the `/version` endpoint 
> Model compatibility in /version endpoint

- alt_requirements/requirements_dev.txt
- docs/conf.py
- bump docs theme version - now builds an xml sitemap as well
> Docs theme

- CHANGELOG.rst
- docs/entities.rst
- docs/evaluation.rst
- docs/migrations.rst
- docs/pipeline.rst
- replaced duckling docks with docks for the http version, the other one is not maintained by facebook anyways
> added duckling http docs

- docs/conf.py
> now this is merged, base_url updated

- docs/quickstart.rst
> fix server path in quickstart

- README.md
Updated README.md - changed Gitter links to Community Forum links.
> Updated README.md to include links to community forum instead of Gitter

- docs/faq.rst
Changed Gitter links to Rasa Community Forum links
> Changed Gitter link to Rasa Community link

- docs/quickstart.rst
> add warning about cells not being independent

- .github/stale.yml
- add an issue bot to the repo
> Add the issue bot

- docs/choosing_pipeline.rst
- docs/components.rst
- docs/dataformat.rst
- docs/evaluation.rst
- docs/index.rst
- docs/quickstart.rst
- mention that rasa platform also offers a ui for annotating data
- reorganize plapipeline and component docs
- simplify quickstart
> docs copy change

- docs/index.rst
- docs/support.rst
Added support section to the docs.
> Add support section to the docs

- rasa_nlu/featurizers/count_vectors_featurizer.py
- fix no OOV token present warning if it is Capital and lowercase is on
> fix no OOV token present warning if it is Capital and lowercase is on

- rasa_nlu/training_data/training_data.py
- tests/base/test_training_data.py
> add convenience method for balanced train test split

- rasa_nlu/classifiers/sklearn_intent_classifier.py
I propose allows using alternative scoring function or defining ones own 
scoring function for evaluating the parameters being selected by the gridsearch.
Results are stored in the `component.clf.cv_results_` allowing us to use 
them in reports on model quality.
> Add scoring function_parameter

- rasa_nlu/data_router.py
- fixes bug where server continues to report 'training' status after training model completed. 
> call training callback after tf training in main thread

- alt_requirements/requirements_bare.txt
- Numpy 1.14.4 has a bug for alpine builds https://github.com/numpy/numpy/pull/11269 which was fixed in 1.14.5
> Increment Numpy patch release

- .github/no-response.yml
- If an issue labeled with "more-information-needed" hasn't been responded to within 14 days, the issue will be automatically closed
> Add no response bot

- docs/installation.rst
- docs/quickstart.rst
Added the starterpack info to the docs
> added starterpack

- docs/changelog.rst
- docs/choosing_pipeline.rst
- docs/components.rst
- docs/config.rst
- docs/customcomponents.rst
- docs/dataformat.rst
- docs/docker.rst
- docs/entities.rst
- docs/evaluation.rst
- docs/fallback.rst
- docs/faq.rst
- docs/feedback.inc
- docs/http.rst
- docs/index.rst
- docs/installation.rst
- docs/languages.rst
- docs/license.rst
- docs/livechat.html
- docs/migrations.rst
- docs/persist.rst
- docs/python.rst
- docs/quickstart.rst
- docs/support.rst
Added support channels to each page: added livechat and support links (forum and github issues)
> added support channels

- CHANGELOG.rst
- alt_requirements/requirements_dev.txt
- docs/migrations.rst
- rasa_nlu/data_router.py
- rasa_nlu/model.py
- rasa_nlu/project.py
- rasa_nlu/server.py
- rasa_nlu/train.py
- rasa_nlu/training_data/loading.py
- rasa_nlu/utils/__init__.py
- setup.py
- tests/base/test_project.py
- tests/base/test_utils.py
- tests/conftest.py
- allows pulling of NLU models from server
- adds EndpointConfig for handling authenticated HTTP requests
> Pull models from server II

- docs/choosing_pipeline.rst
- rasa_nlu/registry.py
- Adds ner_synonyms to tensorflow embedding template, resolves #1386
> Added ner_synonyms to tensorflow template

- rasa_nlu/classifiers/embedding_intent_classifier.py
- rasa_nlu/extractors/crf_entity_extractor.py
- rasa_nlu/extractors/duckling_http_extractor.py
- rasa_nlu/extractors/entity_synonyms.py
- `classmethod`s use `cls` parameter in order to create objects. This will allow subclasses use the functionality without overriding the method.
> add classmethod to use cls parameter for inheritance.

- alt_requirements/requirements_tensorflow_sklearn.txt
Change tensorflow version. This fixes #1385.
> Change tensorflow version

- CHANGELOG.rst
- alt_requirements/requirements_dev.txt
- setup.py
> remove pytest-services

- .travis.yml
- Had a bug in the condition and also it triggered while the pull request merge was tested. It should however only trigger once the PR has been merged in.
> fixed condition + only trigger on merge into master

- CHANGELOG.rst
- rasa_nlu/version.py
- increment version number and update changelot
> Update version to 0.13.5

- setup.py
Updated the links to the docs and community forum inside the setup.py file
> updated docs and community links

- docs/faq.rst
- docs/index.rst
- docs/languages.rst
Re: https://github.com/RasaHQ/rasa_docs/issues/11
- Changed a description of which languages are supported a bit and highlighted any language part.
- Added a question about language support to FAQs
- Moved 'Supported languages' section above the 'entities' section.
> language support

- docs/languages.rst
Added an actual example of how to define the tensorflow pipeline and how to train a model in a custom language.
> added custom language example

- CHANGELOG.rst
- docs/components.rst
- rasa_nlu/classifiers/embedding_intent_classifier.py
Fixes #1412
- Refashion config parameters
- Re-structure functions within the classifier class to mimic the embedding policy class from Rasa Core
- Add comments & types
- Apply blusher & contour to bring out those gorgeous cheekbones
> Refactoring the embedding intent classifier

- alt_requirements/requirements_docs.txt
> bump docs theme 

- alt_requirements/requirements_bare.txt
- there is a security vulnerability in requests 2.18, hence the update to 2.20
> updated requests library

- .travis.yml
> try two step install to break cache

- CHANGELOG.rst
- docs/migrations.rst
- rasa_nlu/server.py
- tests/base/test_server.py
> Remove /config endpoint

- CHANGELOG.rst
- rasa_nlu/tokenizers/jieba_tokenizer.py
- Make sure loading jieba custom dictionaries only once.
> Bugfix: load jieba custom dictionaries repeatedly

- rasa_nlu/classifiers/embedding_intent_classifier.py
Had some incorrect type notations and required `noinspection` tags
Fixes #1507
> TF NLU classifier formatting post-edits

- .travis.yml
- alt_requirements/requirements_docs.txt
> increment docs theme version

- rasa_nlu/utils/__init__.py
- fix which belongs to https://github.com/RasaHQ/rasa_nlu/pull/1538 and https://github.com/RasaHQ/rasa_nlu/issues/1489
- replace old pyaml import
- ~[ ] updated the changelog~
> replace old pyaml import

- setup.py
- Fixed spacy minor version to avoid the numpy conflict with tensorflow (RasaHQ/rasa_core#1336)
> Fixed spacy minor version

- rasa_nlu/data_router.py
- rasa_nlu/project.py
- https://github.com/RasaHQ/rasa_nlu/issues/1522#issue-379637197
> Add failed status to project

- CHANGELOG.rst
- docs/choosing_pipeline.rst
- docs/docker.rst
- Issue https://github.com/RasaHQ/rasa_nlu/issues/1542
- add more documentation for the Docker section
> Improved Docker documentation

- docker/Dockerfile_full
- docker/docker-cloud.yml
- docker/docker-compose.yml
> decomment volume in dockerfile_full, added data volume on docker compose

- CHANGELOG.rst
- rasa_nlu/utils/__init__.py
- tests/base/test_utils.py
- fixes https://github.com/RasaHQ/rasa_nlu/issues/1564
> fix parsing of emojis from json

- CHANGELOG.rst
- rasa_nlu/server.py
- Updated the code to better support CORS.
- Previously the request from cross-origin was failing even after providing `--cors` argument, but with this code, the cross-origin request is working after providing `--cors` argument.
- This small code change is only to fix CORS issue. It does not affect any other functionalities in any way.
> CORS support

- .travis.yml
- CHANGELOG.rst
- related to https://github.com/RasaHQ/rasa_core/issues/1427
- Add an extra stage to the travis script which clones the [NLU starter pack](https://github.com/RasaHQ/starter-pack-rasa-nlu) and tests it upon successful NLU build
> Create extra Travis job to clone and test the starter pack

- .travis.yml
- README.md
- makes sure that we do not add any dependencies with an incompatible license
- travis will check fossa on every build to make sure we are alerted on PR builds
> Added fossa check

- CHANGELOG.rst
- alt_requirements/requirements_bare.txt
- alt_requirements/requirements_spacy_sklearn.txt
- alt_requirements/requirements_tensorflow_sklearn.txt
- rasa_nlu/version.py
- setup.py
- scikit-learn should be a global requirement
> Fix sklearn req

- CHANGELOG.rst
- alt_requirements/requirements_bare.txt
- alt_requirements/requirements_tensorflow_sklearn.txt
- setup.py
> cherry pick edoardos commits

- CHANGELOG.rst
- docs/evaluation.rst
- rasa_nlu/evaluate.py
- tests/base/test_evaluation.py
[More details in original PR](https://github.com/RasaHQ/rasa_nlu/pull/1657)
> Add export function for entity extractors

- .travis.yml
- CHANGELOG.rst
To fix #1671 
- Starter tests now in stage 1
- Starter tests only begin on new version branches
> Update travis script to test starter packs

- .travis.yml
- CHANGELOG.rst
- setup.py
- updates setup.py with correct requirements 
> update setup.py with correct requirements

- .travis.yml
- CHANGELOG.rst
To fix #1682 
- use regex to parse new version builds
- add `branch = 'master'` as a condition
> Add starter pack tests to master build

- docs/python.rst
- Updated docs for Python support
> update python support

- CHANGELOG.rst
- rasa_nlu/evaluate.py
- rasa_nlu/model.py
- rasa_nlu/training_data/loading.py
- fixes https://github.com/RasaHQ/rasa_nlu/issues/1615
- add parameter to skip validation
> Evaluation data validation

- docs/choosing_pipeline.rst
- docs/components.rst
- docs/config.rst
- docs/customcomponents.rst
- docs/dataformat.rst
- docs/docker.rst
- docs/endpoint_configuration.rst
- docs/entities.rst
- docs/evaluation.rst
- docs/fallback.rst
- docs/faq.rst
- docs/http.rst
- docs/index.rst
- docs/installation.rst
- docs/languages.rst
- docs/license.rst
- docs/migrations.rst
- docs/persist.rst
- docs/python.rst
- docs/quickstart.rst
- docs/support.rst
- changed and added meta descriptions
> update meta descriptions

- rasa_nlu/featurizers/bert_featurizer.py
- sample_configs/config_bert.yml
> add configurable model_dir param

- rasa_nlu/evaluate.py
- tests/base/test_evaluation.py
> Empty tokens

- rasa_nlu/train.py
- rasa_nlu/utils/__init__.py
- fix data endpoint keyword passed to `do_train`
> fix data endpoint key

- README.md
- Update all docs links from nlu.rasa.com to new location, rasa.com/docs/nlu/
- Add image of Sara the Rasa mascot
> Update docs links to new docs url & add Sara the Rasa mascot

- rasa_nlu/train.py
- rasa_nlu/utils/__init__.py
-  cherry pick fixing url train
> Fix url 0.14

- CHANGELOG.rst
- docs/config.rst
- rasa_nlu/server.py
- tests/base/test_evaluation.py
- tests/base/test_server.py
- This is needed to run smoothly on openshift. Right now on docker-compose the starting command for nlu gets interpolated and the token is correctly set. This does not happen in openshift becouse the command is run outside docker-compose and the env variable are not available for interpolations in the starting command but are available to the application. 
> make possible to set the auth token from an env variable

- docs/entities.rst
> fix entity table

- rasa_nlu/evaluate.py
> fix imports

- docs/http.rst
- fixes https://github.com/RasaHQ/rasa_nlu/issues/1706
> remove /config endpoint docs

- binder/requirements.txt
no idea why my line at the end of the file isn't rendering, but doesn't seem to be an issue
> Update binder requirementes after renaming pipeline requirement files

- README.md
- added note to README in case anyone is confused when looking at GitHub
> added note about code merge to README

- rasa/core/policies/two_stage_fallback.py
- add same logging to TwoStageFallbackPolicy as was implemented in FallbackPolicy in #2739 
> add core threshold logging for TwoStageFallbackPolicy

- rasa/core/train.py
> Fix typo in namespace variable 'core'

- docs/core/old_core_changelog.rst
- rasa/core/training/dsl.py
> parse intent messages using RegexInterpreter

- docs/core/slotfilling.rst
- examples/formbot/actions.py
- fixes #3176 and 1422 (issue in old core)
- Form validation method is used as intended now and with `validate_{requested_slot}`
> updated formbot and docs

- examples/formbot/actions.py
> type fixed

- CHANGELOG.rst
- rasa/core/tracker_store.py
- tests/core/test_tracker_stores.py
- fixes https://github.com/RasaHQ/rasa_nlu/issues/3136#issuecomment-477118361
> add missing implementation of the keys function

- rasa/cli/initial_project/actions.py
- fix the import of the `CollectingDispatcher` in the template for the custom actions 
> fix import of CollectingDispatcher

- rasa/core/channels/botframework.py
- Change type and rename `bot_id`
> Botframework channel. Change type and rename bot_id

- rasa/core/training/interactive.py
- fixes #3296 
- the new action mapping was incorrect not allowing the user to create new actions, but skipping that step
> fix IL new action

- docs/core/slots.rst
Make the name of the action line up with the rest of the example
- ...
> small typo in using slots doc

- rasa/train.py
- train core and nlu models in tmp directories with only relevant files
- fixes #3173 
> ignore irrelevant files in rasa train core and rasa train nlu

- CHANGELOG.rst
- rasa_nlu/test.py
> Fix bug in test script

- README.md
- rasa/core/events/__init__.py
- tests/core/test_events.py
> some small readme fixes and a typo

- CHANGELOG.rst
- rasa/cli/test.py
- rasa/cli/utils.py
- rasa/test.py
- tests/core/cli/test_utils.py
- compare multiple core models if a list of `tar.gz` model files is pass on to ``--models`` (e.g. `rasa test core --model models/core-20190429-155526.tar.gz models/core-20190429-155543.tar.gz`). If a single model or a directory is provided, the single model is tested.
- ``rasa test`` and sub-commands accept only models that are `tar.gz` files
related to #3272 
> Cli compare test

- CHANGELOG.rst
- Unreleased code, so there's nothing to "fix"
> Remove fixes in changelog for new features

- docs/core/old_core_changelog.rst
- docs/nlu/old_nlu_changelog.rst
- rasa/core/policies/mapping_policy.py
- rasa/nlu/test.py
- tests/core/test_domain.py
- merge #3358 into master
- merge https://github.com/RasaHQ/rasa_core/pull/1894 into master
> Merge bug fixes

- examples/moodbot/domain.yml
- fixes #3384 
- send intent with buttons payload
> payload for buttons is intent

- rasa/core/channels/channel.py
> fix wrong function call

- rasa/core/policies/memoization.py
- rasa/core/training/interactive.py
- tests/core/test_interactive.py
- Fix interactive learning - use correct request parameter.
- Fix memoization policy training
> Fix interactive learning

- rasa/utils/common.py
- Log WARNING from tensorflow and sanic only once.
related to https://github.com/RasaHQ/rasa/issues/3272
> Fix duplicated warning from tensorflow and sanic

- CHANGELOG.rst
- rasa/cli/run.py
- rasa/cli/shell.py
- rasa/nlu/run.py
- rasa/run.py
- `rasa run` always starts Rasa Server
- Remove subparsers `rasa run nlu` and `rasa run core` as they do not differ from `rasa run`
- `rasa shell` offers possibility to chat via command line if Core model is present. Otherwise, the NLU model is used to interpret text.
- `rasa shell nlu` interpret text on the command line as long as the provided model contains an NLU model
related to https://github.com/RasaHQ/rasa/issues/3272
> Update rasa run & rasa shell

- rasa/core/channels/facebook.py
- fix some issues I ran into with setting up a facebook bot, i think they came from the async introduction
> make sanic happy with request formats

- rasa/cli/test.py
- rasa/test.py
> Fix corss validation

- rasa/test.py
- Print error if no NLU model for testing was found
> Print warning on missing model.

- rasa/cli/x.py
- no need to give feedback to user if they didn't provide explicit input
> don't print 'saved' success if no prompt

- rasa/train.py
- split up train functions for core / nlu so it's clearly separted whether the training data has already been loaded (merged in one directory) and the config was separated.
> split up standalone training and stack-training function

- rasa/cli/arguments/test.py
- rasa/cli/test.py
- `rasa test core` does not need a config file
- create result dir if it does not exists for `rasa test core`
- fix command line arguments for `rasa test`
related to https://github.com/RasaHQ/rasa/issues/3272
> Fix rasa test core.

- examples/moodbot/Makefile
take out `-c` in run command and replace with `--connector`
> update moodbot makefile

- rasa/cli/arguments/run.py
- rasa/cli/arguments/shell.py
- rasa/cli/arguments/train.py
- rasa/cli/arguments/x.py
- rasa/cli/show.py
- tests/nlu/base/test_interpreter.py
- Reorganize command line arguments (change order)
- Remove duplicate command line arguments
> Refactor command line arguments #2

- rasa/model.py
- rasa/train.py
- tests/core/test_model.py
- tests/test_train.py
- Refactoring of `rasa/train.py` (functionality stayed the same)
> Refactoring rasa train

- docs/index.rst
- docs/nlu/using-only-nlu.rst
- docs/tutorial.rst
- a zonzero fraction of users only use Rasa NLU, we should make it clear how to do that (especially since the merge of libraries + server)
(ignore the commit about renaming the tutorial, that's already in https://github.com/RasaHQ/rasa/pull/3472 )
> Docs for nlu only

- data/test_dialogues/moodbot.json
- data/test_multi_domain/data/MoodBot/data/nlu.md
- data/test_multi_domain/data/MoodBot/data/stories.md
- data/test_multi_domain/data/MoodBot/domain.yml
- docs/_static/spec/rasa.yml
- docs/core/policies.rst
- examples/moodbot/data/nlu.md
- examples/moodbot/data/stories.md
- examples/moodbot/domain.yml
- rasa/cli/initial_project/data/nlu.md
- rasa/cli/initial_project/data/stories.md
- rasa/cli/initial_project/domain.yml
- rasa/core/actions/action.py
- rasa/core/channels/channel.py
- rasa/core/channels/slack.py
- rasa/core/processor.py
- tests/core/test_channels.py
- tests/test_skill.py
>  merge master into post-merge-docs

- rasa/data.py
- tests/core/test_data.py
- make `_get_core_nlu_files()` public
> Public access to get_core_nlu_files()

- rasa/cli/arguments/data.py
- rasa/cli/arguments/default_arguments.py
- rasa/cli/arguments/interactive.py
- rasa/cli/arguments/run.py
- rasa/cli/arguments/test.py
- rasa/cli/arguments/train.py
- rasa/cli/data.py
- rasa/cli/interactive.py
- rasa/cli/run.py
- rasa/cli/scaffold.py
- rasa/cli/shell.py
- rasa/cli/test.py
- rasa/cli/train.py
- rasa/cli/visualize.py
- rasa/cli/x.py
- rasa/nlu/convert.py
- rasa/run.py
- rasa/train.py
Command line interface: Update help and error messages.
> Update help and error messages of cli

- rasa/cli/x.py
- move metrics and term prompts to rasa-x package
- ask for terms
- only do both in local mode
> add terms prompt from rasa-x package

- docs/command-line-interface.rst
- docs/evaluating-models.rst
- docs/server.rst
Show complete help messages in command-line-interface documentation.
> Update command-line-interface documentation

- docs/core/slot-filling.rst
- docs/migrations.rst
- examples/formbot/actions.py
- add into about validation of pre-filled slots, new helper method return types, etc.
- close #3215
- port some changes that didn't make it over from rasa_core
> docs for form validation

- docs/core/domains.rst
- docs/migrations.rst
> add docs and migrations for io refactor

- rasa/cli/x.py
> fix api to path

- rasa/core/agent.py
- rasa/utils/common.py
- Update log level in model server session to avoid logging 
`2019-05-17 13:02:55 WARNING  rasa.core.agent  - Tried to fetch model from server, but server response status code is 500. We'll retry later...`
related to https://github.com/RasaHQ/rasa-x/issues/628
> Update log level in scheduler

- docs/core/interactive-learning.rst
> fix link to Rasa X & move into note

- rasa/cli/arguments/x.py
- rasa/cli/utils.py
- rasa/cli/x.py
- rasa/run.py
- rasa/utils/common.py
- setup.py
- tests/cli/test_rasa_x.py
- x cli argument cleanup
- code cleanup
> cleanup cli command for rasa x

- docs/api/brokers.rst
- docs/core/domains.rst
- docs/dialogue-elements/completing-tasks.rst
- docs/dialogue-elements/small-talk.rst
> fix some broken links and typos spotted by paula

- rasa/cli/x.py
Starting rasa x locally: Check if current directory is a valid Rasa project. If not, print error message and stop startup.
related to https://github.com/RasaHQ/rasa-x/issues/668
> rasa x: check if directory is a valid Rasa project

- rasa/core/agent.py
- Set log level in `agent` for fetching model from server to debug
> Decrease log level for fetching model

- tests/test_train.py
- remove 'uncompress' tests for model packaging
> remove 'uncompress' tests for model packaging

- README.md
- data/test_config/stack_config.yml
- docs/index.rst
- examples/moodbot/README.md
- rasa/cli/initial_project/actions.py
- rasa/cli/initial_project/config.yml
- rasa/cli/initial_project/credentials.yml
- rasa/cli/initial_project/endpoints.yml
- rasa/cli/scaffold.py
- rasa/constants.py
- rasa/core/agent.py
- rasa/core/channels/slack.py
- rasa/core/policies/ensemble.py
- rasa/core/training/dsl.py
- rasa/nlu/training_data/formats/rasa.py
- rasa/run.py
- setup.py
> more doc links

- README.md
> change make instructions for livedocs

- docs/nlu/choosing-a-pipeline.rst
- We added `RegexFeaturizer` back into `supervised_embeddings` pipeline a few months ago, but didn't update the docs
> Add Regex back to pipeline in docs

- CHANGELOG.rst
- rasa/core/domain.py
- rasa/core/processor.py
- rasa/core/trackers.py
- rasa/server.py
- tests/core/test_trackers.py
- fixes https://github.com/RasaHQ/rasa/issues/3546
- set slots in tracker rather than in processor
> update slots in 'tracker.update()'

- CHANGELOG.rst
- docs/core/policies.rst
- rasa/core/policies/fallback.py
- rasa/core/policies/form_policy.py
- rasa/core/policies/mapping_policy.py
- rasa/core/policies/two_stage_fallback.py
- Form > Fallback > Mapping priority (mapping will only happen if form validation rejects and NLU threshold is reached)
- fixes #3542
- Mapping Policy correctly persists priority
- fixes #3545 
- Update mapping policy docs to clarify UserUtteranceReverted
> Fix mapping policy priority

- .travis.yml
- rasa/core/domain.py
- rasa/core/utils.py
- rasa/utils/common.py
- tests/core/test_channels.py
- tests/test_skill.py
- tests/test_utils.py
- instead of running the tests separately, run tests in one stage
- makes sure we do not miss any tests (e.g. cli or tests placed directly under `tests/`)
> Make sure travis runs all tests

- docs/conf.py
- docs/docker.rst
- docs/migrations.rst
- rasa_nlu/training_data/formats/rasa.py
- setup.py
- change all full links in docs to legacy docs
> fix links for legacy docs

- docs/_static/spec/rasa.yml
Update API spec for Rasa server: References are now rendered.
fixes https://github.com/RasaHQ/rasa/issues/3572
> Update api spec.

- CHANGELOG.rst
- rasa/core/tracker_store.py
- tests/core/test_tracker_stores.py
> support fully specified sql database urls in endpoint config

- CHANGELOG.rst
- rasa/utils/endpoints.py
- tests/test_utils.py
- fix #3638
- remove trailing slash if subpath is None
> Fix error 404 from action server (issue #3638)

- CHANGELOG.rst
- rasa/core/domain.py
- tests/core/test_domain.py
> exclude unfeaturized slots from domain warnings

- CHANGELOG.rst
- rasa/core/domain.py
- fixes #3761 
- includes forms in warnings
- includes default actions listed in the domain from action warnings
> Include forms in warnings

- CHANGELOG.rst
- rasa/core/tracker_store.py
- add lengths so it works on dialects that need it
> Add lengths to VARCHAR to ensure mysql works

- CHANGELOG.rst
- docs/_static/spec/rasa.yml
- rasa/server.py
- tests/test_server.py
> Include agent readiness on /status resource

- CHANGELOG.rst
- rasa/core/channels/facebook.py
- fixes https://github.com/RasaHQ/rasa/issues/3590
> fix facebook quick replies

- CHANGELOG.rst
- rasa/core/channels/facebook.py
> Take FB quick reply payload rather than text as input

- docs/core/domains.rst
- add missing colon
- use better entity names in the example
> add missing colon

- CHANGELOG.rst
- rasa/cli/run.py
- rasa/core/agent.py
- rasa/core/channels/channel.py
- rasa/core/processor.py
- rasa/core/test.py
- rasa/core/trackers.py
- rasa/model.py
- rasa/run.py
- rasa/test.py
- rasa/utils/common.py
- rasa/utils/io.py
- tests/core/test_channels.py
- fix https://github.com/RasaHQ/rasa/issues/3790
- remove unused imports
> Deprecate handle channels

- CHANGELOG.rst
- rasa/core/tracker_store.py
- add logging to tell which tracker store is connected
- closes #3835
> Log tracker store

- CHANGELOG.rst
- rasa/core/agent.py
- rasa/jupyter.py
- tests/core/test_agent.py
- tests/core/test_examples.py
- tests/core/test_restore.py
`Agent.load()`now also accepts `tar.gz` model files.
closes https://github.com/RasaHQ/rasa/issues/3807
> Agent.load also accepts tar.gz model file

- .travis.yml
- CHANGELOG.rst
- rasa/cli/interactive.py
- rasa/core/agent.py
- rasa/core/run.py
- rasa/model.py
- tests/core/test_model.py
- Ensure all temp files are deleted after running `rasa run --enable-api`. Fixes https://github.com/RasaHQ/rasa/issues/3751.
> Fix issue #3751

- CHANGELOG.rst
- rasa/nlu/run.py
- fix https://github.com/RasaHQ/rasa/issues/3862
> dump strings in rasa shell nlu with ensure_ascii=false

- rasa/run.py
- Include the missing import for `Agent` inside the `create_agent` method.
> Add missing import

- CHANGELOG.rst
- docs/api/custom-nlu-components.rst
- docs/api/event-brokers.rst
- docs/api/featurization.rst
- docs/core/about.rst
- docs/core/domains.rst
- docs/core/forms.rst
- docs/core/responses.rst
- docs/core/stories.rst
- docs/migrate-from/ibm-watson-to-rasa.rst
- docs/nlu/language-support.rst
- docs/user-guide/architecture.rst
- rasa/jupyter.py
- this repo should also fix the issue outlined here: https://github.com/RasaHQ/rasa-x/issues/913
> remove references to rasa stack

- rasa/cli/run.py
- rasa/cli/shell.py
- rasa/core/agent.py
- rasa/core/exceptions.py
- rasa/core/run.py
- rasa/exceptions.py
- rasa/model.py
- rasa/run.py
- rasa/test.py
- tests/core/test_model.py
This PR modifies the behavior of `get_model`, so that is raises an exception when it encounters an error instead of returning `None`. This has the following advantages:
- The return type of the function is now `UnpackedModelPath` (was: `Optional[UnpackedModelPath]`), which means that the function can now be used as a context manager without having to check for `None`.
- Different exceptions can be raised depending on the encountered error.
Other changes:
- Add class `RasaException` as a base class for all Rasa exceptions. Make `RasaCoreException` inherit from it. 
- A model was being loaded and then deleted, but not used, in rasa/run.py (function `run`).
> Refactor function get_model

- .travis.yml
- README.md
> use netlify for docs update deploys

- README.md
- fix broken link into README (installation link)
- fixes #3911
> fix(doc): update link for installation guide

- docs/user-guide/cloud-storage.rst
- In user-guide docs, Added **Azure Storage** to the list of supported cloud storage in the sentence as currently only **S3** and **GCS** are included.
> Including Azure Storage to the supported list in the sentence.

- CHANGELOG.rst
- rasa/core/training/interactive.py
- rasa/nlu/training_data/loading.py
- rasa/utils/io.py
- tests/nlu/base/test_training_data.py
- tests/test_utils.py
- fix https://github.com/RasaHQ/rasa/issues/3812
- validate export paths in interactive learning
- added error handling in case path does not exist
> handle invalid export paths

- .travis.yml
Revert the conditions for the PyPI job to their original state.
> Revert conditions for PyPI job

- CHANGELOG.rst
- rasa/core/channels/channel.py
- rasa/core/channels/rasa_chat.py
- tests/core/test_channels.py
- `rasa` part of https://github.com/RasaHQ/rasa-x/issues/769
- use input channel from message if provided
> use input channel from message if provided

- rasa/core/interpreter.py
- tests/core/test_interpreter.py
Fixes  #3836
- Fix urljoin in RasaNLUInterpreter calling right url 
>  Fix url join with RasaNLUInterpreter

- rasa/cli/x.py
- rasa/core/run.py
- rasa/core/utils.py
- When running `rasa run -vv` or `rasa x -vv`, the contents of the `rasa_core.log` file should match what is printed to stdout. Fixes https://github.com/RasaHQ/rasa/issues/4015.
> Make loggers write to rasa_core.log file again

- CHANGELOG.rst
- data/test_domains/default_unfeaturized_entities.yml
- rasa/core/domain.py
- tests/core/test_domain.py
- fix incorrect cleaning of `use_entities`
> fix incorrect cleaning of use_entities

- CHANGELOG.rst
- rasa/cli/train.py
- rasa/constants.py
- rasa/core/train.py
- rasa/model.py
- rasa/train.py
- tests/cli/test_rasa_train.py
- tests/test_train.py
- `rasa train core` with multiple config files trains multiple models and stores all of them compressed (as `tar.gz` files)
fixes https://github.com/RasaHQ/rasa/issues/3983
> Rasa train core compare

- rasa/cli/scaffold.py
> add remote storage to init args

- CHANGELOG.rst
- data/test_stories/stories_with_multiline_comments.md
- rasa/core/training/dsl.py
- tests/core/test_dsl.py
- Story file can have multiline comments (``)
- Rasa ignores multiline comments and can parse story file successfully
closes https://github.com/RasaHQ/rasa/issues/4053
> story file can contain multiline comments

- alt_requirements/requirements_full.txt
- Correct typo in the word: Install
- found in alt_requirements/requirements_full.txt
- [ X ] made PR ready for code review
- [ NA ] added some tests for the functionality
- [ NA ] updated the documentation
- [ NA ] updated the changelog
- [ NA ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)
> Small text edit

- rasa/server.py
- tests/test_server.py
- fix https://github.com/RasaHQ/rasa/issues/4142#event-2526182348
> Interactive learning output channels

- CHANGELOG.rst
- rasa/core/channels/telegram.py
- fix https://github.com/RasaHQ/rasa/issues/4128
> Telegram webhook fix

- CHANGELOG.rst
- rasa/core/channels/telegram.py
- port of https://github.com/RasaHQ/rasa/pull/4172
> remove setWebhook since it is already set before (port)

- docs/api/agent.rst
- docs/api/tracker.rst
- add suggestions instead of direct edits
- I've already updated the rasabaster for the default text ("SUGGEST EDITS"), which will be updated whenever the docs get re-built
> suggest edits

- CHANGELOG.rst
- rasa/cli/utils.py
- rasa/core/channels/channel.py
- rasa/core/channels/console.py
- rasa/core/restore.py
- rasa/core/training/interactive.py
- tests/core/test_interactive.py
- tests/core/utilities.py
> Allow free text input in the presence of buttons

- docs/_static/spec/rasa.yml
- Update example request for `/model/train`
fixes https://github.com/RasaHQ/rasa/issues/4265
> Update example request for /model/train

- requirements.txt
- merge sdk bin from 1.2.x into master
> pin compatible sdk version

- docs/core/stories.rst
- examples/moodbot/domain.yml
- Mention that checkpoints can also start with bot actions
> Checkpoint flexibility

- CHANGELOG.rst
- docs/migration-guide.rst
- rasa/nlu/test.py
- tests/nlu/base/test_evaluation.py
- evaluation of NER does not consider 'no-enity' anymore
closes #4313 
> Exclude 'no-entity' from NER evaluation

- rasa/core/broker.py
- Allow specification of AMGP urls for pika
> Allow specification of AMGP urls for pika

- CHANGELOG.rst
- rasa/core/policies/mapping_policy.py
- tests/core/test_policies.py
- Add a bugfix from a community member (who forked master) to 1.2.x.
Original PR by psds01 is here: https://github.com/RasaHQ/rasa/pull/4243
Issue it adressed is https://github.com/RasaHQ/rasa/issues/4107
> Mappol bugfix

- docs/user-guide/rasa-tutorial.rst
- at the end of the tutorial, provide links with suggested further reading
motivation:
- got feedback from multiple users that it's not clear what to do after completing the moodbot
> Add next steps to tutorial 1.2.x

- docs/_static/spec/rasa.yml
- fixes incorrect description in docs
> correct description of output channel handling in execute endpoint

- docs/core/actions.rst
- docs/core/responses.rst
- docs/core/retrieval-actions.rst
- docs/dialogue-elements/completing-tasks.rst
- docs/index.rst
> alan draft of response selector docs

- docs/_static/spec/rasa.yml
- port https://github.com/RasaHQ/rasa/pull/4338 to 1.2.x
> correct description of output channel handling in execute endpoint 

- docs/core/policies.rst
- rasa/core/policies/ensemble.py
- rasa/core/policies/mapping_policy.py
- Adds to the docs the information that MappingPolicy is required for `'/back'` and `'/restart'` to work. Also adds a debug message to the policy ensemble saying the same thing.
> added some mapping policy related information

- docs/core/actions.rst
- docs/glossary.rst
> Add links to pages from Glossary definitions

- docs/user-guide/connectors/your-own-website.rst
- Add [`rasa-bot`](https://github.com/assister-ai/assister/blob/master/packages/rasa/README.md) to docs as an approach for for hosting on own website.
> Add rasa-bot to docs

- docs/api/tracker-stores.rst
> localhost not required for sqlite

- rasa/nlu/featurizers/__init__.py
- rasa/nlu/featurizers/count_vectors_featurizer.py
- rasa/nlu/featurizers/mitie_featurizer.py
- rasa/nlu/featurizers/spacy_featurizer.py
- Fix `_combine_with_existing_features` with no hardcoding of `_features` suffix.
- Correspondingly change the invocations of the function.
> Fix `_combine_with_existing_features` with no hardcoding of suffix

- docs/core/policies.rst
- vova swapped these in https://github.com/RasaHQ/rasa/pull/4291 after i wrote but before it got merged 😅
> update policy priority

- CHANGELOG.rst
- docs/api/tracker-stores.rst
- rasa/server.py
- tests/test_server.py
- allow NLU-only model in /status endpoint
> allow NLU-only model in /status endpoint

- docs/core/policies.rst
I had to reread the sentence a couple of times before understanding it.
> Change to active voice

- .travis.yml
- scripts/ping_slack_about_package_release.sh
- Fix the release notice Slack script.
> Fix after-deploy Slack script

- .travis.yml
- scripts/ping_slack_about_package_release.sh
- Same as https://github.com/RasaHQ/rasa/pull/4429.
> Fix Slack script for 1.3.x

- CHANGELOG.rst
- Remove changelog for 1.3.4, merge into 1.3.3
> remove changelog for 1.3.4, merge into 1.3.3

- rasa/core/channels/telegram.py
> fix save telegram custom json in tracker store

- CHANGELOG.rst
- rasa/core/channels/telegram.py
- Add changes from PR #4462, fixing #4461 to `1.3.x`.
> port the fix to storing json in telegram channel to 1.3.x

- CHANGELOG.rst
- docs/core/retrieval-actions.rst
- docs/core/stories.rst
- docs/migration-guide.rst
- docs/nlu/training-data-format.rst
- rasa/nlu/training_data/loading.py
- Fixes https://github.com/RasaHQ/rasa/issues/4481
- Add information about restricted usage of `/` token in intent names
> Make format guessing inside NLU more transparent

- docs/_static/spec/rasa.yml
- rasa/server.py
- tests/test_server.py
> Incorporate feedback

- CHANGELOG.rst
- data/test/markdown_single_sections/empty_section.md
- data/test/markdown_single_sections/not_existing_section.md
- rasa/nlu/training_data/formats/markdown.py
- tests/nlu/base/test_training_data.py
- Add test to ensure that empty sections in markdown format are treated correctly.
- Parse unknown sections in markdown format in order to throw an error.
fixes https://github.com/RasaHQ/rasa/issues/4304
> Throw error on unknown sections in markdown format

- CHANGELOG.rst
- rasa/core/policies/ensemble.py
- tests/core/test_ensemble.py
- fix https://github.com/RasaHQ/rasa/issues/4240
> Featurizer not serializable

- CHANGELOG.rst
- rasa/core/agent.py
- rasa/core/run.py
- rasa/server.py
- fixes https://github.com/RasaHQ/rasa/issues/4545
> Cors interactive fix

- CHANGELOG.rst
- rasa/nlu/featurizers/count_vectors_featurizer.py
- Fixes https://github.com/RasaHQ/rasa/issues/4573
> Fix processing of intent inside CountVectorFeaturizer

- CHANGELOG.rst
- move changelog to correct location (it was 1.3.9 not 1.3.8)
> Changelog fix

- CHANGELOG.rst
- rasa/cli/run.py
> Allow passing a package to the "rasa run actions" command

- docs/core/policies.rst
Fixes issue https://github.com/RasaHQ/rasa/issues/4620
Correct slight formatting error in docs of `policies`.
> fix a table and a list

- CHANGELOG.rst
- rasa/cli/x.py
- rasa/nlu/classifiers/embedding_intent_classifier.py
- rasa/utils/common.py
- fix https://github.com/RasaHQ/rasa/issues/4639
> Tf deprecation warnings 2

- CHANGELOG.rst
> Fix underline

- docs/core/stories.rst
Removed duplicate Note in the checkpoints section.
- Updated docs/core/stories.rst file.
> Removed duplicate Note

- rasa/cli/x.py
- rasa/core/brokers/utils.py
- rasa/core/interpreter.py
- rasa/core/policies/ensemble.py
- rasa/core/test.py
- rasa/core/trackers.py
- rasa/core/training/structures.py
- rasa/core/training/visualization.py
- rasa/model.py
- rasa/nlu/test.py
- rasa/nlu/utils/mitie_utils.py
- requirements-dev.txt
- tests/conftest.py
- tests/importers/test_multi_project.py
- update black dependency from 19.3b0 to 19.10b0 and re-format based on changes in black
> update black version

- Makefile
Add `wget` as a dependency to the installation steps for macOS.
> Install wget on macOS during tests setup

- CHANGELOG.rst
- rasa/core/training/interactive.py
- tests/core/test_interactive.py
- fixes https://forum.rasa.com/t/interactive-learning-mode-fails-to-append-nlu-data-to-my-data-json-file/20544
> Export nlu as json from interactive

- .travis.yml
- also install rasa dependencies for docs tests 
> fix failing docs on master

- .travis.yml
> install requirements for docs stage

- CHANGELOG.rst
- rasa/nlu/classifiers/embedding_intent_classifier.py
- rasa/nlu/featurizers/count_vectors_featurizer.py
- tests/nlu/base/test_featurizers.py
- use only word level featurizer for intents
> use only word level featurizer for intents

- docs/core/stories.rst
- the previous headline came up in docs search for stories, which we probably don't want
> change headline of checkpoints section

- rasa/nlu/training_data/formats/markdown.py
- add types to `MarkdownWriter`
> add types to the `MarkdownWriter` class

- CHANGELOG.rst
- rasa/utils/io.py
- tests/utils/test_io.py
- dump domain allowing unicode chars
> dump domain allowing unicode chars

- CHANGELOG.rst
- rasa/core/processor.py
- tests/core/test_processor.py
- fix https://github.com/RasaHQ/rasa/issues/4765
> only log unseen features if domain is not empty

- rasa/utils/train_utils.py
- in my runs it is slightly faster
> slightly cleaner sparse to indicies code

- docs/user-guide/installation.rst
- fix python versions for installation (3.8 is not yet supported)
- add info about upgrading pip (to avoid https://github.com/RasaHQ/rasa/issues/4784)
- rasa -> rasa open source because i'm already editing this file
> update python and pip versions in installation docs

- CHANGELOG.rst
- rasa/core/test.py
- fix https://github.com/RasaHQ/rasa/issues/4684
- Use the matplotlib backend ``agg`` in case the ``tkinter`` package is not installed.
> Tkinter fix

- CHANGELOG.rst
> update release date for 1.5.0

- rasa/core/train.py
- rasa/train.py
- use `asyncio.gather` for coroutines which are independent
> use asyncio.gather

- docs/conf.py
- adapted regexes to restrict older minors to latest patches
> Reduce number of build docs versions

- CHANGELOG.rst
- rasa/core/nlg/interpolator.py
- tests/core/test_nlg.py
- interpolate lists in custom templates (based on https://stackoverflow.com/questions/59029021/rasa-entities-are-not-readable-in-custom-message)
> List interpolation custom templates

- rasa/core/domain.py
- rasa/nlu/classifiers/embedding_intent_classifier.py
- rasa/nlu/config.py
- rasa/nlu/registry.py
- rasa/nlu/training_data/formats/rasa.py
- use `FutureWarnings` for end user (non python API) deprecation warnings (https://docs.python.org/3/library/exceptions.html#warnings)
- fix f-strings in changed files
> use futurewarnings for end user deprecation warnings

- CHANGELOG.rst
- changelog/4873.improvement.rst
- docs/core/actions.rst
- docs/core/domains.rst
- docs/core/policies.rst
- docs/user-guide/running-rasa-with-docker.rst
- examples/concertbot/actions.py
- examples/formbot/actions.py
- examples/restaurantbot/actions.py
- rasa/cli/initial_project/actions.py
- don't use the old deprecated dispatcher methods, use dispatcher.utter_message
> Update all examples/docs with dispatcher.utter_message

- rasa/cli/x.py
- rasa/core/utils.py
- tests/cli/test_rasa_x.py
- fix the case the model endpoint is not given and hence `None`
- refactor event broker overwriting to match model endpoint overwriting
> Fix model endpoint none kwargs

- rasa/cli/x.py
- tests/cli/test_rasa_x.py
- use correct model server url (an `s` was missing)
> use correct model server url when overwriting it

- changelog/4751.improvement.rst
- docs/api/event-brokers.rst
- requirements.txt
- setup.py
> `kafka-python` as extra dependency

- .github/ISSUE_TEMPLATE/bug_report.md
- ask bug reporters' rasa sdk versions as well
> add SDK version to issue template

- Dockerfile
- changelog/4789.bugfix.rst
- docker/Dockerfile_full
- docker/Dockerfile_pretrained_embeddings_mitie_en
- docker/Dockerfile_pretrained_embeddings_spacy_de
- docker/Dockerfile_pretrained_embeddings_spacy_en
- fix https://github.com/RasaHQ/rasa/issues/4789
- add missing `LICENSE.txt` docker images
- link spacy model **after** spacy has been installed
> Spacy docker fix

- MANIFEST.in
- changelog/4914.bugfix.rst
- Added config.yml to wheel distribution
- This PR will close #4914 
> Added rasa/nlu/schemas/config.yml to wheel package

- changelog/4925.bugfix.rst
- rasa/cli/scaffold.py
- tests/cli/conftest.py
- tests/cli/test_rasa_init.py
- Fix #4925 
- Fixed worng behaviour
> Command "rasa init" doesn't ask if user wants to train a model

- tests/core/test_actions.py
- test applied events when a user manually triggers a session restart
> add test for the case when a user manually triggers a session restart

- changelog/4942.bugfix.rst
- requirements.txt
- setup.py
multidict update broke sanic, see https://github.com/huge-success/sanic/issues/1729#issuecomment-564312966
- pins multidict to specific version
- fixes https://github.com/RasaHQ/rasa/issues/4940
> pin multidict version

- changelog/4942.bugfix.rst
- requirements.txt
- setup.py
- port of https://github.com/RasaHQ/rasa/pull/4942 to 1.5.x branch
> Patch multidict fix

- CHANGELOG.rst
- changelog/4914.bugfix.rst
- changelog/4933.improvement.rst
- changelog/4942.bugfix.rst
- rasa/version.py
- release a patch release for 1.5.3
> prepared release of version 1.5.3

- docs/user-guide/installation.rst
Conversation where we decided what to do [linked here](https://github.com/RasaHQ/rasa_docs/pull/104).
> updating pip commands in install docs

- docs/user-guide/installation.rst
I missed a couple mentions of Rasa X in https://github.com/RasaHQ/rasa/pull/4946
- ...
> remove references to Rasa X in install

- changelog/3549.improvement.rst
- rasa/cli/arguments/test.py
- rasa/core/test.py
- rasa/nlu/test.py
- tests/cli/test_rasa_test.py
- tests/nlu/base/test_evaluation.py
> Add a flag to disable plotting in rasa test

- rasa/core/domain.py
- tests/core/test_domain.py
- use session config of other domain in case
- ours is the default
- override is True
> handle merging session configs

- changelog/4995.bugfix.rst
- docs/api/custom-nlu-components.rst
- rasa/nlu/featurizers/featurizer.py
- rasa/nlu/tokenizers/tokenizer.py
- Print warning instead of raising error when config value is missing
- Update docs to make sure default values are set in custom components.
closes https://github.com/RasaHQ/rasa/issues/4995
> Tokenizer featurizer warning

- 5019.bugfix.rst
- setup.py
> pin sanic patch

- CHANGELOG.rst
- changelog/4989.bugfix.rst
- changelog/4995.bugfix.rst
- changelog/5019.bugfix.rst
- changelog/5032.bugfix.rst
- rasa/version.py
- release 1.6.1 with critical fixes for conversation sessions
> prepared release of version 1.6.1

- docs/core/interactive-learning.rst
- docs/user-guide/command-line-interface.rst
- docs/user-guide/connectors/your-own-website.rst
- docs/user-guide/messaging-and-voice-channels.rst
- rasa/cli/x.py
- Should be merged when the new Rasa X docs go live (next rasa x minor)
> update rasa to reflect rasa x docs update

- requirements.txt
- backport of https://github.com/RasaHQ/rasa/pull/5064
> pin sanic-plugins-framework to 0.8.2

- docs/api/rasa-sdk.rst
- Document in rasa-sdk section how to get health & registered actions of a running action server
> Document how to get health & registered actions

- changelog/1988.improvement.rst
- data/test_domains/default_with_slots_and_no_actions.yml
- examples/concertbot/domain.yml
- examples/formbot/domain.yml
- examples/knowledgebasebot/domain.yml
- examples/moodbot/domain.yml
- examples/restaurantbot/domain.yml
- rasa/core/actions/action.py
- rasa/core/domain.py
- tests/core/conftest.py
- tests/core/test_domain.py
- tests/core/test_dsl.py
> Avoid duplication of actions in domain files

- README.md
- changelog/_template.jinja2
- scripts/release.py
- check SDK version before releasing a minor 
- fixed some minor style issues
- ~[ ] updated the changelog (please check [changelog]~(https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)
> check SDK version before releasing a minor

- alt_requirements/requirements_pretrained_embeddings_convert.txt
- docs/nlu/choosing-a-pipeline.rst
- rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
- rasa/nlu/tokenizers/convert_tokenizer.py
- requirements.txt
- Refactored ConveRTTokenizer and ConveRTFeaturizer for TF 2.1
- Bumped up the versions for `tensorflow-text` and `tensorflowhub`
> Refactored ConveRT for TF 2.1

- LICENSE.txt
- README.md
- docs/conf.py
> move to the year 2020

- .travis.yml
- Bring commits from https://github.com/RasaHQ/rasa/pull/5102 into master.
> Use pip 19 when installing dev dependencies

- rasa/nlu/classifiers/embedding_intent_classifier.py
- rasa/utils/tensorflow/tf_layers.py
- rasa/utils/tensorflow/tf_models.py
- part of https://github.com/RasaHQ/research/issues/62
> Use tf.keras.metrics

- setup.py
> Update tensorflow-text version

- rasa/nlu/classifiers/embedding_intent_classifier.py
- rasa/utils/tensorflow/tf_layers.py
- rasa/utils/tensorflow/tf_model_data.py
- rasa/utils/tensorflow/tf_models.py
- rasa/utils/train_utils.py
- reach level of abstraction for `RasaModel`
- utilize same methods in train and predict graphs
- part of https://github.com/RasaHQ/research/issues/62
> refactor RasaModel and nlu

- rasa/core/processor.py
- In a warning message, use "throw off" instead of "throw of"
> Fix warning message in processor.py

- CHANGELOG.rst
- changelog/4989.improvement.rst
- changelog/5111.bugfix.rst
- changelog/5126.bugfix.rst
- rasa/version.py
> prepared release of version 1.6.2

- rasa/core/policies/embedding_policy.py
- rasa/nlu/classifiers/embedding_intent_classifier.py
- rasa/utils/tensorflow/tf_layers.py
implemented simple improvements planned for post tf2: https://github.com/RasaHQ/research/issues/66
to reduce model breaking changes after tf2 merge
- gelu: closes https://github.com/RasaHQ/research/issues/3
- implement dense layer with sparse weights (default sparsity 80%):  closes https://github.com/RasaHQ/research/issues/68
> use gelu, use sparse weights in dense layers

- rasa/core/agent.py
- rasa/core/brokers/broker.py
- rasa/core/brokers/event_channel.py
- rasa/core/brokers/file.py
- rasa/core/brokers/file_producer.py
- rasa/core/brokers/kafka.py
- rasa/core/channels/facebook.py
- rasa/core/domain.py
- rasa/core/interpreter.py
- rasa/core/jobs.py
- rasa/core/policies/embedding_policy.py
- rasa/core/policies/ensemble.py
- rasa/core/policies/mapping_policy.py
- rasa/core/processor.py
- rasa/core/training/dsl.py
- rasa/core/training/generator.py
- rasa/importers/multi_project.py
- rasa/nlu/classifiers/embedding_intent_classifier.py
- rasa/nlu/classifiers/keyword_intent_classifier.py
- rasa/nlu/components.py
- rasa/nlu/config.py
- rasa/nlu/extractors/crf_entity_extractor.py
- rasa/nlu/extractors/duckling_http_extractor.py
- rasa/nlu/extractors/entity_synonyms.py
- rasa/nlu/extractors/mitie_entity_extractor.py
- rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
- rasa/nlu/featurizers/featurizer.py
- rasa/nlu/tokenizers/tokenizer.py
- rasa/nlu/training_data/formats/dialogflow.py
- rasa/nlu/training_data/formats/luis.py
- remove used 'warnings' imports
> remove used 'warnings' imports

- changelog/699.misc.rst
- docs/core/policies.rst
- docs/migration-guide.rst
- examples/concertbot/config.yml
- examples/knowledgebasebot/config.yml
- examples/moodbot/config.yml
- rasa/cli/initial_project/config.yml
- fix https://github.com/RasaHQ/roadmap/issues/699
> Replace keras with ted

- changelog/4682.enhancement.rst
- rasa/core/channels/twilio.py
- added support to send images through the twilio output channel
- fixes #4682
> added twilio image support in output channel

- CHANGELOG.rst
- docs/nlu/components.rst
- an important update was missing from the changelog - around sparse features.
> complete 1.6 changelog with mention of sparse features

- CHANGELOG.rst
- changelog/5106.bugfix.rst
- changelog/5162.bugfix.rst
- changelog/5171.bugfix.rst
- changelog/5199.bugfix.rst
- changelog/5216.bugfix.rst
- rasa/version.py
Prepare release of version 1.7.1
> prepared release of version 1.7.1

- requirements.txt
- setup.py
closes https://github.com/RasaHQ/rasa/issues/5216
> Fix cloudpickle version

- CHANGELOG.rst
- changelog/5197.bugfix.rst
- changelog/5197.doc.rst
- changelog/5210.doc.rst
- docs/api/tracker-stores.rst
- rasa/version.py
> Prepare release 1.7.2

- docs/user-guide/connectors/your-own-website.rst
> fix link to invite users to test

- rasa/utils/tensorflow/model_data.py
- rasa/utils/tensorflow/models.py
- don't create tf function for dataset
> don't create tf function for dataset

- rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
- rasa/nlu/tokenizers/convert_tokenizer.py
- try ... except... so that you don't run into the `tfhub` issue when downloading ConvERT model. 
> changes to avoid OSError in convert tokenizer and featurizer; tqdm;

- changelog/4597.misc.rst
- rasa/core/training/dsl.py
> Make `Domain` arg to `StoryFileReader` optional

- docs/user-guide/building-assistants.rst
- Better story name in example
> Better story name in example

- docs/nlu/choosing-a-pipeline.rst
- docs/nlu/components.rst
- Add information on language models to docs
- part of RasaHQ/research#62
> Add information on language models to docs

- changelog/5286.doc.rst
- docs/user-guide/how-to-deploy.rst
> fix links on deploy assistant page

- CHANGELOG.rst
- changelog/5231.bugfix.rst
- changelog/5286.doc.rst
- rasa/version.py
> prepared release of version 1.7.3

- rasa/core/policies/policy.py
- rasa/nlu/components.py
> add docstrings to Policy

- changelog/5068.bugfix.rst
- rasa/core/processor.py
> Do not save tracker during session update

- CHANGELOG.rst
- changelog/5068.bugfix.rst
- rasa/version.py
> prepared release of version 1.7.4

- docs/core/domains.rst
- closes https://github.com/RasaHQ/rasa/issues/4975
- give an example of the `entities` section of a domain
> give an example of entities in the domain docs

- docker/Dockerfile_full
- docker/Dockerfile_pretrained_embeddings_spacy_de
- docker/Dockerfile_pretrained_embeddings_spacy_en
- Updated dockerfiles, they use proper ENV now
> Fixed dockerifles for 1.8.0 release

- Dockerfile
- docker/Dockerfile_full
- docker/Dockerfile_pretrained_embeddings_mitie_en
- docker/Dockerfile_pretrained_embeddings_spacy_de
- docker/Dockerfile_pretrained_embeddings_spacy_en
- fix DistributionNotFound issue:
```
docker run -v $(pwd):/app rasa/rasa init --no-prompt
...
Status: Downloaded newer image for rasa/rasa:latest
Traceback (most recent call last):
File "/opt/venv/bin/rasa", line 6, in <module>
from pkg_resources import load_entry_point
File "/opt/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3253, in <module>
@_call_aside
File "/opt/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
f(*args, **kwargs)
File "/opt/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/opt/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master …
```
> Make sure we install rasa in non-editable mode in Dockerfiles

- docs/nlu/about.rst
> copy edit to remove old wording

- rasa/nlu/classifiers/diet_classifier.py
- process golden tokens the same way we process other tokens in mask loss
> process masked token the same way

- changelog/5348.misc.rst
- docs/nlu/components.rst
- rasa/nlu/classifiers/sklearn_intent_classifier.py
- rasa/nlu/extractors/crf_entity_extractor.py
- Remove deprecation warnings for `CRFEntityExtractor` and `SklearnIntentClassifier`.
closes #5348 
> Remove deprecation warnings

- CHANGELOG.rst
- data/test_evaluations/end_to_end_story.md
- data/test_evaluations/form-end-to-end-stories.md
- tests/core/conftest.py
- tests/core/test_evaluation.py
- Fix `test_end_to_end_evaluation_script`: Don't rely on restaurant bot anymore.
> Fix flacky test

- .github/workflows/continous-integration.yml
- changelog/5330.misc.rst
> Build docker containers as part of our continuous integration workflow

- changelog/5354.bugfix.rst
- rasa/nlu/utils/hugging_face/hf_transformers.py
- rasa/nlu/utils/hugging_face/transformers_pre_post_processors.py
- tests/nlu/tokenizers/test_lm_tokenizer.py
- fixes https://github.com/RasaHQ/rasa/issues/5353
> Fix special token cleanup when using language models

- poetry.lock
- Update the Poetry lockfile dependencies.
> Run poetry update on the project

- rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py
- Update OOV warning. Mention training data type.
> Update OOV warning in CountVectorsFeaturizer

- CHANGELOG.rst
- changelog/5330.misc.rst
- changelog/5348.misc.rst
- changelog/5354.bugfix.rst
- pyproject.toml
- rasa/version.py
> prepared release of version 1.8.1

- docs/core/slots.rst
Get the value of a slot using .get_slot() with simple example
- ...
> add simple description about get slot value

- docs/api/event-brokers.rst
- Clarify messaging about message broker vs event broker ([conversation](https://rasa-hq.slack.com/archives/C7FCS16SD/p1583284919127600))
- clean up some old "Rasa Core" and unnecessary "endpoints configuration" stuff
- add some TOCs for easier reading
> update event broker docs

- rasa/nlu/utils/hugging_face/hf_transformers.py
- rasa/nlu/utils/hugging_face/transformers_pre_post_processors.py
- Related to https://github.com/RasaHQ/rasa/issues/5319
> Add docstrings to transformers components

- docs/conf.py
- rasa/nlu/classifiers/diet_classifier.py
- rasa/utils/tensorflow/layers.py
- rasa/utils/tensorflow/transformer.py
> change lstm

- docs/migration-guide.rst
- rasa/nlu/config.py
- tests/nlu/test_config.py
- fix updating dict config values
> add hidden_layers_sizes to mimic EmbeddingIntentClassifier

- docs/migration-guide.rst
- rasa/nlu/config.py
- tests/nlu/test_config.py
> fix override config

- docs/migration-guide.rst
- rasa/nlu/classifiers/embedding_intent_classifier.py
> set weight sparsity to 0 in embed intent classifier

- docs/api/tensorflow_usage.rst
- Closes https://github.com/RasaHQ/rasa/issues/5347 and address review comments from https://github.com/RasaHQ/rasa/pull/5266
- Add more details and suggestions on which options to use when.
I don't think linking to more official tensorflow docs is a good idea because they are currently very lean and confusing themselves. In terms of information, there isn't anything more that people can extract out of it from a usage with Rasa perspective. For example, this guide on using a gpu https://www.tensorflow.org/guide/gpu is completely tensorflow focussed.  
API documentation for methods around CPU parallelism are very skinny - https://www.tensorflow.org/api_docs/python/tf/config/threading/set_intra_op_parallelism_threads and …
> Update documentation for advanced tensorflow usage

- changelog/5356.bugfix.rst
- rasa/core/policies/fallback.py
- Fixes https://github.com/RasaHQ/rasa/issues/5356
> Check that last action is not listen

- .pre-commit-config.yaml
- Updated the  `.pre-commit-config.yaml` file as suggested here in this PR : https://github.com/RasaHQ/rasa/pull/5364#issuecomment-598720831 
> Updated .pre-commit-config.yaml

- CHANGELOG.rst
- changelog/5404.doc.rst
- changelog/5438.bugfix.rst
- pyproject.toml
- rasa/version.py
- Releasing a minor bc there's a bunch of important bug fixes that should be release
> prepared release of version 1.8.2

- changelog/5215.bugfix.rst
- docs/api/tracker-stores.rst
- rasa/core/tracker_store.py
- rasa/core/utils.py
- tests/core/test_tracker_stores.py
- tests/core/test_utils.py
> Convert DynamoDB decimals to floats

- docs/user-guide/testing-models.rst
- examples/formbot/tests/end-to-end-stories.md
- fix https://github.com/RasaHQ/rasa-x/issues/2238
> add more examples for end-to-end stories

- rasa/cli/initial_project/credentials.yml
Fixes #4854. Changed a default config file so no formatting/testing required.
> credentials: describe function of rasa attribute

- rasa/nlu/classifiers/diet_classifier.py
- make the epochs warning a `UserWarning` as it's something the user should configure to make the warning go away
> change epochs logger warning to userwarning

- changelog/2237.doc.rst
- docs/core/stories.rst
- docs/index.rst
- docs/user-guide/building-assistants.rst
- docs/user-guide/command-line-interface.rst
- docs/user-guide/testing-models.rst
- examples/formbot/tests/end-to-end-stories.md
- rasa/__main__.py
- rasa/cli/initial_project/tests/conversation_tests.md
- rasa/core/training/dsl.py
> more end-to-end story examples

- docs/user-guide/docker/deploying-in-docker-compose.rst
- clarify how and why to move your actions into an `actions` folder
> small clarity update to action server docs

- CHANGELOG.rst
- changelog/5492.bugfix.rst
- pyproject.toml
- rasa/version.py
> prepared release of version 1.9.1

- docs/nlu/training-data-format.rst
- just remove the whole section because lookup tables already talks about how to supply a bunch of entities
- close #5424
> remove chatito reference

- README.md
> add connectors to readme

- CHANGELOG.rst
- pyproject.toml
- rasa/version.py
- Prepared release of version 1.9.2
> Prepared release of version 1.9.2

- CHANGELOG.rst
- docs/_templates/page.html
- docs/nlu/training-data-format.rst
- docs/user-guide/docker/deploying-in-docker-compose.rst
- pyproject.toml
- rasa/core/brokers/pika.py
- rasa/version.py
- tests/core/test_broker.py
Merge 1.9.x after patch release 1.9.2
> Merge 1.9.x

- CHANGELOG.rst
- changelog/5302.doc.rst
- changelog/5405.bugfix.rst
- changelog/5444.bugfix.rst
- changelog/5506.bugfix.rst
- pyproject.toml
- rasa/version.py
> prepared release of version 1.8.3

- CHANGELOG.rst
- Merge 1.8.x into master after 1.8.3 release
> Merge 1.8 into master

- CHANGELOG.rst
- Cherry pick commits from `1.8` and merge in `1.9` so that commits that were made in `1.8.x` after `1.9.x` was forked exist in `1.9.x` as well.
- This diff only shows the changelog difference because all other changes are identical between 1.8.x and 1.9.x
> Update 1.9 with changes from 1.8

- README.md
- Updated the release documentation section of `README.md` to reflect the usage of `poetry` and to emphasise the fact that `rasa-sdk` needs to be released first.
> Release docs

- CHANGELOG.rst
- changelog/5529.bugfix.rst
- pyproject.toml
- rasa/version.py
- Release patch for memory leak problem
> prepared release of version 1.9.4

- docs/nlu/entity-extraction.rst
- docs/nlu/training-data-format.rst
Add documentation about composite entities.
> Added section about composite entities to the docs

- docs/user-guide/docker/deploying-in-docker-compose.rst
- docs/user-guide/how-to-deploy.rst
- Small edits based on our zoom session to make it easier for the basic user
- make action server deployment info more discoverable https://rasa-hq.slack.com/archives/C7FCS16SD/p1585664404053500
> make actions info more discoverable, comment out non-default docker commands

- docs/user-guide/connectors/twilio.rst
- let users know that they can connect to whatsapp through twilio if they have whatsapp business
> add info on whatsapp in twilio docs

- changelog/5489.bugfix.rst
- data/test_evaluations/end_to_end_trips_circuit_breaker.md
- data/test_evaluations/stories_trip_circuit_breaker.md
- rasa/core/constants.py
- rasa/core/processor.py
- rasa/core/test.py
- tests/core/conftest.py
- tests/core/test_evaluation.py
- closes https://github.com/RasaHQ/rasa/issues/5489
- Check whether the circuit breaker would have tripped because `max_number_of_predictions` was exceeded when testing stories
> check "max_number_of_predictions" parameter when testing

- docs/index.rst
- docs/user-guide/building-assistants.rst
- docs/user-guide/command-line-interface.rst
- docs/user-guide/setting-up-ci-cd.rst
- docs/user-guide/testing-your-assistant.rst
- docs/user-guide/validate-files.rst
- write documentation on CI/CD processes for Rasa bots
- addresses https://github.com/RasaHQ/rasa-x/issues/1864
> ci cd docs

- docs/core/forms.rst
- Fixing a small typo in forms doc
> fix typo in forms doc

- docs/user-guide/connectors/your-own-website.rst
- Remove rasa-webchat from docs
> Remove rasa-webchat from docs

- rasa/nlu/classifiers/diet_classifier.py
> Revert "Move activation to transformer block"

- docs/user-guide/connectors/twilio.rst
> add whatsapp+ prefix to twilio creds

- CHANGELOG.rst
- changelog/4606.improvement.rst
- changelog/5631.misc.rst
- changelog/5709.bugfix.rst
- pyproject.toml
- rasa/version.py
> prepared release of version 1.9.7

- .github/workflows/continous-integration.yml
- poetry.lock
- run `poetry update`
- add check to CI to fail if lockfile is out of date
> make sure lock file is always up to date

- changelog/5617.bugfix.rst
- rasa/utils/tensorflow/models.py
Don't create TensorBoard log files during prediction.
closes #5617
> Don't create TensorBoard logs during prediction

- CHANGELOG.rst
- docs/core/forms.rst
- docs/migration-guide.rst
- docs/nlu/entity-extraction.rst
- docs/user-guide/setting-up-ci-cd.rst
- closes https://github.com/RasaHQ/rasa/issues/4962
- update documentation on deactivating a form inside a slot validatin function
- fixed a few broken :ref:s 
> Update docs on form deactivation inside validate_slot function

- rasa/__main__.py
Changed `platform.system()` to `platform.platform()` for a little bit more info. It was a detail that should have been in [this PR](https://github.com/RasaHQ/rasa/pull/5726/files) but I clicked merge too early #mybad.
> platform.platform fix

- rasa/core/domain.py
- rasa/core/events/__init__.py
- rasa/core/featurizers.py
- rasa/core/interpreter.py
- rasa/core/policies/ted_policy.py
- rasa/core/processor.py
- rasa/core/test.py
- rasa/core/training/dsl.py
- rasa/nlu/classifiers/diet_classifier.py
- rasa/nlu/model.py
- rasa/nlu/training_data/formats/markdown.py
- rasa/test.py
- rasa/train.py
- rasa/utils/io.py
> Entities for E2E and a different data format

- rasa/core/featurizers.py
- rasa/core/interpreter.py
- rasa/core/trackers.py
> Slots for e2e

- docs/user-guide/rasa-tutorial.rst
- update tutorial to refer to responses, not templates
- closes https://github.com/RasaHQ/rasa/issues/5700, in conjunction with https://github.com/RasaHQ/docs-binder/pull/8
> Tutorial update

- CHANGELOG.rst
- changelog/5617.bugfix.rst
- changelog/5638.bugfix.rst
- changelog/5755.bugfix.rst
- changelog/5788.misc.rst
- changelog/5792.bugfix.rst
- changelog/5794.improvement.rst
- changelog/5825.bugfix.rst
- pyproject.toml
- rasa/version.py
Prepared release of version 1.10.1
> Prepared release of version 1.10.1

- .github/workflows/automatic-pr-merger.yml
- .github/workflows/continous-integration.yml
- .mergepal.yml
- add merge pal configuration to automatically merge ready PRs
- checked it is safe: anyone that doesn't have write access to the repo can not attach labels
> add merge pal configuration to automatically merge ready PRs

- changelog/4605.doc.rst
- changelog/5743.enhancement.rst
- docs/user-guide/testing-your-assistant.rst
- rasa/nlu/training_data/message.py
- tests/core/test_tracker_stores.py
- tests/nlu/test_config.py
- tests/nlu/training_data/test_training_data.py
> support for additional training metadata

- rasa/cli/arguments/test.py
- rasa/cli/export.py
- rasa/cli/scaffold.py
- rasa/core/exporter.py
- rasa/core/policies/embedding_policy.py
- rasa/core/training/story_conflict.py
- rasa/nlu/classifiers/diet_classifier.py
- rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py
- rasa/nlu/test.py
- rasa/nlu/training_data/formats/markdown.py
- rasa/nlu/training_data/training_data.py
- rasa/nlu/utils/__init__.py
- tests/conftest.py
- tests/core/test_lock_store.py
- tests/nlu/tokenizers/test_lm_tokenizer.py
- Fix new `flake8` warnings on this branch. [Example errors](https://github.com/RasaHQ/rasa/pull/5818/checks?check_run_id=698768795)
- Most probably due to a recent update of `flake8` itself or its dependencies
> Fix flake8

- changelog/5521.bugfix.rst
- rasa/nlu/training_data/formats/markdown_nlg.py
- tests/nlu/training_data/test_markdown_nlg.py
Fixes #5521
- Support new lines in `responses.md`
> Fix newlines in response

- README.md
With Rasa, you can build contexual*[contextual]* assistants on:
Here is how use*[users]* can install it:
- ...
> Fixed typo contextual & users

- data/test_stories/stories_with_rules.md
- examples/rules/data/stories.md
- rasa/core/policies/ensemble.py
- rasa/core/policies/registry.py
- rasa/core/policies/rule_policy.py
- rasa/core/registry.py
- rasa/core/trackers.py
- rasa/core/train.py
- rasa/core/training/__init__.py
- rasa/core/training/dsl.py
- rasa/core/training/generator.py
- rasa/core/training/structures.py
- tests/core/test_dsl.py
> Split stories into rules and ML-based

- docs/core/interactive-learning.rst
- docs/core/knowledge-bases.rst
> Changed 'and' to 'an'

- CHANGELOG.rst
- changelog/5521.bugfix.rst
- changelog/5758.bugfix.rst
- pyproject.toml
- rasa/version.py
> prepared release of version 1.10.2

- poetry.lock
- pyproject.toml
- some dependencies have been failing in dependabot, hence this manual update
> updated remaining dependencies

- changelog/3900.improvement.rst
- rasa/__main__.py
- rasa/utils/common.py
- tests/utils/test_common.py
Fixes https://github.com/RasaHQ/rasa/issues/3900
- remove duplicated logs (any level)
- remove duplicated warnings: `UserWarnings`, `DeprecatedWarnings` and `FutureWarnings`
_Caveat: it doesn't work when same warning / log are fired in different processes_
> Fix duplicate logs

- .github/workflows/continous-integration.yml
Fixes https://github.com/RasaHQ/engineering-backing/issues/2
- Cherry-pick changes from master
> Lint changelog files in CI

- changelog/5976.bugfix.rst
- rasa/core/agent.py
- tests/conftest.py
- tests/core/test_agent.py
> Catch domain exception due to invalid YAML

- CHANGELOG.rst
- changelog/3900.improvement.rst
- changelog/5972.bugfix.rst
- changelog/5976.bugfix.rst
- poetry.lock
- pyproject.toml
- rasa/core/train.py
- rasa/version.py
> Prepare release 1.10.3

- docs/user-guide/building-assistants.rst
- fix link to rasa-demo actions file
> Fix link to rasa-demo actions file in docs

- docs/user-guide/connectors/twilio.rst
- cherrypick https://github.com/RasaHQ/rasa/pull/5978 onto 1.10.x
> twilio webhook url docs

- changelog/6053.bugfix.rst
- rasa/nlu/classifiers/diet_classifier.py
- rasa/utils/tensorflow/model_data.py
- rasa/utils/tensorflow/models.py
closes https://github.com/RasaHQ/rasa/issues/6053
> Fix option `share_hidden_layers`

- examples/formbot/config.yml
- examples/formbot/data/stories.md
- examples/formbot/domain.yml
- rasa/core/policies/rule_policy.py
- rasa/core/trackers.py
- rasa/core/training/structures.py
- tests/core/actions/test_forms.py
- tests/core/test_interactive.py
- clean version of https://github.com/RasaHQ/rasa/pull/6059
> remove form unfeaturization, fix rules prediction 

- examples/formbot/config.yml
- examples/formbot/data/stories.md
- examples/formbot/domain.yml
- rasa/core/policies/rule_policy.py
- rasa/core/trackers.py
- rasa/core/training/structures.py
- tests/core/actions/test_forms.py
- tests/core/test_interactive.py
> Revert "remove form unfeaturization, fix rules prediction "

- examples/formbot/config.yml
- examples/formbot/data/stories.md
- examples/formbot/domain.yml
- rasa/core/policies/rule_policy.py
- rasa/core/trackers.py
- rasa/core/training/structures.py
- tests/core/actions/test_forms.py
- tests/core/test_interactive.py
> remove form unfeaturization, fix rules prediction

- changelog/5998.bugfix.rst
- rasa/nlu/tokenizers/whitespace_tokenizer.py
- tests/nlu/tokenizers/test_whitespace_tokenizer.py
- redo changes of https://github.com/RasaHQ/rasa/pull/6074 to release them in the next patch
> Whitespace tokenizer regex

- pyproject.toml
related to https://github.com/RasaHQ/rasa/pull/6089#issuecomment-651682089
> Add regex dependency

- changelog/6042.bugfix.rst
- rasa/core/test.py
- tests/core/test_evaluation.py
redo changes of https://github.com/RasaHQ/rasa/pull/6042 
(fix can be released in a patch, we don't need to wait for Rasa 2.0)
> Convert entity values to string during evaluation

- .github/workflows/continous-integration.yml
- CHANGELOG.rst
- changelog/5998.bugfix.rst
- changelog/6031.bugfix.rst
- changelog/6032.bugfix.rst
- changelog/6042.bugfix.rst
- changelog/6078.bugfix.rst
- poetry.lock
- pyproject.toml
- rasa/core/events/__init__.py
- rasa/version.py
> Prepare release 1.10.4

- CHANGELOG.rst
- changelog/6119.bugfix.rst
- pyproject.toml
- rasa/version.py
> prepared release of version 1.10.5

- CHANGELOG.rst
- changelog/6143.bugfix.rst
- pyproject.toml
- rasa/version.py
> prepared release of version 1.10.6

- CHANGELOG.rst
- changelog/6150.bugfix.rst
- changelog/6150.feature.rst
- pyproject.toml
- rasa/version.py
- prepared release of version 1.10.7
> prepared release of version 1.10.7

- docs/user-guide/how-to-deploy.rst
- Update names for installation methods to match those in the Rasa X documentation
> Update deploy docs

- CHANGELOG.rst
- docs/api/event-brokers.rst
- docs/core/interactive-learning.rst
- docs/core/reminders-and-external-events.rst
- docs/user-guide/building-assistants.rst
- docs/user-guide/connectors/your-own-website.rst
- docs/user-guide/how-to-deploy.rst
- docs/user-guide/setting-up-ci-cd.rst
- Update more links from the rasa docs that point to rasa x docs and are now out of date (and will make CI fail if they're not updated on your branch)
> update links to rasa x docs

- rasa/core/actions/forms.py
- rasa/core/actions/loops.py
- tests/core/actions/test_forms.py
- fix https://github.com/RasaHQ/rasa/issues/6016
> have one validate function for the whole form

- docs/user-guide/prototype-an-assistant.rst
- Add tracking to code-editor declaration
> add tracking in code-editor

- docs/conf.py
- The docs can now point to the `2.0.0a1` `2.0.0rc1` version
> Update the tag patter in the docs

- CHANGELOG.rst
- changelog/6075.bugfix.rst.txt
- changelog/6137.bugfix.rst
- pyproject.toml
- rasa/version.py
prepared release of version 1.10.8
> prepared release of version 1.10.8

- data/test_yaml_stories/stories_hybrid_e2e.yml
- rasa/core/training/story_reader/yaml_story_reader.py
- tests/core/training/story_reader/test_yaml_story_reader.py
- port of https://github.com/RasaHQ/rasa/pull/6118/files to e2e branch
> yaml marries end to end2

- changelog/6160.bugfix.rst
- rasa/core/training/interactive.py
- rasa/nlu/training_data/formats/markdown.py
- tests/core/test_interactive.py
- Consider role/group label when comparing entities in interactive learning
closes #6160 
> Fix interactive learning with entity roles/groups

- .gitignore
- Makefile
- newdocs/compile_program_outputs.js
- newdocs/docs/api/rasa-sdk.mdx
- newdocs/docs/user-guide/command-line-interface.mdx
- newdocs/docs/user-guide/testing-your-assistant.mdx
- newdocs/docs/user-guide/validate-files.mdx
- newdocs/docusaurus.config.js
- newdocs/package.json
- newdocs/plugins/program_output.js
- newdocs/yarn.lock
- scripts/push_docs_to_branch.sh
- Fixes https://github.com/RasaHQ/rasa/issues/6202
> Program output with docusaurus

- docs/conf.py
- docs/user-guide/prototype-an-assistant.rst
- poetry.lock
- pyproject.toml
- adds the chat block to prototype-an-assistant page, and also updates the resabaster version
> Prototyper chat block

- docs/docusaurus.config.js
- docs/package.json
- docs/sidebars.js
- docs/yarn.lock
- update docusaurus dependency to make use of https://github.com/facebook/docusaurus/pull/2682
- uncollapse navbar headers to reflect existing docs (but this will be changed anyway, mostly did it for testing purposes)
> update docusaurus dependency

- changelog/6255.improvement.rst
- rasa/core/actions/action.py
- rasa/core/domain.py
- tests/core/test_domain.py
- only add custom actions to `actions` key when converting do dict
- fix https://github.com/RasaHQ/rasa/pull/6255
- enables fixing https://github.com/RasaHQ/rasa/issues/5979 (we just need to bump the Rasa Open Source version in Rasa X)
> fix responses being added to actions

- changelog/6291.bugfix.rst
- docs/user-guide/prototype-an-assistant.rst
- poetry.lock
- pyproject.toml
- Update `rasabaster` to fix the issue with syntax highlighting on "Prototype an Assistant" page.
- Update default stories and rules on "Prototype an Assistant" page.
> Updated prototype-an-assistant.rst page — syntax highlighting, updated default rules and stories

- CHANGELOG.rst
- changelog/6160.bugfix.rst
- changelog/6255.improvement.rst
- pyproject.toml
- rasa/version.py
> prepared release of version 1.10.9

- docs/docs/testing-your-assistant.mdx
- closes https://github.com/RasaHQ/rasa/issues/5251
- note that unit tests are necessary to test custom actions.
> note on testing custom actions

- PRINCIPLES.md
- restored some text to the end of this file, which somehow got truncated during reformatting
> Restore truncated text at end of PRINCIPLES.md

- .github/workflows/documentation.yml
- Fix documentation workflow (failed [here](https://github.com/RasaHQ/rasa/runs/939714365?check_suite_focus=true)). Don't know why it worked before 🤷 
- Fix location of the SSH key for docs
> fix folder for documentation workflow

- README.md
> update README instructions for new docs system

- docs/docs/api/action-server.mdx
- docs/docs/api/http-api.mdx
- docs/package.json
- docs/src/components/redoc.jsx
- docs/yarn.lock
> useBaseUrl() hook for redoc

- CHANGELOG.rst
- changelog/6280.rst
- pyproject.toml
- rasa/version.py
- release 1.10.10
- this should hopefully fix the sphinx CSS stuff since 1.10.x has the upgraded (well downgraded) dependency?
> prepared release of version 1.10.10

- CHANGELOG.mdx
- docs/docs/business-logic.mdx
- docs/docs/chitchat-faqs.mdx
- docs/docs/command-line-interface.mdx
- docs/docs/components/entity-extractors.mdx
- docs/docs/components/featurizers.mdx
- docs/docs/components/intent-classifiers.mdx
- docs/docs/components/language-models.mdx
- docs/docs/components/selectors.mdx
- docs/docs/components/tokenizers.mdx
- docs/docs/connectors/hangouts.mdx
- docs/docs/connectors/your-own-website.mdx
- docs/docs/contextual-conversations.mdx
- docs/docs/custom-actions.mdx
- docs/docs/docker/deploying-in-docker-compose.mdx
- docs/docs/event-brokers.mdx
- docs/docs/migration-guide.mdx
- docs/docs/nlg.mdx
- docs/docs/reminders-and-external-events.mdx
- docs/docs/retrieval-actions.mdx
- docs/docs/setting-up-ci-cd.mdx
- docs/docs/stories.mdx
- docs/docs/testing-your-assistant.mdx
- docs/docs/tracker-stores.mdx
- docs/docs/training-data-format.mdx
- docs/docs/tuning-your-model.mdx
- remove explicit anchors
- fix references to explicit anchors
> use autogenerated anchors instead of explicit ones

- changelog/6044.improvement.rst
- rasa/core/trackers.py
- tests/core/test_trackers.py
> Do not deepcopy domain slots

- rasa/utils/tensorflow/transformer.py
- tests/core/test_policies.py
- relative attention was broken for some max histories including 1
> fix relative attention

- rasa/core/events/__init__.py
- rasa/core/test.py
- rasa/core/training/interactive.py
- rasa/core/utils.py
- rasa/nlu/schemas/nlu.yml
- rasa/nlu/training_data/formats/markdown.py
- rasa/nlu/training_data/formats/rasa_yaml.py
- rasa/nlu/training_data/formats/readerwriter.py
- rasa/nlu/training_data/training_data.py
- rasa/utils/io.py
- tests/cli/conftest.py
- tests/cli/test_rasa_test.py
- tests/cli/test_rasa_train.py
- tests/cli/test_rasa_x.py
- tests/conftest.py
- tests/core/test_exporter.py
- tests/core/test_interactive.py
- tests/importers/test_importer.py
- tests/nlu/training_data/formats/test_rasa_yaml.py
- tests/test_validator.py
- tests/utilities.py
- tests/utils/test_io.py
Closes #6252
- Added a schema and a writer for the 2.0 NLU format
- Extracted common parts of writers for both the MD and YAML
- Fixed a bug with synonyms not being extracted from the entities
> Added a schema and a writer for the 2.0 NLU Parser

- changelog/6354.feature.md
- changelog/6354.removal.md
- docs/static/spec/rasa.yml
- rasa/server.py
- tests/test_server.py
- fix https://github.com/RasaHQ/rasa/issues/6354
> yaml support for train endpoint

- docs/docs/prototype-an-assistant.mdx
- docs/docs/rules.mdx
> Prototyper updates for 2.0.0a2

- docs/docs/nlu-training-data.mdx
- docs/docs/training-data-format.mdx
- remove references to markdown in NLU training data page
> Training data format update

- changelog/6226.improvement.rst
- docs/api/lock-stores.rst
- rasa/core/lock_store.py
- tests/core/test_lock_store.py
- fix https://github.com/RasaHQ/rasa/issues/6226 (I added instructions how to reproduce the problem there)
- add timeout to avoid infinite (or very long) waiting 
- add more logs to ease debugging
> Escalate lockstore errors

- docs/docs/fallback-handoff.mdx
- docs/docs/forms.mdx
- docs/docs/migration-guide.mdx
- docs/docs/prototype-an-assistant.mdx
- docs/docs/testing-your-assistant.mdx
- docs/docs/training-data-format.mdx
- rename `form:` to `active_loop:` in docs pages
> form rename to active_loop

- .github/workflows/documentation.yml
- use Python 3.7 to build docs (check out [this successful build](https://github.com/RasaHQ/rasa/pull/6428/checks?check_run_id=992502239))
- Fixes https://github.com/RasaHQ/rasa/issues/6421
> Fix autodoc

- scripts/push_docs_to_branch.sh
- add missing files to git history, oups 😓 
> fix netlify build

- data/configs_for_docs/example_for_suggested_config_after_train.yml
- data/test_config/config_empty_after_dumping_windows.yml
- pyproject.toml
- rasa/importers/autoconfig.py
- rasa/importers/default_config_windows.yml
- tests/importers/test_autoconfig.py
- hotfixed autoconfiguration to work on windows and without spacy (related to https://github.com/RasaHQ/rasa/issues/6326)
> hotfixed autoconfiguration to work on windows and without spacy

- examples/concertbot/data/nlu.yaml
- examples/concertbot/data/rules.yaml
- examples/concertbot/data/stories.yaml
- examples/concertbot/domain.yml
- examples/knowledgebasebot/data/nlu.yaml
- examples/knowledgebasebot/data/rules.yaml
- examples/knowledgebasebot/domain.yml
- examples/moodbot/data/nlu.yml
- examples/moodbot/data/rules.yml
- examples/moodbot/data/stories.yml
- examples/moodbot/domain.yml
- examples/reminderbot/data/nlu.yml
- examples/reminderbot/data/rules.yml
- examples/reminderbot/domain.yml
- rasa/core/schemas/stories.yml
- tests/examples/test_example_bots_training_data.py
- Added unit test
- Fixed training data
- Fixed schema file for stories
> Added test that checks example bots' training data

- .github/stale.yml
- don't mark `docs` issues as stale
> Docs issues aren't marked as stale

- rasa/cli/initial_project/data/nlu.yml
- rasa/cli/initial_project/data/rules.yml
- rasa/cli/initial_project/data/stories.yml
- rasa/cli/initial_project/domain.yml
- tests/examples/test_example_bots_training_data.py
- Fixed training data for the initial project
- Extended existing unit test
> Fixed training data for the initial project

- .github/workflows/documentation.yml
- We changed the docs SSH key because I messed up with it! 😞 
> fix SSH key in workflow

- data/test_trackers/tracker_moodbot.json
- rasa/core/interpreter.py
- rasa/core/policies/form_policy.py
- rasa/core/policies/sklearn_policy.py
- rasa/core/policies/ted_policy.py
- rasa/nlu/classifiers/diet_classifier.py
- rasa/nlu/selectors/response_selector.py
- rasa/utils/tensorflow/model_data.py
- rasa/utils/tensorflow/model_data_utils.py
- rasa/utils/tensorflow/models.py
- tests/core/test_domain.py
- tests/core/test_featurizer.py
- tests/core/training/story_reader/test_common_story_reader.py
- tests/nlu/extractors/test_crf_entity_extractor.py
- tests/nlu/featurizers/test_convert_featurizer.py
- tests/nlu/featurizers/test_count_vectors_featurizer.py
- tests/nlu/featurizers/test_lexical_syntactic_featurizer.py
- tests/nlu/featurizers/test_lm_featurizer.py
- tests/nlu/featurizers/test_mitie_featurizer.py
- tests/nlu/featurizers/test_regex_featurizer.py
- tests/nlu/featurizers/test_spacy_featurizer.py
- tests/nlu/training_data/test_message.py
> fixing DIET tests

- poetry.lock
- pyproject.toml
- rasa/version.py
> Prepare release 2.0.0a3

- rasa/core/domain.py
- rasa/core/events/__init__.py
- rasa/core/featurizers/single_state_featurizer.py
- rasa/core/training/story_reader/markdown_story_reader.py
- rasa/core/training/story_reader/yaml_story_reader.py
> Ted prediction

- rasa/core/policies/sklearn_policy.py
- rasa/core/policies/ted_policy.py
- rasa/utils/tensorflow/model_data_utils.py
- tests/core/test_policies.py
> ted_tests_fixed

- tests/core/training/story_reader/test_common_story_reader.py
- tests/core/training/story_reader/test_markdown_story_reader.py
- tests/core/training/story_reader/test_yaml_story_reader.py
> fix story reader tests

- rasa/core/actions/forms.py
- tests/core/actions/test_forms.py
- Provide the action endpoint to custom ask slot actions. Closes #6494 
> fix: provide action endpoint to ask slot custom actions (#6494)

- CHANGELOG.rst
- changelog/6549.bugfix.rst
- pyproject.toml
- rasa/version.py
prepared release of version 1.10.12
> prepared release of version 1.10.12

- CODEOWNERS
- tests/shared/utils/test_common.py
- extend `all_subclasses` test by also testing for subclasses
- set up code owners for `rasa.shared` package
- follow up of https://github.com/RasaHQ/rasa/pull/6546
> `rasa.shared` code owners + additional test

- scripts/push_docs_to_branch.sh
- Name versions `2.0.x` instead of `2.0.0`
- Commit for Rasa X is here: https://github.com/RasaHQ/rasa-x/pull/3361/commits/cae56e2529ad5790b815f165621e90a4c329a4f3
> name versions with .x instead of .0 in docs release script

- pyproject.toml
- rasa/version.py
> prepared release of version 2.0.0a5

- rasa/nlu/classifiers/diet_classifier.py
> turn no entity warning to debug log

- data/test_dialogues/formbot.json
- data/test_trackers/tracker_moodbot.json
- data/test_yaml_stories/stories_hybrid_e2e.yml
- rasa/core/events/__init__.py
- rasa/core/schemas/stories.yml
- rasa/core/training/story_reader/yaml_story_reader.py
- tests/core/training/story_reader/test_yaml_story_reader.py
- tests/test_server.py
- last part of the revert of https://github.com/RasaHQ/rasa/pull/6518
- add support for reading end-to-end stories for **training** Rasa Open Source
> Re add e2e reading

- docs/docs/command-line-interface.mdx
- docs/docusaurus.config.js
- docs/package.json
- docs/yarn.lock
This contains an important fix of the GTM container ID!
> New docs: theme updates IV

- docs/docs/retrieval-actions.mdx
- Updated Retrieval Action documentation based on response selector training data format change: #6591 
> Updated retrieval action docs with new prefix

- changelog/6577.bugfix.md
- rasa/nlu/extractors/extractor.py
- tests/nlu/extractors/test_extractor.py
cherry pick fix from https://github.com/RasaHQ/rasa/pull/6577
closes https://github.com/RasaHQ/rasa/issues/6707
> Remove BILOU tag prefix from role and group labels

- docs/plugins/program_output.js
- docs/scripts/compile_program_outputs.js
- hopefully fix the output here: https://rasa.com/docs/rasa/command-line-interface
> add telemetry prefix to docs commands

- CHANGELOG.rst
- changelog/6577.bugfix.md
- pyproject.toml
- rasa/version.py
prepared release of version 1.10.13
> prepared release of version 1.10.13

- CHANGELOG.mdx
- docs/docusaurus.config.js
- docs/package.json
- docs/yarn.lock
These updates sync with theme release 0.7.11
> Docs: theme updates V

- changelog/6741.bugfix.md
- docs/nlu/components.rst
- rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
- rasa/nlu/tokenizers/convert_tokenizer.py
- Same as https://github.com/RasaHQ/rasa/pull/6743 but for `1.10.x` branch.
> Update ConveRT model URL for 1.10.x

- CHANGELOG.rst
- changelog/6741.bugfix.md
- pyproject.toml
- rasa/version.py
> prepared release of version 1.10.14

- pyproject.toml
> bump rasabaster version

- rasa/utils/common.py
- fixed cyclic import while trying to write global configuration. fixes #6758
> fixed global config writing

- docs/docs/installation.mdx
- docs/docs/prototype-an-assistant.mdx
- docs/docusaurus.config.js
- pyproject.toml
- rasa/version.py
- prepared release of version 2.0.0rc2
> prepared release of version 2.0.0rc2

- poetry.lock
- pyproject.toml
- Bump rasabaster properly (forgot to updated the lockfile)
> bump rasabaster

- poetry.lock
- pyproject.toml
- Update to new rasabaster version which includes a banner with a link to 2.0 docs
> [1.10.x] Bump rasabaster version

- rasa/server.py
Previously resulted in a unhandled exception when `eval_agent.model_directory` was null.
> Handle evaluation request when no model is loaded

- tests/nlu/classifiers/test_diet_classifier.py
- tests/nlu/featurizers/test_convert_featurizer.py
- tests/nlu/test_config.py
- tests/nlu/test_interpreter.py
- tests/nlu/test_train.py
- tests/nlu/tokenizers/test_convert_tokenizer.py
Skip tests related to ConveRT as the ConveRT model is not publicly available anymore (see https://github.com/RasaHQ/rasa/issues/6806)
> Skip ConveRT tests

- docs/docs/docker/building-in-docker.mdx
- docs/docs/installation.mdx
- tests/docs/test_docs_use_base_url.py
- fix local links missing `useBaseUrl()`
> Fix prototyper link

- tests/docs/test_docs_header_hierarchy.py
- Relates to https://github.com/RasaHQ/rasa/issues/6764
> Detect wrong heading hierarchy in docs

- pyproject.toml
- rasa/version.py
> prepared release of version 2.0.0rc3

- docs/docs/model-storage.mdx
- Fixes failing build on master
> fix header level in model-storage.mdx

- docs/docs/contextual-conversations.mdx
- docs/docs/fallback-handoff.mdx
- docs/docs/stories.mdx
- docs/docs/testing-your-assistant.mdx
- docs/docs/training-data-format.mdx
- tests/docs/test_docs_training_data.py
- make sure snippets are validated against all schemas, not just the NLU schema
> validate docs snippets against all schemas

- docs/docs/testing-your-assistant.mdx
- Fix small wording issues in e2e testing docs.
> Improve e2e testing docs in testing-your-assistant.mdx

- rasa/cli/data.py
- rasa/core/config.py
- rasa/shared/core/domain.py
- tests/cli/test_rasa_data.py
- tests/core/test_config.py
- tests/shared/core/test_domain.py
- relates to #6820
- needs https://github.com/RasaHQ/rasa/pull/6854
> function to automatically migrate the MappingPolicy

- docs/docs/installation.mdx
- tests/docs/test_docs_use_base_url.py
- Also check that `<Button` uses `useBaseUrl`
> also check for Button href in docs

- docs/docs/migration-guide.mdx
- docs/docs/policies.mdx
- Fixes https://github.com/RasaHQ/rasa/issues/6863
- Documents https://github.com/RasaHQ/rasa/pull/6854
> Update migration guide

- changelog/6900.improvement.rst
- rasa/utils/common.py
> hide matplotlib debug logs

- docs/docs/installation.mdx
- docs/docs/prototype-an-assistant.mdx
- docs/docusaurus.config.js
- pyproject.toml
- rasa/version.py
- ready to go out and get tagged once code free is done
> Prepare release 2.0.0rc4

- changelog/6819.doc.md
- docs/docs/forms.mdx
- docs/docs/migration-guide.mdx
- doc changes for #6819 
- depends on https://github.com/RasaHQ/rasa-sdk/pull/288
> Form validation doc update

- docs/docs/policies.mdx
- port https://github.com/RasaHQ/rasa/pull/6917 to release branch
- close https://github.com/RasaHQ/rasa/pull/6917
> Rules docs update

- docs/docs/installation.mdx
- docs/docs/prototype-an-assistant.mdx
> remove notes about release alpha in docs

- rasa/core/agent.py
- Fixes https://github.com/RasaHQ/rasa-x/issues/3597.
> Delete model directory if it wasn't loaded correctly, when fetching from server

- rasa/cli/x.py
- rasa/exceptions.py
- rasa/nlu/components.py
- rasa/telemetry.py
- tests/cli/test_cli.py
> Avoid raising dependency exception if rasa x is not installed

- changelog/3597.bugfix.rst
- rasa/core/agent.py
- port https://github.com/RasaHQ/rasa/pull/6925 to 1.10.x
> Delete model directory if it wasn't loaded when fetching from server (1.10)

- rasa/core/training/training.py
- tests/core/policies/test_rule_policy.py
- fix collecting fingerprint for action_listen
> fix collecting fingerprint for action_listen

- docs/docs/training-data-format.mdx
> Training data doc bug

- rasa/shared/nlu/training_data/message.py
- tests/shared/nlu/training_data/test_message.py
Update the check on what message comes from core.
> Fix is_core_message()

- docs/docs/forms.mdx
- docs/docs/unexpected-input.mdx
- fix multi intent unhappy path in docs
- fixes https://github.com/RasaHQ/rasa/issues/6861
> fix multi intent unhappy path in docs

- changelog/6899.bugfix.rst
- rasa/core/test.py
> update predicted events in test tracker with policy and confidence

- CHANGELOG.rst
- changelog/3597.bugfix.rst
- changelog/6755.bugfix.rst
- changelog/6899.bugfix.rst
- changelog/6900.improvement.rst
- pyproject.toml
- rasa/version.py
> prepared release of version 1.10.15

- rasa/core/policies/mapping_policy.py
Missing mapping policy error message correction
> Correct missing mapping policy message
