src/emulators/wit.py
Error message I got:
```
127.0.0.1 - - [08/Nov/2016 17:24:07] "GET /parse?q=I+need+a+table+for+4pm HTTP/1.1" 200 -
plain response {'text': 'I need a table for 4pm', 'intent': 'inform', 'entities': {'cuisine': 'table'}}
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52584)
Traceback (most recent call last):
File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 318, in process_request
self.finish_request(request, client_address)
File …
```
=> Fix bug in wit emulator

docs/closeloop.rst, docs/config.rst, docs/contribute.rst, docs/index.rst, docs/migrating.rst, docs/tutorial.rst, docs/visualize.rst, setup.py, src/visualization/__init__.py, src/visualize.py
Thought it would be useful for debugging to have some basic support for visualising entities in training data. 
To use it you run e.g. 
```bash
python -mrasa_nlu.visualize data/examples/luis/demo-restaurants.json 
```
if you then point your browser to http://0.0.0.0:8080/ , you should see something like this:
implementation is pretty quick and dirty so **suggestions for improvement are welcome!**
=> visualise entities in training data

_pytest/test_training_data.py, src/training_data.py
Escaping the tokens to be matched If they include non-alpha chars like ? or (, the regex might not match them. Decoding the tokens to support non-ascii chars.
=> Escaping the tokens to be matched

_pytest/test_emulators.py, _pytest/test_server.py, _pytest/test_tokenizers.py, src/emulators/api.py, src/emulators/luis.py, src/emulators/wit.py, src/interpreters/mitie_interpreter.py, src/interpreters/mitie_sklearn_interpreter.py, src/server.py, src/tokenizers/mitie_tokenizer.py, src/training_data.py
addresses issue #44 
@plauto I would still have a test which includes the server, e.g. 
`requests.post(http_server + "/parse", json={"q": u"hello ńöñàśçií"})` in `test_post_parse()`
and you're right that entities should be a **list**, but with the start and end of each entity specified, e.g. 
```json
{
"text": "show me chinese restaurants",
"intent": "restaurant_search",
"entities": [
{
"start": 8,
"end": 15,
"value": "chinese",
"entity": "cuisine"
}
]
}```
=> Unicode server

src/trainers/spacy_sklearn_trainer.py, src/visualize.py
- Avoid setting `tagger` to `True` during spacy creation
- Properly visualize umlauts
=> fixed two issues with german spacy

src/trainers/spacy_sklearn_trainer.py
Issue - #72 
The error occurred because the `intent_classifier.pkl` file was not opened in binary mode while writing. As per [python docs](https://docs.python.org/2/tutorial/inputoutput.html#reading-and-writing-files) Windows makes a distinction between text and binary files. Changed the code to now open the file as binary - 
`open(classifier_file, 'wb')`
=> Fix for #72 - Error running sklearn backend on windows

requirements.txt
Currently building the docker image and running train will not work due to the lack of scipy, adding it to requirements fixes that.
=> Add scipy requirement for train to work in docker

entrypoint.sh
Use exec in entrypoint.sh so that it is replaced by python or whatever is started in the container. This makes sure that any signals are passed to python and not the entrypoint shell script.
=> Docker entrypoint script fix

src/server.py
This ensure that docker stop/restart etc which sends a SIGTERM signal will cause a graceful shutdown, saving log files and such. Previously docker stop will eventually have to simply kill the container, and log files will not be persisted.
=> Gracefully shutdown server on SIGTERM in addition to SIGINT

src/classifiers/sklearn_intent_classifier.py, src/trainers/spacy_sklearn_trainer.py
- a fixed number of examples was always used for testing
- to allow the training of the best possible model that parameter can now be configured (e.g. set to `0.0`)
=> Allow to specify percentage of test data during intent classification

.gitignore, config_mitie.json, config_spacy.json, data/README.md, docs/closeloop.rst, docs/contribute.rst, docs/http.rst, docs/migrating.rst, docs/tutorial.rst
- fixed configuration paths
- directly include json configuration examples into documentation instead of copying them (ensures the version in the documentation is up to date with the example files)
- fixed some `Title underline too short.` warnings
- added section to contribution page that explains how to setup and run the documentation
=> Fixed configuration and data file paths

setup.py, src/interpreters/spacy_sklearn_interpreter.py, src/trainers/spacy_sklearn_trainer.py, src/trainers/trainer.py, src/utils/spacy.py
If spacy did not properly load a model (e.g. if the user missed to download the language files) an exception is thrown. Previously the training would succeed without error and running the model would lead to uninformative exceptions (see #145).
=> Raise proper errors on if spacy is not loaded

.travis.yml, _pytest/test_config.py, _pytest/test_featurizers.py, _pytest/test_server.py, _pytest/test_train.py, _pytest/test_training_data.py, _pytest/trainers/test_mitie_trainer.py, requirements.txt, setup.cfg, src/classifiers/sklearn_intent_classifier.py, src/config.py, src/train.py, src/trainers/mitie_trainer.py, src/trainers/spacy_sklearn_trainer.py
- use multiple threads during training
- new option `-t` to specify number of threads
- spacy will only use multiple threads during intent classification - not during entity training
- small fix to save mitie models in the same way as spacy (added `create_unique_subfolder` option)
=> Multithreaded training

_pytest/test_train.py, _pytest/test_training_data.py, config_mitie.json, config_mitie_sklearn.json, src/interpreters/mitie_sklearn_interpreter.py, src/server.py, src/train.py, src/trainers/mitie_sklearn_trainer.py, src/trainers/mitie_trainer.py, src/trainers/mitie_trainer_utils.py, src/trainers/sklearn_trainer_utils.py, src/trainers/spacy_sklearn_trainer.py, src/trainers/trainer.py, src/training_data.py
Fixes #137 
Might need to to perform a further update once https://github.com/golastmile/rasa_nlu/pull/151 is accepted in order to add support for the synonyms within the interpreter
=> Refresh mitie sklearn and add tests

_pytest/test_training_data.py, data/examples/api/entities/cuisine.json, data/examples/rasa/demo-rasa.json, src/__init__.py, src/interpreters/mitie_interpreter.py, src/interpreters/mitie_sklearn_interpreter.py, src/interpreters/spacy_sklearn_interpreter.py, src/trainers/mitie_sklearn_trainer.py, src/trainers/mitie_trainer.py, src/trainers/spacy_sklearn_trainer.py, src/trainers/training_utils.py, src/training_data.py, src/util.py
Addresses #106 
now we should be able to generate synonyms from the training data. If any entity is referenced to by one or more synonym then we create a new file named `index.json` where we save the mapping between a word and it's basic form.
For an example of the mapping and a description of the solution, please see the issue in attachment
=> Entity synonym

_pytest/test_config.py, _pytest/test_train.py, src/config.py, src/extractors/spacy_entity_extractor.py, src/train.py, src/trainers/mitie_sklearn_trainer.py, src/trainers/spacy_sklearn_trainer.py
first commit:
- fixed regression of #152 (trainer `persist` got screwed up & entity extractor was not set after training)
second commit:
- improved training tests (they now check if entity extractor & intent classifier exist)
- fixes #166 (allows to fine tune spacys provided NER models with the training data)
- don't `finish` after entity training. fixes #136
=> Provide option to fine tune spacy NER model instead of training from scratch

src/interpreters/mitie_interpreter_utils.py
The current code in the interpreters folders: mitie_interpreter_utils.py gives an incorrect result for the following made up example in the restaurant data:
`I am looking for northern food in the north part of town`
I used this example because it illustrates the point, the `location` `north` entity has a wrong start and end - and overlaps with the `northern` `cuisine` entity.
Before the change:
```
{
"confidence": 0.6449555829969771,
"entities": [
{
"end": 25,
"entity": "cuisine",
"start": 17,
"value": "northern"
},
{
"end": 30,
"entity": "cuisine",
"start": 26,
"value": "food"
},
{
"end": 22,
"entity": "location",
"start": 17,
"value": "north"
}
],
"intent": "restaurant_search",
"text": "I am looking for northern food in the north part of town"
}
```
After the change:
```
{
"confidence": …
```
=> Wrong start and end of entities due to missing offset

README.md
For download & training to work correctly on that platform.
Fixes #237
=> Add Windows for Docker caveat

_pytest/test_training_data.py, rasa_nlu/converters.py, requirements.txt
- validate rasa nlu formatted training data before using it
- a couple of users used wrongly formatted training data which results in strange errors as we simple read the data as json and use it as an object. previous to this PR, errors would surface in strange places.
- this disallows to use e.g. `3` (as a number) as a `"value"` for an entity (see the changed training example). I don't think that this would result in anything useful anyway (since we will never produce non string entity values).
**Status**:
=> Training data validation using json schema

_pytest/test_train.py, _pytest/utilities.py, rasa_nlu/model.py
Throws an exception if the user created a configuration that results in an empty pipeline, i.e. no components are in there. (e.g. happens if the user uses a configuration from 0.7 without a proper migration to 0.8)
=> Fail if pipeline is empty

CHANGELOG.rst, _pytest/test_config.py, _pytest/utilities.py, docs/config.rst, docs/migrations.rst, docs/pipeline.rst, rasa_nlu/config.py, rasa_nlu/extractors/spacy_entity_extractor.py, rasa_nlu/registry.py, rasa_nlu/server.py, rasa_nlu/version.py
- fixes #319 
Hey wasn't to sure about what you mean by removing the training capability of the component:
1. Does this mean to completely remove the training methods: train, finetune, etc.?
2. But then it seems the training is also somehow related to the extraction of entities: 
`if spacy_nlp.entity is not None and self.fine_tune_spacy_ner:`. So I didn't remove anything yet.
@tmbo Could you take over the removal of the necessary parts given the time constraints and your knowledge of the component's internals? Happy to review the changes!
**Status**:
=> replaced spacy_ner with ner_crf in standard pipeline

_pytest/test_components.py, _pytest/test_emulators.py, _pytest/test_interpreter.py, _pytest/test_train.py, rasa_nlu/components.py, rasa_nlu/data_router.py, rasa_nlu/emulators/__init__.py, rasa_nlu/extractors/duckling_extractor.py, rasa_nlu/model.py
Duckling module also supports passing a context using reference_time argument. We can pass a string in RFC3339 format (Eg: '2008-09-08T22:47:31-07:00').
Example: Parsing "tomorrow" with reference_time set to `2008-09-08T20:30:00-07:00` gives back 
`2008-09-09T00:00:00.000-07:00`
Since Rasa supports duckling in the pipeline, I think this will be a useful addition.
**Status**:
=> support reference_time for duckling

docs/pipeline.rst
=> Fix typo in Doc: "classifcation" to "classification"

config_defaults.json, docs/config.rst, docs/http.rst, rasa_nlu/config.py, rasa_nlu/server.py, requirements.txt
- Add CORS option to config as described in #478 
**Status**:
=> Cors support

rasa_nlu/data_router.py
Hey there,
When I use the `/train` route on your server to re-train my models, I get an encoding error (`{"error": "'ascii' codec can't encode character u'\\u2019' in position 29892: ordinal not in range(128)"}`). This happens because I have french punctuation in my training data (`ê`, `é` and friends).
I just propose that we use an UTF-8 encoding on the incoming data. I did prefer to use `f.write(data.encode("utf-8"))` instead of `f.write(data, encoding="utf-8")` for python 2.7 support.
Tested and working on my local server.
I'll wait for your input before writing tests and updating the changelog.
Fixes #524
**Status**:
=> Fix server training encoding

rasa_nlu/extractors/mitie_entity_extractor.py
- allow mitie_ner to skip the examples with entity boundry problem and to output warning messages, while currently mitie_ner stops if such problems exist in any of traning examples. Issue stated as #528 .
**Status**:
=> issue528 in extractors/mitie_entity_extractor.py

rasa_nlu/extractors/entity_synonyms.py
**Proposed changes**: reformat single-line json file
- Currently, entity_synonyms.json contains a single line. It poses difficulties for showing its content for example via Eclipse or various editors and for human-readability, if the file contains much information. Secondly, I see other json files in Rasa-NLU project are all of multiple-line style. So I suggest to reformat entity_synonyms.json
**Status**:
=> one-line file entity_synonyms.json reformatted

README.md
Just a readme change. I'll be perusing for other changes that are needed.
=> Fix version typo in readme for docker commands

_pytest/test_server.py, rasa_nlu/server.py
API.ai doesn't use `q` it uses `query`, rather than handling this in a custom way I think it makes sense to just allow people to submit either q or query and handle both.
- I'm just doing a simple check for `query` in the request parameters and replacing that with `q` if it exists.
**Status**:
=> If /parse contains query remap to q

rasa_nlu/data_router.py, rasa_nlu/server.py, rasa_nlu/train.py, tests/base/test_server.py
- If a training errored, the status of the project was not updated (still `training`) therefore preventing new training requests for this project. This introduce a new Exception wrapper returning the name of the project for which an exception occurred during training.
**Status**:
=> Fixed error in training preventing new training requests

docs/languages.rst
- Fixed 2 typos for the word 'language'
- Corrected `spaCy` and `Wikipedia`
> Did not correct 'alot' since its a valid internet word :)
=> Typos on Language Support page

.travis.yml
- fixes travis build by skipping the docs stage if a PR is originated in a fork
=> Skip doc creation on PRs from forks

CHANGELOG.rst, docker/Dockerfile_devtest, rasa_nlu/config.py, rasa_nlu/data_router.py, rasa_nlu/persistor.py, rasa_nlu/project.py
Adds a fix for issue #633 (S3 persistence for models not working in 0.10.1). The issue is that models persistent in S3 are not loading on server startup.
- most important: update `rasa_nlu/persistor.py` to use API of boto3 (Seems to currently call methods from boto2 but boto3 is installed as per requirements. Compare http://boto.cloudhackers.com/en/latest/ref/s3.html#boto.s3.bucket.Bucket.list vs http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Bucket.objects).
- extracts constant DEFAULT_PROJECT_NAME to `RasaNLUConfig` to make it accessible in both `rasa_nlu/data_router.py` and `rasa_nlu/persistor.py`. Required for loading models for project "default" since currently, it tried to load S3 objects whose key starts with "None_" but training creates …
=> fix s3 model training and loading

docs/installation.rst
Fixes filename for TIP on installing all dependencies.
Correct filename is `alt_requirements/requirements_full.txt`
- [] made PR ready for code review
=> Doc on dependency installation instructions

rasa_nlu/data_router.py
- This fixes the out-of-the-box failure generated by an info level logging statement that doesn't include a format string to format.  It's not a good fix (it adds an empty string), but it is at least concise.
```
curl -XPOST localhost:5000/parse -d '{"q":"hello there", "model": "default" }'
{"error": "'NoneType' object has no attribute '_formatter_parser'"}
```
=> quick fix for None "_formatter_parser" bug

rasa_nlu/server.py
Logging exceptions and their stack trace for internal server errors on parsing. Otherwise, it can be difficult to understand which pipeline component is having trouble. Even searching for the specific error message does not necessarily lead to results, since it might not originate from within rasa.
=> parsing-exception-stacktrace

rasa_nlu/server.py
The `request.args` dictionary for Klein under python3 uses byte strings as for keys and values. As a result, the token cannot be retrieved using a normal string. See https://github.com/twisted/klein/issues/157
=> fixing token auth for py3

rasa_nlu/extractors/duckling_extractor.py, rasa_nlu/extractors/duckling_http_extractor.py
=> Duckling - handle intervals

rasa_nlu/config.py
**Proposed changes**: The latest master is throwing the following warning which signifies that the storage parameter in the config is missing:
WARNING:rasa_nlu.project:Failed to list models of project xxxxxx. u'No persistent storage specified. Supported values are aws, gcs'
Just added "storage": None,
- ...
=> Fix missing storage config parameter

README.md
- Replaced `api.ai` mentions with `Dialogflow` in README
=> Replace api.ai mentions with Dialogflow in README

rasa_nlu/project.py
- Currently only models that start with `model_` are loaded and shown in the `/status` endpoint.
=> Remove Model Naming Requirement for loading

rasa_nlu/extractors/entity_synonyms.py
- Non-ASCII characters in entity synonyms can generate a `UnicodeEncodeError`
- this is avoided by wrapping each argument of the warning message with `repr()`
=> Avoid UnicodeEncodeError by using repr() in warning

rasa_nlu/config.py
- currently the nlu crashes on env vars that contain "RASA" but not "RASA_"
this is a fix.
- [*] made PR ready for code review
=> fix: crash on unexpected env vars

rasa_nlu/utils/md_to_json.py
- Add a strip_comments() function in md_to_json.py which removes MarkDown
comments from a line
- The function uses a regexp to detect and remove comments
- Call the function before processing each line of the file being read
=> Fix bug in MarkDown to JSON conversion

docs/tutorial.rst
The link points to a domain with an expired SSL cert which then redirects to the Medium homepage.
- Update the link to https://medium.com/rasa-blog/put-on-your-robot-costume-and-be-the-minimum-viable-bot-yourself-3e48a5a59308
=> Update link for "pretend to be the bot yourself"

data/test/demo-rasa-small.md, docs/dataformat.rst, rasa_nlu/utils/md_to_json.py, tests/base/test_training_data.py
- Since the training data format already supports markdown, I added support for listing examples as [unordered lists](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) using asterisks `*` instead of minus `-` symbols.
- Removed some PEP8 errors from `rasa_nlu/utils/md_to_json.py`
E.g.
```
* yes
* yep
* yeah
```
=> Added Support for Asterisks in Markdown Training Files

.travis.yml, CHANGELOG.rst, README.md, alt_requirements/requirements_dev.txt, docker/Dockerfile_test, docs/installation.rst, requirements.txt
- Removes `-e .` from all `requirements.txt` files (which messes with some tools, although recommended from parts of the python community - safer to separately do `pip install -r requirements.txt` and `pip install -e .`)
=> remove -e . from requirements

alt_requirements/requirements_dev.txt, rasa_nlu/config.py, rasa_nlu/convert.py, rasa_nlu/extractors/duckling_extractor.py, rasa_nlu/extractors/duckling_http_extractor.py, rasa_nlu/extractors/entity_synonyms.py, rasa_nlu/featurizers/regex_featurizer.py, rasa_nlu/model.py, rasa_nlu/server.py, rasa_nlu/training_data.py, rasa_nlu/utils/__init__.py, tests/base/test_multitenancy.py, tests/base/test_server.py, tests/utilities.py
- Fix #683 
- Use `ensure_ascii=False` as default for `json.dumps` so that non-ascii characters are not escaped. Any opinion on this approach vs. having a wrapper for `json.dumps` that we use across the code base?
=> default ensure_ascii=False for json dumps

data/examples/rasa/demo-rasa.json, data/examples/rasa/demo-rasa.md, rasa_nlu/utils/md_to_json.py, tests/base/test_training_data.py
- Fixes entity parsing in Markdown converter  
Previously samples such as `show me [chines](cuisine:chinese) restaurants in the [north](location)` would get wrong start/end offsets due to the use of two regexes in the code
=> Fixes entity parsing in markdown

CHANGELOG.rst, docs/evaluation.rst, docs/index.rst, rasa_nlu/evaluate.py, rasa_nlu/extractors/crf_entity_extractor.py, rasa_nlu/model.py, tests/evaluation.py
1. Extended evaluation script to measure entity extraction performance. I used a simple tag-based approach, as opposed to using BILOU tags, i.e. we only have entity tags like "LOC" instead of "B-LOC", "I-LOC" etc. This approach is a tad more lenient when it comes to evaluation since it also rewards partial extraction and does not punish the split of an entity. It is debatable which approach is better, but partial eval might be a tad more realistic. For example, the given the entity "near Alexanderplatz" and a system that extracts "Alexanderplatz", the simple tags would reward the extraction of Alexanderplatz and punish the missed out word "near". The BILOU tags, however, would evaluate it as a complete failure since "Alexanderplatz" should be an inside- or a closing …
=> NER evaluation

rasa_nlu/converters.py
When converting from DialogFlow you get this `@sys.ignore` all over the place. The PR is a simple fix for this
```
- [je veux](@sys.ignore) parler [avec toi](@sys.ignore)
- [et](@sys.ignore) [si](@sys.ignore) [on](@sys.ignore) discutait
- [j](@sys.ignore)'aimerais bavarder
```
=> fixed @sys.ignore entities all around when converting from Dialogflow

rasa_nlu/utils/spacy_utils.py
I noticed because of case sensitivity, the SVM intent classification is failing in some cases. For example, the text '**hello**' with different cases results different classification. So using the lowercase for spacy_doc in both training and request processing.
> MVUNDELA-MBP:rasa mvundela$ curl 'http://localhost:5001/parse?q=**Hello**'
> {"entities": [{"start": 0, "extractor": "ner_crf", "end": 5, "value": "Hello", "entity": "greetings_identifier"}], "intent": {"confidence": 0.9475492827995153, "name": "**smalltalk_greetings**"}, "text": "Hello", "intent_ranking": [{"confidence": 0.9475492827995153, "name": "smalltalk_greetings"}, {"confidence": 0.016386606127676846, "name": "smalltalk_positive"}, {"confidence": 0.008669188232799085, "name": "smalltalk_negative"}, {"confidence": …
=> Fixing the case sensitive issue for intent classification

CHANGELOG.rst, data/examples/rasa/multiple_files_json/demo-rasa-affirm.json, data/examples/rasa/multiple_files_json/demo-rasa-goodbye.json, data/examples/rasa/multiple_files_json/demo-rasa-greet.json, data/examples/rasa/multiple_files_json/demo-rasa-restaurant_search.json, data/examples/rasa/multiple_files_markdown/demo-rasa-affirm.md, data/examples/rasa/multiple_files_markdown/demo-rasa-goodbye.md, data/examples/rasa/multiple_files_markdown/demo-rasa-greet.md, data/examples/rasa/multiple_files_markdown/demo-rasa-restaurant_search.md, docs/config.rst, docs/dataformat.rst, rasa_nlu/converters.py, tests/base/test_training_data.py
- allow splitting for JSON format
- allow splitting for markdown format
This fixes #180 at least for the Rasa-native formats.
Tested with split files using:
`converters.load_data(dir_containing_multiple_md_files).as_json()`
and
`converters.load_data(dir_containing_multiple_json_files).as_json()`
I did not touch the other formats as I cannot test those.
=> Allow to use split training files into multiple files (#180)

CHANGELOG.rst, rasa_nlu/extractors/__init__.py, rasa_nlu/extractors/crf_entity_extractor.py, tests/base/test_extractors.py
- ``Extractor`` objects have the option to filter out pretrained entity examples
- implemented in the ``CRFEntityExtractor``
=> Filter out pre-trained entities before CRF entity training

CHANGELOG.rst, rasa_nlu/data_router.py, rasa_nlu/project.py, rasa_nlu/server.py, tests/base/test_multitenancy.py, tests/base/test_server.py
- only ever keep one model per project in the server's memory under `Project._models`
- unload previous NLU model from `Project` when a new model is requested by the server
=> Unload unused models from server memory

rasa_nlu/evaluate.py, rasa_nlu/extractors/crf_entity_extractor.py, tests/base/test_evaluation.py
- Before, entity predictions were always extracted which isn't possible when only using the tensorflow classifier pipeline because it has no tokenizer. Now we check whether an intent classifier/entity extractor is present before running evaluation on either. (this also means no weird confusion matrix is generated when only evaluating an NER pipeline)
- We also skip evaluation of duckling
- Fixed the crf extractor 
=> Make evaluation script compatible with tensorflow classifier

docs/pipeline.rst, rasa_nlu/featurizers/count_vectors_featurizer.py, tests/base/test_featurizers.py
- replace pure number tokens like `90210` with `NUMBER` in `countvectorfeaturizer`
questions:
- should this be configurable? is there any use case where different numbers might indicate a different intent?
- if we do this, it should obviously be well documented behaviour
- It might be an idea to also have a special `OOV` token (for test time) because e.g. a lot of unfamiliar words will likely indicate an out of scope utterance. Not as straightforward to implement bc as it's currently implemented all tokens in the training set are in the vocab (so no way for model to learn how to use what's in the OOV column)
@Ghostvv @akelad @tmbo 
=> text normalisation

.travis.yml
- build docs onto the `docs` branch instead of `gh-pages` (this will allow us to deactivate github page hosting of the docs)
- fixes #998 
=> push docs to docs branch

rasa_nlu/data_router.py, rasa_nlu/project.py, rasa_nlu/server.py
**Proposed changes**: Preload the projects into the memory before starting the server as per user requirement through command line argument. By default, no projects will be loaded. If specified an argument `--pre_load` as `all`, all the projects will be preloaded with the latest model. Otherwise, the user can specify a list of projects and those alone will be preloaded.
=> Preload the projects into the memory before starting the server

rasa_nlu/featurizers/count_vectors_featurizer.py
- Lowercase text before passing to count vector featurizer. I think wanting to threat capitalised & uncapitalised words differently is such a rare use case that we don't even need to make this confugrable. thoughts?
=> lowercase text in count vector featurizer

rasa_nlu/evaluate.py
- This refactores the evaluate script, so that the script can be called via the main function from somewhere else.
- Use case: We want to set different numpy printoptions before running the script.
=> Allow to run evaluate script from other code via main function.

CHANGELOG.rst, rasa_nlu/server.py, tests/base/test_server.py
- ...
added ability to accept pure json that includes both pipeline configuration and rasa data in the /train endpoint of the http server. 
- [x ] made PR ready for code review
- [x ] added some tests for the functionality
=> Train with json config

README.md
The currently used homepage for LUIS will not respond as apparently the host is not configured to respond to naked domain requests.
=> Fix URL for LUIS in README

rasa_nlu/tokenizers/spacy_tokenizer.py
- `SpacyTokenizer` component is missing `requires = ["spacy_doc"]` requirement which is used for validating pipeline correctness on pipeline initialization.
=> Add missing "requires" to spacy tokenizer

CHANGELOG.rst, docs/evaluation.rst, rasa_nlu/evaluate.py, tests/base/test_evaluation.py
- log the intent samples which failed during evaluation with text, prediction confidence and true label
- show and save histogram of confidence scores
- auto-save confusion-matrix
=> log wrong intent predictions during evaluation / show histogram of confidence scores

CHANGELOG.rst, rasa_nlu/extractors/duckling_http_extractor.py
- we were passing it in seconds previously, but duckling needs it in miliseconds and so it was just showing the current date to be in 1970 😄 
- fixes #1291 
=> Pass duckling reference time in miliseconds

rasa_nlu/evaluate.py
Regarding issue #1289, using `ensure_ascii=False` in the parameter of json dump inside the `save_nlu_errors` function, non-ascii characters will be show correctly in the `error.json` file.
=> support non-ascii characters in errors.json

rasa_nlu/evaluate.py
`run_evaluation` has `errors_filename` as optional param.
it passed to `evaluate_intents` but the func assumed that value is valid (not None)
so when you don't pass it, it riases an exception in `save_nlu_errors`.
while I can understand that `run_evaluation` to be called from `main` and it pass default value 
if caller doesn't provide the value but you can't expect that caller will always use `evaluate.main` to call `run_evaluation`. thus I propose add same default value to `run_evaluation`.
=> ADD default value of errors_filename to run_evaluation

setup.py
- Add missing `scipy` dependency to tensorflow pipeline extras - should fix most parts of #1315
=> Add missing scipy dependency to tensorflow pipeline extras

docs/http.rst
unloading a model from the server memory should pass the parameters through the URL
- ...
- [√] updated the documentation
=> Update command of unloading models

rasa_nlu/evaluate.py
Fix for the issue #1298 (namedtuple bug in evaluate.py)  on all-zero embedding vectors and replacing None with empty string in evaluation script 
- replace line 176 in evaluate.py with r = r._replace(prediction="")
=> fix for the issue #1298 

docs/fallback.rst
- `Fallback Policy` should linked to `/docs/core/fallbacks/`
=> Fix doc link target 404

CHANGELOG.rst, docs/evaluation.rst, rasa_nlu/evaluate.py
- Change `evaluate.py` script to allow for separate histogram bars plotting wrong and correct intent predictions confidence distributions.
Changes related to issue #1354
=> Separate confidence distributions histograms

.gitignore, CHANGELOG.rst, rasa_nlu/training_data/formats/markdown.py, tests/base/test_training_data.py
- fixed entity regex for markdown files to support special characters in the entity name (e.g. `-` or `#`)
- characters not allowed: `:` and `)`
- fixes #1360
=> fixed entity regex for markdown files. 

CHANGELOG.rst, rasa_nlu/project.py, tests/base/test_project.py
=> Add flag to projects that pull remotely and use in-memory model

CHANGELOG.rst, alt_requirements/requirements_bare.txt, alt_requirements/requirements_dev.txt, rasa_nlu/persistor.py, tests/base/test_persistor.py
- Lazy-import for `boto3` and `botocore` since they are only used for persisting the model to S3.
=> Lazy-import boto3

rasa_nlu/emulators/dialogflow.py, tests/base/test_emulators.py
Fixes https://github.com/RasaHQ/rasa_nlu/issues/1484
- Set DialogFlow response key `action` to intent name
- Set DialogFlow response key `score` to intent confidence
=> Fix DialogFlow emulator response to match API

README.md
**Problem**:
- https://github.com/RasaHQ/rasa_nlu/issues/1504
- The curl command to train the NLU server based on a http request with a yaml body led to an error 
```json
{
"error": "while parsing a block mapping\n  in \"<unicode string>\", line 1, column 1:\n    language: \"en\"pipeline: \"spacy_s ... \n    ^\nexpected <block end>, but found '<scalar>'\n  in \"<unicode string>\", line 1, column 15:\n    language: \"en\"pipeline: \"spacy_sklearn\"# data  ... \n                  ^"
}
```
- use  the `--data-binary` flag as it is done for the curl command in the readme
=> fix the curl command for the nlu json training

docs/components.rst, rasa_nlu/classifiers/embedding_intent_classifier.py, tests/training/test_train.py
Training the Tensorflow Embedding currently gives different results after each run, even if nothing else changed. This can lead to very unstable behavior especially with regards to unseen samples, but also for the training data. For example the user input "ich brauche zahnersatz" yields totally different results after two runs with exactly the same parameters and data. This sample is a part of a slightly longer sample which is in the training data:
rasa_core.processor  - Received user message 'ich brauche zahnersatz' with intent '{'name': 'zahnersatz_zuschuss', 'confidence': 0.909192681312561}' 
rasa_core.processor  - Received user message 'ich brauche zahnersatz' with intent '{'name': 'zahnersatz_zuschuss', 'confidence': 0.6224032044410706}'
The same goes for actual training data like …
=> Set random seed for embedding pipeline (default is None)

CHANGELOG.rst, docs/endpoint_configuration.rst, docs/index.rst, rasa_nlu/utils/__init__.py, tests/base/test_utils.py
- see issue #1517
- allow specification of environment variables in yaml configuration files.
- these are specified with `${x}`
- prefixes and postfixes are picked up, e.g. `dir/${x}/another` with `x=path` becomes `dir/path/another`
=> replace environment variables in config files with actual values #1517

CHANGELOG.rst, alt_requirements/requirements_bare.txt
- fixes https://github.com/RasaHQ/rasa_nlu/issues/1514
- increment cloudpickle to use the latest release
**Testing**
- You can test this running the container on gcloud. Before the pr it failed before with the error from the issue. 
=> use cloudpickle==0.6.1

alt_requirements/requirements_tensorflow_sklearn.txt
- According to [Issue #1315](https://github.com/RasaHQ/rasa_nlu/issues/1315), the lack of `scipy` in requirements list might cause a fail at training with TensorFlow.
=> Missing dependency for TensorFlow

CHANGELOG.rst, alt_requirements/requirements_bare.txt, data/examples/rasa/demo-rasa.json, rasa_nlu/config.py, rasa_nlu/utils/__init__.py, setup.py, tests/base/test_server.py, tests/base/test_utils.py, tests/utilities.py
- replace `pyaml` with `ruamel.yaml` since it is 
* better supported
* handles emojis in yamls out of the box
- provide encoding for the created tmp file
=> handle emojis when running as server

rasa_nlu/utils/__init__.py, tests/base/test_utils.py
- try parsing it as usual and apply emoji fixes only in case of a `ScannerError``
- add more test cases
- ~[ ] updated the changelog~ (already included in changelog)
=> fix emoji errors with regex patterns

CHANGELOG.rst, alt_requirements/requirements_spacy_sklearn.txt, alt_requirements/requirements_tensorflow_sklearn.txt, rasa_nlu/classifiers/sklearn_intent_classifier.py, setup.py
`scikit-learn==0.20.2` has a nice `output_dict` feature we can use in our evaluate script, but it was causing [errors with our classifier](https://github.com/RasaHQ/rasa_nlu/issues/1600)
- Transpose `intent_ids` vector
- Pin `scikit-learn==0.20.2`
=> Increase scikit-learn version

CHANGELOG.rst, rasa_nlu/utils/spacy_utils.py
Closes #1649
Use Spacy 2 syntax to disable dependency parser
See the note "Uses Spacy 2 syntax to disable dependency parser" in https://spacy.io/usage/processing-pipelines#disabling
=> Uses Spacy 2 syntax to disable dependency parser

rasa_nlu/classifiers/embedding_intent_classifier.py
Commit 4c6b1e3 introduced additional type hints. Prior to PEP 563 (Python 3.7+) these are evaluated directly. In the class `EmbeddingIntentClassifier` type hints for TensorFlow classes are added which result in a crash if TensorFlow can not be imported.
By expressing tf type hints as string literals this problem can be avoided.
=> Fixes type hints if tensorflow is not imported

.travis.yml
Many of the past travis tests failed because this download:
```
wget --quiet -P /tmp/cached/ https://s3-eu-west-1.amazonaws.com/mitie/total_word_feature_extractor.dat
```
took longer than the standard 10 minute timeout. 
This PR precedes it with the travis_wait function which doubles the timout to 20 minutes according to the [docs](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received).
=> fix travis build timeout error

rasa_nlu/evaluate.py
- re-add evaluate with deprecation warning
=> add evaluate with deprecation warning

CHANGELOG.rst, rasa_nlu/test.py, tests/base/test_evaluation.py
- update do_extractors_support_overlap to return false with empty list of extractors
=> Fix extractors overlap

rasa_nlu/training_data/formats/dialogflow.py, tests/base/test_training_data.py
- When using RASA with Dialogflow input data format, you don't get the added benefits of lookup tables as it is not added during the format transformation. This PR adds the lookup table from the entity examples
=> Process lookup table when transforming Dialogflow Data

rasa_nlu/training_data/util.py
There was a small formatting error in the error message in case of inconsistent synonyms (the overwritten synonym was displayed instead of the replacement). Additionally, I added a space before with.
- ~~added some tests for the functionality~~
- ~~updated the documentation~~
=> Fixes warning of inconsistent entity synonyms

rasa_nlu/classifiers/mitie_intent_classifier.py
I wonder if the `import mitie` should perhaps also just happen in the beginning.
Currently it is imported at the beginning of the module only `if typing.TYPE_CHECKING` but then it is imported in two different methods.
=> removed unnecessary import

rasa_nlu/featurizers/regex_featurizer.py
Windows defaults to using cp1252 for open.  This creates a UnicodeError potentially when trying to
use files for Lookup Tables (list method still works in Windows).  Apply this fix such that the encoding is
explicitly utf-8 (as it is in other places in the repository).
- Change the open statement to use encoding='utf-8' as to do other open statements throughout the project.
- fixes #1781 
=> Issue #1781.  Resolving UnicodeError for Windows and Lookup Tables via file method

setup.py
tf 1.13.* satisfies the current requirement:
```
Requirement already satisfied: tensorflow~=1.12; extra == "tensorflow" in /Users/erohmensing/anaconda3/envs/demobot/lib/python3.6/site-packages (from rasa_nlu[tensorflow]~=0.14.4->rasa-demo==1.1) (1.13.1)
```
but that isn't compatible with core:
```
rasa-core 0.13.4 has requirement tensorflow~=1.12.0, but you'll have tensorflow 1.13.1 which is incompatible.
```
this will match the core requirement and require that the version be 1.12.*
=> fix tf requirement

rasa_nlu/version.py
merged PR #1787 on 0.14.x because the pip download requirements were allowing users to keep tensorflow `1.13.*` when we only support `1.12.*`. This may be moot on master if by the next major release we switch to tf `1.13.1` to support python 3.7 (#1709) though.
=> merge 0.14.x into master

rasa/core/policies/fallback.py
- Log a message in the `FallbackPolicy` when the `core_threshold` is used as confidence. In case the FallbackPolicy was chosen in the end, the user knows from the log message before, that there was no other action policy that had a higher confidence than the `core_threshold`.
=> FallbackPolicy: Log if core threshold is used as confidence

examples/concertbot/Makefile, examples/formbot/Makefile, examples/moodbot/Makefile, rasa/core/policies/form_policy.py, rasa/core/test.py
-  FormAction is not run, so we add `ActionExecutionRejected` event if form action is predicted, but not expected and if "unhappy" intent is remembered by FormPolicy
- fixes #2792 
=> emulate form rejection in evaluation

README.md
The dependencies txt file "requirements-dev" appears to be named "dev-requirements" by mistake which results in pip package installation error.
- ...
- [Y] made PR ready for code review
- [Y] updated the documentation
=> Updating requirements-dev filename

docs/nlu/components.rst
- we already have this option to set a duckling url environment variable (to be able to change your duckling url for the same trained model in a different environment, for example) -- this puts the information in the docs. See #3216 
=> add info about duckling url env var to docs

docs/core/docker_walkthrough.rst
I got this error when running docker-compose up : "No project found with name 'current'."
I fixed it by changing “current” to “default”
=> update docker-walkthrough docs

docs/nlu/languages.rst
- Updated link to pretrained fastText vectors since current link is dead (404).
=> Updated link to pretrained fastText vectors

CHANGELOG.rst, rasa/cli/test.py, rasa/cli/train.py, rasa/cli/utils.py, rasa/core/server.py, rasa/core/test.py, rasa/nlu/test.py, rasa/test.py, tests/core/test_evaluation.py
- ``rasa test`` was ignoring additional arguments, such as `e2e` or `successes`, before. now those arguments are considered and used during evaluation.
related to #3272 
=> rasa test: make use of additional arguments

CHANGELOG.rst, rasa/cli/interactive.py, rasa/cli/train.py, rasa/train.py, tests/core/conftest.py
- `rasa train` fails if only `nlu.data` or `stories.md` are provided. Both data types need to be there in order to execute `rasa train`
- `rasa train core` and `rasa train nlu` will also fail if data is missing
- add `rasa interactive core` to train a core model in interactive mode (regex interpreter will be used for the nlu part - no nlu model is trained)
- `rasa interactive` fails if only `stories.md` data are provided.
related to #3272 
=> Cli rasa interactive

rasa/core/channels/botframework.py, rasa/core/channels/callback.py, rasa/core/channels/channel.py, rasa/core/channels/facebook.py, rasa/core/channels/mattermost.py, rasa/core/channels/rocketchat.py, rasa/core/channels/slack.py, rasa/core/channels/socketio.py, rasa/core/channels/telegram.py, rasa/core/channels/twilio.py, rasa/core/channels/webexteams.py
- call `request.form` instead of `request.values` -- as far as I can see the sanic `Response` class doesn't have this functionality 
- typing
=> fix call to request.values

rasa/cli/x.py, tests/cli/test_rasa_x.py
- fixes the "Input is not to a terminal (fd=4)." error if no credentials are given
- automatically inserts `rasa` channel credentials if none are present
=> create rasa credentials if not given

rasa/test.py
`rasa test`/ `rasa test core`: Per default use a `RegexInterpreter` for the evaluation. Only when the user runs a `e2e` evaluation, the NLU model gets loaded for the evaluation it it is present.
Fixes `WARNING  rasa.core.training.dsl  - Found unknown intent 'None' on line 22. Please, make sure that all intents are listed in your domain yaml.`
=> 'rasa test' use RegexInterpreter by default

docs/migrations.rst, rasa/cli/arguments/data.py, rasa/cli/arguments/default_arguments.py, rasa/cli/arguments/interactive.py, rasa/cli/arguments/run.py, rasa/cli/arguments/test.py, rasa/cli/arguments/train.py, rasa/cli/arguments/visualize.py, rasa/cli/arguments/x.py, rasa/cli/test.py, rasa/cli/visualize.py, rasa/cli/x.py, rasa/nlu/convert.py, rasa/train.py, tests/cli/test_rasa_data.py, tests/cli/test_rasa_test.py, tests/cli/test_rasa_visualize.py, tests/cli/test_rasa_x.py
- Use `--out` for all kind of output files/directories (before `--out`, `--output`, `--out-file`).
- Use `--nlu` for specifying NLU data (before `--nlu`, `--nlu-data`).
- Use `--data` for specifying data files/data directory (before `--data`, `--data-file`, `--data-path`).
=> Standardized command line arguments

rasa/core/training/visualization.py
A typo in the sanitize function caused it to always remove the first
character (alphanumerical or _ - or whitespace) from messages before they
would be used to label the graph.
This has been changed to remove any characters from the message other than alphanumerical, white space or ,.'@!?-_
=> sanitize() now removes unusual character instead of the first

rasa/core/training/interactive.py, rasa/utils/io.py
- Create output paths for `stories.md` and `domain.yml` file if path not exists.
related to http://github.com/RasaHQ/rasa/issues/3504
=> Interactive learning: Fix  "No such file or directory: 'data/core/stories.md'"

docs/conf.py, docs/core/about.rst, docs/index.rst, docs/nlu/about.rst
- add what used to be the landing pages of Core and NLU docs as nlu/about and core/about
=> Add nlu core about pages

rasa/core/utils.py, rasa/model.py, rasa/train.py, tests/core/test_model.py
- Divide fingerprint of `config.yml` into three parts: core config, nlu config, remaining config
- Re-train NLU model if remaining config or nlu config changed
- Re-train Core model if remaining config or core config changed
=> Re-train only NLU/Core model if corresponding config parameters changed

rasa/nlu/training_data/training_data.py
- Changing `rasa.nlu.training_data.training_data.TrainingData.persist()` to work more smoothly. Previously, there were `filename` and `fformat` parameters. This meant that you could specify a file called `filename.md` and a file format `json`. and you would get a markdown file with a json file extension. I think it makes more sense to just add the filename and then check the extension of that filename.
=> changing persist to work more smoothly with markdown

CHANGELOG.rst, rasa/cli/x.py, tests/cli/test_rasa_x.py
- add assertions to avoid https://github.com/RasaHQ/rasa/issues/3606
=> check if local tracker store is the correct one

rasa/cli/run.py, rasa/core/agent.py, rasa/core/run.py, rasa/model.py, rasa/run.py
`rasa run --enable-api` does not need a model. The server can start without any model as you are able to train a model via the API once the server is up and running.
closes https://github.com/RasaHQ/rasa/issues/3588
=> enable-api does not need a model.

rasa/core/agent.py, rasa/core/domain.py, rasa/train.py
Move method `warn_missing_templates` out of `_check_domain_sanity`. If warning should be printed separate method needs to be called.
closes https://github.com/RasaHQ/rasa/issues/3706
=> Don't log warning per default.

CHANGELOG.rst, docs/core/policies.rst, rasa/core/processor.py
Currently, the agent can predict a maximum number of 10 next action. This number is hard coded and cannot be updated.
After merging, the number of maximum predictions can be updated via an environment variable called `MAX_NUMBER_OF_PREDICTIONS`. 
closes https://github.com/RasaHQ/rasa/issues/3664
=> Max number of predictions

rasa/core/training/interactive.py
In case the bot predicts `actions_listen` and there are no events yet or just one, we get an `list index out of range`. To avoid that, check if we already one two or more events, in order to display any buttons.
fixes https://github.com/RasaHQ/rasa/issues/3691
=> Fix list index out of range error

CHANGELOG.rst, rasa/core/interpreter.py, tests/core/test_interpreter.py, tests/core/test_processor.py, tests/nlu/base/test_interpreter.py
Fix creation of `RasaNLUHttpInterpreter`:
* if an endpoint is provided, a `RasaNLUHttpInterpreter` is created
* if no endpoint is provided, but a valid path to a NLU model is given, a `RasaNLUInterpreter` is created
* otherwise a `RegexInterpreter` is created
fixes https://github.com/RasaHQ/rasa/issues/3672
=> Fix creation of RasaNLUHttpInterpreter

rasa/nlu/featurizers/count_vectors_featurizer.py
- Disable OOV substitution in `char_wb` and `char` analyser mode in the count vector featuriser. This bug was causing most words to be replaced by the OOV token at test time if the configuration specified a character-level analyser mode (i.e. `char_wb` or `char`) _and_  `OOV_token` was specified.
=> Fix a bug in the count vectors featuriser

CHANGELOG.rst, rasa/utils/endpoints.py, tests/test_utils.py
- revert stripping of trailing slashes for endpoint urls and replace it with a debug message
- fixes https://github.com/RasaHQ/rasa/issues/3776#event-2412592607
=> Endpoints urls with slash

CHANGELOG.rst, docs/_static/spec/rasa.yml, rasa/server.py, tests/test_server.py
- /model/train: add the filename of the trained model to the response header
=> /model/train: add filename to response header

.travis.yml, setup.cfg, tests/conftest.py, tests/core/conftest.py, tests/nlu/base/test_evaluation.py, tests/nlu/conftest.py
- Skip the PyPI job entirely if conditions are not met. Before, the job was always started and then would end with "Skipping a deployment with the pypi provider because this is not a tagged commit".
- Make testing less verbose: show only warnings and errors. Went from 7800 lines of output to 3300 in this commit.
=> Make TravisCI builds less verbose and skip PyPI stage when possible

.travis.yml, CHANGELOG.rst, Makefile, rasa/cli/train.py, rasa/core/training/dsl.py, rasa/core/validator.py, rasa/utils/io.py, requirements-dev.txt, setup.cfg, tests/core/test_agent.py, tests/nlu/base/test_utils.py
This PR adds flake8 to the project. Initially, flake8 will be ran with the `--exit-zero` flag enabled, so that all checks can be fixed incrementally.
Additionally:
- The `.travis.yml` was modified so that it uses `Makefile` recipes. `Makefile` recipes can be now used to lint, format and test the code correctly.
- `pip install black` was removed from `.travis.yml` and added to `requirements-dev.txt`, with a pinned version.
The following `Makefile` recipes were modified:
- `formatter`: Applies black formatting to the code.
- `lint`: Runs flake8 and black checks on the code (does not modify it).
- `types`: Runs pytypes checks on the code.
- `test`: Runs all tests.
=> Add flake8 linting, update Makefile

.travis.yml, CHANGELOG.rst
- Starter packs were deprecated and therefore can no longer be tested
=> Remove starter packs from Travis testing

docs/user-guide/running-the-server.rst, rasa/cli/arguments/run.py, rasa/cli/run.py, rasa/core/agent.py
- Remove default value of argument `model` for `rasa run` so that it is actually possible to fetch a model from a server.
fixes https://github.com/RasaHQ/rasa/issues/3931
=> rasa run: remove default model path

rasa/model.py, rasa/train.py, rasa/utils/common.py, tests/cli/test_rasa_train.py, tests/test_train.py
This PR modifies the train function so that it always deletes all temporary files and directories it creates. Fixes https://github.com/RasaHQ/rasa/issues/3851.
The following cases **should not** leave behind any temp files or directories:
- `rasa train`, without an existing model already trained
- `rasa train`, with an existing model already trained and nothing else modified
- `rasa train`, interrupted by pressing Ctrl-C at any moment
- `rasa train --force`
=> Cleanup all temporary directories after training

CHANGELOG.rst, rasa/core/trackers.py, tests/core/test_trackers.py
- Fixes #3803 
The problem is a new tracker that is created in interactive learning but does not get passed the domain. It defaults to use `AnySlotDict` which should act as if it contains are slot.
=> fix `in AnySlotDict` behaviour

tests/cli/test_rasa_train.py
The function `count_rasa_temp_files` can fail to run if it encounters a directory it can't access. Ignore those cases as they aren't needed for the tests to run.
=> Ignore permission errors in count_rasa_temp_files

CHANGELOG.rst, rasa/train.py, tests/cli/test_rasa_train.py
Fixes #3794
- An Error message will be displayed in case of invalid domain file provided
or no domain file provided at all for `rasa train core` only
- One more additional check added to `--domain` argument
**Tests**:
- [CORE] Provide Invalid domain file path  **[Error Message Displayed]**
`python rasa/rasa train core --domain rasa/examples/formbot/domain1.yml  --config rasa/examples/formbot/config.yml --stories rasa/examples/formbot/data/ --out rasa/examples/formbot/models --augmentation 0 --quiet`
- [CORE] No domain file provided **[Error Message Displayed]**
`python rasa/rasa train core  --config rasa/examples/formbot/config.yml --stories rasa/examples/formbot/data/ --out rasa/examples/formbot/models --augmentation 0 --quiet`
- [CORE] Provided valid domain file …
=> Fixed crash when --domain not provided for rasa train command

docs/_static/spec/rasa.yml, rasa/core/interpreter.py, rasa/server.py, tests/core/test_interpreter.py
-  Pass "message_id" to _rasa_http_parse method in RasaNLUHttpInterpreter
- fixes #3819 
=> Issue 3819 - pass message_id to _rasa_http_parse

rasa/utils/common.py
Rasa run and run actions give the following warnings:
W0702 04:32:27.312059 140439586187072 deprecation_wrapper.py:119] From /srv/conda/envs/migliora/lib/python3.7/site-packages/rasa/utils/common.py:113: The name tf.logging.ERROR is deprecated. Please use tf.compat.v1.logging.ERROR instead.
W0702 04:32:27.312467 140439586187072 deprecation_wrapper.py:119] From /srv/conda/envs/migliora/lib/python3.7/site-packages/rasa/utils/common.py:115: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.
Thus, I edited the tensorflow logger references from tf.logging to tf.compat.v1.logging in the update_tensorflow_log_level function of the rasa.utils.common module.
- ...
- [x ] made …
=> Follow tensorflow logger deprecation warning

CHANGELOG.rst, rasa/cli/interactive.py, rasa/core/actions/action.py, tests/core/test_actions.py
- closes #3959 
- use `endpoints.yml` as the default endpoints path in `rasa_interactive` 
- show error message in info mode if endpoints are not configured and custom actions are called
**Formbot** (endpoints required)
- Case 1: endpoints.yml exists but not passed -- endpoints are used
- Case 2: endpoints.yml DNE -- error message shows in chat:
```
2019-07-08 18:01:07 ERROR    rasa.core.actions.action  - The model predicted the custom action 'restaurant_form', but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration via the --endpoints flag. https://rasa.com/docs/rasa/core/actions
```
**Moodbot** (endpoints not required)
- functionality does not change whether or not endpoints.yml exists …
=> use `endpoints.yml` as a default endpoints path for `rasa interactive`

rasa/nlu/training_data/loading.py
- re-add `_guess_format` to not break compatibility with Rasa X` 
=> re-add _guess_format(...) to not brake compatibility with Rasa X

rasa/core/domain.py
fix bug of #3917, Ignore order difference when compares the domain spec of the current and
the loaded domain.
-It shouldn't raise except when the domain spec of the current and
the loaded domain is same but with different order. Change the two list as set to ignore the order difference when compares them.
=> fix bug of #3917. Ignore order difference when compares the domain spec of the current and the loaded domain

CHANGELOG.rst, rasa/__main__.py, rasa/cli/__init__.py, rasa/cli/run.py
- always include current path in syspath for CLI so that custom channels, policies, and components can be found
- fix https://github.com/RasaHQ/rasa/issues/3883
=> insert current path in syspath whenever cli invoked [WIP]

.travis.yml
Apparently the `branch` variable is not set to `master` when Travis checks the job conditions on tag builds, so we shouldn't use it there. The branch can be checked later on the deploy conditions.
=> Fix .travis.yml so that runs the PyPI job

.travis.yml
- In the deploy steps, the Travis PyPI job was using the `branch` variable which was being set to the tag's name, not to "master". Remove this check and rely only on the `if: tag IS present` condition.
=> Remove "on" condition for PyPI job

CHANGELOG.rst, rasa/cli/interactive.py, rasa/cli/run.py, rasa/cli/train.py, tests/cli/test_rasa_run.py, tests/cli/test_rasa_train.py
`rasa run` without `--enable-api` parameter works as long as you have a remote storage system, a model server or a local model configured. Before you always needed to have a local model.
- fix #3722 
=> Rasa run model server

CHANGELOG.rst, rasa/utils/io.py
`self` was being passed to `prompt_toolkit`'s validation methods, which would cause errors during interactive learning
- Make the validate method static
=> Make vaildate method static

rasa/cli/run.py, rasa/nlu/persistor.py, tests/nlu/base/test_persistor.py
- see #4008 TL;DR: we are not able to fetch model from remote storage (GCS in particular). I've tested live with an existing project, it works like a charm. Waiting for CI in order to ensure that nothing else has been broke.
=> fix remote storage model fetching

rasa/cli/run.py
- Add `return` statements in `cli/run.py::run()` so that the function always returns after the server has finished running. Fixes https://github.com/RasaHQ/rasa/issues/4012.
=> Always return after starting server in cli/run.py

CHANGELOG.rst, rasa/core/agent.py, rasa/server.py, tests/core/test_agent.py
Signed-off-by: ArthurTemporim <arthurrtl@gmail.com>
Fix Rasa-X to understands **intent payload input**, further discussion [here](https://github.com/RasaHQ/rasa-x/issues/928).
- Change Rasa to understands `/` messages
- Create method `parse_message_from_text()` on `agent.py` (In RASA have others `_parse_messages()` methods, but this receive text type and not `UserMessage` object)
=> Create method to handle prefixed intent messages in server

docs/core/forms.rst
policies are defined in config.yml, not domain.yml.
- Policies are defined in config.yml
=> Fix documentation error

docs/user-guide/messaging-and-voice-channels.rst
- The ngrok link is dead. It now resides in the Rasa X part of the website. But since the Rasa X docs is not in this repo, I'm not sure how to link to it so I just put the html link instead. Please advise if there are better approaches.
=> Fix dead link

CHANGELOG.rst, rasa/core/processor.py
- fix setting of slots in interactive learning with the TwoStageFallbackPolicy https://forum.rasa.com/t/two-stage-fallback-policy-slot-reset/13133/7
- fix https://github.com/RasaHQ/rasa/issues/4090
=> Fix twostage il

CHANGELOG.rst, rasa/core/run.py, rasa/server.py, tests/conftest.py, tests/test_server.py
`curl -X GET http://localhost:5005/` responses with `Hello from Rasa: 1.x` for server started with and without `--enable-api`
fixes https://github.com/RasaHQ/rasa/issues/4066
=> Add root route to server started without --enable-api

CHANGELOG.rst, rasa/cli/arguments/run.py
- API requests are not longer logged to ``rasa_core.log`` by default in order to avoid
problems when running on OpenShift
=> don't log to file by default

CHANGELOG.rst, rasa/core/events/__init__.py
**Proposed change**:
This adds the event timestamp to the message representation of `BotUttered` events. This is useful for custom channels, especially for communication with Rasa X, which uses the timestamp as the id.
=> add timestamp to BotUttered message representation

docs/_static/spec/rasa.yml
This makes it clear that a new model is created and trained, rather than re-training an existing model. Fixes #4131
- Reword HTTP API route documentation for POST /model for clarity
=> Clarify HTTP API route documentation for POST /model

CHANGELOG.rst, rasa/cli/utils.py, tests/cli/test_utils.py
- fix https://github.com/RasaHQ/rasa/issues/4206
- show warning when default is used over invalid provided value
=> show warning in case default value is used instead of invalid value

docs/nlu/choosing-a-pipeline.rst, docs/nlu/components.rst, docs/nlu/language-support.rst
- fix #4070 
- make it very clear we support all languages
- keep this page about support and not configuration
=> revamp language support page

docs/conf.py, docs/user-guide/installation.rst, requirements-docs.txt
- Fix https://github.com/RasaHQ/roadmap/issues/644
=> Revamp installation page

rasa/core/policies/embedding_policy.py, rasa/utils/train_utils.py
- add ability to extract attention weights from other attention types
=> add ability to extract attention weights from other attention types

CHANGELOG.rst, rasa/cli/arguments/test.py, rasa/cli/test.py, rasa/core/test.py, rasa/nlu/test.py, rasa/test.py, tests/cli/test_rasa_test.py, tests/core/conftest.py, tests/nlu/base/test_evaluation.py
- remove the `--report` argument for `rasa test nlu` and use the output directory (`--out`) instead
- change `--successes` to a boolean value for `rasa test nlu` -  if set successful predictions are written to a file
- rename `--errors` to `--no-errors`. By default incorrect predictions are written to a file. If `--no-errors` is set, predictions are not written to a file.
- write successful/incorrect predictions for NER to a file
closes https://github.com/RasaHQ/rasa/issues/4329
=> Report successful and incorrect predictions of NER

docs/user-guide/rasa-tutorial.rst
=> Fix broken link to glossary from tutorial page

rasa/core/channels/twilio.py
because if you send response.text, the message "success" will apear after you sent message to twilio
- ...
=> update twilio response

docs/core/policies.rst
The document didn't give a very clear picture on which fallback action was getting called during rephrasing and which action was getting called when showing all the intent alternatives . I have added one-liner to the explanation of each fallback action i.e. fallback_nlu_action_name and fallback_core_action_name in the table.
- Added one-liner explanation to each fallback action property in the table.
=> Explain fallback action clearly

examples/formbot/actions.py
- fixed wrong return type of validate_{slot} methods in examples.
This also fixes a bug in the example code of https://rasa.com/docs/rasa/core/forms/#validating-user-input
=> Fix bug in examples and docs - slot validation method of form class should return a dict of {'slot_name': value}

CHANGELOG.rst, requirements.txt, setup.py
- Pin `gast` version as a temporary fix until `tensorflow@1.15.x` or a pre-release patch is released
@tmbo created a new branch based on `1.3.x` instead of cherry-picking the other one.
=> Pin gast version

docs/user-guide/installation.rst
The docs refer only to `pip` in the installation, this only works if `pip` has been linked to `pip3`. It might slightly annoying to users who do not have this linked, if they just copy and paste the commands.
- Change 'quick install' to use `pip3` and add a note to clarify that pip3 is meant.
=> Add note about pip version

CHANGELOG.rst, rasa/nlu/featurizers/count_vectors_featurizer.py
**Proposed changes:**
- Add a check for empty text list for a particular attribute before calling the fit function on CountVectorizer object.
- Train method will now only log a warning if some text is provided for an attribute, but still .fit() throws an exception.
=> Avoid training CountVectorizer if no text is provided

CHANGELOG.rst, rasa/nlu/utils/spacy_utils.py, tests/nlu/base/test_featurizers.py
Proposed changes:
As discussed here third-party libraries or applications that rely on `spaCy `might have problems with spaCy's `Doc`-objects created by parsing empty strings. To avoid that, only those training samples should further be sent to `nlp.pipe`, that actually carry content, however, the order of training samples need to be preserved and in addition, the batch-processing of `spaCy `should still be used. The new workflow consists of:
1. Index all training samples
2. Splitting empty from content-carrying training samples
3. Update content-carrying training samples by converting `(index, text)` to `(index, Doc)` samples
4. Update empty training samples by converting `(index, "")` to `(index, Doc)` samples
5. Merging the resulting lists back into their original order
The …
=> Flexible handling of non-existent message_attribute for given training sample

CHANGELOG.rst, docs/user-guide/connectors/mattermost.rst, rasa/cli/initial_project/credentials.yml, rasa/core/channels/mattermost.py, tests/core/test_channels.py
- rasa\core\channels\mattermost.py
- Implement send_text_with_buttons() in MattermostBot class according to mattermost message buttons docs
- Initialize MattermostBot and MattermostInput with an additional parameter webhook_url
- rasa\cli\initial_project\credentials.yml (not really necessary, but very helpful for an easy start)
- add Mattermost example with additional webhook_url
=> Fixes #4455 Implement buttons for Mattermost channel

rasa/core/channels/rasa_chat.py, tests/core/test_channels.py
=> use sender id from message object from permitted users

CHANGELOG.rst, rasa/core/agent.py, rasa/utils/io.py, tests/core/test_agent.py
- Add the parameter `slow_callback_duration` to the utils function `enable_async_loop_debugging` and change its default value to 100ms, up from 1ms.
Any asyncio calls that take longer than `slow_callback_duration` produce a warning. (There were lots of warnings)
That was also the reason `agent.load_model_from_server` called `set_log_level`, since this is no longer necessary the call has been removed (it caused some other troubles).
`enable_async_loop_debugging` is called in tests and if rasa is run with `--debug`. A default value of 100ms might not always be appropriate and we might have to change it in some places for https://github.com/RasaHQ/rasa/issues/4356
=> make slow_callback_duration a parameter in asyncio debugging

CHANGELOG.rst, rasa/core/run.py, rasa/server.py
- fix https://github.com/RasaHQ/rasa/issues/4463
- clean up some function importing in server.py and run.py
=> configure CORS on server without api

.travis.yml, CHANGELOG.rst, rasa/core/channels/console.py, rasa/core/lock_store.py, rasa/core/training/structures.py, rasa/model.py, rasa/nlu/registry.py, rasa/nlu/training_data/training_data.py, setup.py, tests/conftest.py, tests/core/test_agent.py, tests/nlu/base/test_components.py
=> Drop Python 3.5 support

rasa/core/policies/mapping_policy.py
- Let the mapping policy check whether the last action was actually predicted by a policy. This fixes an issue where if the latest action in the tracker did not have an associated policy and had the same name as the mapped action for the current intent the mapping policy would fail.
Also changed the name check to only check if `action.policy` ends with `policy.name` as should covers both previous cases.
=> Mappol lastaction nopolicy

CHANGELOG.rst, docs/nlu/components.rst, rasa/nlu/extractors/duckling_http_extractor.py
- Fixed the bug being discussed under #1695
- Added a timeout of a default of 3 seconds to t.he Duckling HTTP Request Invocation and made it a configurable component parameter.
- Updated the docs to reflect the new timeout parameter.
- Updated the changelog to reflect the fix.
- Reformatted the code using black.
- Ran a few tests to ascertain the fix.Attached a screenshot (below) of the test that fulfills the fix.
=> DucklingHTTPExtractor with defined request timeout

CHANGELOG.rst, rasa/core/channels/channel.py
- remove kwargs from default channel implementation. If users want to support these kwargs and e.g. passing them along to another function (from elements to text with buttons, for example), they can still implement their own `send_elements` function that does just that. 
- fixes the following multiple values error we have seen with migrating from a `send_elements` workaround before `send_custom_json` existed:
```
File "c:\anaconda3\envs\rasa_latest\lib\site-packages\rasa\core\channels\chan
nel.py", line 255, in send_elements
recipient_id, element_msg, element.get("buttons", []), **kwargs
TypeError: send_text_with_buttons() got multiple values for argument 'text'
```
=> remove kwargs from default channel implementation send methods

CHANGELOG.rst, docs/core/retrieval-actions.rst
- Add link to blog post on Retrieval Actions
- Add warning related to usage of Rasa X with Retrieval Actions.
=> Fix missing link to blog post on Retrieval Actions

CHANGELOG.rst, docs/nlu/components.rst, rasa/nlu/extractors/duckling_http_extractor.py
DucklingHTTPExtractor with defined request timeout
- Port the fix in #4525 to 1.3.x
- Fixes #1695
=> Port fix to duckling timeout to 1.3.x

CHANGELOG.rst, rasa/core/tracker_store.py, tests/core/test_tracker_stores.py
Like other store types, custom tracker needs event_broker to stream events.
issue #4577
- Add event_broker parameter to custom tracker
=> Add event_broker param to custom tracker

CHANGELOG.rst, rasa/cli/arguments/train.py, rasa/cli/train.py, rasa/train.py, tests/cli/test_rasa_train.py
- Added persist-nlu-data flag in CLI to allow nlu training data to be stored in model file (if needed). Added tests and all passed. 
- [ x] made PR ready for code review
- [x ] added some tests for the functionality
- [x ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa_nlu#code-style) for instructions)
=> Add flag to CLI to persist NLU data #4599

CHANGELOG.rst, rasa/server.py
- Adding in a new `latest_model` object in the /status response object that is basically the `model.get_latest_model()` so we actually can get the original model location.
Right now it only shows the model_file with the tmp location which I'm not sure if we want to just replace that or not with this option above?  The only reason I can see maybe keeping it around is for troubleshooting to know where the actual model is that we are using and not that we trained from.
Thoughts?
=> Fix /status route in server.py to include original model location

CHANGELOG.rst, docs/user-guide/validate-files.rst, rasa/core/validator.py, tests/core/test_validator.py
Closes #4566 
- The command `rasa data validate` checks there is no duplicated example data at nlu file.
**Expected Behavior**:
- nlu data file has some intents as shown:
```
- hello
- hello
```
- The following warning should be displayed when running `rasa data validate`:
```
WARNING  rasa.core.validator  - The example 'hello' was found in these multiples intents: goodbye, greet
```
=> Add validation for duplicated data example in multiple intents

CHANGELOG.rst, rasa/importers/multi_project.py, tests/importers/test_multi_project.py
The random_seed parameter of EmbeddingIntentClassifier does not work properly when using MultiProjectImporter.
The file order changes when training, which changes the order of the intent_examples in TrainingData.
- Change set to list to preserve order.
=> fixed random_seed does not work due to file order change when using MultiProjectImporter

CHANGELOG.rst, requirements.txt, setup.py, tests/core/test_visualization.py
networkx 2.4 breaks visualization (i.e. `rasa interactive` as well as the visualization on rasa x -- viz just doesn't appear). pinning to 2.3 fixes this. Tested on rasa x by extending the rasa x image to install 2.3 and visualizations re-appeared. this should be in the next patch so that we can create a rasa x patch that pulls from this rasa version.
- pin networkx==2.3
- fix https://github.com/RasaHQ/rasa/issues/4643#issue-509074209 is the error that shows up in rasa x
- fix the rasa side of https://github.com/RasaHQ/rasa-x/issues/1464 (still need to update rasa x to use this rasa version)
=> pin networkx in setup.py

CHANGELOG.rst, rasa/core/channels/console.py
- Fixes #4630 
- Them problem was that the loop for getting messages wasn't yielding the event loop, not allowing finish tasks to be executed
=> Yield event loop while receiving messages on rasa shell

CHANGELOG.rst, rasa/cli/x.py, rasa/core/agent.py, rasa/core/processor.py, rasa/core/test.py, rasa/core/tracker_store.py, tests/core/test_tracker_stores.py
- fix https://github.com/RasaHQ/rasa/issues/3243
- add `FailSafeTrackerStore` which wraps the actual tracker store and falls back to a `InMemoryTrackerStore` in case there is any problem
- use `InMemoryTrackerStore` in case there is a problem during the initialization of the tracker store
=> Tracker fallback

.travis.yml, CHANGELOG.rst, requirements.txt, setup.py
- up tensorflow requirement to avoid numpy deprecation errors
=> remove numpy deprecation errors when installed from pip

CHANGELOG.rst, Dockerfile, docker/Dockerfile_full, docker/Dockerfile_pretrained_embeddings_mitie_en, docker/Dockerfile_pretrained_embeddings_spacy_de, docker/Dockerfile_pretrained_embeddings_spacy_en
- make sure pip is updated to the latest version in our dockerfiles. fixes https://hub.docker.com/repository/registry-1.docker.io/rasa/rasa/builds/82494013-fba4-4ff4-8861-8178c4ec52be
```
Could not find a version that satisfies the requirement tensorflow==1.15.0 (from -r requirements.txt (line 11)) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, …
```
=> fix missing tensorflow version in dockerfiles

CHANGELOG.rst, data/test_evaluations/end_to_end_story.md, rasa/nlu/training_data/loading.py, tests/core/test_evaluation.py
- modify retrieval action story regex to exclude matching e2e stories
- closes #4520 
@wochinge 
=> recognise e2e format when intent restated as /intent

CHANGELOG.rst, rasa/cli/x.py, tests/cli/test_rasa_x.py
When starting Rasa X with `rasa x`, the event broker must be correctly configured to use SQLite pointing to an `events.db` file. However, a bug is preventing this event broker to be setup correctly if the user has configured any tracker store in their `endpoints.yml` file. The configuration for the tracker store and event broker should be completely independent. The problem was introduced [here](https://github.com/RasaHQ/rasa/commit/1bad671b3223041872410b6728d7c4d06c9561d5#diff-105c8c88bfadbf18d0c93ae0defa0da5R133).
This PR fixes the problem by unconditionally overwriting the event broker config when using Rasa X in local mode. If the user had configured an event broker, they will be prompted to check if they are OK with another event broker being used.
cc @btotharye …
=> Fix Rasa X (local) not working when any tracker store was configured for Rasa

.travis.yml, Makefile, tests/cli/test_rasa_train.py, tests/nlu/base/test_interpreter.py, tests/nlu/training/test_train.py, tests/nlu/utilities.py, tests/test_train.py
- Remove tests that ran Rasa as a separate process to test for temp files, as counting global temporary files may not always work when running tests concurrently.
- Update previous tests that ran `train()` and checked for created temp files in a particular directory, not accessible to other processes.
=> Fix tests for temp files

rasa/core/tracker_store.py, tests/core/test_tracker_stores.py
- fix issue where slots in the domain are lost in local rasa x mode
- when the failsafe tracker store's domain is updated, update the wrapped tracker store's domain
Still needs a changelog entry
=> let failsafe tracker store set wrapped tracker store domain

docs/core/policies.rst
- Fix small but important max history mistake
=> Fix max_history example

changelog/4894.docs.rst, docs/core/actions.rst
- fix url to async actions endpoint 
=> Fix async actions url

changelog/4898.bugfix.rst, rasa/data.py
- When you have subdirectories in your training data directory `os.walk` won't return the files in the same order each time. This leads to inconsistent training results when using a random_seed. 
- Now we sort the files to ensure consistency
=> Make order of files loaded consistent

changelog/4918.bugfix.rst, rasa/core/lock.py, rasa/core/lock_store.py, tests/core/test_lock_store.py
=> Fix TicketExistsError

changelog/4792.improvement.rst, rasa/utils/common.py
- add library loggers from socketio connector to `set_log_level` to be set by the `LOG_LEVEL_LIBRARIES` env var or default
- fix #4792
=> add socket logging libraries to set_log_level

CHANGELOG.rst, changelog/3684.bugfix.rst, changelog/3684.improvement.rst, changelog/4789.bugfix.rst, changelog/4792.improvement.rst, changelog/4802.bugfix.rst, changelog/4844.doc.rst, changelog/4844.misc.rst, changelog/4869.doc.rst, changelog/4873.improvement.rst, changelog/4894.doc.rst, changelog/4898.bugfix.rst, changelog/4918.bugfix.rst, rasa/version.py
=> prepared release of version 1.5.2

docs/user-guide/evaluating-models.rst
- After running the code block ``rasa data split nlu``, your test data can be found at ``train_test_split/test_data.md`` instead of at ``test_set.md``.
- [* ] updated the documentation
=> Test split data location

docs/nlu/choosing-a-pipeline.rst
@dakshvar22 Re: Update note in pretrained_embeddings_convert section #4920
I believe it is tensorflow-text and tensorflow-hub rather than tensorflow_text and tensorflow_hub (although apparently these should resolve to the same packages anyhow).
Unfortunately, I don't think you can install tensorflow-text on Windows or other non-Linux platforms.
- [* ] updated the documentation
=> Update note in pretrained_embeddings_convert section - 1.5.x

changelog/4647.improvement.rst, rasa/cli/arguments/data.py, rasa/cli/data.py, rasa/nlu/training_data/training_data.py, tests/cli/test_rasa_data.py, tests/nlu/base/test_training_data.py
- Enable the user to set a seed to split the NLU data into test and training.
- Close https://github.com/RasaHQ/rasa/issues/4647
**Expected behavior**:
- When a user is splitting the NLU data, a new argument specifying a random seed (in sklearn, known  as random_state) could be passed, as shown below:
```rasa data split nlu --random-seed=42```
=> Random seed split

changelog/4933.improvement.rst, rasa/core/policies/ensemble.py
- clarify warning message that appears in this case: https://github.com/RasaHQ/rasa/issues/4933
- make it clear which policy failed to initialize:
```
File "/Users/ella/rasa/rasa/core/policies/ensemble.py", line 322, in from_dict
raise Exception(f"Could not initialize {policy_name}. {e}")
Exception: Could not initialize FormPolicy. __init__() got an unexpected keyword argument 'nlu_threshold'
```
=> make it clear what policy failed because of bad kwarg

docs/core/actions.rst
Community member pointed out that link to the endpoint does not work. It is because of the `.html` after `http-api`. The current link works when you run `make livehtml`; however, it does not work when the docs are deployed on `rasa.com/docs`. Not sure how to make sure my change works
- ...
=> fix wrong link to endpoint

changelog/4990.removal.rst, rasa/core/agent.py
- deprecated `agent.continue_training` it is not used anywhere, not even for interactive learning.
=> deprecated continue training

changelog/4989.bugfix.rst, rasa/core/agent.py, tests/core/test_agent.py
- use an empty domain in case a model is loaded which has no domain (avoids error when access `agent.doman.<some attribute>`
=> use empty domain in case Domain is None (e.g. if it's a NLU only model)

docs/core/stories.rst
- Changed "end-to-end-evaluation" link to "events"
=> Fixed wrong link in documentations

changelog/5029.feature.rst, rasa/nlu/classifiers/embedding_intent_classifier.py, rasa/nlu/components.py, tests/nlu/base/test_components.py, tests/nlu/classifiers/test_embedding_intent_classifier.py, tests/nlu/example_component.py
- Add `one_of` to component. It allows you to say that the component requires either X, Y, or Z.
closes #5029
=> Add any_of helper method to component

docs/user-guide/connectors/slack.rst
- fix: **change the prefix of the slack token** form xoxob to xoxb to ease the reading of the documentation
- source : https://rasa.com/docs/rasa/user-guide/connectors/slack/
=> docs(fix): change the prefix of the slack token

requirements.txt
Master currently fails with 
```
pkg_resources.ContextualVersionConflict: (sanic 19.9.0 (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages), Requirement.parse('sanic<=19.6.3,>=0.8.3'), {'sanic-plugins-framework'})
```
As a workaround pin the version of `sanic-plugins-framework` to 0.8.2.
=> pin sanic-plugins-framework to 0.8.2

changelog/5057.bugfix.rst, rasa/core/channels/botframework.py
- Updated BotFramework connector to address https://github.com/RasaHQ/rasa/issues/5056
- fixed https://github.com/RasaHQ/rasa/issues/5056
=> ISSUE-2760 Resolving compatibility issues with Microsoft Bot Framework emulator

changelog/4989.improvement.rst, requirements.txt, setup.py
- TensorFlow 1.15 for some reason includes the binaries for cpu and gpu which makes our docker images huge. Switching to the cpu only package.
- Rasa part of https://github.com/RasaHQ/rasa-x/issues/1643
- more information here https://www.tensorflow.org/install/pip
=> use tf without gpu support by default

changelog/4664.misc.rst, requirements-dev.txt, tests/core/conftest.py, tests/core/test_channels.py, tests/nlu/base/test_evaluation.py
This PR introduces a new dependency (`pytest-asyncio`) because a suitable async framework is required to run asynchronous tests. `pytest-sanic` doesn't work in this particular situation — it's designed only to help testing sanic application with async coroutines.
- fix #4664
=> Make asynchronous Slack tests run properly

.travis.yml
- Try to fix the Travis build by using pip 19 to install the dependencies when testing Rasa.
=> Use pip 19 when installing dev dependencies

changelog/5092.bugfix.rst, rasa/core/utils.py, tests/core/test_utils.py
No rounding is currently performed prior to saving to DynamoDB tracker on Decimal values. This can result in saving errors if a value is greater than [38 characters](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-data-types).
Rounded to 9 decimal places as per @akelad's recommendation 🙂 
=> [bug] Round Decimal to 9 places to support DynamoDB constraints

changelog/5126.bugfix.rst, rasa/core/training/dsl.py
- Change the warning message in the `rasa/core/training/dsl.py` file for the ValueError on end-to-end testing to be the proper updated doc link.
=> Fix end-to-end warning url

changelog/5111.bugfix.rst, requirements.txt, setup.py
- fix https://github.com/RasaHQ/rasa/issues/5111 by pinning prompt-toolkit version
- workaround until https://github.com/prompt-toolkit/python-prompt-toolkit/issues/951 is fixed
=> fix rasa init uvloop error

.travis.yml, README.md
- netlify now configured to deploy any push to `docs` branch, so no need for this
=> remove build stage, no longer needed

rasa/nlu/extractors/crf_entity_extractor.py, rasa/nlu/featurizers/featurizer.py, tests/nlu/featurizers/test_featurizer.py
- We removed the option `return_sequence` in Rasa 1.7.0. Update log messages that still point to this option.
=> Update log messages that include return_sequence

changelog/5171.bugfix.rst, rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py, rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py, tests/nlu/featurizers/test_count_vectors_featurizer.py
When training a Rasa model that contains responses for just some of the intents, training was failing.
Fixed `CountVectorsFeaturizer` to return a consistent feature vector in case no response was given for a specific message.
closes https://github.com/RasaHQ/rasa/issues/5171
=> Fix bug in sparse featurizers

docs/user-guide/building-assistants.rst
- Some very small fixes to typos to try and get the hang of things in here.
=> Fix some typos in building assistants tutorial

README.md, changelog/5180.misc.rst, tests/cli/test_rasa_x.py, tests/core/test_broker.py, tests/core/test_dsl.py, tests/core/test_visualization.py, tests/test_server.py, tests/utils/test_io.py
- use file io utils in tests where appropriate.
- fixes #4495
=> use file utils with proper encoding instead of open

changelog/5162.bugfix.rst, data/examples/rasa/demo-rasa-multi-intent.md, data/examples/rasa/demo-rasa.json, rasa/nlu/classifiers/embedding_intent_classifier.py, tests/core/test_data.py, tests/nlu/classifiers/test_embedding_intent_classifier.py
- Training with multi-intents using `CountVectorsFeaturizer` and `EmbeddingIntentClassifer` is working again.
closes https://github.com/RasaHQ/rasa/issues/5162
=> Fix bug with multi-intents

changelog/5199.bugfix.rst, data/test/many_intents.md, rasa/nlu/classifiers/embedding_intent_classifier.py, tests/nlu/classifiers/test_embedding_intent_classifier.py
=> Add check for text features

rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py
This is a small readability fix. When the path to a lookup table is incorrect, the ValueError raised has the string ```Could not load lookup table /some/incorrect/pathMake sure you've provided the correct path```, fixed this to add a whitespace ```Could not load lookup table /some/incorrect/path Make sure you've provided the correct path```
- small readability fix
=> Improved ValueError string

changelog/5106.bugfix.rst, rasa/data.py, tests/core/test_dsl.py, tests/nlu/base/test_training_data.py, tests/test_data.py, tests/utils/test_io.py
- improved utf-8 file loading. don't fail on file exceptions when guessing file types of story files
- fixes #5106
- not sure if there is a sane way to test this
=> improved utf-8 file loading. #5106

changelog/5216.bugfix.rst, requirements.txt, setup.py
Fix cloudpickle version
`tensor2tensor` requires `gym`, which requires `cloudpickle`. We cannot increase the version of `tensor2tensor`. Also the latest version of `gym` (0.16.0) has requirement `cloudpickle~=1.2.0`. So, we need to pin `cloudpickle`.
fixes https://github.com/RasaHQ/rasa/issues/5216
=> fix cloudpickle version

rasa/core/tracker_store.py, tests/core/test_tracker_stores.py
- fix behavior of Python 3.7.6 where `urlsplit("localhost:1234")` returns `ParseResult(scheme='localhost', netloc='', path='1234', params='', query='', fragment='')` 
=> Fix urlsplit python3.7.6

changelog/5197.bugfix.rst, changelog/5197.doc.rst, docs/api/tracker-stores.rst, rasa/core/tracker_store.py, rasa/core/utils.py
- Change SQLTrackerStore to use a primary key compatible with oracle
=> make integer primary key compatible with oracle

.github/workflows/continous-integration.yml
- avoid the need for a coveralls repo token secret (they are not available to PR builds from other repos)
=> Avoid github action secret error on external PR builds

changelog/4991.removal.rst, rasa/cli/arguments/interactive.py, rasa/cli/arguments/train.py, rasa/cli/train.py, rasa/core/agent.py, rasa/core/policies/embedding_policy.py, rasa/core/policies/ensemble.py, rasa/core/policies/keras_policy.py, rasa/core/policies/memoization.py, rasa/core/policies/policy.py, rasa/core/train.py, rasa/core/training/interactive.py, tests/cli/test_rasa_interactive.py, tests/cli/test_rasa_train.py, tests/core/test_policies.py
- removed previously deprecated continue training #4990 
- removed `dump_flattened_stories` from `Agent.persist`
- improves memory footprint as the trained agent does not keep a reference to all training trackers as part of the ensemble anymore.
=> removed unused continue training

changelog/5277.bugfix.rst, rasa/core/channels/twilio.py
- fixes #5277 
- use the `from_` attribute instead of `from` when sending a custom JSON message through Twilio
=> fix missing underscore when sending custom json through twilio

docs/user-guide/how-to-deploy.rst
- fix information heirarchy in docker docs to make it clear which subsections belong to which section
- try to make things a little less overwhelming with more TOCs for each section, but a max depth of 2
- clarify that you don't need to go through the whole tutorial if you already have a model you don't want to deploy
- Fix note that said our images run as root, which isn't true anymore (the original goal of this branch lol) 
In general I think this page just has way too much information, and should be only about deploying your model, while all of the info about how to build an assistant in docker should be moved. but, small iterations to start.
=> info heirarchy docker docs

changelog/5317.improvement.rst, rasa/cli/export.py, rasa/core/brokers/pika.py, rasa/core/constants.py, rasa/core/exporter.py, tests/core/test_broker.py, tests/core/test_exporter.py
=> add RabbitMQ message header to "rasa export"

docs/conf.py
- Add `canonical_url` option to sphinx config
=> Update docs config and enable canonical meta tags

changelog/5361.bugfix.rst, docs/conf.py, rasa/core/channels/botframework.py, rasa/core/channels/channel.py, rasa/core/channels/facebook.py, rasa/core/channels/mattermost.py, rasa/core/channels/rocketchat.py, rasa/core/channels/slack.py, rasa/core/channels/socketio.py, rasa/core/channels/telegram.py, rasa/core/channels/twilio.py, rasa/core/channels/webexteams.py, tests/core/test_channels.py
- fix https://github.com/RasaHQ/rasa/issues/5361
- strip the end of messages before splitting them into multiple based on `\n\n` in order to avoid an empty message before or after if the message starts or ends with these characters
=> strip responses before splitting them on newlines

rasa/nlu/selectors/response_selector.py
- move warning for `retrieval intent` left empty to a function which is called only during training.
=> Move warning for retrieval intent left empty

rasa/core/policies/ted_policy.py, rasa/nlu/classifiers/diet_classifier.py, rasa/utils/tensorflow/layers.py, rasa/utils/tensorflow/transformer.py
- add docstrings to tf classes
- part of https://github.com/RasaHQ/rasa/issues/5319
=> add docstrings to tf classes

changelog/5404.doc.rst, docs/user-guide/how-to-deploy.rst
- the Rasa SDK image doesn't run as root user anymore since version 1.8.0. This needs to be clarified in the docs to avoid misunderstandings as in https://github.com/RasaHQ/rasa-sdk/issues/157
=> explain no-root user for SDK image

changelog/5389.feature.rst, docs/nlu/components.rst, rasa/nlu/utils/hugging_face/hf_transformers.py
-  Add `cache_dir` for save HFTransformersNLP pre-trained model data
=> Add cache_dir config for save HFTransformersNLP pre-trained model data.

rasa/utils/common.py
- Partly fixes https://github.com/RasaHQ/rasa/issues/5369
- Suppresses the first set of warnings sourced at `tensorflow/stream_executor/platform/default/dso_loader.cc` and `tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30`. These warnings were raised at the first import of tensorflow
- `E tensorflow/stream_executor/cuda/cuda_driver.cc:351]` is set at a log level `ERROR` which is an implementation bug from tensorflow's side since they merged CPU and GPU packages in a single package. We can neither suppress all `ERROR` logs from tensorflow, nor suppress all logs from  `tensorflow/stream_executor/cuda/cuda_driver.cc:351` since the same module does log useful information when a GPU is used. Many issues have been raised on TF repo regarding the same, for e.g. - …
=> Suppress unnecessary tensorflow warnings

changelog/5444.bugfix.rst, rasa/nlu/classifiers/diet_classifier.py
- Improved logging as it was unclear whether a log message comes from DIETClassifier or a subclass.
**Changes made**:
- added class name of caller to log message
=> Fixed ambiguous logging in DIETClassifier

changelog/5492.bugfix.rst, rasa/core/brokers/pika.py, tests/core/test_broker.py
- since there was a default value for the `queues` argument and a `queues` argument takes precedence over a potentially specified `queue` argument, the `queue` argument was always ignored
- long story short: Rasa sent events to the wrong queue when using the old `queue` argument
=> fix RabbitMQ 'queue' argument usage

docs/_templates/page.html
We were overwriting the footer block that triggered Sara. 
Solution:
If you override a block, call {{ super() }} somewhere to render the block’s original content in the extended template – unless you don’t want that content to show up.
=> Fix docs: Don't overwrite footer

changelog/5506.bugfix.rst, rasa/nlu/selectors/response_selector.py
=> set default value for weight_sparsity in response selector to 0

CHANGELOG.rst, changelog/5505.bugfix.rst, pyproject.toml, rasa/version.py
=> prepared release of version 1.9.3

changelog/5509.bugfix.rst, rasa/nlu/classifiers/diet_classifier.py, rasa/nlu/extractors/crf_entity_extractor.py, rasa/nlu/extractors/duckling_http_extractor.py, rasa/nlu/extractors/extractor.py, rasa/nlu/extractors/mitie_entity_extractor.py, rasa/nlu/extractors/spacy_entity_extractor.py, rasa/utils/tensorflow/models.py, tests/nlu/extractors/test_extractor.py
- fix #5509 
An entity now always covers a complete word, not just parts of it.
=> Entity applies to complete word not just parts of it

changelog/3765.feature.rst, docs/core/forms.rst, docs/nlu/entity-extraction.rst, rasa/core/trackers.py, tests/core/test_trackers.py
Update the method `get_latest_entity_values` to take an optional role/group label. Needed to allow users to fill a slot that depends on a specific role/group in a custom action.
=> Get entity with specific role/group from tracker

docs/core/knowledge-bases.rst
In the documentation there's an object being created without showing how to import it's base-classes. Added two import statements to the knowledge-base docs.
=> docs : import knowledgebase before using it

examples/formbot/actions.py, examples/formbot/data/nlu.md, examples/formbot/domain.yml
- remove num_people entity from formbot example as it should be picked up by duckling. This led to confusion about if duckling was working or not: ` I think my project is not sending anything to duckling since in the debug output I can only see the extraction from DIETClassifier.`
- close https://github.com/RasaHQ/rasa/issues/5380
- i decided not to make 2 examples as that would have involved changing many paths and not for much output, as the original recommendation was to use duckling anyway. 
=> remove num_people diet entity in formbot example

changelog/5426.bugfix.rst, rasa/nlu/test.py, tests/nlu/conftest.py, tests/nlu/test_evaluation.py
Fixes: https://github.com/RasaHQ/rasa/issues/5426
- Fix the number of examples used for plotting.
=> rasa test nlu: use the correct number of examples

changelog/5544.improvment.rst, rasa/nlu/test.py, tests/nlu/test_evaluation.py
- Similar to the intent evaluation reports, I added the "confused_with" attribute to the `response_selection_report.json`
- Also similar to intent evaluation, I added a plot of the confusion matrix for response selection evaluation
=> Added "confused_with" & confusion matrix to response selector evaluation

data/test/demo-rasa-composite-entities.md, rasa/nlu/training_data/training_data.py, tests/nlu/training_data/test_training_data.py
Part of https://github.com/RasaHQ/research/issues/69
Update the training data statistics to include roles and groups.
Log warning if just one training example with a role/group is given.
Merged into `composite-entities`
=> Log roles and groups in training data stats

changelog/5626.msic.rst, rasa/nlu/classifiers/diet_classifier.py, rasa/utils/tensorflow/transformer.py
Move activation to transformer block.
=> Move activation to transformer block

changelog/5631.misc.rst, rasa/nlu/classifiers/embedding_intent_classifier.py
Set regularization constant in `EmbeddingIntentClassifier` to 0.001.
=> Set regularization constant in `EmbeddingIntentClassifier` to 0.001

docs/user-guide/building-assistants.rst
=> fix typo in type def, plus remove redundant comment

rasa/nlu/classifiers/diet_classifier.py
- output inputs before masking, for them to be used as golden tokens
=> fix golden inputs in case mask loss is on in diet

rasa/nlu/classifiers/diet_classifier.py, rasa/utils/tensorflow/models.py
Pass entity tags instead of logits as features to second level CRFs in DIETClassifier.
=> Pass entity tags as features to second level CRFs in DIETClassifier

changelog/4606.improvement.rst, rasa/core/channels/console.py, tests/core/test_channels.py
- make timeout for `rasa shell` configurable through env variable `RASA_SHELL_STREAM_READING_TIMEOUT_IN_SECONDS`
- fix https://github.com/RasaHQ/rasa/issues/4606
=> make timeout for rasa shell configurable

changelog/5709.bugfix.rst, rasa/nlu/classifiers/diet_classifier.py, rasa/nlu/selectors/response_selector.py, rasa/utils/tensorflow/model_data.py
Reverts RasaHQ/rasa#5565 and RasaHQ/rasa#5626. 
These create breaking model changes that should not be on the 1.9.x branch; after releasing 1.9.7 and merging this commit into master, we should re-apply those PRs to the master branch.
=> Revert model breaking changes in 1.9.x

changelog/2224.improvement.rst, rasa/core/brokers/pika.py, tests/core/test_broker.py
- suppress `pika` logs during startup
- this happens only during startup, the behavior after the startup stays the same
- the logs are not suppressed when a log level <= `DEBUG` (10) is used
- fix https://github.com/RasaHQ/rasa-x/issues/2224
=> suppress pika logs during startup

changelog/5638.bugfix.rst, rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py, tests/nlu/featurizers/test_spacy_featurizer.py
Skip featurizer via `SpacyFeaturizer` if an empty SpaCy model is used.
closes https://github.com/RasaHQ/rasa/issues/5638
=> Fix usage of empty spaCy model

CHANGELOG.rst, docs/nlu/training-data-format.rst, rasa/nlu/training_data/formats/markdown.py
The `sed` command was not working for all OS. Updated the command. It should work now for most OS. Added a sentence that the syntax might be adapted depending on OS.
=> Update 'sed' command for updating training data

CHANGELOG.rst, docs/nlu/training-data-format.rst, rasa/nlu/training_data/formats/markdown.py
I've been trying the `sed` command for the new entities format on the following test file:
```markdown
Order something
Order [pizza](food) please
Order [pizza](food) in [Berlin](city) please
Order [döner](food:döner kebab) in [Berlin](city) please
Order [döner](food) in [Berlin](city:brn) please
Order [döner](food:döner kebab) in [Berlin](city:brn) please
```
The output is:
```bash
$ sed -E 's/\[([^]]*)\]\(([^:]*):([^)]*)\)/\[\1\]\{"entity": "\2", "value": "\3"\}/g' test.md 
Order something
Order [pizza](food) please
Order [pizza](food) in [Berlin](city) please
Order [döner]{"entity": "food", "value": "döner kebab"} in [Berlin](city) please
Order [döner]{"entity": "food) in [Berlin](city", "value": "brn"} please
Order [döner]{"entity": "food", "value": "döner kebab"} …
```
=> Fix sed command

changelog/5792.bugfix.rst, rasa/nlu/extractors/duckling_http_extractor.py, rasa/utils/endpoints.py, tests/utils/test_endpoints.py
- use concat_url instead of basic string concatenation to handle trailing slashes on the URL
- fix #5792
=> use concat_url to add "/parse" to duckling url safely

changelog/5755.bugfix.rst, rasa/nlu/extractors/duckling_http_extractor.py, rasa/nlu/extractors/mitie_entity_extractor.py, rasa/nlu/extractors/spacy_entity_extractor.py
Fixes https://github.com/RasaHQ/rasa/issues/5755
Remove `clean_up_entities` from extractors that extract pre-defined entities. Just keep the clean up method for entity extractors that extract custom entities.
=> Keep clean_up_entities just for custom entity extractors

changelog/5788.misc.rst, rasa/nlu/extractors/extractor.py, tests/nlu/extractors/test_extractor.py
Fixes https://github.com/RasaHQ/rasa/issues/5788
Don't set roles and groups to `O` (nothing found) when constructing entities from model predictions.
=> Don't set roles/groups to 'O'

changelog/5808.bugfix.rst, rasa/core/channels/hangouts.py
-  Changed the CERT_URI in hangouts.py to a string.
- [**Fixed this error** traceback (most recent call last):
```
File "/home/ec2-user/.local/lib/python3.6/site-packages/sanic/app.py", line 976, in handle_request
response = await response
File "/home/ec2-user/.local/lib/python3.6/site-packages/rasa/core/channels/hangouts.py", line 280, in receive
self._check_token(token)
File "/home/ec2-user/.local/lib/python3.6/site-packages/rasa/core/channels/hangouts.py", line 257, in _check_token
bot_token, self.project_id, cert_uri=CERT_URI,
File "/home/ec2-user/.local/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
return wrapped(*args, **kwargs)
File …
```
=> Fix Cert_URI Bug to string for Hangouts Channel

changelog/5794.improvement.rst, rasa/core/domain.py, tests/core/test_domain.py
Previously, in `rasa.core.domain.` `Domain.fromDict` and `Domain.__init__` could alter their inputs because of the way `Domain.collect_slots` and `Domain.collect_intent_properties` were implemented.
This PR makes sure these `collect` functions don't alter their inputs.
This is related to https://github.com/RasaHQ/rasa-x/pull/2669, which fixes an issue in Rasa X that was caused by such a domain dictionary alteration.
=> make sure Domain.fromDict(domain) doesn't change its input domain

changelog/5825.bugfix.rst, rasa/nlu/utils/bilou_utils.py, tests/nlu/utils/test_bilou_utils.py
- Fix error in `ensure_consistent_bilou_tagging`.
=> Fix error in 'ensure_consistent_bilou_tagging'

rasa/core/channels/webexteams.py
- changed `personId` to `roomId` on input channel since all of the output channel functions use roomId
- changed `roomID` to `roomId` in custom_json output
=> changing personId to roomId

changelog/4605.doc.rst, docs/user-guide/testing-your-assistant.rst
- This PR is to remove the outdated warning about white space tokenizer addressing issue #4605
=> Remove warning about WhitespaceTokenizer

rasa/nlu/training_data/message.py
Method `set` of class `Message` does not properly set attribute `text`. I know that it can be set as in `message.text = "foo"`, but method `set` should work as a unified API with method `get` for an intuitive API. Setting attribute `text` might be required for noisy text normalizers as a custom component, and calling `message.set('text', 'bar')` would not work just as in my case. I had to read the source code to make it work for me.
- Update method `set` to set `self.text` if `prop == TEXT`.
=> Update class Message to properly set attribute text

docs/core/policies.rst
I've made a small change to the docs [here](https://rasa.com/docs/rasa/core/policies/#action-selection). 
My impression is that the `SklearnPolicy` is not really supported and it is also not documented so it should not be listed. 
I've also removed `EmbeddingPolicy` because we now favor TED.
=> Minor docs fix for Action Selection

changelog/5135.bugfix.rst, rasa/core/channels/console.py, tests/core/channels/test_cmdline.py
Closes #3856
- `rasa shell` now prints buttons-message in the console channel even if they were immediately followed by other buttons
Originally community change: #5135 
=> Fix shell skips button messages

changelog/5758.bugfix.rst, rasa/core/exporter.py, rasa/core/tracker_store.py, tests/core/test_exporter.py, tests/core/test_tracker_stores.py
- fix https://github.com/RasaHQ/rasa/issues/5787
- add a variable `load_events_from_previous_conversation_sessions` to each `TrackerStore`. The `Exporter` can use this to explicitly disable session queries for `TrackerStore`s
=> migrate all events with rasa export

docs/migrate-from/google-dialogflow-to-rasa.rst
**Proposed changes**: Documentation update
```bash
rasa run nlu
```
throw
```
rasa run: error: invalid choice: 'nlu' (choose from 'actions')
```
so i suggested
```bash
rasa run
```
Which works
=> Start a server with your NLU model with "rasa run"

rasa/core/run.py, rasa/server.py
- add a log that tells the user when the server is up and ready. This is helpful because sometimes the loading of the model takes a while, and one can't tell when the server is ready to accept HTTP requests. These were part of rasa and rasa-sdk before we moved to sanic: https://github.com/RasaHQ/rasa_core/blob/0.14.0/rasa_core/run.py#L120
=> add up and ready server log

changelog/5972.bugfix.rst, rasa/nlu/classifiers/diet_classifier.py, rasa/nlu/extractors/crf_entity_extractor.py
- fixes https://github.com/RasaHQ/rasa/issues/5972
Remove `clean_up_entities` from the `DIETClassifier` and the `CRFEntityExtractor` as the method let to incorrect entity predictions.
=> Remove 'clean_up_entities' from DIETClassifier and CRFEntityExtractor

changelog/5481.improvement.rst, docs/nlu/entity-extraction.rst, rasa/nlu/classifiers/diet_classifier.py, rasa/nlu/test.py, rasa/utils/tensorflow/crf.py, rasa/utils/tensorflow/layers.py, tests/nlu/test_evaluation.py
- Update the CRF to return scores that can be used as confidence values.
- `DIETClassifier` now adds a confidence value to entity predictions.
closes https://github.com/RasaHQ/rasa/issues/5481
(Will also make a PR to tensorflow addons directly. If they take the changes and adapt the CRF, we can remove our custom CRF again.)
=> DIETClassifier adds a confidence value to entity predictions

docs/migrate-from/ibm-watson-to-rasa.rst
- Fix the button link on the IBM Watson migration page to point to the rasa tutorial
=> Fix button link on Watson docs page

changelog/6032.bugfix.rst, rasa/core/processor.py, tests/core/test_processor.py
- exit function early if no domain is provided (if you train with `rasa train nlu`), since the point is to check against the domain
- fix https://github.com/RasaHQ/rasa/issues/6032
=> fix log_unseen_features warning for nlu-only models

changelog/6042.bugfix.rst, rasa/core/test.py, tests/core/test_evaluation.py
In our tests all entity values are of type string. However, values from duckling can be of any type. In order to correctly compare predicted and target entities, we need to convert the entity values from duckling to strings during our evaluation.
related to https://github.com/RasaHQ/rasa/pull/5977
=> Convert entity values from Duckling to strings for testing

rasa/core/actions/forms.py, tests/core/actions/test_forms.py
=> RulePolicy: scope dispatches per form

changelog/5998.bugfix.rst, rasa/nlu/tokenizers/whitespace_tokenizer.py, tests/nlu/tokenizers/test_whitespace_tokenizer.py
Replace `re` with `regex` in `WhitespaceTokenizer` to consider UNICODE characters correctly.
closes #5998 
=> Whitespace tokenizer vowel signs

changelog/6031.bugfix.rst, rasa/core/lock_store.py
fixes #6031 
Pass an `EndpointConfig` to `rasa.core.lock_store._load_from_module_string` instead of a string.
**Potential follow-up**
The name of the function implies that its input should be a string. We can't pass only the string, because the whole `EndpointConfig` is needed to load it. So we should probably adapt the name.
The same holds for the `_load_from_module_string` functions in some other `rasa.core` modules, namely `nlg.generator`, `broker`, `interpreter` and `tracker_store`.
=> Fix lock store bug

changelog/6078.bugfix.rst, rasa/core/channels/webexteams.py
This is a much needed fix because presently we are unable to have the rasa-bot respond back to the specific room that sends the message thus enabling `no reply` to the user
The fix is also presented at https://github.com/RasaHQ/rasa/pull/5460 but since it will be released at 1.11.0 thenn we need to hotfix it soon.
References RasaHQ/rasa#5460
- ...
=> Webex Channel Fix: personId -> roomId

changelog/6119.bugfix.rst, rasa/nlu/tokenizers/whitespace_tokenizer.py, tests/nlu/tokenizers/test_whitespace_tokenizer.py
- Since, we shifted away from `re` to `regex`, it looks like the `.sub` method introduces a few null unicode chars in the resultant string. These needed to be cleaned up.
=> Remove empty tokens from whitespace tokenizer

changelog/6143.bugfix.rst, rasa/nlu/tokenizers/whitespace_tokenizer.py, tests/nlu/tokenizers/test_whitespace_tokenizer.py
- If the original utterance contains just an emoji like "👍" then the output tokens should be ["👍"] and not [].
=> Fix empty strings as output of whitespace tokenizer

changelog/6075.bugfix.rst.txt, rasa/server.py
- expose "filename" header for model download
=> Add 'Access-Control-Expose-Headers' for 'filename' header (#6075)

CHANGELOG.rst, changelog/5759.improvement.rst, docs/api/event-brokers.rst, docs/core/interactive-learning.rst, docs/core/reminders-and-external-events.rst, docs/nlu/components.rst, docs/user-guide/building-assistants.rst, docs/user-guide/connectors/your-own-website.rst, docs/user-guide/how-to-deploy.rst, docs/user-guide/setting-up-ci-cd.rst, rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py, rasa/nlu/tokenizers/convert_tokenizer.py, rasa/nlu/tokenizers/mitie_tokenizer.py, rasa/nlu/tokenizers/whitespace_tokenizer.py, tests/nlu/featurizers/test_regex_featurizer.py, tests/nlu/tokenizers/test_whitespace_tokenizer.py
- Remove the option from the ``WhitespaceTokenizer`` and ``ConveRTTokenizer``.
- Add option ``case_sensitive`` to the ``RegexFeaturizer``.
closes #5759 
=> Move option 'case_sensitive' from tokenizers to featurizers

rasa/core/actions/forms.py, rasa/core/actions/loops.py
- make sure trigger inout get validated
- clean up unused method
=> validate user input in activation

changelog/6137.bugfix.rst, rasa/nlu/train.py
- Fixed passing the wrong value to ```get_nlu_data``` during training
- This is a fix for existing functionality.
- No documentation updates required. The steps in current documentation work as expected now.
=> Dialogflow Import Fix for Issue 6137 in branch 1.10.x

docs/nlu/components.rst, docs/nlu/training-data-format.rst
- Doc update on EntitySynonymMapper based on customer feedback
- Update adds a note that EntitySynonymMapper needs to be placed below the Entity Extractor in config.yml to work properly (Rasa will train if this doesn't happen, but the synonym mapper won't work) 
- Included a few minor doc formatting fixes as well
=> Added Config Note on EntitySynonymMapper

changelog/6198.bugfix.rst, docs/nlu/components.rst, rasa/nlu/extractors/entity_synonyms.py
Closes #6198
- Add `EntityExtractor` as a requirement for `EntitySynonymMapper` in a pipeline
**Comment**:
I failed to test the PR locally (I have missed up with my clone and I haven't been able to build Rasa from source yet).
I would really appreciate if you can test the edit.
The change is intuitive yet it needs to be tested.
=> Add EntityExtractor as a requirement for EntitySynonymMapper

rasa/nlu/training_data/message.py
- Fix typing in `Message` class. It made my builds fail here: https://github.com/RasaHQ/rasa/pull/6211/checks?check_run_id=890593396
=> Fix typing in Message class

rasa/constants.py, rasa/core/domain.py, rasa/core/schemas/domain.yml, rasa/core/training/story_reader/yaml_story_reader.py, rasa/nlu/training_data/formats/rasa_yaml.py, rasa/validator.py, tests/core/training/story_reader/test_yaml_story_reader.py, tests/nlu/training_data/formats/test_rasa_yaml.py, tests/test_validator.py
Closes #6246
- Users are warned if training data files are not compatible
- If no version is specified, latest one is assumed
=> Add a "version" key for the training data files

changelog/6280.rst, rasa/core/nlg/interpolator.py, rasa/core/nlg/template.py, tests/core/test_nlg.py
- revert [this change](https://github.com/RasaHQ/rasa/pull/5875/files), which turned all template values into strings in interpolation in order to avoid int and None values from breaking templates 
- fix #5453 by bypassing interpolation for int, None, and bool values
- avoid turning ints, Nones, and bools into strings, which can negatively affect the type of the value sent to the connector
Note: when 1.10.x is merged to master, we need to revert the change in the above PR, as it won't show in the diff
=> correctly (don't) interpolate non-text values in custom responses

docs/core/reminders-and-external-events.rst
Otherwise it would throw an error
- ...
=> The triggers after EXTERNAL_REMINDER: SHOULD HAVE A TAB SPACE

changelog/6374.feature.md, data/test_mixed_yaml_md_stories/stories_part_1.yml, data/test_multifile_yaml_stories/stories_part_1.yml, data/test_yaml_stories/rules_without_stories.yml, data/test_yaml_stories/simple_story_with_only_end.yml, data/test_yaml_stories/stories.yml, data/test_yaml_stories/stories_and_rules.yml, data/test_yaml_stories/stories_defaultdomain.yml, data/test_yaml_stories/stories_unused_checkpoints.yml, data/test_yaml_stories/story_with_slot_was_set.yml, examples/rules/data/rules.yml, rasa/core/schemas/stories.yml, rasa/core/training/story_reader/markdown_story_reader.py, rasa/core/training/story_reader/story_reader.py, rasa/core/training/story_reader/story_step_builder.py, rasa/core/training/story_reader/yaml_story_reader.py, rasa/core/training/story_writer/yaml_story_writer.py, rasa/core/training/structures.py, tests/core/training/story_reader/test_yaml_story_reader.py, tests/core/training/story_writer/test_yaml_story_writer.py
Closes #6374 
**Proposed changes:**
- Added a schema and a writer for the 2.0 Core format
- Unified the syntax for `slot_was_set` event
- In this implementation we skip stories that contain forms
- This implementation of writer is done with "old MD -> YAML" in mind, so neither forms nor rules are supported now
=> Added a schema and a writer for the 2.0 Core training data

.typo-ci.yml, docs/docs/http-api.mdx, docs/docs/index.mdx, docs/docs/installation.mdx, docs/docs/messaging-and-voice-channels.mdx, docs/docs/model-storage.mdx, docs/docs/nlg.mdx, docs/docs/prototype-an-assistant.mdx, docs/docs/testing-your-assistant.mdx
- remove leading `$ ` from bash code blocks (as it gets copied when you click the copy button which is very annoying). if we feel we need it, it should be implemented in the highlighter for bash as a displayed but not copied char
- made the docs landing page a little more useful with a pointer where to go next
- cleaned up the installation page
- removed TOC (not necessary, we got a sidebar now)
- added a hint to run `rasa init` after installation or use prototyping page
- use groups for the tab sections (selecting "MacOS" once will show you macos for all tab groups)
- always use `pip3` and `python3` as it is a best practice
- made extra dependencies headlines more useful in sidebar
=> improved getting started docs

rasa/validator.py, tests/core/training/story_reader/test_yaml_story_reader.py, tests/nlu/training_data/formats/test_rasa_yaml.py, tests/test_validator.py
Closes #6361 
- Don't raise a warning in case `version` key is not specified in the training data
=> 2.0 training data format improvement

rasa/cli/data.py, rasa/core/training/story_writer/yaml_story_writer.py, rasa/utils/io.py, tests/cli/test_rasa_data.py, tests/core/training/story_writer/test_yaml_story_writer.py
Closes #6501 
- `form` is converted to `active_loop`
- users are warned that `FormPolicy` has to be activated
=> `rasa data convert` should be able to convert forms to `YAML` format

docs/docs/forms.mdx, docs/docs/migration-guide.mdx, rasa/core/test.py, rasa/core/training/generator.py, tests/test_test.py
- fix https://github.com/RasaHQ/rasa/issues/6509
- fix https://github.com/RasaHQ/rasa/issues/6492
- exclude `rules` from story testing since rules only represent story snippets and not conversations. 
- rename the docs placeholder for `get_extracted_slots` to `form_slots_to_validate` which was implemented in https://github.com/RasaHQ/rasa-sdk/issues/238
=> exclude rules from testing

docs/docs/custom-actions.mdx
- Quite common question I get from the community:`tracker.latest_message` returns a dictionary so when users try to get the latest message by using the command `tracker.latest_message.text` as mentioned in the docs, it throws an error. Updated an example showing how to access the latest message by returning the value based on the key.
=> update the command to get the latest message

rasa/core/domain.py, rasa/model.py, tests/core/test_model.py
- fix a bug when fingerprinting models which have a domain with `trigger: ` intents. The problem was that the fingerprinting removed the `responses` from the domain and then created domain which was checked for its validity. As the responses were missing, the related actions were also missing. This caused an error in the domain sanity check as the triggered actions aren't existing
- remove `test_create_fingerprint_from_invalid_paths`: This test just tested the behavior of `RasaFileImporter` but not the actual fingerprinting functionality
- added more tests, mainly to make sure that changed response texts only affect the NLG fingerprint
- added more typing
=> fix fingerprinting of domains with `triggers: `

changelog/6549.bugfix.rst, rasa/nlu/extractors/crf_entity_extractor.py
Fix slow training of CRFEntityExtractor when using Entity Roles and Groups.
related to https://github.com/RasaHQ/research/issues/105
=> Fix slow training of CRFEntityExtractor when using Entity Roles and Groups

rasa/nlu/selectors/response_selector.py
- `label_intent_response_key` is `None` when response selector wasn't trained. The check for response templates should be skipped then.
=> No warning during prediction if Response Selector was not trained

docs/pydoc-markdown.yml, poetry.lock, pyproject.toml
- Use official version instead of our fork ([my PR](https://github.com/NiklasRosenstein/pydoc-markdown/pull/151) just got released \o/ cc @tmbo )
=> Bump pydoc-markdown to the latest version

tests/test_server.py
- fix failing test `test_train_status_is_not_blocked_by_training` caused by [this PR](https://github.com/RasaHQ/rasa/pull/6493)
- add missing timeout: This avoids endless loops in case the test breaks
- remove duplicate `version: 2.0` entry when concatenating the files for the HTTP request. This led to a YAML error as the same key was specified multiple times. 
=> fix breaking master tests + endlessly running tests

rasa/nlu/classifiers/fallback_classifier.py, rasa/nlu/model.py
Do not featurize message using the `FallbackClassifier` during core featurization when training with `rasa train`.
`FallbackClassifier` is an `IntentClassifier`.
=> Exclude FallbackClassifier from core featurization

CODEOWNERS
- Tagging the team instead of single developers avoids that each developer is getting a review request. Instead GitHub will pick one developer from the team.
=> tag team instead of single developers

rasa/shared/core/events.py, rasa/shared/importers/importer.py, tests/shared/importers/test_importer.py
- fix https://github.com/RasaHQ/rasa/issues/6659
- A change of the story order or the order within the steps should not affect the NLU training data. If this constraint is not respected, then the NLU model will be retrained whenever the story or event order changed. To guarantee the stableness of the NLU data, the events are deduplicated and ordered before generating the `Message` objects from them. Note: New actions / utterances still need to cause a new training of the NLU model as this is required for the end-to-end support
- get rid of a couple of `asyncio.coroutine` usages as this function is deprecated as of Python 3.8
=> sort and deduplicate story events before adding them to NLU training data

data/test_stories/story_slot_different_types.md, data/test_yaml_stories/story_slot_different_types.yml, rasa/utils/schemas/stories.yml, tests/core/training/converters/test_story_markdown_to_yaml_converter.py, tests/shared/core/training_data/story_reader/test_common_story_reader.py, tests/shared/core/training_data/story_reader/test_markdown_story_reader.py
- Support `list` for the `slot_was_set` action in `2.0` Stories
=> Support list for the `slot_was_set` action

poetry.lock, pyproject.toml
- Updates to 0.7.34, 0.7.33 had a z-index issue that only surfaced with the production deployment
=> [1.10] Bump rasabaster version to 0.7.34

tests/nlu/classifiers/test_diet_classifier.py, tests/nlu/featurizers/test_convert_featurizer.py, tests/nlu/test_config.py, tests/nlu/test_train.py, tests/nlu/tokenizers/test_convert_tokenizer.py
As the ConveRT model is not available right now (https://github.com/RasaHQ/rasa/issues/6806), ignore all tests that would download the ConveRT model so that we are still able to merge other PRs.
=> Ignore tests that use ConveRT for now

changelog/5921.bugfix.md, rasa/core/training/interactive.py, tests/core/training/test_interactive.py
- handle PermissionError on file export during interactive training and allow the user the retry
- addresses https://github.com/RasaHQ/rasa/issues/5921
I did not catch the error at the higher level, because then the individual files could not be retried and inconsistent data (like double appends) would be unavoidable.
This is my first pull request for this project. It would be great to have some feedback.
=> retry on PermissionError during data export

changelog/6755.bugfix.rst, rasa/nlu/tokenizers/convert_tokenizer.py, rasa/nlu/utils/hugging_face/hf_transformers.py, rasa/utils/train_utils.py, tests/nlu/tokenizers/test_lm_tokenizer.py
- when count string length, treat the length of special token `[UNK]` as 1, to fix the OOV issue
fix #6754
=> [bugfix][WIP] Fix the bug of Chinese tokenization in 1.10.12

docs/docs/policies.mdx, rasa/cli/data.py, rasa/core/constants.py, rasa/core/policies/ensemble.py, rasa/core/policies/rule_policy.py, tests/cli/test_rasa_data.py, tests/core/test_ensemble.py
- fix https://github.com/RasaHQ/rasa/issues/6820#issuecomment-702246054
- make it possible to use the `RulePolicy` in conjunction with the old, deprecated "rule-style" policies. Motivation: As a user I want to migrate the assistant step by step. The procedure is roughly the following
1. Migrate one policy
2. Train assistant
3. test
4. Migrate next policy
This was not possible without this PR as the training would have thrown an exception about the combined usage. This exception is now relaxed to a warning.
- give the `RulePolicy` a higher priority to make sure it can be used in conjunction with `MappingPolicy` and co
- change check for `FormPolicy` in `rasa data convert config` to a warning
=> Allow old school rule-like policies with RulePolicy

rasa/core/actions/forms.py, tests/core/actions/test_forms.py
- forms are now correctly disabled when a custom validation action sets the next requested slot to `None`
- form can now be disabled during validation by setting the currently `active_loop` to None
=> form deactivations during validation

docs/docusaurus.config.js, docs/themes/theme-custom/index.js, docs/themes/theme-custom/styles.css
- Temporarily disable search box shortcuts
=> disable searchbox shortcut in docs

changelog/7001.bugfix.md, docs/themes/theme-custom/theme/Prototyper/download-button.jsx
=> Update Rasa Playground "Download" button to work correctly depending on the current chat state 

changelog/7033.bugfix.md, rasa/core/training/converters/story_markdown_to_yaml_converter.py, rasa/shared/core/training_data/story_reader/markdown_story_reader.py, rasa/shared/core/training_data/story_reader/story_reader.py, rasa/shared/core/training_data/story_reader/story_step_builder.py, rasa/shared/core/training_data/story_reader/yaml_story_reader.py, rasa/shared/core/training_data/structures.py, tests/shared/core/training_data/story_reader/test_yaml_story_reader.py, tests/shared/core/training_data/story_writer/test_yaml_story_writer.py, tests/shared/core/training_data/test_structures.py
- Allow using `_is_used_for_training=False` in YAMLStoryReader, so that we can represent OR statements as lists of events, instead of having to split off into multiple stories.
- Enable MarkdownStoryWriter to write StorySteps with OR statements.
Fixes https://github.com/RasaHQ/rasa-x/issues/3735 and https://github.com/RasaHQ/rasa-x/issues/3733.
=> Fixes for story/rules reading and writing for both formats

rasa/__main__.py
The original issue was [#6496], where the --version command breaks in windows.
Eventhough the PR[#6926] solved the problem, it looked a bit complicated of parsing twice.
- In this fix, I used platform.python_version() to solve the issue.  Totally removed the sys.version function.
- Working both in windows and linux.
=> Update to PR [#6926]

docs/docs/command-line-interface.mdx
- Fix overflowing code blocks due to accidentally deleted "```" in `rasa data validate` docs.
=> Fix deleted code block backticks in the rasa data validate docs part.

changelog/6721.bugfix.md, changelog/6721.removal.md, docs/static/spec/rasa.yml, rasa/core/agent.py, rasa/core/processor.py, rasa/core/tracker_store.py, rasa/server.py, rasa/shared/core/events.py, tests/core/test_processor.py, tests/core/test_tracker_stores.py, tests/shared/core/test_events.py, tests/test_server.py
- fixes #6721 
- the bug comes from the fact that previously no session start was run if slots were appended to a new tracker
- this manifests itself in different `prediction_states` depending on whether or not the session start sequence was run at the beginning of the tracker
- this leads to different policy behaviour - in the linked issue, it makes the difference between the memo policy kicking in or not
- this PR fixes this behaviour by making sure that when appending events to a new tracker, there is always a session start
=> Setting slots via API does not influence conversation

changelog/7053.bugfix.md, poetry.lock, pyproject.toml, rasa/shared/utils/cli.py, tests/cli/test_rasa_init.py
- fixed cmdline coloring on windows. fixes #7053 
- adds `colorama` as a windows only dependency (was already a dependency for development) 
=> fixed cmdline coloring on windows

rasa/core/featurizers/tracker_featurizers.py, rasa/shared/core/trackers.py, rasa/utils/tensorflow/model_data.py, tests/core/featurizers/test_single_state_featurizers.py, tests/core/featurizers/test_tracker_featurizer.py
Add tests for state and tracker featurizers.
relates to https://github.com/RasaHQ/rasa/issues/6670
=> Add tests for state and tracker featurizers

docs/docusaurus.config.js, docs/package.json, docs/yarn.lock
This is a patch theme update to support a `customFields.rootEditUrl` property, as a quick fix for [404 errors on "Edit This Page" links](https://github.com/RasaHQ/rasa/issues/7011). 
[Theme changes can be seen here](https://github.com/RasaHQ/tabula/commit/1feccb59e035563ffabf726163fcf975e1519857)
My suggestion for this property is to create a section in the README which explains how to submit PRs for docs fixes, including which branches/versions will be allowed, and put that anchor link in.
Closes https://github.com/RasaHQ/tabula/issues/49
=> Bump theme to 0.8.2, configure `rootEditUrl`

docs/plugins/program_output.js
- Fixing [deployment issue](https://app.netlify.com/sites/rasahq-docs-rasa-v2/deploys/5f91bad6c3068c0007b578df) of the docs
- Make `remarkProgramOutput()` version-aware
💡 what actually happened: we included a new codeblock in 2.0.x that shows the output of the program, but this codeblock does not exist on master. The generation worked as expected, but when building the docs, it tried to load the master-version of the source file, which doesn't exist; it should have tried to load a version-aware file.
- checkout the `documentation` branch
- delete file `docs/docs/sources/rasa_data_validate__help.txt` if it exists
- copy the plugin file contained in this branch into the local version of the file on the documentation branch
- run `yarn build server` => no errors, it works
=> Fix docs plugin version behaviors

changelog/7090.misc.md, rasa/utils/schemas/stories.yml
Previously, stories allowed for a metadata key, but not rules.
=> add missing metadata key in rule schema

docs/docs/policies.mdx, rasa/core/policies/ted_policy.py, rasa/utils/tensorflow/model_data_utils.py, tests/utils/tensorflow/test_model_data_utils.py
`TEDPolicy` now has the option `featurizers`. It can be set to a list of featurizer names (name of `alias`). Only the given featurizers will be considers when the dialogues are featurized.
related to https://github.com/RasaHQ/rasa/issues/6670
=> Add option "featurizers" to TEDPolicy

docs/docusaurus.config.js
This just makes sure that the link to action-server opens in the same tab, like the one to rasa-x
=> docs: conform nav-header contents/behavior

.github/workflows/continous-integration.yml
- Enable more parallelism for windows builds; that way people don't have to wait too long
=> remove max-parallel from workflow

Makefile
- only use diff of new changes of the current PR. This avoids errors when running an outdated PR against a target branch. Previously this used the diff of the target branch for linting.
=> pydocstyle only new changes

changelog/6629.bugfix.md, rasa/core/utils.py, tests/core/test_utils.py, tests/core/utilities.py
- backport https://github.com/RasaHQ/rasa/pull/6676
=> backport fix for multiple sanic workers

changelog/7176.bugfix.md, rasa/core/actions/two_stage_fallback.py, rasa/shared/core/trackers.py, tests/core/actions/test_two_stage_fallback.py
- fix https://github.com/RasaHQ/rasa/issues/7176
- `TwoStageFallbackAction` has only to revert once as `applied_events` reverts the events within the loop itself. Means we only have to revert the low confidence message with triggered the fallback. 
- fixed the tests which were missing the logging of the `ActionExecuted(ACTION_TWO_STAGE_FALLBACK_NAME)`. As this was missing, the `applied_events` logic didn't work for the tests
- fix an error which happened during interactive learning and led to a bug in the `TwoStageFallbackAction`: As the verbosity was `AfterRestart` and it didn't consider `UserUtteranceReverted` messages in between, the `TwoStageFallbackAction` though that we had two `nlu_fallback` messages in a row. We now consider `UserUtteredReverts` events as …
=> Two stage fallback fix

.github/workflows/continous-integration.yml, Makefile
- use `Make` conditions
- fix the following error (`sh` doesn't support `[[`)
```
make lint-docstrings
make[1]: Entering directory '/home/runner/work/rasa-sdk/rasa-sdk'
if [[ -n "origin/master" ]]; then \
git diff origin/master...HEAD -- rasa-sdk | poetry run flake8 --select D --diff; \
fi
/bin/sh: 1: [[: not found
```
=> fix docstyle validations

docs/docs/training-data-format.mdx
Closes #6734
- Added a doc entry for the `|` symbol
=> Add docs for the pipe symbol in YAML

.github/workflows/continous-integration.yml, changelog/5974.bugfix.md, rasa/shared/core/events.py, tests/core/test_processor.py, tests/shared/core/test_trackers.py
Issue: https://github.com/RasaHQ/rasa/issues/5974
This PR adds `ActionSessionStart` as the followup action to `ActionRestart`.
=> Trigger session start action as follow up to restart action

changelog/7122.improvement.md, rasa/core/actions/forms.py, rasa/shared/core/domain.py, tests/core/actions/test_forms.py, tests/shared/core/test_domain.py
- fix https://github.com/RasaHQ/rasa/issues/7122
- move `SlotMapping` to `Domain` as we require it in the `rasa.shared` package
- implement the validations as Python code as `pykwalify`
- doesn't allow different types for dictionary keys (`forms` can be a `list` or `dict`) (see https://github.com/Grokzen/pykwalify/issues/112)
- we need different validations based on the `type` field of the slot mapping
=> add validation for slot mappings

changelog/7246.bugfix.md, rasa/core/utils.py, rasa/model.py, rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py, rasa/nlu/featurizers/dense_featurizer/lm_featurizer.py, rasa/nlu/utils/hugging_face/hf_transformers.py, rasa/shared/core/domain.py, rasa/shared/core/training_data/structures.py, rasa/shared/nlu/training_data/message.py, rasa/shared/nlu/training_data/training_data.py, rasa/shared/utils/io.py, tests/shared/nlu/training_data/test_message.py, tests/shared/nlu/training_data/test_training_data.py, tests/utils/test_io.py
**Issue**:
- we relied on hashes in some places to fingerprint parts of the configuration / training data. hashes of strings are not stable across python (>3.3) runs, which means that the fingerprint changes even though the configuration / data is still the same
- implement proper fingerprinting using md5 for strings instead of python native hashes
=> Fixed changing fingerprints even though training data did not change

.pre-commit-config.yaml
In `.pre-commit-config.yaml` we used `stable` version of `black` but in `pyproject.toml` we had a fixed major version. Now the version should is fixed inside `.pre-commit-config.yaml` as well.
I've checked locally and the updated config installs the right version of `black` into my pre-commit hook.
=> Fix `black` to be the same version in the pre-commit config as it's in the pyproject config

changelog/7313.doc.md, docs/sidebars.js
- Returns back the "Migrate from" entry to the docs sidebar
=> Return "Migrate from" entry to the docs sidebar

.github/workflows/continous-integration.yml, changelog/7338.bugfix.md, rasa/shared/core/trackers.py, tests/shared/core/test_trackers.py
- The `init_copy` function of `DialogStateTracker` now uses the `sender_id` of the tracker to be copied
- Fixes #7338 
=> Fix tracker init copy method

changelog/7316.bugfix.md, rasa/core/featurizers/single_state_featurizer.py, rasa/core/featurizers/tracker_featurizers.py, tests/core/test_featurizer.py
- fix issue when separate core and nlu training and combining models manually broke core featurizers
=> core featurizers should use regex interpreter if core was trained separately

docs/docs/policies.mdx
There's a slight mis-interpretation possible when reading the docs on the `MemoizationPolicy`. 
> It checks if the current conversation matches a story in the training data. If so, it will predict the next action from the matching story of your training data with a confidence of 1.0
> It checks if the current conversation matches the stories in your training data. If so, it will predict the next action from the matching story of your training data with a confidence of 1.0
The idea is that "matches a story in the training data" suggests that we only are matching if there is *any* story that matches. We also expect the stories to be consistent. This prompted a question in me so I figured this small change would be good. I discussed the change with @Ghostvv and @JEM-Mosig on slack.
=> Minor Language Tweak for Memoization Policy

rasa/shared/nlu/training_data/message.py, rasa/shared/nlu/training_data/training_data.py, tests/shared/nlu/training_data/test_training_data.py
- Closes https://github.com/RasaHQ/rasa/issues/7273
- Instead of chunk memory, the method receives number of chunks to be returned. Computing the total memory of a complex object like `TrainingData` is [tricky](https://stackoverflow.com/questions/449560/how-do-i-determine-the-size-of-an-object-in-python).
- Make `TrainingDataChunk` a sub-class of `TrainingData`
=> Chunk TrainingData into smaller chunks

docs/docs/policies.mdx
I've noticed that our DIET section links to the algorithm whiteboard while the TED section does not. Figured I'd add a link.
=> Add TED link for Youtube.

changelog/7340.bugfix.md, rasa/core/tracker_store.py
- The "old" DynamoDB TrackerStore implementation created one table entry per Tracker update resulting in many objects/rows per user and session. This was caused because of the use of a timestamp (`session_date`) as part of the table's index. This fix drops the index `session_date` and only uses the `sender_id` when creating/updating DB entries. 
- The PR includes a backward compatibility check to continue usage for DynamoDBs tables with the old schema. It also introduces a deprecation warning for these kind of tables.
- Changes we tested together with @tmbo on a private project connecting to DynamoDB.
=> Fix DynamoDB TrackerStore

changelog/7306.bugfix.md, rasa/core/tracker_store.py, tests/shared/core/test_trackers.py
Fix #7306
- Use `self.key_prefix` instead of the erroneous `self.prefix` in `rasa.core.tracker_store.RedisTrackerStore`.
=> Fix incorrect attribute for key prefix in RedisTrackerStore

changelog/7232.improvement.md, rasa/shared/nlu/training_data/schemas/responses.yml
Add support for the top-level response keys `quick_replies`, `attachment` and `elements` refered to in `rasa.core.channels.OutputChannel.send_reponse`, as well as `metadata`.
=> Amend response schema to support missing top-level keys

changelog/7417.bugfix.md, data/test_domains/domain_with_categorical_slot.yml, rasa/core/agent.py, rasa/model.py, rasa/shared/core/domain.py, tests/conftest.py, tests/core/conftest.py, tests/core/test_model.py
`Domain.compare_with_specification` was failing when running `rasa train` after only changing NLG data. This is because the categorical slots were not having the default `__other__` value added when the domain was updated using `update_model_with_new_domain` - so it ended up being inconsistent. 
Solution was to also set up the default slots in this method.
=> Correctly set slots in domain when just updating nlg.

changelog/6410.removal.md, rasa/core/actions/action.py, rasa/core/actions/forms.py, rasa/core/actions/two_stage_fallback.py, rasa/core/featurizers/single_state_featurizer.py, rasa/core/policies/policy.py, rasa/core/policies/rule_policy.py, rasa/core/processor.py, rasa/core/training/training.py, rasa/shared/core/domain.py, rasa/shared/core/trackers.py, rasa/shared/importers/importer.py, rasa/telemetry.py, rasa/validator.py, tests/core/actions/test_forms.py, tests/core/featurizers/test_single_state_featurizers.py, tests/core/policies/test_rule_policy.py, tests/core/test_actions.py, tests/core/test_agent.py, tests/core/test_ensemble.py, tests/core/test_policies.py, tests/core/test_processor.py, tests/core/training/test_interactive.py, tests/shared/core/test_domain.py, tests/shared/importers/test_importer.py, tests/shared/importers/test_multi_project.py, tests/shared/importers/test_rasa.py
- fix https://github.com/RasaHQ/rasa/issues/6410
- deprecate `random_template_for` as it's unused
- rename `Domain.action_names` to `Domain.action_names_or_texts`. Added a property with deprecation message for `Domain.action_names`
- add docstrings
- utter end-to-end bot responses if predicted
- log end-to-end action correctly (`action_text` property is set)
- added method `event_for_successful_execution` to `Action` to encapsulate action event with the action which ran it
=> utter end-to-end responses

Makefile
- download mitie from github instead of s3
=> download mitie from github instead of s3

changelog/7418.bugfix.md, rasa/model.py, rasa/shared/core/domain.py, rasa/shared/nlu/training_data/formats/rasa_yaml.py, tests/shared/core/test_domain.py, tests/shared/nlu/training_data/formats/test_rasa_yaml.py
Fix for https://github.com/RasaHQ/rasa-x/issues/3900 and https://github.com/RasaHQ/rasa-x-demo/issues/27
- Preserve ordering of domain slots while dumping
- Preserve multi line strings in responses `text` key
=> Preserve domain slot ordering and multistrings while dumping

changelog/7422.bugfix.md, docs/docs/components.mdx, rasa/nlu/extractors/regex_entity_extractor.py, rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py, rasa/nlu/utils/pattern_utils.py, tests/nlu/extractors/test_regex_entity_extractor.py, tests/nlu/featurizers/test_regex_featurizer.py
- Add use_word_boundaries option for RegexFeaturizer to control the lookup table regex generation
**Proposal**
Need the user specifies the option (`use_word_boundaries=False`) manually, it will equal to:
```python
result = list(re.finditer("(上海|北京)", "明天上海的天气", flags=0))
print(result)
```
result:
```text
[<_sre.SRE_Match object; span=(2, 4), match='上海'>]
```
fixs #7421 
fixs #7091
=> Add use_word_boundaries option for RegexFeaturizer and RegexEntityExtractor

rasa/core/test.py, rasa/core/training/interactive.py, rasa/core/training/story_conflict.py, rasa/exceptions.py, rasa/shared/core/events.py, rasa/shared/core/training_data/story_reader/markdown_story_reader.py, rasa/shared/core/training_data/story_reader/yaml_story_reader.py, rasa/shared/core/training_data/story_writer/yaml_story_writer.py, rasa/shared/core/training_data/structures.py, rasa/shared/exceptions.py, rasa/shared/importers/importer.py, rasa/train.py, tests/core/featurizers/test_single_state_featurizers.py, tests/core/featurizers/test_tracker_featurizer.py, tests/core/test_policies.py, tests/core/test_processor.py, tests/core/training/converters/test_story_markdown_to_yaml_converter.py, tests/shared/core/test_events.py, tests/shared/core/test_trackers.py, tests/shared/core/training_data/story_reader/test_markdown_story_reader.py, tests/shared/core/training_data/story_writer/test_markdown_story_writer.py, tests/shared/core/training_data/story_writer/test_yaml_story_writer.py, tests/shared/core/training_data/test_structures.py, tests/shared/importers/test_importer.py, tests/shared/test_data.py, tests/test_server.py, tests/test_test.py
- fix https://github.com/RasaHQ/rasa/issues/7130
- fix printing of end-to-end bot actions in `rasa interactive`
- fix failing tests due to the `DEFAULT_STORIES_FILE` changed to be yaml
- fix reading and writing of yaml stories with end-to-end tests and end-to-end training data
- raise exception if end-to-end `UserUttered` / `ActionExecuted` events are tried to be printed to markdown
- change fingerprinting to use yaml to make sure it works with end-to-end training data (fingerprinting is still not stable for checkpoints - however, should be fixed on `master` and not here
- change story structure validator to use `str` to represent actions instead of markdown representation which uses `as_story_string`
=> E2e story printing

rasa/model.py, tests/conftest.py, tests/core/test_model.py
Adds a new method `rasa.model.can_fine_tune` which uses fingerprinting to determine if a model can be fine-tuned.
=> 7330 Add functionality to check if a model is fine-tunable

rasa/core/agent.py, rasa/core/policies/ensemble.py, rasa/core/policies/fallback.py, rasa/core/policies/form_policy.py, rasa/core/policies/mapping_policy.py, rasa/core/policies/memoization.py, rasa/core/policies/policy.py, rasa/core/policies/rule_policy.py, rasa/core/policies/sklearn_policy.py, rasa/core/policies/ted_policy.py, rasa/core/policies/two_stage_fallback.py, rasa/core/train.py, rasa/train.py, tests/core/conftest.py, tests/core/test_ensemble.py, tests/core/test_policies.py, tests/test_train.py
Load the core models in fine-tuning mode.
=> #7329 load models in finetune mode core

.github/workflows/ci-model-regression-on-schedule.yml, .github/workflows/ci-model-regression.yml, .github/workflows/continous-integration.yml, .github/workflows/documentation.yml, .github/workflows/security-scans.yml, Makefile
- Use the same key name to restore a cache
- Don't load Poetry cache for Windows
- Include poetry version in a cache key
=> [Unit tests] Don't load Poetry cache for Windows

changelog/7495.removal.md, docs/docs/migration-guide.mdx, rasa/core/training/converters/story_markdown_to_yaml_converter.py, rasa/nlu/training_data/converters/nlg_markdown_to_yaml_converter.py, rasa/nlu/training_data/converters/nlu_markdown_to_yaml_converter.py, rasa/shared/constants.py, rasa/shared/core/training_data/story_reader/markdown_story_reader.py, rasa/shared/core/training_data/story_writer/markdown_story_writer.py, rasa/shared/nlu/training_data/formats/markdown.py, rasa/shared/nlu/training_data/formats/markdown_nlg.py, tests/core/training/converters/test_story_markdown_to_yaml_converter.py, tests/nlu/training_data/converters/test_nlg_markdown_to_yaml_converter.py, tests/nlu/training_data/converters/test_nlu_markdown_to_yaml_converter.py, tests/shared/core/training_data/story_reader/test_markdown_story_reader.py, tests/shared/nlu/training_data/formats/test_markdown.py, tests/shared/nlu/training_data/formats/test_markdown_nlg.py
- deprecate Markdown Training Data (reading and writing)
- Story reading / writing
- NLU reading writing
- Response Selector reading / writing
- skip printing deprecation warnings when converting training data
=> Deprecate Markdown Training & Test Data

changelog/7458.removal.md, docs/docs/migration-guide.mdx
Add migration steps for rasa 2.1 to 2.2 caused by continuous training
=> Add migration guide for policies

examples/moodbot/config.yml, rasa/core/featurizers/tracker_featurizers.py, rasa/core/policies/ted_policy.py, rasa/shared/core/domain.py, rasa/shared/core/events.py, rasa/shared/core/trackers.py, rasa/utils/train_utils.py
- use `apply_to` methods instead of `tracker.applied_events`
=> update user messages in apply_to of define events

tests/test_train.py
Fixes the tests that were broken by the new `TrainingResult` passed around the train module.
=> fix e2e train tests

changelog/7423.improvement.md, rasa/nlu/test.py, tests/nlu/test_evaluation.py
- At the moment, when running an NLU evaluation for response selectors the plotted confusion matrix with use the training data utterances as plot labels. This small PR uses the response selector keys and predicted (sub)-intents as labels instead. This make the confusion matrix a lot more readable and useful.
- Similarly, the `response_selection_report.json` uses the same labels leading to better comprehension.
**Examples** 
Before 
After
=> Use response selector keys for confusion matrix labelling

rasa/shared/core/events.py
- force implementation of `__eq__` for Events
- add a helper class for Events without attributes to avoid duplicating their `__eq__` implementation
- mark `Event` class as abstract
=> Review comments2

.github/workflows/continous-integration.yml
This PR temporarily disables windows 3.8 CI tests.
=> Temporarily disable windows 3.8 CI tests

changelog/7585.bugfix.md, rasa/core/tracker_store.py, tests/core/test_tracker_stores.py
- correctly interpolate text by using the `sqlalchemy.text` construct
- make sure the database creation is only used for postgresql database
=> correctly replace database name in query

poetry.lock, pyproject.toml
- the private registry was part of the `pyproject.toml` as we needed it to pull our old `rasabaster` docs template. This is no longer need since `2.0.0` as we revamped our docs.
=> remove private registry from pyproject.toml

changelog/7575.bugfix.rst, rasa/nlu/test.py
@dakshvar22 To my dismay I discovered that my refactoring reintroduced a bug in my original PR #7423. Unfortunately, it was not captured by any of the unit the tests. I came across it when running a new response selector evaluation today. This PR should fix it.
In short, the default value for a response selector key was wrong. It needs to default to `None` for all "regular" intent examples or otherwise those won't be filtered out further down the pipeline and crash the sklearn reports.
cc @tmbo 
=> Amendmend to PR #7423

docs/docs/default-actions.mdx
- adds a warning to force retraining when overriding a default action
=> add warning about retraining with --force

changelog/7692.bugfix.md, poetry.lock, pyproject.toml
- `cryptography` wasn't part of our Docker images which caused the validation of JWT tokens to fail
- upgrading `PyJWT` to it's latest version
- fixes this error when using Rasa X
```
2021-01-07T14:41:05.1125275Z [36mrasa-x_1            |[0m [2021-01-07 14:41:05 +0000] - (sanic.access)[INFO][172.18.0.12:55370]: GET http://rasa-x:5002/api/version  200 616
2021-01-07T14:41:05.2506098Z [35;1mrasa-production_1   |[0m 2021-01-07 14:41:05 ERROR    rasa.core.channels.rasa_chat  - Failed to decode bearer token.
2021-01-07T14:41:05.2509294Z [35;1mrasa-production_1   |[0m Traceback (most recent call last):
2021-01-07T14:41:05.2510788Z [35;1mrasa-production_1   |[0m   File "/opt/venv/lib/python3.7/site-packages/jwt/api_jws.py", line 219, in _verify_signature …
```
=> make cryptography dep required

tests/core/conftest.py, tests/core/test_examples.py
- use session scoped formbot fixture
- re-use fixture in `test_formbot` test to avoid extra model training
- this hopefully stabilizes failing Windows tests
=> use session scoped formbot agent fixture

rasa/cli/test.py, rasa/nlu/test.py, rasa/server.py, rasa/shared/importers/importer.py, rasa/test.py, rasa/train.py, tests/conftest.py, tests/nlu/test_evaluation.py
Implementing the 2nd Part of the changes described in [Issue 5986](https://github.com/RasaHQ/rasa/issues/5986) related to `run_evaluation`.
_The current PR is a continuation of this one [#7539](https://github.com/RasaHQ/rasa/pull/7539) - in the 7539 I had issues with the CLA certificate and then squash and rebase became very difficult because of merged commits so I decided to create a new one, the current one._
- Loading `test data` using `TrainingDataImporter` in `run_evaluation` function.
- Changed the `Optional` parameters in `load_from_dict` of TrainingDataImporter to make it work with the data we have in `run_evaluation`.
- Instead of having 1 function, the `run_nlu_test` now we have 2 functions described below : 
1. `run_nlu_test` that runs `run_nlu_test_async` …
=> Implementing the use of TrainingDataImporter in rasa test 

rasa/core/training/interactive.py
A tiny typofix for `rasa interactive`
=> typofix: 'Ctr-c' -> 'Ctrl-c'

changelog/7722.bugfix.md, rasa/core/processor.py
External Message Entity Auto-Filling Fix
- Fixed external message's tracker update call to enable slot-autofilling when an entity is passed in via the [trigger_intent API endpoint](https://rasa.com/docs/rasa/pages/http-api#operation/triggerConversationIntent)
=> External Message Entity Auto-Filling Fix

changelog/7731.improvement.md, rasa/shared/nlu/training_data/formats/rasa_yaml.py, rasa/shared/nlu/training_data/formats/readerwriter.py, tests/shared/nlu/training_data/formats/test_rasa_yaml.py
This adds support to the `RasaYAMLWriter` for writing intent and example metadata back into YAML files.
The parsing functionality has been added in #5989.
Fixes #7731 
- ~~[ ] updated the documentation~~
=> Support for writing NLU intent/example metadata to YAML

changelog/7764.bugfix.md, rasa/core/actions/forms.py, tests/core/actions/test_forms.py, tests/core/test_examples.py
- Call the `validate_slots` function even if there are no slots to validate to get which slots to request next
- This fixes a bug where the next slot asked was not consistent when returning to a form from an unhappy path https://github.com/RasaHQ/rasa-sdk/issues/389
=> valide slots when coming back from unhappy paths

rasa/core/featurizers/tracker_featurizers.py
- entity tags is a list of named tuples with dicts inside. `jsonpickle.decode` cannot recreate the object. The proper fix requires significant refactor of entity tag spec. Created the issue for that: https://github.com/RasaHQ/rasa/issues/7870
=> temporary fix of persisting entity tags

docs/_headers, docs/conf.py
- As @lunelson [mentioned](https://github.com/RasaHQ/rasa/pull/7844#issuecomment-770797441), the `_redirects` file doesn't actually work for headers. Renamed it and simplified the header rule
=> Rename _redirects to _headers and update X-Robots-Tag

changelog/7420.bugfix.md, changelog/7420.improvement.md, changelog/7420.misc.md, data/test_trackers/tracker_moodbot.json, docs/docs/default-actions.mdx, rasa/core/processor.py, rasa/shared/core/constants.py, rasa/shared/core/domain.py, rasa/shared/core/slots.py, rasa/shared/core/trackers.py, tests/core/test_actions.py, tests/core/test_processor.py, tests/shared/core/test_slots.py, tests/shared/importers/test_rasa.py, tests/test_server.py
- fix https://github.com/RasaHQ/rasa/issues/7420
- invalid slot configs now throw an exception which inherits from `RasaException`. This avoids noise in sentry reporting. 
- Fixed an error when using the endpoint `GET /conversations/<conversation_id:path>/story`
with a tracker which contained slots.
=> make metadata accessible for custom action_session_start

.github/workflows/documentation.yml, Makefile, scripts/push_docs_to_branch.sh
- Fix regex pattern in doc release script to match all micros. Until now it matched all the micros not containing a "0" digit (`2.2.1`, `2.2.7`, `2.2.12`), missing micros like `2.2.10` or `2.2.20`
=> fix regex pattern to match all new micro versions

docs/docs/migrate-from/google-dialogflow-to-rasa.mdx
Part of our [docs](https://rasa.com/docs/rasa/migrate-from/google-dialogflow-to-rasa/) don't render nicely because of a few backticks missing.
This PR fixes that. 
**What it currently looks like**
=> Small code-tick fix. 

.github/workflows/continous-integration.yml
- Use the `GITHUB_REF` variable instead of `GITHUB_TAG` that is a custom variable (the name is misleading)
=> Fix tagging the latest stable version as latest

.github/workflows/continous-integration.yml
- Use the GITHUB_REF variable instead of GITHUB_TAG that is a custom variable (the name is misleading)
=> [2.3.x] Fix tagging the latest stable version as latest

changelog/7970.bugfix.md, rasa/shared/utils/validation.py, tests/shared/utils/test_validation.py
- `pykwalify` uses a global `ruamel.yaml` instance. This instance sets object attributes while reading files (e.g. the YAML schema files itself!) . This can lead to problem when we  have multiple concurrent yaml validations.  Fix: Either load the yaml files for pykwalify (what I did in my PR) or provide the schema files in json
=> load schema files for `pykwalify` to avoid global `yaml` usage

changelog/8016.mis.md, rasa/telemetry.py, tests/test_telemetry.py
- Return fresh copy of telemetry context to make sure telemetry always records OS
=> Return fresh copy of context to make sure telemetry always records OS

changelog/8007.bugfix.rst, rasa/core/brokers/kafka.py
- Add a **kwargs argument to the Kafka event broker to allow using the config for a Kafka event consumer, which may contain parameters not supported by a Kafka producer, such as in the case of deploying Rasa X with the helm charts
=> add kwargs to kafka event broker

changelog/8001.bugfix.md, rasa/core/agent.py, rasa/core/processor.py, tests/core/actions/test_forms.py, tests/core/conftest.py, tests/core/test_processor.py
- Added lock_store as an input to MessageProcessor so that handle_reminder can properly lock the conversation
- Updated handle_reminder to lock the conversation before retrieving the tracker store & executing
- Updated default_processor to pass in InMemoryLockStore as a param for test cases
- Resolves Issue #7887
=> Added Locking Mechanism to Reminders Handler

docs/docs/reaching-out-to-user.mdx
- Fix markdown of link to the reminderbot's README file in docs ("[Reaching Out to the User](https://rasa.com/docs/rasa/reaching-out-to-user#2-get-the-conversation-id)")
=> Fix a link markdown

changelog/8080.docs.md, docs/docs/http-api.mdx, docs/docs/migration-guide.mdx
Sanic recently updated links so the old ones now return 404 which makes `cd docs && yarn mdx-lint` command fail.
=> Update links to Sanic docs in our documentation

tests/integration_tests/core/conftest.py
- Fix RedisLockStore fixture to use 1 different database per process
=> fix redis_lock_store fixture to work with multiple processes

changelog/7932.bugfix.md, rasa/shared/utils/io.py, tests/shared/utils/test_io.py
=> Fix a bug with `read_yaml` function failing when trying to expand an environment variable which contains a `$`

tests/core/test_tracker_stores.py
- Added a timeout of 5 seconds on the mongo db connection of the test
```
pytest tests/core/test_tracker_stores.py::test_tracker_store_connection_error
```
and replacing that way the default MongoDB setting of 30s.
- There are [3 main parameters](https://scalegrid.io/blog/understanding-mongodb-client-timeout-options/) that can affect the timeout of the MongoDB Client : 
- `serverSelectionTimeoutMS`
- `connectTimeoutMS` and 
- `socketTimeoutMS`
- I tried them all and the only one that had any effect was the `serverSelectionTimeoutMS` and [this](https://stackoverflow.com/questions/39297979/how-to-set-connection-timeout-for-mongodb-using-pymongo) stackoverflow post reinforced my decision to use this parameter. 
- I chose 5 seconds thinking that is a good timeout option …
=> Added a timeout on a test's mongodb connection 

changelog/8208.improvement.md, rasa/shared/core/training_data/story_reader/yaml_story_reader.py, rasa/shared/nlu/training_data/formats/rasa_yaml.py, rasa/shared/utils/io.py, tests/shared/core/training_data/story_reader/test_yaml_story_reader.py, tests/shared/nlu/training_data/formats/test_rasa_yaml.py, tests/shared/utils/test_io.py
- use quick `is_key_in_yaml` implementation
=> use quick `is_key_in_yaml` implementation

tests/test_server.py
The test case sometimes failed due to the code executing faster than expected, see [this failure](https://github.com/RasaHQ/rasa/pull/7589/checks?check_run_id=2138461367#step:12:105) for instance. I fixed this.
=> Fix test_server.py:test_pushing_event occasionally failing

changelog/8194.bugfix.md, rasa/core/policies/ted_policy.py, tests/core/policies/test_ted_policy.py
- fix ted training e2e entities when none are given in the stories but there are entities in the domain
=> fix ted training e2e entities when none are given

Makefile, rasa/core/tracker_store.py, rasa/core/training/interactive.py, rasa/core/utils.py, rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py, rasa/nlu/persistor.py, rasa/nlu/tokenizers/whitespace_tokenizer.py, rasa/shared/core/domain.py, rasa/shared/core/events.py, rasa/shared/core/generator.py, rasa/shared/core/training_data/story_reader/story_reader.py, rasa/shared/core/training_data/structures.py, rasa/shared/nlu/training_data/formats/readerwriter.py, rasa/shared/nlu/training_data/loading.py, rasa/shared/nlu/training_data/training_data.py, rasa/utils/common.py, rasa/utils/tensorflow/crf.py, rasa/utils/tensorflow/model_data.py, rasa/utils/tensorflow/models.py, rasa/utils/tensorflow/temp_keras_modules.py, stubs/redis/__init__.py
- enforce that calls can only target typed functions
- fixed related issues
=> Disallow calls to untyped functions

changelog/7835.bugfix.md, data/test_nlu_no_responses/nlu_with_unicode.yml, rasa/shared/core/training_data/story_reader/yaml_story_reader.py, tests/shared/core/training_data/story_reader/test_yaml_story_reader.py, tests/shared/importers/test_importer.py
- fix https://github.com/RasaHQ/rasa/issues/8215
- add missing encoding
- fix https://github.com/RasaHQ/rasa/issues/8231
=> add encoding

docs/docs/migrate-from/google-dialogflow-to-rasa.mdx
- Added ```enable-api``` to Step 5 so users following the documentation enable the API server before running the curl command in the next set of code.
=> included the enable-api command in step 5

.github/workflows/ci-model-regression-on-schedule.yml, .github/workflows/ci-model-regression.yml
Model regression tests broke down with the Spacy update (to 3.0) because `spacy link` is no longer supported.
In this repo, I'm just removing the problematic command. In the `training-data` repo (see [the PR](https://github.com/RasaHQ/training-data/pull/10)), I specify the Spacy model in the config files. Only once that other PR is merged, the regression tests should work again (with the changes from this PR).
=> Fix model regression tests after Spacy has been updated

data/test_config/stack_config.yml, rasa/nlu/test.py, tests/nlu/test_evaluation.py
closes #8325
Problem: 
we compare set to empty list to check whether set is empty.
Solution:
Check for set len.
- ~updated the documentation~
- ~updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/main/changelog) for instructions)~
=> Bug in is_entity_extractor_present() in rasa/nlu/test.py

changelog/8345.improvement.rst, rasa/core/lock_store.py, tests/core/test_lock_store.py
- Improve Lockstore Queuing Log Message in 1.10.X
- Backport of #8105 feature enhancement for 1.10.X
=> Improve Lockstore Queuing Log Message in 1.10.X

.github/workflows/continous-integration.yml
**The problem**:
The `wait for docs test` step in the CI looks for the workflow run based on `the _head_ branch name`. For example, the `wait for docs test` was doing this:
```
Retrieving check runs named Test Documentation on RasaHQ/rasa@fix-wait-for-docs....
```
even when the branch is from a forked repo. The step fails because couldn't find the branch in RasaHQ/rasa (like [this](https://github.com/RasaHQ/rasa/pull/8358)). 
- Change the reference to SHA so it will look for SHA instead of branch name
- Correct the repo owner so it will know which repo to look for the workflow run
- Also remove the checkout step because the wait for action does not require the checkout step.
```
Retrieving check runs named Test …
```
=> fix wait for docs test step in CI

CODEOWNERS
- related to discussion [here](https://rasa-hq.slack.com/archives/C36SS4N8M/p1617800136346200?thread_ts=1617783559.338900&cid=C36SS4N8M)
- make @RasaHQ/enable-squad own `rasa.shared` instead of the entire backend team
=> make enable-squad own rasa.shared

changelog/8382.bugfix.md, rasa/shared/core/domain.py, rasa/shared/utils/io.py, tests/shared/utils/test_io.py
- replace `ValueError` with `RasaException` in `replace_environment_variables` function because it's indeed a usage error
- it's basically a post-merge update to #8140
- fixes #7932 
=> Replace `ValueError` with `RasaException` in `replace_environment_variables` function

changelog/8429.enhancement.rst, data/test_endpoints/event_brokers/kafka_plaintext_endpoint.yml, docs/api/event-brokers.rst, rasa/core/brokers/kafka.py, tests/core/test_broker.py
- Added Partition Key Parameter for Kafka Producer
- Backport of #8335 
=> 1.10.x Back-port for Kafka Partition Key Implementation

docs/docs/connectors/your-own-website.mdx
I couldn't copy/paste the example because it didn't list valid json. There's a comma too many. So I made a quick fix. 
The example can be found [here](https://rasa.com/docs/rasa/connectors/your-own-website#request-and-response-format). 
This isn't valid json. 
```json
{
"sender": "test_user",
"message": "Hi there!",
}
```
This is. 
```json
{
"sender": "test_user",
"message": "Hi there!"
}
```
=> Turn Docs example into valid json

.github/workflows/continous-integration.yml, changelog/5786.enhancement.md, changelog/7685.improvement.md, changelog/8074.improvement.md, changelog/8428.removal.md
- This is a test PR for https://github.com/RasaHQ/rasa/pull/8489
- Test the `Check for changelog` job in CI
=> [CI] Prepare release test

docs/docs/setting-up-ci-cd.mdx
- fix url for rasa-demo pipeline to `main` (it was master)
=> fix rasa-demo url in docs

changelog/8545.bugfix.md, rasa/utils/plotting.py
Fixes https://github.com/RasaHQ/rasa/issues/8545
Or rather mitigates it. People with falsy config encounter this issue when running virtually any rasa command (some stacktraces occurred for `rasa init` for instance). This moves matplotlib backend manipulation in a decorator, instead of at the module level today.
=> Fix matplotlib backend in decorator

changelog/8560.improvement.md, rasa/core/policies/ted_policy.py, rasa/nlu/classifiers/diet_classifier.py, rasa/utils/tensorflow/models.py, rasa/utils/train_utils.py, tests/utils/tensorflow/test_models.py
- All models now use `run_inference` method to generate predictions through the model. `run_inference` is meant to perform batch inferencing as well which means that it implements the batching and combining of output for different batches. The specific TF models like `TED`, `DIET` do not need to know the implementation details of this batch inferencing.
- Needed for future features like `IntentTEDPolicy`.
=> Implement interface for bulk inferencing in TF models

changelog/8341.bugfix.md, rasa/core/training/interactive.py, tests/core/training/test_interactive.py
- Fixes #8341 
- Chinese and other east asian characters can have a wider visible width than ascii characters, even in monospace fonts. This breaks the table that we have been using (see https://github.com/RasaHQ/rasa/issues/8341#issuecomment-817607778)
- Added a simple search algorithm to find the widest feasible width for line wrapping taking into account the visible width of the specific string
=> Fixed long east asian character sequences in interactive training

changelog/7908.bugfix.md, rasa/shared/utils/pykwalify_extensions.py, rasa/shared/utils/validation.py, rasa/validator.py, tests/cli/test_rasa_data.py, tests/shared/utils/test_validation.py, tests/test_validator.py
=> Add error message for rasa validate when text is null in a response

changelog/8641.misc.md, rasa/nlu/extractors/regex_entity_extractor.py
- `RegexEntityExtractor` load method instantiates the component using the hardcoded class type as oppose to the `cls` argument, which loses the subclass type. This caused issues when subclassing `RegexEntityExtractor`.
=> Fix RegexEntityExtractor subclass loading

changelog/8364.bugfix.md, rasa/core/actions/forms.py, rasa/shared/core/slots.py, tests/core/actions/test_forms.py, tests/shared/core/test_slots.py
- fix https://github.com/RasaHQ/rasa/issues/8364
- The issue was that we decided whether something should be filled with a list based on how many matching entities were extracted. This means if we e.g. asked for pizza toppings and a user only wants "mushrooms" we would have set the slot with the string "mushroom" instead of `[mushroom]`. This behavior is fine unless it's for `ListSlot`s as these should (as the name suggests) always be `List`s
- we are now checking the slot type before deciding whether to convert the entities to single items or not
- I also modified the setter for `ListSlot` so that items which aren't `List`s are automatically put into a list to ensure `ListSlot` values are always `List`s
**Things I didn't do**
- I considered adding a warning if there …
=> fix slot filling for `ListSlot`s in case only a single matching entity was extracted

docs/docs/business-logic.mdx, docs/docs/components.mdx, docs/docs/domain.mdx, docs/docs/generating-nlu-data.mdx
- DucklingHTTPExtractor -> DucklingEntityExtractor everywhere. This change should have been made in the 2.0 release, but looks like some docs escaped notice
- Add a note about autofilled slots behaviour
=> Add note on autofilled slots behaviour & consistently refer to duckling as DucklingEntityExtractor

changelog/8631.bugfix.md, data/test_domains/default_retrieval_intents.yml, data/test_domains/response_selector_responses_in_domain.yml, rasa/validator.py, tests/test_validator.py
- Only recognize the first chunk of response selector responses when looking for names of actions in the domain file for action/story validation (e.g. `utter_chitchat` of `utter_chitchat/ask_name`
- Fix https://github.com/RasaHQ/rasa/issues/8633
=> correctly validate whether response selector responses from stories are valid if responses are found in the domain

changelog/8587.bugfix.md, changelog/8587.misc.md, data/test_yaml_stories/rules_missing_intent.yml, data/test_yaml_stories/stories_missing_intent.yml, rasa/shared/core/training_data/story_reader/yaml_story_reader.py, tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
=> Check for missing intent value in stories and rules and raise exception

changelog/8544.misc.md, rasa/core/brokers/broker.py, tests/core/test_broker.py
=> catch and convert all aio_pika connection exceptions

changelog/7691.improvement.md, data/test_config/config_empty_en_after_dumping.yml, data/test_config/config_empty_en_after_dumping_core.yml, data/test_config/config_empty_fr_after_dumping.yml, data/test_config/config_with_comments_after_dumping.yml, rasa/shared/importers/default_config.yml
Changed the default config to train the `RulePolicy` before the `TEDPolicy`.
Fixes: #7691 
=> Changed the default config to train the RulePolicy before the TEDPolicy.

changelog/8719.bugfix.md, rasa/core/channels/telegram.py, tests/core/channels/test_telegram.py
- add handling of edited message on the Telegram channel
- if the edited message is unhandled it is causing crash and all communication on the channel is stopped
When receiving edited message telegram channel connector crashes:
```
Exception occurred while handling uri: 'http://***/webhooks/telegram/webhook'
Traceback (most recent call last):
File "/home/martin/anaconda3/envs/rasa-2.4/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
response = await response
File "/home/martin/anaconda3/envs/rasa-2.4/lib/python3.7/site-packages/rasa/core/channels/telegram.py", line 218, in message
if self._is_user_message(msg):
File "/home/martin/anaconda3/envs/rasa-2.4/lib/python3.7/site-packages/rasa/core/channels/telegram.py", line 177, in _is_user_message …
```
=> Fix telegram message update

.github/workflows/continous-integration.yml, Makefile
- Resolves https://github.com/RasaHQ/rasa/issues/8656
The errors are most likely caused by the downtime of the external server. The package manager we are using for Windows is very unreliable. We can check the status here: https://status.chocolatey.org
There seems [no out-of-box solution for it](https://docs.chocolatey.org/en-us/choco/commands/install). The good news is that the GitHub Action team implemented a choco installation helper in their Windows VM, we can use it directly in the CI.
=> Fix choco install error

changelog/8658.misc.md, tests/test_server.py
- fix #8658 
The reason for this change: it sometimes takes longer to run the training process on Windows (everything is a bit slower on Windows GH runners), and that's why the test for `tests/test_server.py::assert_trained_model` is sometimes flakey. This change fixes it.
=> Increase the timeout to run `tests/test_server.py::assert_trained_model` test successfully on Windows

.github/workflows/documentation.yml, scripts/push_docs_to_branch.sh
- Failfast in the bash script that pushes docs
- Notify Slack channel when docs workflow fails (currently we rely on "people" telling us that the docs do not appear on the docs website)
- unifies the behaviour with Rasa X (see https://github.com/RasaHQ/rasa-x/pull/5137)
**This PR needs...**:
=> Failfast when publishing docs

docs/docs/fallback-handoff.mdx, docs/docs/tuning-your-model.mdx
**Description**:
- box didn't render with the indentation
- ConvertTokenizer was recommended but it's link directly leads to a deprecation message (https://rasa.com/docs/rasa/components#converttokenizer)
=> fix one caution box; rm reference to converttokenizer

changelog/improvement.8295.md, rasa/core/policies/rule_policy.py
- fix https://github.com/RasaHQ/rasa/issues/8295
- cache `_rule_key_to_state` as this a hotspot of the contradiction check according to the [profiling results](https://drive.google.com/file/d/154vW5bufikVcjXfrmqDDdA3A4PmXIeEt/view?usp=sharing) (viewable with [snakeviz](https://jiffyclub.github.io/snakeviz/))
- this speeds up the `RulePolicy` training with Sara from 14.4 seconds to 5.26 seconds
- see memory considerations of the cache [here](https://github.com/RasaHQ/rasa/issues/8295#issuecomment-856720809)
- follow up issue for bigger changes to the `RulePolicy` https://github.com/RasaHQ/rasa/issues/8850
=> speed up rule policy contraction check

changelog/8812.bugfix.md, rasa/nlu/test.py, rasa/utils/plotting.py, tests/utils/test_plotting.py
- Fixes https://github.com/RasaHQ/rasa/issues/8812
=> Don't evaluate entities if no entities present in test data

.github/workflows/continous-integration.yml, CHANGELOG.mdx, changelog/8892.feature.md, pyproject.toml, rasa/version.py
- Back port #8724 to the 2.5.x branch
- Adds an optional parameter for defining `sasl_mechanism` for the Kafka event broker
=> prepared release of version 2.5.2

docs/docs/components.mdx
We had a [false bug alarm](https://github.com/RasaHQ/rasa/issues/8468) due to some confusion over the behaviour of `WhitespaceTokenizer`. This PR is an attempt to clarify the behaviour of `WhitespaceTokenizer`.
The resulting page looks like:
=> Clarify the behaviour of `WhitespaceTokenizer`

changelog/8421.improvement.md, rasa/core/test.py, rasa/core/training/interactive.py, tests/core/training/test_interactive.py
- Adapts `rasa interactive` to `IntentTEDPolicy` (`action_unlikely_intent`)
- fixes #8421 
**It requires `rasa test` updates to be merged first! https://github.com/RasaHQ/rasa/pull/8843**
=> `IntentTEDPolicy`: `rasa interactive` updates

rasa/core/policies/intent_ted_policy.py, rasa/utils/tensorflow/constants.py, tests/core/policies/test_intent_ted_policy.py
- Refactors metadata attached to the prediction of the policy.
- Metadata looks like this now:
```
Metadata schema looks like this:
{
"query_intent": <metadata of intent that was queried>,
"ranking": <sorted list of metadata corresponding to all intents.
Sorting is based on predicted similarities.>
}
Each metadata dictionary looks like this:
{
"name": <name of intent>,
"score": <predicted similarity score>,
"threshold": <threshold used for intent>,
"severity": <absolute difference between score and threshold>
}
```
=> IntentTEDPolicy: Add severity to metadata

rasa/cli/test.py, rasa/core/constants.py, rasa/core/test.py, tests/cli/test_rasa_test.py, tests/core/test_evaluation.py, tests/core/test_test.py
- do monkey patching inside `rasa test` tests because every time the tests are run, training will result in different model weights which will result in different predictions of `action_unlikely_intent`.
- update the imports inside `rasa.cli.test`
=> `IntentTEDPolicy`: Updated `rasa test` tests

.github/workflows/ci-model-regression-on-schedule.yml, .github/workflows/vulnerability-scan.yml
- Use `RASABOT_GITHUB_TOKEN` to create issues in workflows so that subsequent workflows are triggered. (the behaviour is described [here](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token))
=> Use RASABOT_GITHUB_TOKEN to create issues in workflows

rasa/core/policies/intent_ted_policy.py, tests/core/policies/test_intent_ted_policy.py, tests/core/policies/test_rule_policy.py, tests/core/policies/test_ted_policy.py, tests/core/test_ensemble.py, tests/core/test_policies.py, tests/core/test_utils.py
- Add experimental label
- Integration test to check if `action_unlikely_intent` is ignored in all story based policies but is not ignored for RulePolicy.
- Integration test to check if ensemble prevents multiple predictions of `action_unlikely_intent`.
- Integration test to check to check that the ensemble does not pick `action_unlikely_intent` when rule is triggered.
=> IntentTEDPolicy: Misc updates from QA

changelog/9045.removal.md, docs/docs/components.mdx, docs/docs/migration-guide.mdx, docs/docs/policies.mdx, rasa/utils/train_utils.py, tests/utils/test_train_utils.py
- Deprecate `linear_norm` as a possible value for `model_confidence`.
=> Deprecate `linear_norm` as a possible value for `model_confidence`

.github/workflows/automatic-release-to-main-merger.yml
closes #6207 
- Automatically create a PR that merges changes from the release branch into main **and** close older PRs of that sort.
=> Automatically merge release branch into main

changelog/8694.misc.md, rasa/telemetry.py
- As a result of findings for issue #8694, I added [AWS CI environment variables](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html) to the `telemetry` module to improve tracking of all CI pipelines.
=> Add AWS CI to telemetry CI checks

rasa/cli/train.py, rasa/core/agent.py, rasa/core/channels/botframework.py, rasa/core/channels/channel.py, rasa/core/channels/console.py, rasa/core/channels/hangouts.py, rasa/core/channels/slack.py, rasa/core/channels/socketio.py, rasa/core/lock_store.py, rasa/core/policies/ted_policy.py, rasa/core/test.py, rasa/core/training/interactive.py, rasa/model.py, rasa/model_training.py, rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py, rasa/nlu/registry.py, rasa/nlu/train.py, rasa/shared/nlu/training_data/formats/rasa_yaml.py, rasa/shared/nlu/training_data/message.py, rasa/utils/common.py, rasa/utils/tensorflow/environment.py, rasa/utils/tensorflow/model_data_utils.py, rasa/utils/tensorflow/models.py, rasa/utils/tensorflow/rasa_layers.py, tests/core/utilities.py
=> fix `return` mypy issues

CHANGELOG.mdx, changelog/8868.removal.md, data/test_domains/default_with_slots.yml, data/test_domains/form.yml, docs/docs/domain.mdx, docs/docs/migration-guide.mdx, rasa/shared/core/domain.py, rasa/shared/core/slots.py, rasa/shared/utils/schemas/domain.yml, tests/cli/test_rasa_data.py, tests/core/actions/test_forms.py, tests/core/featurizers/test_single_state_featurizers.py, tests/core/policies/test_rule_policy.py, tests/core/test_actions.py, tests/core/test_agent.py, tests/core/test_ensemble.py, tests/core/test_processor.py, tests/core/training/test_interactive.py, tests/docs/test_docs_training_data.py, tests/shared/core/test_domain.py, tests/shared/core/test_slots.py, tests/test_validator.py
- fix https://github.com/RasaHQ/rasa/issues/8868
- enforce `Domain` schema
- Exclude the migration guide from this check as the migration guide might contain training data which once was valid but is not valid anymore. E.g. the migration guide for Rasa Open Source 2 defined a form schema which is no longer valid since Rasa Open Source 3.
=> remove deprecations from `Domain`

changelog/8872.removal.md, rasa/shared/nlu/training_data/training_data.py
=> Remove deprecated `sorted_intent_examples` method from `TrainingData`

.github/dependabot.yml
- tag Maxime instead of enable-squad for docs dependencies updates
=> tag Maxime instead of enable-squad for docs dependencies updates

.github/workflows/ci-model-regression-on-schedule.yml
- Some GH issues created by `ci-model-regression-on-schedule` are not assigned to the right GH project (example: https://github.com/RasaHQ/rasa/issues/9154)
- Use `RASABOT_GITHUB_TOKEN` to trigger subsequent workflows
=> use the right GH token for ci-model-regression-on-schedule.yml

changelog/8024.doc.md, changelog/8791.doc.md, docs/docs/command-line-interface.mdx, docs/docs/nlu-training-data.mdx, rasa/nlu/train.py
We are moving two features from experimental to fully integrated. This pull request removes the experimental feature warning messages from the **rasa docs** and the **code**. The behaviour of the features remains unchanged.  
1. **Entity roles and groups** (see: #8791). I removed the experimental feature warning from:
- The rasa docs
- The code, where it only appeared as a print statement
2. **Story validation tool** (see #8024). I removed the experimental feature warning from:
- The rasa docs only (I could not find a warning in the code)
=> 2.8.x: Remove experimental feature warning for story validation and entity roles and groups

changelog/7695.bugfix.md, rasa/validator.py, tests/test_validator.py
Skips checking that intent is in domain for E2E story utterances when running `rasa data validate`. This is a bug fix for [this on-point discussion](https://rasa-hq.slack.com/archives/C021ZTVSY77/p1628018843068000) targeting `2.7.x` but it could also be added to `main` for `3.0.x`.
=> Skip checking intent is in domain for utterances with no intent.

poetry.lock, pyproject.toml, rasa/engine/exceptions.py, rasa/engine/graph.py, rasa/engine/validation.py, rasa/nlu/components.py, rasa/utils/common.py, tests/engine/test_validation.py, tests/nlu/test_components.py, tests/utils/test_common.py
- fix https://github.com/RasaHQ/rasa/issues/9181
- Add validation for graph schemas
=> implement graph schema validation

rasa/engine/graph.py, rasa/nlu/classifiers/_diet_classifier.py, rasa/nlu/classifiers/diet_classifier.py, rasa/nlu/extractors/_extractor.py, rasa/nlu/extractors/extractor.py, tests/engine/graph_components_test_classes.py, tests/engine/runner/test_dask.py, tests/engine/test_graph_node.py, tests/nlu/classifiers/test_diet_classifier.py, tests/nlu/extractors/test_extractor.py, tests/nlu/selectors/test_selectors.py, tests/utils/test_common.py
fix #9275 
This the equivalent of #9306 but for the `DIETClassifier`
Adapted classes:
* ~`Component` -> `NLUGraphComponent`~
* ~New graph component interface for nlu components~
* ~Lots of code is deleted~
* ~Methods changed to match `GraphComponent` interface~
* ~`IntentClassifier` -> `IntentClassifierGraphComponent`~
* ~New (empty) base class for all intent classifiers~
* `EntityExtractor` -> ~`EntityExtractorGraphComponent`~ `EntityExtractorMixin`
* ~New base class for all entity classifiers~ Now just a container for some shared functionality.
* only small changes
* `DIETClassifier` -> `DIETClassifierGraphComponent`
* adapt `create` and `load` functions to new signatures 
* adapt default config
* adapt `required_packages` and `supported_languages`  
* adapt …
=> Convert DIETClassifier to be a GraphComponent

.github/PULL_REQUEST_AUTOMATIC_TEMPLATE.md
- This template already exists on `main` but it's needed in `2.8.x` so that the automatic backmerge workflows succeed,
- Example failure [here](https://github.com/RasaHQ/rasa/runs/3372722142?check_suite_focus=true)
=> Porting GH template to latest release branch

changelog/9490.bugfix.md, rasa/shared/core/events.py, tests/shared/core/test_events.py
=> `hide_rule_turn` should default to `False` when `ActionExecuted` is deserialised.

rasa/shared/data.py
- fix circular import when doing `from rasa.shared.core.training_data.story_writer.yaml_story_writer import YAMLStoryWriter`
- [see Slack](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1631040070251200)
```
In [1]: from rasa.shared.core.training_data.story_writer.yaml_story_writer import YAMLStoryWriter
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b1dfec1f0224> in <module>
----> 1 from rasa.shared.core.training_data.story_writer.yaml_story_writer import YAMLStoryWriter
~/Workspace/stack/rasa/shared/core/training_data/story_writer/yaml_story_writer.py in <module>
26 )
27
---> 28 from rasa.shared.core.training_data.story_reader.yaml_story_reader …
```
=> fix circular import for YAMLStoryReader/Writer

rasa/shared/nlu/training_data/features.py, tests/shared/nlu/training_data/test_features.py
- remove origin check in `Features.combine` if `expected_features` is `None` because there is nothing we can check - the origins must differ as it is should be the only thing that differs (attribute, type, sparseness are identical)
- added a unit test case 
- adapted tests for `Features.reduce` which was misusing that "feature"
=> fix origin check in Features.combine; add tests

.github/configs/tf-cuda.json, .github/runner/github-runner-deployment.yaml.tmpl, .github/workflows/ci-model-regression-on-schedule.yml, .github/workflows/ci-model-regression.yml
Add a TensorFlow-CUDA mapping to select GitHub GPU runner according to the TensorFlow version defined in `pyproject.toml`. 
The mapping is defined in `tf-cuda.json` file. If there is any updates on the [compatibility matrix](https://www.tensorflow.org/install/source#gpu), this file should be updated accordingly.
For example,
- If the `tf` version is not set in `tf-cuda.json` file, we use the default image tag  `latest`, which refers to the latest gpu runner. 
- If `tf` version is `>=2.3.4, 2.4`, the GitHub runner will use `cuda-10.1` and `cudnn7`. See the test run [here](https://github.com/RasaHQ/rasa/pull/9686/checks?check_run_id=3664735921#step:4:12) and [here](https://github.com/RasaHQ/rasa/pull/9686/checks?check_run_id=3664735921#step:5:10).
- When `tf` version …
=> model regression test: support various GPU runners

.github/workflows/continous-integration.yml, rasa/api.py
Add a step right after backend's test. If the test fails, setup a tmate session, which allows us ssh into it and debug directly from there.
=> add tmate session to debug runner

.github/workflows/continous-integration.yml, tests/nlu/classifiers/test_diet_classifier.py
As per discussion [here](https://rasa-hq.slack.com/archives/C01H2UCNP2T/p1632832706102800), I'm limiting the pytest jobs to 1 on CI for problematic configurations (Windows + `test-nlu-predictors`). 
This is a *temporary* fix in order to get TF 2.6 micro out as quickly as possible. I've created a followup issue to investigate and address the memory issues so that the fix can be reverted.
=> Limit pytest jobs to 1 on CI for Windows and test-nlu-predictors

.github/workflows/ci-model-regression-on-schedule.yml, .github/workflows/ci-model-regression.yml, scripts/read_tenforflow_version.sh
**The problem:**
We were using `sed`-style to read TF version from `pyproject.toml`, which leads us to problems when the version constraints aren't cover in the sed command. We need to find a way to read TensorFlow version from `poetry.lock` directly.
Use python's toml library to parse and read TensorFlow version from `poetry.lock`. 
It now uses the new `read_tenforflow_version.sh` script to retrieve tf version (e.g. [`2.6`](https://github.com/RasaHQ/rasa/pull/9785/checks?check_run_id=3790279267#step:4:17)) and CUDA/cuDNN libraries [successfully load](https://github.com/RasaHQ/rasa/pull/9785/checks?check_run_id=3790295792).
=> Read TF version from poetry.lock

.github/workflows/documentation.yml, scripts/push_docs_to_branch.sh
=> Update documentation workflow to only publish one version per major

rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py, tests/nlu/featurizers/test_count_vectors_featurizer.py
- rename `spacy_nlp` to `model` as the recipe by default tries to fill the `model` param if `model_from` was specified
=> fix param name in `CountVectorsFeaturizer`

docs/versioned_docs/version-2.x/command-line-interface.mdx, docs/versioned_docs/version-2.x/policies.mdx, docs/versioned_docs/version-2.x/stories.mdx, docs/versioned_docs/version-2.x/training-data-format.mdx, docs/versioned_docs/version-2.x/training-data-importers.mdx
- The update has been made on `main` already, it's a matter of harmonising the callouts across docs versions.
- This PR is targeting `documentation` to make a direct update to the doc without needing a release; [this other PR](https://github.com/RasaHQ/rasa/pull/10166) is targeting 2.8.x so that the next time there is another micro release on 2.8.x, the changes made into `documentation` won't be erased (it's some sort of manual sync, basically)
=> update experimental feature callouts

rasa/cli/scaffold.py, rasa/cli/utils.py
Fixes https://github.com/RasaHQ/rasa/issues/10101
=> Fix model dir

rasa/engine/caching.py, rasa/engine/storage/resource.py, rasa/engine/training/hooks.py, tests/engine/graph_components_test_classes.py, tests/engine/storage/test_resource.py, tests/engine/test_caching.py, tests/engine/training/test_graph_trainer.py
Use a unique fingerprint for a resource that is consistent after caching. This ensures we always retrieve the correct resource for a node from the cache.
Fixes #10147
=> Use a unique fingerprint for a resource that is consistent after caching.

rasa/nlu/utils/mitie_utils.py
closes #10140
Adds a separate error message to clarify when configuration for MITIE NLU component is incorrect due to a missing file.
=> 3.0 mitie nlp error message

changelog/10079.bugfix.md, data/test_config/config_defaults.yml, data/test_validation/data/nlu.yml, data/test_validation/data/stories.yml, data/test_validation/domain.yml, rasa/validator.py, tests/test_validator.py
Fixes #10079.
The following changes were made:
- we exclude the default / implicit intents from generating warnings if they're unused; otherwise, any empty / newly initialized rasa project would throw warnings for unused intents, which would be confusing to the user
- if an intent is defined, but not used in the NLU data at all, we generate a warning and consequently abort if `--fail-on-warnings`.
- if an intent is defined, but not used either in a story or rule we generate a warning and consequently abort if `--fail-on-warnings`. Note here that the debug message that was printed before was also inexact since it mentioned only stories, this was clarified to also include rules.
- The same as in the bullet point before was also implemented for utterances
**Status (please check what you …
=> Validations for unused intents and utterances

rasa/core/actions/action.py, tests/core/test_actions.py
=> Fix confusing warning message when using custom mapping action

docker/configs/config_pretrained_embeddings_spacy_de.yml
- `Dockerfile.pretrained_embeddings_spacy_de` installs `de_core_news_sm` instead of `de_core_news_md`, so change config YAML to match this (closes #10139 )
=> Swap spacy model used by dockerfile

rasa/core/actions/action.py, rasa/shared/core/slot_mappings.py, tests/core/actions/test_forms.py, tests/core/test_actions.py
=> slots extracted `from_intent` or `from_entity` for an un-specified intent/entity raises no error/warning

Makefile
Fixes bug where transformers models for CI tests were being cached to incorrect location on Windows
Since the $HOME env isn’t set in Windows we were downloading the `lm_featurizer` models to a different place from where it looks when you run the `lm_featurizer` tests, so if it has to download them within the test then it can crash or timeout.
=> Use correct env var for home dir on Windows in Makefile

docs/static/spec/rasa.yml, rasa/server.py
Fixes https://github.com/RasaHQ/rasa/issues/10148
- Updates `/model/train` endpoint in docs to only accept YAML input
- Updates `/model` endpoint to clarify model path
=> Fix API docs

rasa/shared/utils/validation.py
Closes #10288
- This adds a log warning in the case where a user has manually migrated their domain and data files to the latest Rasa Open Source version format, but is still specifying a lower version in these files. eg: using a rasa 3.0 format, but still specifying `version: "2.0"`. 
- This warning will be logged during the validation step, asking the user to update the version in their domain or data files to the LATEST_TRAINING_DATA_FORMAT_VERSION.
=> add warning log asking user to update training data version

.github/workflows/ci-model-regression-on-schedule.yml
Fixes: https://github.com/RasaHQ/rasa/issues/10349
- Enable datadog API for `ci-model-regression-on-schedule.yml`
- This is the same as https://github.com/RasaHQ/rasa/pull/10075/, but for the on-schedule regression tests.
=> Send datadog metrics for regression tests on Schedule

docs/docs/nlu-training-data.mdx, rasa/nlu/utils/pattern_utils.py, tests/nlu/utils/test_pattern_utils.py
addresses the OSS side of #6960
This adds regex validation to the `extract_pattern` method of `rasa/nlu/utils/pattern_utils.py` and a corresponding test.
I'm not totally sure about the error message, eg:
```
"Model training failed. '*[0-9]{5}' is not a valid regex. Please update your nlu training data configuration at {'name': 'zipcode', 'pattern': '*[0-9]{5}'}."
```
Discussion concluded that training should fail and a readable error message displayed, however I'm not sure if this message gives the user enough info about where this config is.
=> add regex validation to pattern utils

rasa/engine/graph.py, rasa/nlu/utils/spacy_utils.py
Closes #10232 
This uses the originating error info in `graph.py` when a rasa exception is raised. 
These errors now appear as:
```
❯ rasa train
2021-11-26 16:24:14 INFO     rasa.nlu.utils.spacy_utils  - Trying to load SpaCy model with name 'None'.
2021-11-26 16:24:14 ERROR    rasa.engine.graph  - Error initializing graph component for node provide_SpacyNLP0.
InvalidModelError: Missing model configuration for `SpacyNLP` in `config.yml`.
You must pass a model to the `SpacyNLP` component explicitly.
For example:
- name: SpacyNLP
model: en_core_web_md
More information can be found on https://rasa.com/docs/rasa/components#spacynlp
❯ rasa train
2021-11-26 16:25:40 INFO     rasa.nlu.utils.spacy_utils  - Trying to load SpaCy model with name 'IUYIUYI'.
2021-11-26 16:25:40 …
```
=> Tidy output when raising InvalidModelError

changelog/10413.improvement.md, rasa/core/brokers/kafka.py
- Add a `RASA_ENVIRONMENT` header to the Kafka event producer to make it available to consumers [as is done in the `app_id` for Pika](https://github.com/RasaHQ/rasa/blob/4fd90e7b55a6e354a7dfd16286e5fe7f11b53f52/rasa/core/brokers/pika.py#L297)
- Closes https://github.com/RasaHQ/rasa-x/issues/7010 in conjunction with https://github.com/RasaHQ/rasa-x/pull/7013
=> Make `RASA_ENVIRONMENT` available in events logged by Kafka producer

.github/workflows/automatic-release-to-main-merger.yml
- Disable the `release-to-main-merger` workflow on `2.8.x` branch
=> Don't merge 2.8.x into main

changelog/10391.bugfix.md, rasa/core/policies/unexpected_intent_policy.py, rasa/engine/graph.py, rasa/utils/common.py, rasa/utils/train_utils.py, tests/engine/test_graph_node.py, tests/nlu/classifiers/test_diet_classifier.py, tests/utils/test_common.py
Fixes #10391 
The error reported in the above ticket seemingly comes from the default configuration being overridden without taking care of nested dictionaries. This as far as I can tell happens in the `GraphNode` implementation in `rasa/engine/graph.py`, where the default and custom configs of a component get merged via [dictionary unpacking](https://github.com/RasaHQ/rasa/blob/3.0.x/rasa/engine/graph.py#L362). Since by definition of the dictionary creation via unpacking, the [last value for a given key wins](https://stackoverflow.com/a/39678945/17496163), this will not keep the unspecified keys of the nested dict in the default config.
- In Rasa 2.x, default and custom config parameters were combined using the function …
=> Overriding default config in case of nested dictionaries

rasa/utils/train_utils.py, tests/utils/test_train_utils.py
- Duplicate of https://github.com/RasaHQ/rasa/pull/8944
- Adds the actual values of the configuration to the warning message to make the warning more helpful.
(The community member didn't respond for a long time, so this PR just completes their work, sadly I can't do it in their PR itself.)
=> Fix warning to display actual configuration values

changelog/10458.bugfix.md, rasa/core/policies/ensemble.py, rasa/core/policies/unexpected_intent_policy.py, tests/core/policies/test_unexpected_intent_policy.py
- Port the fix that makes action metadata available in the tracker to 2.8.x
=> Make action metadata available in tracker in 2.8.x

changelog/10507.misc.md, rasa/server.py
closes #10507
Add deprecation warning to POST `/conversations/<conversation_id:path>/execute` endpoint
=> add deprecation warning to `/execute` endpoint

.github/workflows/ci-model-regression.yml
[This PR](https://github.com/RasaHQ/rasa/pull/10522) renamed the on-schedule workflow, but the reference was not updated. This causes the comment step to fail, e.g. https://github.com/RasaHQ/rasa/runs/4535398390?check_suite_focus=true
- Mention the referred workflow by it's new name
=> Fix comment issue (can't find last on-schedule MR test)

changelog/10448.bugfix.md, data/test/demo-rasa-lookup-ents.yml, rasa/nlu/test.py, tests/nlu/test_evaluation.py
Fixes #10448 
Since the lookup tables that are defined in the NLU training data, did not get copied to the `TrainingData` folds that are created by [generate_folds](https://github.com/RasaHQ/rasa/blob/3.0.x/rasa/nlu/test.py#L1442) for cross validation, the entities predicted by `RegexEntityExtractor` remained empty. Adding the `lookup_tables` parameter solves the issue and all expected entities in the lookup table are recognized.
- Add `lookup_tables` parameter to training data folds in `generate_folds` function.
=> Bugfix 10448 cross validation lookup tables

.github/workflows/ci-model-regression-on-schedule.yml
**Bug**: Last weekend the on-schedule regression tests failed, see https://github.com/RasaHQ/rasa/actions/runs/1599710132, because `report.json` didn't exist when the `analyse_performance` job would be looking
- Make `analyse_performance` job wait for `combine_reports` job to finish to find `report.json`
=> Fix on-schedule regression tests

.github/change_filters.yml, .github/workflows/ci-docs-tests.yml, .github/workflows/continous-integration.yml, .github/workflows/documentation.yml, .github/workflows/security-scans.yml, changelog/10601.misc.md
- Create virtual environments manually in all workflows that need one (mimic'ing what we do for unit tests)
- Update `change_filters.yml` to also listen to changes in workflow files
- Introduce PR labels to invalidate poetry cache if needed
=> Fix CI workflow runs using manually created virtual environments

changelog/10385.misc.md, docs/docs/components.mdx
This docs update aims to clarify some details around which HuggingFace models can be used with `LanguageModelFeaturizer`. Despite the supported architectures being listed in our docs, users often try others and report errors in the forum. Furthermore, not all pretrained weights from the HF models hub for the supported architectures can be used (e.g. due to missing TF weights or non-standard tokenizers being used), which results in error messages that are hard to interpret.
A related ticket with links to forum issues can be found here [here](https://github.com/RasaHQ/rasa/issues/10385).
- Clarify the limitations of the current implementation of `LanguageModelFeaturizer` w.r.t. model architectures and weights from HuggingFace
**Status (please check what you already …
=> Clarify limitations of LanguageModelFeaturizer in docs

changelog/10634.bugfix.md, rasa/core/brokers/kafka.py
- Only add `RASA_ENVIRONMENT` header if the env var is set
- Resolves problem [here](https://github.com/RasaHQ/rasa/pull/10614#discussion_r777035191)
=> Only add rasa_environment header to kafka message if it is set

rasa/shared/constants.py, rasa/shared/nlu/interpreter.py
partially closes #9619 
- This is a small change that updates the error message returned when a regex message is used within `rasa shell` and `rasa interactive`. 
- This change is for `2.8.x`, a separate PR for `main` will be raised.
=> update error message for cli regex parse error

rasa/shared/core/training_data/story_reader/yaml_story_reader.py
partially closes #9619
This is a small change that updates the error message returned when a regex message is used within rasa shell and rasa interactive.
This change is for `main`, a separate PR for `2.8.x` has been raised.
=> update message for regexp parsing error

changelog/10634.bugfix.md, rasa/core/brokers/kafka.py
- backport of https://github.com/RasaHQ/rasa/pull/10634/files
=> (2.8 backport) Only add rasa_environment header to kafka message if it is set

.github/stale.yml
- Addresses one discussion point from https://github.com/RasaHQ/enable_squad/issues/76
- Mark PRs as stale if they didn't receive activity in the past 90 days
- Close stale PRs 21 days after they're marked as stale
=> Update stale bot configuration to also cover PRs

changelog/10658.misc.md, docs/docs/components.mdx
Added a note to the docs. Some forum members were a bit confused about pre-trained models in DIET.
=> Added small clarification related to pretrained models

.github/workflows/ci-model-regression.yml
**Motivation:** Since https://github.com/RasaHQ/rasa/pull/10574, summary comments after a MR test run are gone, if a job is failing
- Add comment also in case of (partial) failure (also send email in the same cases)
- GH labels (`status:model-regression-tests` and `runner: gpu`) are now removed in both cases: success and failure
- `result.json` artifact contains (only) results from those jobs that succeeded
- Implementation: Introduce `set_job_success_status` job to set the overall run status to failed if one of the jobs failed
- keep on-schedule as is (doesn't have comments)
**Checked:**
=> Regression Test Failure Comment

.github/workflows/ci-model-regression.yml
I think I found a dead link, so I figured I'd do the right thing and replace it.
=> Replaced dead link in ci-model-regression

.github/workflows/documentation.yml
- Fixes https://github.com/RasaHQ/rasa/issues/10707
=> Disable docs preview workflow on PRs coming from forks

changelog/10536.doc.md, docs/docs/forms.mdx
=> Dynamic Form Docs Section Update

.github/poetry_version.txt, docker/docker-bake.hcl, poetry.lock
Fixes https://github.com/RasaHQ/rasa/issues/10708
We noticed some developer environments had problems with earlier Poetry
and also some community pull requests failed. Error such as:
```
ERROR: Could not install packages due to an OSError: [WinError 2] The
system cannot find the file specified:
'd:\\a\\rasa\\rasa\\.venv\\Lib\\site-packages\\nr\\__init__.py'
```
and
`'Link' object has no attribute 'is_absolute'`
- Upgrade poetry to 1.1.11
=> Upgrade poetry to 1.1.11

.github/dependabot.yml, CODEOWNERS
- Rename in CODEOWNERS
- Rename in dependabot config
- @joejuzl can you rename the `RasaHQ/enable-squad` GitHub handle to `RasaHQ/atom-squad` upon merge of this PR?
=> Rename enable-squad -> atom-squad

changelog/10782.bugfix.md, data/test_classes/custom_slots.py, data/test_domains/custom_slot_domain.yml, rasa/shared/utils/schemas/domain.yml, tests/shared/core/test_domain.py
- Allow arbitrary keys under a slot in the domain as was allowed in 2.x
- closes https://github.com/RasaHQ/rasa/issues/10765
=> Fix domain slot schema

changelog/10516.bugfix.md, rasa/core/policies/ted_policy.py, rasa/nlu/classifiers/diet_classifier.py, tests/core/policies/test_ted_policy.py, tests/nlu/classifiers/test_diet_classifier.py, tests/nlu/selectors/test_selectors.py
- Fixes #10516 
- Implements overwriting the final model weights with the checkpoint weights after training of `DIETClassifier`, `ResponseSelector` and `TEDPolicy`. 
=> Overwrite final weights with checkpoint weights before persisting

changelog/10840.bugfix.md, rasa/server.py
- When bumping Rasa Enterprise to Rasa Open Source, Rasa Open Source crashed during startup due to a missing asyncio loop. This creates the event loop in case it's not yet initialized.
```
Starting Rasa X in production mode... 🚀
deployment-rasa-production-1  | Traceback (most recent call last):
deployment-rasa-production-1  |   File "/opt/venv/bin/rasa", line 8, in <module>
deployment-rasa-production-1  |     sys.exit(main())
deployment-rasa-production-1  |   File "/opt/venv/lib/python3.8/site-packages/rasa/__main__.py", line 121, in main
deployment-rasa-production-1  |     cmdline_arguments.func(cmdline_arguments)
deployment-rasa-production-1  |   File "/opt/venv/lib/python3.8/site-packages/rasa/cli/x.py", line 364, in rasa_x
deployment-rasa-production-1  | …
```
=> fix: :bug: fix server startup with JWT secret

docs/docs/reaching-out-to-user.mdx
- Example rule had `action_schedule_reminder` which is not consistent with example reminder bot, nor the actions.py above in this page.
=> Change Rule to match actions.py

.github/configs/mr-test-schedule.json, .github/workflows/ci-model-regression-on-schedule.yml
This PR made multiple changes on the schedule version of Model Regression Tests workflow:
- Quote path strings
When passing dataset/config path to `rasa test core/nlu`, paths with whitespaces will break at whitespace which leads to unexpected results, e.g., not being able to locate stories to test on. 
- Upload diagnostic data to artifact if tests that test `rasa test core`. 
Resolves https://github.com/RasaHQ/rasa/issues/10730
- Skip Slack notifications on github events other than `on schedule`
We don't want to make noise while testing on PR 🙃
TODOs:
=> ci: Upload diagnostic data as artifact

rasa/core/migrate.py, rasa/shared/core/domain.py, tests/cli/test_rasa_data.py, tests/cli/test_rasa_test.py, tests/core/actions/test_forms.py, tests/core/actions/test_two_stage_fallback.py, tests/core/nlg/test_response.py, tests/core/policies/test_rule_policy.py, tests/core/policies/test_ted_policy.py, tests/core/policies/test_unexpected_intent_policy.py, tests/core/test_actions.py, tests/core/test_evaluation.py, tests/core/test_migrate.py, tests/core/test_processor.py, tests/core/test_test.py, tests/core/training/test_interactive.py, tests/nlu/extractors/test_extractor.py, tests/shared/core/test_domain.py, tests/shared/core/test_slot_mappings.py, tests/shared/core/test_trackers.py, tests/shared/core/training_data/story_writer/test_yaml_story_writer.py, tests/shared/core/training_data/test_structures.py, tests/shared/utils/test_validation.py, tests/test_model_testing.py, tests/test_model_training.py, tests/test_server.py, tests/test_validator.py
- Reference the constant `LATEST_TRAINING_DATA_FORMAT_VERSION` everywhere instead of hardcoding `"3.0"`. This makes it simpler to bump the training data version in the future (will be required soon).
=> use constant for training data version everywhere

.github/scripts/mr_publish_results.py, .github/workflows/ci-model-regression-on-schedule.yml, .github/workflows/ci-model-regression.yml
**Motivation:** 🌆  We used this Metabase page https://metabase.rasa.com/dashboard/166-research-model-performance :chart_with_upwards_trend: for tracking ML model performance. However, we also have Datadog for the same purpose right now basically containing the same (even more) information: [This](https://app.datadoghq.eu/dashboard/xsh-dvk-jca/rasaoss-regrtest-model-performance-runtimes?tpl_var_config=%2A&tpl_var_dataset=%2A&from_ts=1642427639416&to_ts=1645106039416&live=true) comparable Datadog dashboard can be used.
- Deprecate the Metabase regression test page (the page will stay online in case we need to inspect historical data, but not receive any new data)
- Simplify the regression test implementation
=> Sunset Segment/Metabase for regression tests

.github/scripts/start_dd_agent.sh, .github/workflows/ci-model-regression-on-schedule.yml, .github/workflows/ci-model-regression.yml
After a [small investigation](https://app.datadoghq.eu/notebook/24825/interval-of-gpu-nvml-metrics-measurement), we see that it is possible to see more fine-grained GPU measurements. The datadog default interval was 15 seconds, in this PR we can set it to 1 second.
- Add `NVML_INTERVAL_IN_SEC` param to `start_dd_agent.sh`
- The `NVML_INTERVAL_IN_SEC` param can be set as a global env variable in regression tests
**Future work:**
- Consider putting parameter into `/modeltest` comment (to improve easy of use)
**Question for reviewers**
- What should the default interval be?
=> Regr Tests: Add GPU NVML Interval

changelog/_template.md.jinja2, scripts/release.py
- Update release script to use `towncrier` API that changed in `21.9.0`
- `towncrier` [changelog](https://github.com/twisted/towncrier/blob/master/NEWS.rst)
- Here is the [blame of the poetry.lock file on main](https://github.com/RasaHQ/rasa/blame/main/poetry.lock#L3077)). The changes in `rasa` codebase are recent (I guess I was lucky to find the issue, [the 3.0.8 changelog seems to be fine](https://github.com/RasaHQ/rasa/blob/main/CHANGELOG.mdx)!)
- They added a new `--version` option that prints `towncrier` version and exits, which makes our changelog generation fail silently. In addition they introduced a `build` command.
- Update changelog template to fix missing title issues
**In order to test**, you can run `make generate-pending-changelog` to see how this …
=> update towncrier command to new API

changelog/10675.bugfix.md, rasa/cli/data.py, rasa/nlu/convert.py, tests/cli/test_rasa_data.py
- fix JSON to YAML convert
- fix https://github.com/RasaHQ/rasa/issues/10675
=> fix: fix JSON to YAML conversion

changelog/10989.removal.md, docs/docs/migration-guide.mdx, rasa/shared/nlu/training_data/formats/rasa.py, tests/cli/test_rasa_data.py
- NLU data in JSON format is deprecated and will be removed in Rasa Open Source 4.0.
- fix ATO-26
=> deprecate: deprecate NLU JSON format

.github/workflows/continous-integration.yml
**Motivation**: We use pytest-xdist to run multiple tests in parallel.  https://pypi.org/project/pytest-xdist/ mentions that "pytest will spawn a number of workers processes", therefore our naming with "threads" is slightly confusing
- Rename "thread" to "process"
=> Rename thread to process

tests/conftest.py, tests/core/test_evaluation.py, tests/core/test_processor.py, tests/nlu/featurizers/test_lm_featurizer.py
**Reasoning:** 
- As part of https://github.com/RasaHQ/rasa/issues/9734, we found some tests that cause resource exceptions on Windows CI
- this leads to errors with JOBS=2
- These tests take too long to run in the CI, disabling them for now
- Skip some tests on CI that take a lot of time
=> Skip e2e tests on CI

docs/docs/command-line-interface.mdx
- Fixes https://rasahq.atlassian.net/browse/ROSS-18
- Fixes https://rasahq.atlassian.net/browse/ROSS-34
- Fixes https://rasahq.atlassian.net/browse/ROSS-91
- Fixes https://rasahq.atlassian.net/browse/ROSS-90
=> Ross 18 log level libraries setting does not override default debug log level when running cli with debug

docs/docs/components.mdx
- Add a note that `model_confidence: cosine` will still be used if `loss_type: margin` is specified, regardless of `model_confidence` set in config.yml.
=> add a footnote about model_confidence cosine

docs/docs/how-to-deploy.mdx
- Redirects URLs to removed Rasa X installation methods to Rasa X 1.0.x docs. 
=> redirect to 1.0.x rasa x docs for removed installation methods

data/graph_schemas/graph_config_short_train_schema.yml, data/test_config/graph_config_short.yml, docs/docs/graph-recipe.mdx
- The graph config example in the [graph recipe docs page](https://rasa.com/docs/rasa/graph-recipe/#graph-configuration-file-structure) is incomplete in the `train_schema` section and could cause confusion. Added missing nodes for a complete config file.
=> Fix incomplete graph config docs example

changelog/11102.improvement.md, rasa/cli/arguments/train.py, tests/cli/test_rasa_train.py
- Add the `--endpoints` argument to rasa train to make endpoints available during training if needed.
=> Add optional `--endpoints` argument to `rasa train`

changelog/10480.bugfix.md, rasa/cli/x.py, tests/cli/test_rasa_x.py
- Move the warning raised for `rasa x` so that it does not warn for `rasa x --production` which does not start localmode.
=> remove warning when running `rasa x --production`

.github/workflows/continous-integration.yml, Makefile, setup.cfg
- [ATO-54](https://rasahq.atlassian.net/browse/ATO-54)
- Added a make target to check changelog fragment filenames are in the expected format at the PR level.
**Tested with error filename**:
=> [ATO-54] Add make target to lint changelog filenames at PR level

.github/dependabot.yml
- Remove automatic reviewer in dependabot PRs for python
=> Do not assign a reviewer to dependabot PRs for python

changelog/11129.bugfix.md, changelog/README.md, rasa/core/channels/botframework.py, tests/core/channels/test_botframework.py
This PR enables JSON Web Token validation for the JWTs coming in from the Azure botframework channel. This is achieved by periodically updating the keys that Microsoft uses to sign the tokens, saving those in memory, and then validating the tokens and verifying their signature for incoming requests from the bot framework. 
For details on how the botframework does authentication, see [here](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0#connector-to-bot).
=> Validate incoming JWT tokens from the bot framework

changelog/10430.bugfix.md, rasa/validator.py, tests/test_validator.py
=> Fix `rasa data validate` for rules containing default actions as `active_loop`

.github/workflows/automatic-release-to-main-merger.yml
We do not want to merge back these releases to the main branch.
Ex:
* https://github.com/RasaHQ/rasa/pull/11250
* https://github.com/RasaHQ/rasa/pull/11202
=> Do not merge 3.0/3.1 back to main

.github/dependabot.yml, .github/workflows/ci-github-actions.yml
We can't configure dependabot for targeting upgrades related to security vulnerabilities only.
As it is, it creates too much noise.
=> Remove dependabot targeting previous releases

changelog/11305.bugfix.md, rasa/core/channels/slack.py, tests/core/channels/test_slack.py
- Fixed response when slack sends retries (None was giving error)
- Running on_new_message as an asyncio background task instead of a blocking await (so that we immediately return 200 to Slack and we don't reach the 3 seconds timeout if the action execution is slow)
=> Slack channel fixes

changelog/11326.bugfix.md, rasa/core/actions/forms.py, tests/core/actions/test_forms.py
- Revert change here https://github.com/RasaHQ/rasa/pull/10295/files#r807244104 that removed running the form validation action on activation of the form (before the loop is active).
- This would make #10913 obsolete since the 2.x mechanism for achieving the same thing would be returned.
- Closes #11199 
- Resolves the issue where any `extract_<slot_name>` method in a FormValidationAction subclass only runs after a required_slot in the form has been set (i.e. after activation).
=> ATO 207 run form validation  on form activation

changelog/11333.bugfix.md, data/test_action_extract_slots_11333/config.yml, data/test_action_extract_slots_11333/data/nlu.yml, data/test_action_extract_slots_11333/data/stories.yml, data/test_action_extract_slots_11333/domain.yml, data/test_action_extract_slots_11333/tests/test_stories.yml, rasa/core/actions/action.py, tests/core/test_actions.py, tests/regressions/test_action_extract_slots_11333.py
- Apply https://github.com/RasaHQ/rasa/pull/11333 to 3.2.x
=> Port RasaHQ/ATO-218-always-set-slots

docs/plugins/program_output.js
- Change regex for docusaurus plugin that looks for versioned docs to look for `X.x` folders not `X.x.x`
=> update plugin for program output in docs

changelog/11362.bugfix.md, data/test_custom_action_triggers_action_extract_slots/config.yml, data/test_custom_action_triggers_action_extract_slots/domain.yml, data/test_custom_action_triggers_action_extract_slots/nlu.yml, data/test_custom_action_triggers_action_extract_slots/stories.yml, rasa/core/processor.py, tests/core/test_processor.py
- Fixes https://rasahq.atlassian.net/browse/ATO-244
=> Run default `action_extract_slots` after a `UserUttered` event returned by a custom action

changelog/11368.bugfix.md, rasa/core/tracker_store.py, tests/core/test_tracker_stores.py
- Fixes https://rasahq.atlassian.net/browse/ATO-222
=> Allow `EndpointConfig` as parameter type given to `AwaitableTrackerStore.create()` method

changelog/11390.bugfix.md, docs/docs/domain.mdx, rasa/core/actions/action.py, tests/core/test_actions.py
- Fixes 2.x regression (broken in `3.x`) where the expected priority order in which slot mappings are applicable is from the beginning to the end of the slot mappings list specified in the domain (more context [here](https://rasahq.atlassian.net/browse/ATO-219))
- Clarifies this implicit priority order in the docs.
=> Fix the priority order of slot mappings in which slots are filled

.github/workflows/ci-docs-tests.yml, Makefile
- The last step of `make test-docs` is to lint check the docs, this performs a `remark --frail` command which exits on any linter warnings. This is a problem when we have third party dead URLs warnings over which we have no control (such as currently https://duckling.wit.ai/).
- I propose to separate the linting check into its own non-required CI job.
=> Separate docs linting into a non-required job

changelog/11394.bugfix.md, rasa/core/processor.py, tests/core/test_processor.py
- Fixes https://github.com/RasaHQ/rasa-sdk/issues/612 (more context in the discussion [here](https://rasahq.atlassian.net/browse/ATO-245))
=> Fix `ValidationAction` dispatching of `BotUttered` messages

.github/workflows/documentation.yml, scripts/evaluate_release_tag.py
- Fix release tag evaluation in docs workflow so that docs are not built for previous minors on the latest major, which were overwriting the latest version of the docs
=> update release tag evaluation in docs workflow

changelog/11311.bugfix.md, rasa/core/channels/rest.py
Replacement PR for #11311 re-based on `3.2.x`.   I'm targeting `main` for this PR since that's the GitHub default. Am I supposed to target `3.2.x`?
The REST channel should by default load the `metadata` key.  I thought this worked in the past but can't seem to find when it was dropped.
=> REST metadata

tests/conftest.py, tests/core/test_test.py
- Disabling the last of the 3 e2e agent tests. The other two had been disabled previously. This one was missed and takes on average 6 min in the unit testing according to our data.
=> disabled last of the slow e2e agent tests for now

.github/workflows/documentation.yml
The documentation workflow has been failing with ModuleNotFoundError: No module named 'pep440_version_utils', in the branch 3.1.x this additional step was [added](https://github.com/RasaHQ/rasa/pull/11444/files#diff-d7ecc9db1d2f1f75440ba2c3e433aec8c252e9c86a6260732400737857c71d3bR73) to fix this but its missing from main.
=> Add workflow step to install pep440

poetry.lock
- Part of fix required for [ATO-299](https://rasahq.atlassian.net/browse/ATO-299)
- ujson already updated to `5.4.0` as written in `poetry.lock` [here](https://github.com/RasaHQ/rasa/blob/e4a5943823fbff746d514395b63d418cefa94aab/poetry.lock#L3109)
=> Update sanic and rasa sdk to latest security patches in 2.8.x

.github/workflows/documentation.yml
This PR reverts commit https://github.com/RasaHQ/rasa/commit/b775964bc57eaf3ffef1ecdd6075efb6aac0ea3b.
- Currently the documention website requires node.js <= 12.22.x, this PR reverts an accidental change
=> Restore documentation building parameters compatible with node 12

changelog/ATO-264.improvement.md, rasa/shared/nlu/training_data/features.py, rasa/shared/nlu/training_data/message.py, tests/shared/nlu/training_data/test_features.py, tests/shared/nlu/training_data/test_message.py
- Caching fingerprints of messages until message is manipulated
- Caching fingerprints of features until they are manipulated
In my test on the oos dataset (roughly 15k nlu examples) the changes shaved off around 25 seconds of around 40 seconds in total for the fingerprinting. So roughly a 2/3 reduction in pure fingerprinting time.
I also looked at more general options to speed up caching, but our caching methods are just very generic and work on a very diverse set of inputs, especially arbitrarily nested dicts and lists. I found that my attempts to improve caching there, for example trying to employ frozendicts to cache some of the dictionaries, lead to longer fingerprinting times.
I also considered adding additional safeguards such as a test that checks whether all …
=> Caching feature and message fingerprints

README.md, docs/docs/installation.mdx
- poetry installation instructions on the README were deprecated. Since there's a variety of ways to install poetry I simply referred to the official installation instructions in the readme and updated the existing linux/mac section in docs
=> refer to official poetry installation instructions

.github/ISSUE_TEMPLATE/bug_report.yaml
- Python version option items are specified as numbers which cause s 3.10 to be displayed as 3.1. Just quoted options to treat them as strings. Fixes https://github.com/RasaHQ/rasa/issues/11634
=> fix: wrong python version is issue template

changelog/11724.doc.md, docs/docs/forms.mdx, docs/docs/migration-guide.mdx
- Completes [ATO-442](https://rasahq.atlassian.net/browse/ATO-442)
=> Update docs with strong prescriptive recommendation on how to handle dynamic form behaviour with custom slot mappings

changelog/11768.doc.md, docs/docs/responses.mdx
Update the documentation for Buttons using messages with '/'. It wrongly stated that messages with '/' bypass NLU, which is not the case.
=> Ato 266 docs update 

changelog/11766.doc.md, docs/docs/testing-your-assistant.mdx
- Clearify in the documentation how to write testing stories if a user press a button with payload
=> doc: add testing story example for button with payload

changelog/11818.bugfix.md, docs/docs/connectors/telegram.mdx, docs/docs/messaging-and-voice-channels.mdx, rasa/core/channels/telegram.py, tests/core/test_channels.py
- Fixes `RuntimeWarning: coroutine 'Bot.set_webhook' was never awaited` issued when starting the rasa server, that causes Telegram bot to be unresponsive.
- Tested manually with moodbot in Telegram and only locally by using ngrok, bot was responsive after the fix.
=> Fix unawaited method issue in Telegram channel interface

.github/workflows/continous-integration.yml, changelog/11792.bugfix.md, rasa/engine/storage/local_model_storage.py, tests/engine/storage/test_local_model_storage.py
- LocalModelStorage bypasses windows path name length restriction upon saving archive
- Made sure the test was failing using TDD (see [build logs](https://github.com/RasaHQ/rasa/actions/runs/3564189533/jobs/5987876826))
=> LocalModelStorage bypasses windows path name length restriction upon saving archive

changelog/11926.misc.md, scripts/evaluate_release_tag.py, tests/scripts/test_evaluate_release_tag.py
Docs are only published for official releases. Decision to publish docs must not depend on the fact that next major or minor release had an alpha release.
=> [ATO-573] Doc release should omit alpha releases

changelog/11926.bugfix.md, scripts/evaluate_release_tag.py, tests/scripts/test_evaluate_release_tag.py
- port https://github.com/RasaHQ/rasa/pull/11926 to 3.4.x
=> Scripts/ato 573 3.4.x doc release should omit alpha releases

changelog/11926.bugfix.md, scripts/evaluate_release_tag.py, tests/scripts/test_evaluate_release_tag.py
=> Scripts/ato 573 3.3.x doc release should omit alpha releases

changelog/11926.bugfix.md, scripts/evaluate_release_tag.py, tests/scripts/test_evaluate_release_tag.py
=> Scripts/ato 573 3.2.x doc release should omit alpha releases

docs/docs/policies.mdx
Co-authored-by: Antonio <netocaastro10@gmail.com>
- Removed model_confidence's linear-norm setting from the policies.mdx. Linear-norm was [removed](https://github.com/RasaHQ/rasa/blob/main/CHANGELOG.mdx#300---2021-11-23) in 3.0.0.
=> Remove linear-norm

changelog/12052.bugfix.md, rasa/shared/core/domain.py, tests/shared/core/test_domain.py
- the changes implemented fixes the bug that for multiple domain files whilst merging would throw an error when trying to explictly send domain for certain custom actions 
=> fix: allow send domain explictly for actions from multiple files

changelog/12059.bugfix.md, rasa/model_training.py, tests/test_model_training.py
- Check unresolved slots before initiating model training.
- Collects all the unresolved slots and throws an error mentioning the same. Hence, allows user to know all the slot mismatches at the first try itself.
- Fixes: https://rasahq.atlassian.net/browse/ENG-151
=> Slots in rules are not validated against declared slots - [ENG 151]

tests/core/test_processor.py
- Increased flaky test timeout to 180s to fix failures [here](https://github.com/RasaHQ/rasa/actions/runs/4254517398/jobs/7418499157)
=> Increase timeout on flaky tests

rasa/core/actions/action.py, rasa/plugin.py
Add hookspec to collect default actions from plugins and merge them to the `default_actions` list.
One of the ways how a user can activate space is by triggering intent that calls activation action. To make activation action non-custom action here, we add a mechanism to extend `default_actions`.
=> Add the hook to get extra non-custom actions from plugins

changelog/12096.bugfix.md, rasa/core/actions/action.py, rasa/core/processor.py, rasa/shared/core/slot_mappings.py, tests/shared/core/test_slot_mappings.py
- Fixes bug where a slot  - with `from_intent` mapping which contains no input for `intent` parameter - will no longer fill for any intent that is not under the `not_intent` parameter. Instead this warning is issued due to this check [here](https://github.com/RasaHQ/rasa/blob/3.4.x/rasa/shared/core/slot_mappings.py#L207):
```
/opt/venv/lib/python3.10/site-packages/rasa/shared/utils/io.py:98: UserWarning: Slot 'test_slot' uses a 'from_intent' mapping for a non-existent intent 'None'. Skipping slot extraction because of invalid mapping.
```
=> Fix bug in from_intent slot mapping without intent specified

changelog/12099.bugfix.md, rasa/utils/tensorflow/temp_keras_modules.py
Use validation dataset caching only when batch_size is static.
When `batch_size` is dynamic, it changes the length of the dataset, what causes skipping the evaluation step.
- ...
=> Fix skipping evaluation when batch_size is dynamic (#12099)

rasa/nlu/tokenizers/jieba_tokenizer.py, rasa/nlu/tokenizers/mitie_tokenizer.py, rasa/nlu/tokenizers/spacy_tokenizer.py, rasa/nlu/tokenizers/tokenizer.py, rasa/nlu/tokenizers/whitespace_tokenizer.py, tests/nlu/tokenizers/test_tokenizer.py
When tokenising intent, preserve the prefix as a word
When the intent is constructed as a `space+name!ask+language` prefix (`space+name`) needs to be processed separately and as a word. 
=> Add intent's prefix splitting step before intent tokenization

changelog/12137.misc.md, rasa/nlu/classifiers/diet_classifier.py, rasa/utils/tensorflow/constants.py, rasa/utils/tensorflow/models.py, tests/nlu/classifiers/test_diet_classifier.py
Add run_eagerly parameter to control whether to compile model before running or not
Saves computation time when user prelimienerly knows that model will be executed only for few steps.
- ...
=> Add run_eagerly parameter

.github/workflows/continous-integration.yml
- Deploying of 3.5.0 to pypi failed because the workflow had dependencies on the test runs and quality checks that were recently skipped during tag push.
- Removed condition to to redeploy tag to pypi
- Docker images were successfully published, so docker build step will fail so also had to remove any dependencies to the step: docker.
=> Remove workflow conditions to redeploy 3.5.0 pypi

changelog/12174.bugfix.md, rasa/utils/tensorflow/models.py
Training `DIETClassifier` fails on the GPU with an error
```
A deterministic GPU implementation of SparseTensorDenseMatmulOp is not currently available
```
=> Remove tensorflow ops force being deterministic

changelog/12144.improvement.md, docs/docs/generating-nlu-data.mdx, docs/docs/nlu-training-data.mdx, rasa/nlu/extractors/entity_synonyms.py, tests/nlu/extractors/test_entity_synonyms.py
- Add a self-reference of the synonym in the EntitySynonymMapper to handle entities extracted in a casing different to synonym case. (For example if a synonym `austria` is added, entities extracted with any alternate casing of the synonym will also be mapped to `austria`). It addresses [ATO-616](https://rasahq.atlassian.net/browse/ATO-616)
[ATO-616]: https://rasahq.atlassian.net/browse/ATO-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add a self-reference in synonyms map

.github/workflows/continous-integration.yml, changelog/12139.bugfix.md, rasa/core/processor.py, rasa/core/tracker_store.py, rasa/server.py, rasa/shared/core/trackers.py, tests/conftest.py, tests/core/test_processor.py, tests/core/test_tracker_stores.py, tests/integration_tests/core/test_tracker_store.py, tests/test_server.py, tests_deployment/docker-compose.integration.yml
- Fixes [ATO-694](https://rasahq.atlassian.net/browse/ATO-694) ticket in 2 parts:
1. The cause for not retrieving full tracker from GET endpoint `conversations/{conversation_id}/tracker?include_events=ALL` was two-fold: 
-  The endpoint was retrieving only the latest session of the tracker
-  Updated the implementation  using `TrackerStore.retrieve_full_tracker` method and therefore discovered that `FailSafeTrackerStore` was missing the implementation for this method.  
- Added the implementation of this method in this interface as well as in all other TrackerStore interfaces missing this implementation (e.g. `InMemoryTrackerStore`, `RedisTrackerStore`, `DynamoTrackerStore`).
2. Retrieving empty stories for a tracker which included a `Restarted` event was fixed by …
=> Fix retrieving a conversation tracker from HTTP API endpoint dependent on query params

changelog/12144.improvement.md, docs/docs/generating-nlu-data.mdx, docs/docs/nlu-training-data.mdx, rasa/nlu/extractors/entity_synonyms.py, tests/nlu/extractors/test_entity_synonyms.py
- Changes from https://github.com/RasaHQ/rasa/pull/12144 and [ATO-616](https://rasahq.atlassian.net/browse/ATO-616) to change the behaviour of Synonym 
[ATO-616]: https://rasahq.atlassian.net/browse/ATO-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Port ATO-616 for 3.5.x

changelog/12144.improvement.md, docs/docs/generating-nlu-data.mdx, docs/docs/nlu-training-data.mdx, rasa/nlu/extractors/entity_synonyms.py, tests/nlu/extractors/test_entity_synonyms.py
- Changes from https://github.com/RasaHQ/rasa/pull/12144 and [ATO-616](https://rasahq.atlassian.net/browse/ATO-616) to change the behaviour of Synonym 
[ATO-616]: https://rasahq.atlassian.net/browse/ATO-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> backport changes for ATO-616

.github/workflows/continous-integration.yml, changelog/12226.bugfix.md, poetry.lock, pyproject.toml, tests/integration_tests/core/brokers/conftest.py, tests/integration_tests/core/brokers/test_pika.py
- Fix issue with failures while publishing events to RabbitMQ after a RabbitMQ restart.
The fix consists of pinning aio-pika dependency to 8.2.3, since this issue was introduced in aio-pika v8.2.4.
=> Port aio-pika bugfix to 3.5.x

tests/core/policies/test_ted_policy.py, tests/core/policies/test_unexpected_intent_policy.py
- Testing ted policy is currently a fairly complex, entangled test matrix with multiple levels of subclassing. Through this subclassing, a lot of long-running tests were executed multiple times with little benefit. I made sure that small config tests only trigger one training for this config but not 5 or 6 trainings as of now.
- reusing trained model in UnexpecTED testing when the model isn't altered during the test
- takes pure testing time down from ~30 min to 12-15min
=> Eng 248 policy tests speedup

.typo-ci.yml, changelog/12290.doc.md, docs/docs/command-line-interface.mdx
- Add a note to the CLI documentation page to address encoding/colour issues on certain windows terminals (git bash)
- Only way to fix [ATO-779](https://rasahq.atlassian.net/browse/ATO-779) (comments for info)
[ATO-779]: https://rasahq.atlassian.net/browse/ATO-779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATO-779 Add a note to documentation for fixing Windows character encoding or text colour 

changelog/12295.bugfix.md, rasa/server.py, tests/test_server.py
- Fixes [ATO-604](https://rasahq.atlassian.net/browse/ATO-604) and [OSS-129](https://rasa-open-source.atlassian.net/browse/OSS-129). These two tickets share the same root cause that an instance of an `output_channel` is not given in the API function handling endpoint GET `/conversations/{conversation_id}/tracker` [here](https://github.com/RasaHQ/rasa/blob/756d1c02aba002f1b79b8eb4894c8acd0be1e9ae/rasa/server.py#L723).
[ATO-604]: https://rasahq.atlassian.net/browse/ATO-604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix error when customizing `action_session_start` via a custom action

Makefile, changelog/12325.bugfix.md, rasa/core/brokers/pika.py, tests/core/test_broker.py, tests/integration_tests/core/brokers/test_pika.py
- Fixes [ATO-978](https://rasahq.atlassian.net/browse/ATO-978) and [ATO-976](https://rasahq.atlassian.net/browse/ATO-976)
- Adds integration tests for both cases (when credentials are passed in the endpoints url and when they're not)
- Fixes [docker prune conflict issue](https://github.com/RasaHQ/rasa/actions/runs/4789600582/jobs/8517691342#step:13:431) when the integration tests were run in parallel by applying pytest recommendation to use `--dist loadgroup` and `xdist_group` pytest marker
[ATO-978]: https://rasahq.atlassian.net/browse/ATO-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATO-976]: https://rasahq.atlassian.net/browse/ATO-976?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
=> Fix RabbitMQ url parsing 

.github/workflows/continous-integration.yml
- made windows datadog profiling dependent on explicit flag. Installation of the docker container on windows takes 2-6 minutes and adds significantly to run time.
- this works with the only caveat, that the label needs to be present at PR creation, or during reopening of the ticket to be taken into account 🤔 https://stackoverflow.com/a/59588725
=> made datadog on windows dependent on ci flag

.github/workflows/continous-integration.yml, .github/workflows/rasa-install-cron-check.yml, README.md, changelog/12355.removal.md, poetry.lock, pyproject.toml
- Python 3.7 is approaching its [end-of-life soon](https://devguide.python.org/versions/). Let's drop support for it.
- This involves updating the changes in dependencies, documentation, and CI Scripts.
=> Drop Python 3.7 Support

scripts/lint_python_docstrings.sh
=> Fix make lint-docstrings

.github/workflows/continous-integration.yml
- The default timeout for jobs on github actions is 360mins which means failing jobs especially for the tests keep running for hours. So restricting the timeout for the test steps in the workflow to 60mins, after which GithubActions should terminate the job.
- Needs to be ported to 3.5.x,3.4.x,3.3.x
=> Adding a timeout of 60mins for the test steps

changelog/11222.improvement.md, docs/docs/nlg.mdx, docs/docs/responses.mdx, rasa/core/actions/action.py, rasa/core/nlg/callback.py, rasa/shared/core/domain.py, rasa/shared/nlu/training_data/schemas/responses.yml, tests/core/nlg/callback.py, tests/core/test_actions.py, tests/integration_tests/core/actions/conftest.py, tests/integration_tests/core/actions/test_action.py, tests/shared/core/test_domain.py
Adding capability to set id for response variations in `domain.yml`.
Ids will be transmitted to the NLG so that NLG can make more informed decision when choosing appropriate response.
If response has a condition set then it will be examined before ID is transmitted to the NLG. 
=> [ATO-1122] Add response_ids to domain

docs/docs/rules.mdx
=> fix python typo (pypo?) in rules.mdx

.github/workflows/continous-integration.yml
Build both platforms on the same machine
=> Multi-platform image with GitHub Actions

docs/docs/llms/llm-flow-classifier.mdx, docs/docs/llms/llm-intent.mdx
- described basic working of llmflowclassifier
=> described basic working of llm flows classifier

changelog/12534.bugfix.md, rasa/cli/utils.py, tests/cli/test_utils.py, tests/nlu/featurizers/test_lm_featurizer.py, tests/nlu/test_train.py
- Fix [ATO-1151] 
[ATO-1151]: https://rasahq.atlassian.net/browse/ATO-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ATO-1151] Parentheses in button title overwrite button payload in rasa shell

changelog/12512.misc.md, docs/docs/telemetry/telemetry.mdx, rasa/plugin.py, rasa/telemetry.py, tests/test_telemetry.py
- Port fix to [ATO-1152](https://github.com/RasaHQ/rasa/pull/12512)
[ATO-1152]: https://rasahq.atlassian.net/browse/ATO-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ATO-1152] Port of Add license hashes to telemetry

changelog/12549.bugfix.md, rasa/cli/data.py, tests/cli/conftest.py, tests/cli/test_rasa_data.py
- Port of [PR](https://github.com/RasaHQ/rasa/pull/12521)
=> [ATO-797] Port of rasa data validate does not catch domain loading as an error

docs/docs/monitoring/analytics/realtime-markers.mdx
- Use `useBaseUrl` for pointing at image URL in docs (otherwise it doesn't work when there are multiple versions of the docs)
- This caused this issue: https://github.com/RasaHQ/rasa/actions/runs/5455513425/jobs/9927061615 (on the `documentation` branch)
=> fix img url in realtime-markers docs

changelog/12638.bugfix.md, rasa/model.py
- Fix [ATO-1138](https://rasahq.atlassian.net/browse/ATO-1138)
- getctime -> the last time file owner/permission changed or last time modified
- getmtime -> last time modified 
- `test_get_latest_model` already exists
[ATO-1138]: https://rasahq.atlassian.net/browse/ATO-1138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ATO-1138] Getctime does not select the latest model

changelog/12640.bugfix.md, rasa/model.py
- Port of [PR](https://github.com/RasaHQ/rasa/pull/12638)
=> [ATO-1138] Port of getctime does not select the latest model

changelog/12650.misc.md, poetry.lock, pyproject.toml
Update requests to 2.31.0 to fix CVE-2023-32681.
=> Update requests to 2.31.0 on 3.3.x

changelog/12649.misc.md, poetry.lock, pyproject.toml
Update requests to 2.31.0 to fix CVE-2023-32681.
=> Update requests to 2.31.0 on 3.5.x

changelog/12712.doc.md, docs/docs/pii-management.mdx
- Adds docs for [ATO-1264](https://rasahq.atlassian.net/browse/ATO-1264) & [ATO-1269](https://rasahq.atlassian.net/browse/ATO-1269)
[ATO-1264]: https://rasahq.atlassian.net/browse/ATO-1264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATO-1269]: https://rasahq.atlassian.net/browse/ATO-1269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update PII docs

poetry.lock, pyproject.toml
Bump pyjwt from 2.7.0 to 2.8.0
Bump cryptography from 41.0.2 to 41.0.3
Bump pyjwt from 2.7.0 to 2.8.0 https://github.com/RasaHQ/rasa/pull/12705
Bump cryptography from 41.0.2 to 41.0.3 https://github.com/RasaHQ/rasa/pull/12705
=> Housekeeping: update python deps pyjwt and cryptography

changelog/12737.bugfix.md, poetry.lock, pyproject.toml
- Ports Fixe for [ATO-1419](https://rasahq.atlassian.net/browse/ATO-1419)
[ATO-1419]: https://rasahq.atlassian.net/browse/ATO-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Port dnspython dependency fix to 3.6.x

rasa/shared/utils/llm.py
- ignore the warning, the framework sucks and actually you can't create an instance in that place without encountering the warning...
fixes https://rasa-hq.slack.com/archives/C05KCQDV8PJ/p1692012866420379
=> "Fix" langchain user warning

rasa/core/lock_store.py
- Connect to a Redis Lock Store with TLS
- I'm not making any documentation changes as these params already seem to be there, https://rasa.com/docs/rasa/lock-stores/#redislockstore
=> [ATO-1367] Add SSL cert parameters to Redis lock store

changelog/12778.improvement.md, data/test_classes/graph_component_interface.py, rasa/engine/graph.py, rasa/engine/training/fingerprinting.py, tests/engine/training/test_fingerprinting.py
- Added method to `GraphComponent` that allows users to add additional fingerprint data to their component, such as external files, knowledge bases etc. that are not directly in the rasa graph
=> allow components to add fingerprints of external data

changelog/12778.improvement.md, data/test_classes/graph_component_interface.py, rasa/engine/graph.py, rasa/engine/training/fingerprinting.py, tests/engine/training/test_fingerprinting.py
* allow components to add fingerprints of external data
- port of #12778 
=> allow components to add fingerprints of external data (#12778)

changelog/12790.bugfix.md, rasa/core/nlg/callback.py
- Port #12790 to `3.6.x` to fix [ATO-1529](https://rasahq.atlassian.net/browse/ATO-1529)
[ATO-1529]: https://rasahq.atlassian.net/browse/ATO-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ATO 1529] Port fix to 3.6.x

.github/workflows/continous-integration.yml, 3.7.0b1/main_plain/.config/rasa/global.yml
When multi-platform docker images are built push them directly from docker-container's registry.
=> [ATO-1518] Push multi-platform Docker images directly from buildx's docker-container

changelog/12827.improvement.md, rasa/utils/tensorflow/data_generator.py, tests/nlu/classifiers/test_diet_classifier.py
- Solves issues were single examples made it into the last batch and created updates with bad directions
- made sure there's always at least one batch per epoch
- dropping the last batch if it has less than 50% of batch size
=> Better last batch logic

changelog/12827.improvement.md, rasa/utils/tensorflow/data_generator.py, tests/nlu/classifiers/test_diet_classifier.py
* Better last batch logic
- port of #12827 
=> Better last batch logic (#12827)

rasa/core/policies/flow_policy.py, rasa/shared/core/flows/flow.py
- Fixes [ATO-1550](https://rasahq.atlassian.net/browse/ATO-1550)
- In addition, I will prepare a docs PR + a PR to update the bot repo too (although `scope` wasn't used at all)
[ATO-1550]: https://rasahq.atlassian.net/browse/ATO-1550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update collect_information `scope` to `reset_after_flow_ends` bool property

docs/docs/concepts/dialogue-understanding.mdx
- List all the commands in CALM and document them
=> document all the commands in CALM

rasa/cli/data.py, rasa/cli/utils.py, rasa/dialogue_understanding/patterns/default_flows_for_patterns.yml, rasa/shared/core/flows/flow.py, rasa/validator.py, tests/cli/test_rasa_data.py, tests/test_validator.py
- Implements [ATO-1530](https://rasahq.atlassian.net/browse/ATO-1530)
[ATO-1530]: https://rasahq.atlassian.net/browse/ATO-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement `rasa data validate flows`

.github/workflows/continous-integration.yml, changelog/12886.bugfix.md, rasa/core/agent.py, rasa/core/run.py, rasa/utils/endpoints.py, tests/core/test_run.py, tests/utils/test_endpoints.py
- Fixes [ATO-1646](https://rasahq.atlassian.net/browse/ATO-1646)
- Had to pin `ddtrace` in the CI workflows because the new version `2.0.0` released on Tue 3rd Oct upgrades `wrapt` to `1.15` and uninstalls Tensorflow's constraint to be pinned at `<1.15`, this causes 30 job failures.
[ATO-1646]: https://rasahq.atlassian.net/browse/ATO-1646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Cache `EndpointConfig` session

.github/workflows/continous-integration.yml, pyproject.toml, rasa/version.py
=> Prepared release of version 3.8.0a10

.github/workflows/automatic-release-to-main-merger.yml
Fixes https://rasahq.atlassian.net/browse/ATO-1627
- Don't run roberto workflow on pull requests coming from forks
=> dont run roberto workflow on forks

rasa/core/actions/action.py, rasa/shared/core/domain.py, rasa/shared/core/slots.py, tests/core/test_actions.py, tests/shared/core/test_domain.py, tests/shared/core/test_slots.py
- Implements [ATO-1624](https://rasahq.atlassian.net/browse/ATO-1624)
[ATO-1624]: https://rasahq.atlassian.net/browse/ATO-1624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Disallow dialogue stack slot from being set in custom actions & mark builtin slots

docs/docs/concepts/components/llm-configuration.mdx, docs/docs/concepts/components/llm-custom.mdx, docs/docs/concepts/components/overview.mdx, docs/docs/concepts/dialogue-understanding.mdx, docs/sidebars.js
- addresses https://rasahq.atlassian.net/browse/ENG-562
=> Docs cleanup components

docs/docs/concepts/policies.mdx
- addresses https://rasahq.atlassian.net/browse/ENG-560
=> update descriptions of flow policy and intentless policy

rasa/core/policies/flow_policy.py, rasa/shared/core/flows/flow.py, rasa/shared/core/flows/flows_yaml_schema.json
- fixes [ENG-594](https://rasahq.atlassian.net/browse/ENG-594)
- Remove `EntryPromptFlowStep` 
- Remove `entry_prompt` from yaml schema
[ENG-594]: https://rasahq.atlassian.net/browse/ENG-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-594] Remove entry prompt

docs/docs/concepts/flows.mdx
- related to [ENG-594](https://rasahq.atlassian.net/browse/ENG-594)
- remove `entry_prompt` from the docs
[ENG-594]: https://rasahq.atlassian.net/browse/ENG-594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ENG-594] Remove entry_prompt from docs

rasa/dialogue_understanding/generator/command_prompt_template.jinja2, rasa/dialogue_understanding/generator/llm_command_generator.py
- The `LLMCommandGenerator` currently includes the allowed values of categorical slots only when an active flow is present. Adding the `allowed values` to the slots, at the time of defining the flows helps in the LLM mapping the input to one of the defined categorical values. 
- Added e2e tests - https://github.com/RasaHQ/financial-demo-flows-llms/pull/50
=> Modify LLMCommandGenerator prompt to include possible categorical slot values - [ENG 607]

changelog/12948.bugfix.md, rasa/nlu/classifiers/diet_classifier.py, rasa/utils/tensorflow/constants.py, rasa/utils/tensorflow/data_generator.py, rasa/utils/train_utils.py, tests/nlu/classifiers/test_diet_classifier.py
- added config var for "drop small last batch" for DIET which is off by default and results in the original batching logic
- turned off the logic permanently for TED- and UnexpecTEDIntentPolicy
- added tests that batching logic reacts to the parameter
- did not add test for UnexpecTEDIntentPolicy not failing because it was way to complex to create the needed precomputation objects to really simulate a full training. In a naive test the policy did not fail at all. Reproduced the error locally as follows and confirmed that it is now gone
**Error reproduction**
- initialize a new bot repo using `rasa init`
- add UnexpecTEDIntentPolicy to the policies, with batch size 5
- remove rules
- replace stories.yml with the yml below containing 12 stories that will lead to two …
=> Made use of drop-small-last-batch logic only possible in DIET and configurable

scripts/release.py
=> adjusted release script to work with public remote (#12953)

docs/docusaurus.config.js
⚠️ This needs to be released when the Rasa Pro docs are live
- Add new banner
- Update site title
=> add new banner for docs change

CHANGELOG.mdx, Makefile, pyproject.toml, rasa/version.py
=> prepared release of version 3.6.15

.github/workflows/continous-integration.yml, docs/docs/monitoring/load-testing-guidelines.mdx
- Source https://www.notion.so/rasa/Telekom-Voice-Bot-Performance-Tracing-5d3b31f745394e4487cab658434bbca9
=> Additional load testing recommendations

docs/docs/changelog.mdx, trivy-secret.yaml
=> Update missed changlog - main/unreleased

CHANGELOG.mdx
- Update changelog with entries from 3.5.x releases, on the 3.6.x branch, so that next time we do a micro release on 3.6.x, the changelog gets updated properly (I already made the edits on the `documentation` branch so that the changes are live immediately)
=> update changelog with entries from 3.5.x releases

.github/workflows/documentation.yml
- Tested successfully with tag 3.6.16 https://github.com/RasaHQ/rasa/actions/runs/7543003070/job/20533046087
Note : This change will only need to remain on 3.6.x, on 3.5.x it will always fail https://github.com/RasaHQ/rasa/actions/runs/7543134913/job/20533450956
=> Edit docs workflow to release docs for 3.6.x

rasa/core/processor.py, tests/core/test_processor.py
- Adds `FULL_RETRIEVAL_INTENT_NAME_KEY` to the intent dictionary. This has downstream effects and fixes a bug in the Analytics pipeline that expects this key
- Works on [ATO-1956](https://rasahq.atlassian.net/browse/ATO-1956)
[ATO-1956]: https://rasahq.atlassian.net/browse/ATO-1956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Get Full Retrieval Intent Name

.github/workflows/continous-integration.yml, Makefile, changelog/13017.bugfix.md, docs/docs/docker/building-in-docker.mdx, rasa/core/brokers/kafka.py, tests/integration_tests/core/brokers/test_kafka.py, tests/integration_tests/core/brokers/test_pika.py, tests/integration_tests/core/test_exporter.py
- Fixes [ATO-2122](https://rasahq.atlassian.net/browse/ATO-2122)
- Update CI workflow to run broker integration tests separately
[ATO-2122]: https://rasahq.atlassian.net/browse/ATO-2122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ATO-2122] Backport `rasa export` Kafka bugfix to `3.6.x`

changelog/13019.bugfix.md, rasa/core/exporter.py, rasa/core/tracker_store.py, tests/core/test_exporter.py, tests/core/test_tracker_stores.py
- Works on https://rasahq.atlassian.net/browse/ATO-2192
- The timestamps are being set by [events.py](https://github.com/RasaHQ/rasa/blob/3.6.x/rasa/shared/core/events.py#L284) when the events are created. There seem to be two losses at play here,
- [documentation](https://docs.python.domainunion.de/3/library/time.html#time.time) of time.time() notes that "not all systems provide time with a better precision than 1 second". This is a little wild to me!
- precision loss due to timestamp being a float type: Given that timestamp is created during event object creation. The case of (ev1.id > ev2.id) && (ev1.timestamp < ev2.timestamp) don't seem to be possible here. I also can't think of why sorting by timestamp would be good idea at all (possibility of collisions even in …
=> SQL event.timestamp is not always unique 

docs/docusaurus.config.js
Changes the link to Studio docs from incorrect https://rasa.com/docs/rasa-studio/ to correct https://rasa.com/docs/studio/
=> fix link to Studio docs

.github/workflows/continous-integration.yml
- Release success notifications will be sent to channel #release and failure on #dev-tribe
=> Update slack release notifications channels

.github/workflows/git-backup.yml
- Add repository backup to AWS S3 as part of disaster recovery
=> Add backup to s3

changelog/13031.misc.md, poetry.lock, pyproject.toml
- Fixes [ATO-2362](https://rasahq.atlassian.net/browse/ATO-2362)
[ATO-2362]: https://rasahq.atlassian.net/browse/ATO-2362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add upper limit version constraint for scipy on 3.6.x

docs/docs/docker/building-in-docker.mdx, docs/docs/llms/llm-intent.mdx, docs/docs/llms/llm-nlg.mdx, docs/package.json
=> Reflect LLMIntentClassifier removal in docs

.github/workflows/continous-integration.yml
- Bump `actions/upload-artifact` and `actions/download-artifact` to v4
=> [INFRA-1124] Update deprecated dependencies
