changelog/6571.improvement.md
rasa/model.py

- Add model relative path to CLI commands logs
Resolving issue #6571

Add model relative path to CLI commands logs

---

changelog/6703.bugfix.rst
rasa/core/brokers/pika.py
tests/core/test_broker.py

- backport https://github.com/RasaHQ/rasa/pull/6760 to fix pika threading bug

Backport pika fix

---

CHANGELOG.rst
changelog/6703.bugfix.rst
pyproject.toml
rasa/version.py

prepared release of version 1.10.16

---

.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml
.github/workflows/continous-integration.yml
.github/workflows/documentation.yml
.github/workflows/vulnerability-scan.yml

Resolves https://github.com/RasaHQ/rasa-x/issues/3668

Don't use set-env in the CIs

---

.github/workflows/security-scans.yml

Use gitleaks for detecting hardcoded secrets, https://github.com/RasaHQ/rasa-x/issues/3624

Use gitleaks for detecting hardcoded secrets

---

.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/security-scans.yml
.github/workflows/vulnerability-scan.yml

Resolves https://github.com/RasaHQ/rasa-x/issues/3687

Add Slack notifications for schedule workflows

---

data/test_dialogues/default.json
data/test_dialogues/formbot.json
data/test_dialogues/moodbot.json
rasa/__main__.py
rasa/core/policies/ted_policy.py
rasa/nlu/classifiers/diet_classifier.py
rasa/shared/core/trackers.py
rasa/shared/core/training_data/story_reader/yaml_story_reader.py
rasa/utils/tensorflow/model_data.py
tests/core/policies/test_rule_policy.py
tests/core/test_ensemble.py
tests/core/test_policies.py
tests/core/test_processor.py
tests/shared/core/test_trackers.py
tests/shared/importers/test_importer.py
tests/shared/nlu/training_data/test_training_data.py
tests/test_test.py

Fixes all tests on the `e2e` branch.

Fix tests on e2e branch

---

docs/docs/command-line-interface.mdx
docs/docs/setting-up-ci-cd.mdx

- Add content for the `rasa data validate` command by adapting existing content from [docs/rasa/setting-up-ci-cd#validating-data-and-stories](https://rasa.com/docs/rasa/setting-up-ci-cd#validating-data-and-stories)

Document `rasa data validate` in CLI docs

---

changelog/7015.misc.md
rasa/shared/importers/importer.py

- Remove duplicate imports in shared/importers/importer.py
- Resolves issue #7015 

removed duplicate import

---

changelog/7018.bugfix.md
rasa/core/brokers/kafka.py

- update `_create_producer` function in `kafka.py` to create correct `KafkaProducer`s

Create correct KafkaProducer for PLAINTEXT and SASL_SSL security protocols.

---

scripts/push_docs_to_branch.sh

- Support duplicate tag pushes in the docs release mechanism (it led to this silent issue: https://github.com/RasaHQ/rasa/runs/1226850034?check_suite_focus=true)

Docs update mechanism supports duplicate versions

---

.github/workflows/security-scans.yml

Remove Slack notifications for gitleaks.

Remove Slack notifications for gitleaks

---

docs/docs/language-support.mdx
docs/sidebars.js

- Added Language Support Page to 2.0 Docs

Added Language Support Page to 2.0 Docs

---

CHANGELOG.mdx
changelog/7018.bugfix.md
changelog/7033.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.0.1

---

scripts/push_docs_to_branch.sh

- Fixes https://github.com/RasaHQ/rasa/issues/7072
- I've also fixed the docs manually here: 23af5f431a6

avoid duplicating docs/ folder when releasing micros

---

rasa/core/policies/rule_policy.py

- hopefully make error messages from contradicting rules clear

enrich error messages from contradicting rules

---

docs/_redirects
docs/conf.py
docs/robots.txt
poetry.lock

- Robots rules for rasa-x legacy docs (RasaHQ/rasa-x#3738)

add robots.txt and redirection headers

---

rasa/__main__.py

port windows --version fix to 2.0.x

---

rasa/shared/core/trackers.py

- Append stories (don't overwrite) if file exists

Append stories if file exists on export

---

CHANGELOG.mdx
changelog/6691.bugfix.md
changelog/7053.bugfix.md
changelog/7057.misc.md
pyproject.toml
rasa/version.py

Prepare release 2.0.2

---

docs/plugins/google-tagmanager/index.js

This is a hotfix, to include our [Klaro](https://kiprotect.com/docs/klaro/) consent management script in the docs deployments.

Hotfix: tracking consent in docs

---

.github/workflows/continous-integration.yml
changelog/7102.improvement.md
docs/docs/components.mdx
rasa/nlu/utils/hugging_face/registry.py
tests/nlu/test_train.py
tests/nlu/tokenizers/test_lm_tokenizer.py
tests/nlu/utils/test_hf_transformers.py

- Closes https://github.com/RasaHQ/research/issues/119

Change the default model weights for HFTransformersNLP

---

changelog/7108.bugfix.rst
examples/formbot/actions/actions.py
examples/formbot/domain.yml

- Update example formbot to use new `FormValidationAction`
- closes https://github.com/RasaHQ/rasa/issues/7108

Update formbot to use new validation action

---

CODEOWNERS

- backport of https://github.com/RasaHQ/rasa/pull/7127

backport shared codeowner

---

docs/docs/components.mdx

- it's not up to date with 2.0 and therefore confusing

Remove custom components  tutorial link

---

docs/docs/conversation-driven-development.mdx

Fixed a spelling mistake in the conversation-driven-development doc

fixing typo in conversation-driven-development file

---

.github/workflows/cancel-stale-workflows.yml

- Add workflow to periodically cancel stale workflows

add workflow to periodically cancel stale workflows

---

docs/docs/command-line-interface.mdx
docs/docs/generating-nlu-data.mdx
docs/docs/installation.mdx
docs/sidebars.js

Docs edits alan 202010 backport

---

docs/docs/event-brokers.mdx

- Add a line for loading the domain in the example code for instantiating a kafka event broker

Kafka broker docs

---

changelog/7140.bugfix.md
rasa/cli/x.py

Fix failure of rasa x CLI command if git is not installed

---

docs/yarn.lock

- Fix vulnerability alerts: https://github.com/RasaHQ/rasa/network/alerts

update yarn.lock for security patches

---

CHANGELOG.mdx
changelog/7140.bugfix.md
changelog/7186.bugfix.md
pyproject.toml
rasa/version.py

- prepared release of version 2.0.4

prepared release of version 2.0.4

---

.github/workflows/security-scans.yml

- Run the gitleaks scan only on a pull request event

Run the gitleaks scan only on a pull request event

---

CHANGELOG.mdx
changelog/7200.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.0.5

---

CHANGELOG.mdx
changelog/6629.bugfix.md
changelog/7176.bugfix.md
pyproject.toml
rasa/version.py

- micro release for https://github.com/RasaHQ/rasa/pull/6676#issuecomment-723232839

prepared release of version 2.0.6

---

.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml

- Update the setup-gcloud GH action due to security vulnerability

Update the setup-gcloud GH action

---

.github/workflows/continous-integration.yml
changelog/7219.bugfix.rst
rasa/core/brokers/pika.py
tests/core/test_broker.py

- based on what's done in this PR: https://github.com/RasaHQ/rasa/pull/7217
What's essential here is that now we prevent the message handling process from being terminated.

Pika multiprocessing fix for 1.10.x

---

CHANGELOG.rst
changelog/7219.bugfix.rst
pyproject.toml
rasa/version.py

prepared release of version 1.10.17

---

.github/change_filters.yml
.github/workflows/continous-integration.yml

- Fixes https://github.com/RasaHQ/rasa-x/issues/3847
- Move documentation tests out of the "Code Quality" workflow, and merged it with the "Test API spec" workflow. Renamed it "Test Documentation". This will require an update of the repo configuration
- Setup change filters: `backend`, `docker` and `docs`, and update workflows to only run if these files changed

Tweak workflow execution with change filters

---

docs/docs/fallback-handoff.mdx

fix docs for implementing two-stage fallback.

---

docs/docs/forms.mdx

- fix https://github.com/RasaHQ/rasa/issues/7211
- recommend to use `FormValidationAction` everywhere.
- update how custom slots are extracted
- describe how to deal with dynamic slot mappings

update documentation for custom slot mappings

---

.github/workflows/ci-model-regression.yml
.github/workflows/security-scans.yml

- Fixes https://github.com/RasaHQ/rasa/issues/7180

use another GH action to cancel workflow runs

---

changelog/7278.improvement.md
docs/docs/components.mdx
rasa/nlu/classifiers/fallback_classifier.py
tests/nlu/classifiers/test_fallback_classifier.py

- fixes https://github.com/RasaHQ/rasa/issues/6685

set nlu fallback confidence to 1 - intent confidence

---

rasa/core/policies/policy.py
rasa/nlu/components.py
rasa/shared/nlu/training_data/training_data.py

Basic interface in order to tackle the remaining issues for partial dataset loading.
closes #7270 

Add interface for partial dataset loading

---

rasa/core/policies/ted_policy.py
tests/core/test_ensemble.py
tests/core/test_policies.py
tests/shared/core/training_data/story_reader/test_common_story_reader.py

- refactor prediction method of e2e ted
- part of https://github.com/RasaHQ/rasa/issues/6670

refactor e2e ted choice

---

docs/docs/default-actions.mdx

As discussed in following issue: #7094 
This PR updates the code sample for customising ActionSessionStart to work for latest version of Rasa SDK
updated the documentation

Updates code example to work for latest version of Rasa SDK

---

docs/sidebars.js

- return "Migrate from" entry to the docs sidebar

Return "Migrate from" entry to the docs sidebar

---

.github/workflows/continous-integration.yml

- Rasa Open Source version of https://github.com/RasaHQ/rasa-sdk/pull/354

use ref instead of branch name

---

CHANGELOG.mdx
changelog/7338.bugfix.md
pyproject.toml
rasa/version.py

- micro release with the fix for https://github.com/RasaHQ/rasa/pull/7341

prepared release of version 2.1.1

---

docker/Dockerfile_full
docker/Dockerfile_pretrained_embeddings_mitie_en

- Download the MITIE models from GitHub

Download the MITIE models from GitHub

---

CHANGELOG.mdx
changelog/5974.bugfix.md
changelog/7316.bugfix.md
changelog/7317.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.0.7

---

.github/workflows/continous-integration.yml
.github/workflows/documentation.yml
.github/workflows/vulnerability-scan.yml

- Remove the `set-env` command

Remove the set-env command - 1.10.x

---

rasa/cli/initial_project/config.yml

@tmbo as discussed on slack, this PR puts back the original `config.yml` file such that users can easily make changes to it.

Don't start with an Empty config.yml

---

CHANGELOG.rst
changelog/7340.bugfix.md
pyproject.toml
rasa/version.py

Prepare release 1.10.18

---

CHANGELOG.mdx
changelog/7235.bugfix.md
pyproject.toml
rasa/version.py

- Micro release that fixes bugs in `RulePolicy`, see [this forum thread](https://forum.rasa.com/t/contradicting-rules-or-stories-found/36563) and #7244 for the issues, #7235 for the fixes.

prepared release of version 2.0.8

---

changelog/7235.bugfix.md
rasa/core/policies/rule_policy.py
tests/core/policies/test_rule_policy.py

- Bring in changes from bug-fixing PR #7235 .

Bring 2.0.x RulePolicy bug fixes into 2.1.x

---

CHANGELOG.mdx
changelog/7235.bugfix.md
changelog/7345.bugfix.md
pyproject.toml
rasa/version.py

- Prepare the release of 2.1.2.

prepared release of version 2.1.2

---

changelog/6251.improvement.md
rasa/core/brokers/kafka.py
rasa/core/tracker_store.py

- Apply @rgstephens changes from https://github.com/RasaHQ/rasa/pull/6521
- Kafka Producer, add group id & client id
- Kafka Producer save/reuse connection
- patch master fix https://github.com/RasaHQ/rasa/pull/6233 

Kafka group id, create producer & Dynamo check

---

.github/change_filters.yml

- Changes in the Makefile should trigger all our change filters!
- Background discussion [here](https://rasa-hq.slack.com/archives/C36SS4N8M/p1607004812232100)

Add Makefile to all CI filters

---

Makefile

Fix Windows unit tests

---

data/test_endpoints/event_brokers/kafka_sasl_ssl_endpoint.yml
data/test_endpoints/event_brokers/kafka_ssl_endpoint.yml

- Fix SSL endpoint example configs

Fix kafka SSL endpoint examples

---

rasa/nlu/extractors/extractor.py

- Improve the warning message when entity misaligned
fixs #7409

improve warning message when entity misaligned

---

CHANGELOG.mdx
changelog/7316.bugfix.md
changelog/7390.bugfix.md
changelog/7417.bugfix.md
changelog/7418.bugfix.md
changelog/7426.improvement.md
pyproject.toml
rasa/version.py

- Prepare the micro release `2.1.3`.

prepared release of version 2.1.3

---

rasa/server.py
tests/test_server.py

use HTTPStatus constant

---

changelog/7395.improvement.md
rasa/exceptions.py
rasa/shared/core/trackers.py
tests/shared/core/test_trackers.py

- Closes https://github.com/RasaHQ/rasa/issues/7395

Implement tracker persist and load

---

examples/moodbot/config.yml
rasa/nlu/model.py
rasa/nlu/train.py
rasa/train.py
tests/test_train.py

Load NLU model in fine-tuneing mode

#7329 load models in finetune mode nlu

---

docs/docs/command-line-interface.mdx
docs/docs/components.mdx

- Part of https://github.com/RasaHQ/rasa/issues/6971

Docs for incremental training

---

docs/docs/nlu-training-data.mdx

fixed typo

---

tests/cli/conftest.py

- use shutil which to avoid rasa executable not being found on windows
fix is based on https://stackoverflow.com/a/32799942/1906073

Fix the unit-tests for Windows

---

CHANGELOG.mdx
rasa/core/exporter.py
rasa/core/run.py

- fix https://github.com/RasaHQ/rasa/issues/7296
- move deprecation date to 3.0.0 (in line with engineering guidelines)

remove 2.2.0 deprecations

---

rasa/model.py
rasa/shared/nlu/training_data/training_data.py
rasa/train.py
tests/conftest.py
tests/shared/nlu/training_data/test_training_data.py
tests/test_model.py
tests/test_train.py

Integrate the finetune fingerprint checks into the train commands.

Integrate the finetune fingerprint checks into the train commands.

---

rasa/train.py
tests/test_train.py

Add experimental warning to e2e training

Add experimental warning to e2e training

---

rasa/core/brokers/kafka.py

- Added SASL username & password to SASL-SSL producer

Added SASL username & password to SASL-SSL producer

---

.github/configs/mr-test-example.yaml
.github/scripts/mr_generate_summary.py
.github/scripts/mr_publish_results.py
.github/templates/model_regression_test_config_to_json.tmpl
.github/templates/model_regression_test_results.tmpl
.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml

Checkout a custom branch of training data repo for model regression tests

---

docs/docs/command-line-interface.mdx
rasa/train.py

Mark incremental training experimental

---

CODEOWNERS

- Add RasaHQ/infrastructure to the CODEOWNERS file

Add RasaHQ/infrastructure to the CODEOWNERS file

---

CHANGELOG.rst
changelog/6251.improvement.md
changelog/6814.improvement.md
changelog/7423.improvement.md
pyproject.toml
rasa/version.py

prepared release of version 1.10.19

---

CHANGELOG.mdx
changelog/7557.bugfix.md
changelog/7585.bugfix.md
pyproject.toml
rasa/version.py

- release 2.2.1 with a critical fix for the SQLTrackerStore (especially when used with Rasa X)

prepared release of version 2.2.1

---

CHANGELOG.rst
changelog/7575.bugfix.rst
pyproject.toml
rasa/version.py

prepared release of version 1.10.20

---

changelog/7592.bugfix.md
rasa/cli/x.py

Rasa x startup issues with Rasa Open Source 2.2.x and Rasa X < 0.35

---

CHANGELOG.mdx
changelog/7592.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.2.2

---

.github/workflows/continous-integration.yml
tests/core/test_evaluation.py

- Resolves https://github.com/RasaHQ/rasa/issues/7572
- Increase pytest timeout for test_retrieval_intent

Increase pytest timeout for the test_retrieval_intent unit test

---

changelog/7601.misc.md
rasa/core/brokers/kafka.py

- Removed group_id from Kafka Producer's Description

Removed group_id from Kafka Producer's Description

---

docs/docs/default-actions.mdx

add missing close of caution

---

docs/docs/migration-guide.mdx

fix migration guide so it's in line with formbot example

---

CHANGELOG.mdx
changelog/7622.bugfix.md
changelog/7684.bugfix.md
pyproject.toml
rasa/server.py
rasa/version.py
tests/test_server.py

- fix https://github.com/RasaHQ/rasa/pull/7684
- release micro 
(combining these to save time)

Prepare release 2.2.3

---

changelog/6251.improvement.md
changelog/7439.improvement.md
rasa/core/brokers/kafka.py

- Add support for list of Kafka servers, drop group_id from producer

Support server list, drop group_id from producer

---

changelog/7638.bugfix.md
rasa/core/utils.py
tests/core/test_utils.py

- Backport of #6676 for Rasa 1.10

Backport Multiple Sanic Workers fix for 1.10.x

---

CHANGELOG.mdx
changelog/7520.improvement.md
changelog/7692.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.2.4

---

changelog/7717.bugfix.md
rasa/core/exporter.py
rasa/core/run.py
tests/core/test_exporter.py
tests/core/test_run.py

- fix wrong `The method 'EventBroker.close was changed to be asynchronous` warning (the condition wasn't negated 🤦🏻 )
- add missing single quotes

fix EventBroker async warning

---

.github/workflows/continous-integration.yml

- Add an option to the CI that allows using the `unit-tests:clear-poetry-cache` label to clear poetry cache

Add a step to the CI to clear poetry cache

---

.github/ISSUE_TEMPLATE/feature_request.md

- Fixing a typo in the GitHub feature request issue template
- ~~[ ] added some tests for the functionality~~
- ~~[ ] updated the documentation~~
- ~~[ ] updated the changelog (please check [changelog](https://github.com/RasaHQ/rasa/tree/master/changelog) for instructions)~~
- ~~[ ] reformat files using `black` (please check [Readme](https://github.com/RasaHQ/rasa#code-style) for instructions)~~

Fix typo in GitHub feature request template

---

.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml
.github/workflows/continous-integration.yml
.github/workflows/documentation.yml
.github/workflows/security-scans.yml

- The only option to get rid of the old cache is to use a new key. Add the `POETRY_CACHE_VERSION` variable to the poetry cache key in order to control the key without additional steps that require commits

Change cache key for poetry by a secret variable

---

CHANGELOG.mdx
changelog/7717.bugfix.md
changelog/7720.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.2.6

---

docs/docs/connectors/rocketchat.mdx

Fix docs link on 2.2.x

---

changelog/4311.bugfix.md
rasa/shared/core/domain.py
tests/shared/core/test_domain.py

Fixes: https://github.com/RasaHQ/rasa-x/issues/4311
- Added a `try..catch` block in `is_domain_file()`

Added (try..except) block for is_domain_file

---

CHANGELOG.mdx
changelog/4311.bugfix.md
changelog/7731.improvement.md
pyproject.toml
rasa/version.py

Prepare release of Rasa OSS 2.2.7.

Prepare release 2.2.7

---

CHANGELOG.mdx
changelog/7764.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.2.8

---

docs/_redirects

Proposed changes:
Fix _redirects so that netlify picks up the noindex, nofollow rule

Fix v1 docs noindex header

---

docs/_redirects
docs/robots.txt

- This was likely introduce by a wrong merge
- It'll need to be updated on `main` and `documentation` branches

remove _redirects and robots.txt files in docs site

---

CHANGELOG.rst
changelog/7439.improvement.md
changelog/7638.bugfix.md
changelog/7722.bugfix.md
pyproject.toml
rasa/version.py

Prepared Release of Version 1.10.21

---

changelog/7861.bugfix.md
rasa/nlu/test.py
rasa/server.py
tests/nlu/test_evaluation.py

- include 'confused' with field when doing model testing
- add more logs when doing model testing via server

add missing 'confused with' field to model report

---

CHANGELOG.mdx
changelog/7861.bugfix.md
pyproject.toml
rasa/version.py
tests/core/test_evaluation.py
tests/core/test_examples.py
tests/nlu/test_evaluation.py

- release 2.2.9 with a fix for intent insights

prepared release of version 2.2.9

---

docs/docs/http-api.mdx

- added a caution note about using multiple sanic workers with SocketIO

sanic worker doc update

---

.github/workflows/security-scans.yml

- Update the gitleaks action to the 1.3.0 version

Update the gitleaks action to the 1.3.0 version

---

CHANGELOG.rst
changelog/7754.bugfix.rst
pyproject.toml
rasa/version.py

- release with the pika backport to address https://github.com/RasaHQ/rasa/issues/7772
- fix https://github.com/RasaHQ/rasa/issues/7772

Prepare release 1.10.22

---

CHANGELOG.mdx

- add changelog of 1.10.x micro releases

add changelog of 1.10.x micro releases

---

CHANGELOG.mdx
changelog/7069.improvement.md
changelog/7885.bugfix.md
pyproject.toml
rasa/version.py

- release 2.2.10 with a pinned `numpy` version to fix errors for users with old pip versions.

prepared release of version 2.2.10

---

setup.cfg

- ignore missing docstrings for magic methods

ignore missing docstrings for magic methods

---

docs/docs/nlg.mdx

Minor fix for a typo in NLG server documentation.

fix typo where wrong form of send is used

---

rasa/core/policies/ted_policy.py
rasa/nlu/classifiers/diet_classifier.py
rasa/nlu/selectors/response_selector.py
rasa/utils/tensorflow/layers.py

Make `similarity_confidence_from_embeddings` public

---

changelog/7829.bugfix.md
rasa/cli/train.py
rasa/core/brokers/kafka.py
tests/cli/test_rasa_train.py

- Adding an `else` statement in `rasa/cli/train.py._model_for_finetuning`

Finetuning (--finetune) with a specific model as an argument

---

CHANGELOG.mdx
changelog/7970.bugfix.md
pyproject.toml
rasa/version.py

- prepare release of Rasa Open Source 2.3.1 with some fixes for concurrent server calls

prepared release of version 2.3.1

---

.github/workflows/continous-integration.yml

- Use a correct variable to determine the latest tag

[2.3.x] Fix tagging the latest stable version as latest

---

.github/workflows/continous-integration.yml

- Use a correct variable to determine the latest tag

Fix tagging the latest stable version as latest

---

tests/test_server.py

- speed up test by using minimal config instead of default config (the default config was used due to a typo)

fix typo in test

---

rasa/nlu/data_augmentation/augmenter.py
tests/cli/test_rasa_data.py

Minor offline changes proposed to paraphrasing CLI

---

CHANGELOG.mdx
pyproject.toml
rasa/shared/utils/validation.py
rasa/version.py
tests/shared/utils/test_validation.py

Merge 2.3.x into main

---

.github/runner/github-runner-deployment.yaml.tmpl
.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml

Update GPU cluster

---

.github/workflows/ci-model-regression-on-schedule.yml

Update secret for the model regression tests workflow

---

CHANGELOG.mdx
changelog/7972.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.3.2

---

CHANGELOG.mdx
changelog/8001.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.3.3

---

CHANGELOG.rst
changelog/7895.bugfix.rst
pyproject.toml
rasa/version.py

prepared release of version 1.10.23

---

docs/docs/connectors/custom-connectors.mdx
docs/docs/http-api.mdx
docs/docs/migration-guide.mdx

Fix sanic docs link

---

CHANGELOG.mdx

- Added 1.10.23 updates to 2.3.X Changelog

Added 1.10.23 updates to 2.3.X Changelog

---

README.md

- Added new hiring banner to the readme, added missing alt tags, centre align header text

Add new banner to the readme

---

changelog/8100.improvement.md
rasa/core/lock_store.py
tests/core/test_lock_store.py

- fix https://github.com/RasaHQ/rasa/issues/8100

improve Lockstore queuing log message

---

.github/workflows/continous-integration.yml

- disable `fail-fast` for the Python test suite so it's possible to see all potential errors at once instead of having to fix-and-rerun to see the next issue

disable fail fast

---

changelog/8198.bugfix.md
rasa/shared/importers/autoconfig.py
tests/shared/importers/test_importer.py

- follow-up from https://github.com/RasaHQ/rasa/pull/7965/files: correctly validated model configuration when using autoconfig

correctly validate config when using autoconfig

---

changelog/8007.bugfix.rst

- Delete duplicate changelog entry

Rm changelog

---

changelog/8102.bugfix.md
rasa/core/actions/forms.py
tests/core/actions/test_forms.py

- Fixed: https://github.com/RasaHQ/rasa/issues/8102

Bugfix slot mapping doesn't work if intent name is substring of another intent

---

CHANGELOG.mdx
changelog/8194.bugfix.md
changelog/8198.bugfix.md
changelog/8223.bugfix.md
poetry.lock
pyproject.toml
rasa/version.py

prepared release of version 2.4.1

---

CHANGELOG.mdx
changelog/7835.bugfix.md
changelog/8258.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.4.2

---

changelog/8114.bugfix.md
rasa/shared/nlu/training_data/formats/readerwriter.py
tests/shared/core/test_events.py

Cherry pick of https://github.com/RasaHQ/rasa/pull/8271 for 2.4.x

8114/handle entities with no start and end when writing stories 2.4.x

---

CHANGELOG.mdx
changelog/8114.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.4.3

---

docs/docs/migrate-from/google-dialogflow-to-rasa.mdx

- Updated the command in Step 5 to enable the API when running the server so the curl command gives the proper intent in Dialogflow format.

Update command in Step 5 to enable API

---

CHANGELOG.rst
changelog/8007.bugfix.rst
changelog/8019.bugfix.rst
pyproject.toml
rasa/version.py

Prepare release 1.10.24

---

changelog/8178.bugfix.md
rasa/core/brokers/broker.py
rasa/core/brokers/pika.py
tests/core/test_broker.py

Catch ChannelNotFoundEntity and raise as RasaException

---

.github/workflows/continous-integration.yml

fix wait for doc test for PR from forked repo

---

changelog/8124.misc.md
tests/cli/test_rasa_test.py
tests/cli/test_rasa_train.py
tests/conftest.py
tests/core/actions/test_forms.py
tests/core/test_run.py
tests/shared/core/test_trackers.py
tests/test_model.py
tests/test_server.py

Amend fixtures in tests that don't need model training

---

changelog/7379.bugfix.md
data/test_number_nlu_examples/nlu.yml
data/test_number_nlu_examples/rules.yml
data/test_number_nlu_examples/stories.yml
rasa/shared/nlu/training_data/training_data.py
tests/shared/nlu/training_data/test_training_data.py

Count only nlu training examples

---

tests/test_memory_leak.py

- bump limit as it was causing flakey tests [here](https://github.com/RasaHQ/rasa/pull/8354/checks?check_run_id=2285196359)

bump limit for memory tests

---

tests/test_memory_leak.py

bump memory thresholds

---

poetry.lock
pyproject.toml

- Don't pin version for dm-tree

Don't pin version for dm-tree

---

CHANGELOG.rst
changelog/8345.improvement.rst
changelog/8429.feature.rst
pyproject.toml
rasa/version.py

prepared release of version 1.10.25

---

changelog/8300.bugfix.md
rasa/shared/core/training_data/story_writer/yaml_story_writer.py
tests/shared/core/training_data/story_writer/test_yaml_story_writer.py

Make it possible to use `null` entities in stories

---

.github/workflows/assign-default-project.yml
.github/workflows/cancel-stale-workflows.yml
.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/vulnerability-scan.yml

- Fixes #8474 
- Tested with this repository: https://github.com/m-vdb/test-repo-project
- I forked the action to support 2 cases:
- If a user creates an issue and assigns it to a project during the issue creation, the workflow was failing because the issue is "awaiting triage" (more of an edge case)
- Issues already in a project should be left untouched (more of safety on issue creation to prevent race conditions, but it's important if we want to support the use case of adding/removing labels)
- After merge of this PR, remove the `RASABOT_ASSIGN_ISSUE_RESEARCH_BOARD_TOKEN` value from this repository's secrets (it has been renamed to a more generic name)

Improve vulnerability scan workflow

---

.github/workflows/continous-integration.yml

- Pass the CI even if converalls fails

Pass the CI even if converalls fails

---

CHANGELOG.mdx
changelog/8446.bugfix.md
changelog/8545.bugfix.md
pyproject.toml
rasa/version.py

- Prepared release of version 2.5.1

prepared release of version 2.5.1

---

docs/docs/fallback-handoff.mdx

- Fix typos in `fallback-handoff.mdx`. Detected thanks to [this workflow](https://github.com/RasaHQ/rasa/pull/8565/checks?check_run_id=2457816431) during release of 2.5.1

Fix typos in fallback-handoff.mdx

---

changelog/8079.doc.md
docs/docs/default-actions.mdx

- Clarify docs according to thread in issue #8079 

Update default actions docs

---

changelog/8581.bugfix.md
rasa/core/policies/rule_policy.py
tests/core/policies/test_rule_policy.py

Same as https://github.com/RasaHQ/rasa/pull/8612, but aiming for `2.6.x` instead of `main`.

Repeat PR on 2.6.x branch

---

.github/templates/model_regression_test_results.tmpl
.github/workflows/ci-model-regression.yml

- Remove test ref for the model regression tests

Remove test ref for the model regression tests

---

changelog/8590.bugfix.md
rasa/shared/core/domain.py
tests/shared/core/test_domain.py

Handle empty slot mappings in domain forms

---

CHANGELOG.mdx
changelog/8079.doc.md
changelog/8364.bugfix.md
changelog/8581.bugfix.md
changelog/8587.misc.md
changelog/8590.bugfix.md
changelog/8631.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.6.2

---

changelog/8546.bugfix.md
rasa/telemetry.py

add OSError to telemetry ignore_errors

---

changelog/8547.bugfix.md
rasa/core/policies/ted_policy.py
tests/core/policies/test_ted_policy.py

change ValueError to RasaException in TED model

---

rasa/architecture_prototype/config_to_graph.py
rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py
tests/architecture_prototype/graph_schema.py

- correctly load trained featurizaters for processing step during training 
- drop duplicate featurization of `CountVectorFeaturizer` during training

Architecture prototype/featurization fixes

---

docs/docs/connectors/your-own-website.mdx

- use correct endpoint in docs

fix socket.io post url in docs

---

changelog/8727.misc.md
rasa/core/lock_store.py
rasa/core/tracker_store.py
tests/core/test_lock_store.py
tests/core/test_tracker_stores.py

Fix Redis errors as RasaException subclass

---

changelog/8639.bugfix.md
rasa/jupyter.py

- Moved an import out of the type check to fix this: #8639

Jupyter import fix

---

changelog/7906.misc.md
rasa/core/channels/telegram.py
tests/core/test_channels.py

Re-raise ApiTelegramException as RasaException

---

changelog/8726.misc.md
rasa/core/tracker_store.py
tests/core/test_tracker_stores.py

Fix Sentry PyMongo error

---

changelog/8386.bugfix.md
data/test_yaml_stories/test_stories_entity_annotations.yml
rasa/core/test.py
tests/core/test_test.py

Fix bug in evaluation of test stories with entity annotations

---

Dockerfile
changelog/8802.misc.md
docker/Dockerfile.base
docker/Dockerfile.full
docker/Dockerfile.pretrained_embeddings_mitie_en
docker/Dockerfile.pretrained_embeddings_spacy_de
docker/Dockerfile.pretrained_embeddings_spacy_en

- Create rasa user and group
- Set the `HOME` environment variable to `/app`

[Dockerfile] Create rasa user and group

---

rasa/core/policies/intent_ted_policy.py
rasa/utils/tensorflow/models.py

Add `dot_product_loss_layer` property

---

changelog/8200.bugfix.md
rasa/utils/plotting.py

- Closes https://github.com/RasaHQ/rasa/issues/8200

Prevent overlapping plots when comparing multiple NLU pipelines.

---

changelog/8415.improvement.md
data/test_config/config_empty_en_after_dumping.yml
data/test_config/config_empty_en_after_dumping_core.yml
data/test_config/config_empty_fr_after_dumping.yml
data/test_config/config_with_comment_between_suggestions.yml
data/test_config/config_with_comments_after_dumping.yml
rasa/shared/importers/default_config.yml

Add `IntentTEDPolicy` to the default configuration.

---

poetry.lock

- ran `poetry update tensorflow` and got 2.3.3, looks right, but might want to check the new dependency? 

Update tensorflow version to 2.3.3

---

CHANGELOG.mdx
changelog/7286.bugfix.md
changelog/8200.bugfix.md
changelog/8812.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.7.1

---

.github/workflows/continous-integration.yml
CHANGELOG.mdx
changelog/4612.bugfix.md
changelog/7955.improvement.md
changelog/8080.docs.md
changelog/8100.improvement.md
changelog/8649.bugfix.md
changelog/8860.feature.md
pyproject.toml
rasa/version.py

prepared release of version 2.3.5

---

.github/workflows/continous-integration.yml
CHANGELOG.rst
changelog/8876.feature.rst
pyproject.toml
rasa/version.py

prepared release of version 1.10.26

---

rasa/core/policies/intent_ted_policy.py
rasa/shared/core/trackers.py
tests/core/policies/test_intent_ted_policy.py

IntentTEDPolicy: Fix when predictions should be skipped

---

changelog/8801.improvement.md
changelog/8801.misc.md
docs/docs/components.mdx
rasa/nlu/classifiers/fallback_classifier.py
tests/nlu/classifiers/test_fallback_classifier.py

Change `FallbackClassifier` score to fallback threshold

---

CHANGELOG.mdx

- Updated `main` branch changelog

Updated main changelog

---

.github/dependabot.yml

- Add `/docs` to dependabot, auto-assign to `@RasaHQ/scale-squad`

Add docs to dependabot

---

.github/workflows/continous-integration.yml
tests/conftest.py

- Since Feb/Mar we upload several reports to coveralls, and hence we must tell coveralls we are done reporting :) 

Fix Coveralls reporting

---

data/test_moodbot/unexpected_intent_policy_config.yml
tests/core/test_test.py

- Fix for https://github.com/RasaHQ/rasa/pull/8913#discussion_r665244346

UnexpecTEDIntentPolicy: Update tests

---

.github/workflows/security-scans.yml

Correct the path to gitleaks config

---

.gitleaks.toml

ignore fake credentials

---

changelog/9091.removal.md
data/configs_for_docs/pretrained_embeddings_spacy_config.yml
data/test_config/config_crf_custom_features.yml
data/test_config/config_defaults.yml
data/test_config/config_pretrained_embeddings_spacy_duckling.yml
data/test_spacybot/config.yml
docs/docs/components.mdx
rasa/nlu/utils/spacy_utils.py
tests/nlu/test_spacy_utils.py

This PR fixes https://github.com/RasaHQ/rasa/issues/8882.

Remove spaCy 3.0 deprecation warnings

---

changelog/8862.removal.md
rasa/core/brokers/broker.py
rasa/core/exporter.py
rasa/core/run.py
tests/core/test_broker.py
tests/core/test_exporter.py
tests/core/test_run.py

Remove event broker deprecation warnings

---

changelog/8867.removal.md
docs/docs/jupyter-notebooks.mdx
rasa/shared/data.py
tests/shared/test_data.py

Follow through on deprecation warnings for `rasa.shared.data`.

---

changelog/5546.bugfix.md
changelog/5546.improvement.md
rasa/core/policies/memoization.py
rasa/core/trackers.py
rasa/core/training/generator.py
tests/core/policies/test_memoization.py
tests/core/test_processor.py

- Fixes https://github.com/RasaHQ/rasa-x/issues/5546
- Copies essential changes from https://github.com/RasaHQ/rasa/pull/6711 to this old Rasa version

Increase speed of augmented lookup for `AugmentedMemoizationPolicy`

---

.github/PULL_REQUEST_AUTOMATIC_TEMPLATE.md

Add automatic merge PR template

---

.github/workflows/vulnerability-scan.yml

- Overwrite `lazy-actions/gitrivy` default of `HIGH,CRITICAL` with all severities

Add missing severity to vulnerability report

---

rasa/engine/caching.py
rasa/nlu/model.py
rasa/nlu/utils/__init__.py
rasa/utils/common.py
tests/conftest.py
tests/engine/test_caching.py
tests/utils/test_common.py

- implement `Cache`, `LocalCache`, `Cacheable` of https://github.com/RasaHQ/rasa/issues/9178

3.0 architecture revamp/9178/caching

---

rasa/engine/graph.py
rasa/engine/training/hooks.py
tests/engine/conftest.py
tests/engine/graph_components_test_classes.py
tests/engine/training/test_hooks.py

Training hooks for caching and fingerprinting.
Still need to unit test, but was going to wait until we potentially have interface for caches and model storage.

Training hooks

---

scripts/push_docs_to_branch.sh

- Fix "Publish Documentation" workflow
- I've also re-run the fixed workflow locally to make sure the docs are updated. Build is running [here](https://app.netlify.com/teams/rasahq/builds/610ab3c915a9c90007571183)
cc @aeshky as you ran the release of 2.8.2 and uncovered the issue 😄 thanks!

Fix doc push

---

CHANGELOG.mdx
changelog/7695.bugfix.md
changelog/8711.bugfix.md
pyproject.toml
rasa/version.py

- release a 2.7.x  micro with the change of https://github.com/RasaHQ/rasa/pull/9265

prepared release of version 2.7.2

---

rasa/engine/graph.py
rasa/engine/loader.py
tests/engine/test_graph.py
tests/engine/test_loader.py

Graph Loader

---

rasa/engine/graph.py
rasa/engine/runner/dask.py
rasa/engine/training/components.py
rasa/engine/validation.py
tests/engine/graph_components_test_classes.py
tests/engine/test_graph_node.py
tests/engine/test_validation.py
tests/engine/training/test_components.py
tests/engine/training/test_hooks.py

- return tuple from `GraphNode` instead of `{"node_name": value"}`
- improve docstring
- validate for cycles in the schema
- change `defaults` to `get_default_config` (from property to method)

3.0 architecture revamp/integration branch review comments kathrin

---

scripts/push_docs_to_branch.sh

- Backport [this change](https://github.com/RasaHQ/rasa/pull/9387) to 2.7.x
- Backport [this change](https://github.com/RasaHQ/rasa/pull/9285/commits/f60df9670427c399142f5869f7afa251234850b8) to 2.7.x

Fix doc push part2 backport 2.7.x

---

scripts/push_docs_to_branch.sh

- Backport [this change](https://github.com/RasaHQ/rasa/pull/9387) to 2.8.x

fix script to install docs: skip node_modules

---

docs/docs/connectors/your-own-website.mdx

- backport https://github.com/RasaHQ/rasa/pull/9076/files

backport chat widget docs

---

CHANGELOG.mdx
changelog/7695.bugfix.md
pyproject.toml
rasa/version.py

- fix https://github.com/RasaHQ/rasa/issues/9334

prepared release of version 2.8.3

---

docs/docs/policies.mdx

- add some missing words to help make the TEDPolicy documentation a bit more readable

Fix some wording issues on TEDPolicy documentation

---

README.md

Adapted README to warn of compiler issues when setting up dev env

---

rasa/core/policies/_unexpected_intent_policy.py
rasa/core/policies/unexpected_intent_policy.py
tests/core/policies/test_unexpected_intent_policy.py

Adapt UnexpecTEDIntentPolicy to new GraphComponent interface

---

rasa/graph_components/providers/domain_provider.py
tests/test_graph_components/providers/test_domain_provider.py

Implement `DomainProvider` graph component

---

CHANGELOG.mdx
changelog/5546.improvement.md
changelog/7362.bugfix.md
changelog/8682.misc.md
changelog/9490.bugfix.md
pyproject.toml
rasa/version.py

Prepared release of version 2.8.4

Prepared release of version 2.8.4

---

CODEOWNERS

Fix team name typo

---

tests/conftest.py
tests/core/conftest.py
tests/core/test_evaluation.py
tests/nlu/conftest.py
tests/nlu/featurizers/test_spacy_featurizer.py

- narrow scope of fixtures which load a model into memory to release the memory if it's no longer needed

WIP: fix CI memory issues

---

CHANGELOG.mdx
changelog/9476.bugfix.md
changelog/9542.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.5

---

CHANGELOG.mdx
changelog/9302.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.6

---

rasa/engine/graph.py
rasa/engine/validation.py
rasa/nlu/tokenizers/_whitespace_tokenizer.py
rasa/nlu/tokenizers/whitespace_tokenizer.py
tests/engine/test_validation.py
tests/nlu/tokenizers/test_whitespace_tokenizer.py

- fix #9499 
*It requires https://github.com/RasaHQ/rasa/pull/9562 to be merged first!*

Migrate `WhitespaceTokenizer` to GraphComponent interface

---

rasa/nlu/tokenizers/_spacy_tokenizer.py
rasa/nlu/tokenizers/spacy_tokenizer.py
rasa/nlu/tokenizers/tokenizer.py
tests/nlu/tokenizers/test_spacy_tokenizer.py

Migrate SpacyTokenizer for the graph

---

rasa/nlu/featurizers/dense_featurizer/_mitie_featurizer.py
rasa/nlu/featurizers/dense_featurizer/mitie_featurizer.py
rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py
rasa/nlu/featurizers/featurizer.py
rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py
tests/nlu/featurizers/test_mitie_featurizer.py

- fix https://github.com/RasaHQ/rasa/issues/9453

Adapt `MitieFeaturizer` to new GraphComponent interface

---

rasa/nlu/featurizers/sparse_featurizer/_regex_featurizer.py
rasa/nlu/featurizers/sparse_featurizer/regex_featurizer.py
tests/nlu/featurizers/test_regex_featurizer.py

- fix https://github.com/RasaHQ/rasa/issues/9451
- migrate `RegexFeaturizer`

migrate `RegexFeaturizer`

---

rasa/nlu/featurizers/dense_featurizer/_convert_featurizer.py
rasa/nlu/featurizers/dense_featurizer/convert_featurizer.py
tests/nlu/featurizers/test_convert_featurizer.py

convert featurizer

---

rasa/nlu/selectors/_response_selector.py
rasa/nlu/selectors/response_selector.py
tests/nlu/selectors/test_selectors.py

Adapt `ResponseSelector` to `GraphComponent` interface

---

rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py
rasa/nlu/utils/spacy_utils.py
tests/nlu/classifiers/test_diet_classifier.py
tests/nlu/classifiers/test_mitie_intent_classifier.py
tests/nlu/classifiers/test_sklearn_classifier.py
tests/nlu/conftest.py
tests/nlu/extractors/test_crf_entity_extractor.py
tests/nlu/extractors/test_extractor.py
tests/nlu/featurizers/test_convert_featurizer.py
tests/nlu/featurizers/test_count_vectors_featurizer.py
tests/nlu/featurizers/test_lexical_syntactic_featurizer.py
tests/nlu/featurizers/test_lm_featurizer.py
tests/nlu/featurizers/test_mitie_featurizer.py
tests/nlu/featurizers/test_regex_featurizer.py
tests/nlu/featurizers/test_spacy_featurizer.py
tests/nlu/selectors/test_selectors.py
tests/nlu/test_evaluation.py
tests/nlu/test_interpreter.py
tests/nlu/tokenizers/test_tokenizer.py
tests/nlu/tokenizers/test_whitespace_tokenizer.py
tests/nlu/utils/test_bilou_utils.py

Migrate all nlu unit tests to new components

---

.github/workflows/continous-integration.yml
changelog/9557.misc.md

Windows CI tests

---

CHANGELOG.mdx
changelog/9678.bugfix.md
pyproject.toml
rasa/version.py

- release 2.8.7 with a correctly specified upper tensorflow dependency limit

prepared release of version 2.8.7

---

tests/conftest.py
tests/core/conftest.py
tests/core/test_evaluation.py
tests/nlu/conftest.py
tests/nlu/featurizers/test_spacy_featurizer.py

- fix memory issues with CI on 2.8.x
- cherry-picked from here https://github.com/RasaHQ/rasa/pull/9545

Fix memory issues 2.8.x

---

changelog/9078.misc.md
rasa/cli/initial_project/data/nlu.yml
rasa/shared/importers/default_config.yml
tests/conftest.py
tests/shared/importers/test_rasa.py
tests/test_default_project.py

Make sure there are no warnings in default config

---

docs/docs/event-brokers.mdx

Added note in docs regarding GSSAPI C dependencies

---

rasa/engine/training/graph_trainer.py
rasa/graph_components/validators/finetuning_validator.py
tests/graph_components/validators/test_finetuning_validator.py

- validating configs contained in graph schema from execution context instead of config from importer

fine tuning validator (changing configs to be validated)

---

.github/workflows/continous-integration.yml
Makefile

- Fixes #9253 
- Move from Coveralls to CodeClimate!
- Repo here --> [codeclimate link](https://codeclimate.com/github/RasaHQ/rasa)
- Coverage percentage will now show up until this code runs on `main` , FYI!
- [The full report](https://codeclimate.com/repos/5d668ca8f6a09f019e010459/settings/test_reports/6153122be2dc0b2d39008455) has been successfully uploaded in the latest test run (not sure if you can see it without being a repo admin though) -- basically, it works lol

Codeclimate integration

---

rasa/core/actions/action.py
rasa/core/actions/forms.py
rasa/core/processor.py
rasa/shared/core/constants.py
rasa/shared/core/domain.py
tests/core/actions/test_forms.py
tests/core/featurizers/test_tracker_featurizer.py
tests/core/test_actions.py
tests/core/test_processor.py
tests/shared/core/test_domain.py
tests/shared/core/training_data/story_reader/test_yaml_story_reader.py
tests/shared/importers/test_rasa.py
tests/test_default_project.py

Implement new default action to set slots after each user turn

---

changelog/9780.doc.md
docs/docs/glossary.mdx
docs/docs/responses.mdx
rasa/shared/core/domain.py

remove CRVs experimental warning

---

rasa/cli/interactive.py
rasa/cli/shell.py
rasa/engine/storage/local_model_storage.py
rasa/engine/storage/storage.py
rasa/engine/training/graph_trainer.py
rasa/model.py
rasa/model_testing.py
rasa/model_training.py
tests/core/policies/test_ted_policy.py
tests/engine/storage/test_local_model_storage.py
tests/engine/storage/test_storage.py
tests/test_model_training.py

Include training type in metadata

Include training type in metadata

---

rasa/model_testing.py
rasa/nlu/classifiers/mitie_intent_classifier.py
rasa/nlu/featurizers/dense_featurizer/lm_featurizer.py
tests/conftest.py
tests/engine/conftest.py
tests/engine/test_caching.py
tests/engine/training/test_components.py
tests/engine/training/test_graph_trainer.py
tests/engine/training/test_hooks.py
tests/nlu/test_config.py
tests/nlu/test_train.py

- fix caching fixture for tests
- fix some test errors

fix cache usage in tests

---

rasa/engine/training/fingerprinting.py
tests/engine/training/test_fingerprinting.py
tests/test_model_training.py

- fix https://github.com/RasaHQ/rasa/issues/9769

include class implementation in fingerprint

---

rasa/cli/arguments/evaluate.py

- Fixed a problem with paths being read as strings. 

Fixing types for paths

---

setup.cfg
stubs/sanic/__init__.pyi
stubs/sanic/app.pyi
stubs/sanic/mixins/exceptions.pyi

- fix sanic typing issues
- renable `no-untyped-call`

add missing type annotations

---

docs/docs/training-data-format.mdx

- Fix syntax in training data example in `training-data-format.mdx` (uncovered by doing QA and copy-pasting from the docs)

fix syntax in training data example in the docs

---

changelog/7619.improvement.md

- closes #10111  (cf. [2.8.9 changelog](https://rasa.com/docs/rasa/changelog/#289---2021-10-08)) 

add changelog entry about tf2.6 update

---

docs/docs/command-line-interface.mdx
docs/docs/policies.mdx
docs/docs/stories.mdx
docs/docs/training-data-format.mdx
docs/docs/training-data-importers.mdx

- The update has been made on `main` already, it's a matter of harmonising the callouts across docs versions.
- Relates to https://github.com/RasaHQ/rasa/pull/10165

update experimental feature callouts

---

CHANGELOG.mdx
changelog/10146.misc.md
changelog/9949.bugfix.md
changelog/9982.bugfix.md
changelog/9989.misc.md
pyproject.toml
rasa/version.py

- Changes to channels for Slack and Hangouts integrations

prepared release of version 2.8.13

---

docs/docs/fallback-handoff.mdx
docs/docs/migration-guide.mdx
docs/docs/policies.mdx

- Add `recipe: default.v1` to full config examples in docs 
Closes https://github.com/RasaHQ/rasa/issues/10073

Add `recipe` to config examples in docs

---

rasa/engine/validation.py

- fix https://github.com/RasaHQ/rasa/issues/10142
- check origin type instead of type annotation (as we are ignoring the contents of the list)

fix windows 3.8 issue

---

rasa/constants.py

closes #10114
Minor update to `MINIMUM_COMPATIBLE_VERSION` constant

make model version 3.0.0

---

rasa/core/actions/forms.py

Fix dynamic forms bug

---

pyproject.toml
rasa/version.py

prepared release of version 3.0.0rc2

---

rasa/core/evaluation/marker_base.py
rasa/core/evaluation/marker_stats.py
rasa/shared/constants.py
tests/core/evaluation/test_marker.py
tests/core/evaluation/test_marker_stats.py

- bug fix. closes https://github.com/RasaHQ/rasa/issues/10192
- changed the column names in marker output file
- changed the stat names to past tense
- referenced the Marker docs in the error messages

Marker fixes

---

changelog/10230.doc.md
docs/docs/installation.mdx

Fixes https://github.com/RasaHQ/rasa/issues/10230
- Update docs: upgrade pip and talk about version compatible
Old docs:
https://rasa.com/docs/rasa/next/installation
Changes:

Update pip and also add warning to docs

---

rasa/cli/arguments/evaluate.py
rasa/cli/evaluate.py
rasa/core/evaluation/marker_tracker_loader.py
tests/cli/test_rasa_evaluate_markers.py
tests/core/evaluation/test_marker_tracker_loader.py

- Closes https://github.com/RasaHQ/rasa/issues/10174
- Closes https://github.com/RasaHQ/rasa/issues/10227

Markers cli changes

---

rasa/core/processor.py
rasa/server.py
tests/core/test_processor.py
tests/test_server.py

- closes #10053 
- closes #10213
- closes #10220

trigger slot extraction in interactive mode

---

docs/docs/command-line-interface.mdx
docs/docs/markers.mdx

- Marker docs ready for a second round of reviews. 
- Please comment on the old PR https://github.com/RasaHQ/rasa/pull/10095. I will address the changes in this PR. And you can approve once you're satisfied. 

Marker docs RC2

---

rasa/nlu/test.py

Adds missing import.
Fixes #10254

Add missing import to fix nlu test compare models

---

CHANGELOG.mdx
changelog/10241.bugfix.md
changelog/10257.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.14

---

rasa/core/migrate.py

closes #10242
This improves the success message when domain data is successfully migrated from 2.0 to 3.0

Improve success message of data migration

---

docs/docs/model-configuration.mdx
rasa/cli/initial_project/config.yml
rasa/shared/importers/default_config.yml

Add comment to recipe in the default and scaffold configs

---

docs/sidebars.js

- Add `Slot Validation Actions` to the Actions sidebar

Add new item to Actions sidebar

---

docs/docs/training-data-format.mdx
rasa/shared/constants.py
rasa/shared/utils/validation.py

Improvements based on @ancalita's comments on https://github.com/RasaHQ/rasa/pull/10352

10288 training data version warning

---

rasa/core/migrate.py
tests/core/test_migrate.py

Update training data version during domain migration to "3.0"

---

rasa/core/processor.py
tests/core/test_processor.py

- Log when loading a model like we did in 2.8.x

Log when loading model.

---

rasa/cli/evaluate.py

- Make sure domain is passed to tracker store factory for proper validation (closes #10239)

Use domain with tracker store factory on markers

---

.github/templates/model_regression_test_results.tmpl

[model regression tests] Print `no-data` for diff in comment table if data not found in main branch run

---

docs/docs/slot-validation-actions.mdx

- Move most of the content to Rasa SDK docs and edit slot validation action docs to align with Rasa SDK docs.

Edit slot validation action docs

---

rasa/engine/graph.py

- closes #10217
- removes the graph-component related printouts in #10232

reraise only for non-rasexception in graph.py

---

docs/docs/introduction.mdx
docs/docusaurus.config.js

Fixes https://github.com/RasaHQ/rasa/issues/10368

update banner and home page to refer to 2.x instead of 1.x

---

docs/docs/nlu-training-data.mdx
rasa/nlu/utils/pattern_utils.py
tests/nlu/utils/test_pattern_utils.py

Applies the changes in PR#10376 to `2.8.x` branch

validate regexes

---

CHANGELOG.mdx
changelog/10384-bugfix.md
pyproject.toml
rasa/version.py

- validation for regexes in nlu training data config [#6960](https://github.com/RasaHQ/rasa-x/issues/6960)

Prepare release 2.8.15

---

examples/knowledgebasebot/domain.yml

- Update slot mappings in `examples/knowledgebasebot` from `type: custom` to `type: from_entity`.

Update slot mappings in `knowledgebasebot`

---

.github/workflows/continous-integration.yml
rasa/api.py

- Use the `ddtrace-patch-all` flag for pytests

Use `ddtrace-patch-all` for pytests

---

CHANGELOG.mdx

Closes https://github.com/RasaHQ/rasa/issues/10399

fix typo in CHANGELOG

---

.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml

- Remove duplicate environment variables (these get set again a few lines after)
- Improve wording

Refactor model regression tests

---

changelog/9351.bugfix.md
rasa/cli/arguments/test.py
rasa/cli/test.py
tests/cli/test_rasa_test.py

Add an option to specify `--domain` for `rasa test nlu` CLI command

---

docs/docs/tuning-your-model.mdx

- Replaces dead link in the docs (see [thread](https://rasa-hq.slack.com/archives/C016FLYV4QN/p1638525710066700))

Replace external dead link in the docs

---

changelog/10291.doc.md
docs/docs/migration-guide.mdx
docs/docs/slot-validation-actions.mdx

- Fixes yaml indentation in slot mappings migration guide + replaces `next` links with the released docs.
- Closes #10291 

Some docs improvements

---

CHANGELOG.mdx

- Fixes https://github.com/RasaHQ/rasa/issues/10452

Fix changelog link error

---

CHANGELOG.mdx
changelog/10291.doc.md
changelog/10374.bugfix.md
changelog/10391.bugfix.md
changelog/10401.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.0.2

---

CHANGELOG.mdx
changelog/10413.improvement.md
changelog/10458.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.16

---

changelog/10143.misc.md
rasa/graph_components/validators/default_recipe_validator.py
tests/graph_components/validators/test_default_recipe_validator.py

Raise an exception if a policy has no priority

---

changelog/7645.bugfix.md
data/test/simple_retrieval_intent_nlu.yml
data/test_domains/missing_chitchat_response.yml
data/test_domains/simple_retrieval_intent.yml
rasa/shared/core/domain.py
tests/shared/importers/test_importer.py

Fixes https://github.com/RasaHQ/rasa/issues/7645
- Take subintent action utterances into consideration when checking for missing responses

Fix warning when action for subintent has response

---

.github/workflows/ci-model-regression.yml

This was introduced in https://github.com/RasaHQ/rasa/pull/10380
- Fix empty BRANCH datadog-tag

Fix MR test bug: empty branch tag

---

changelog/9945.misc.md
docs/docs/forms.mdx
rasa/core/actions/forms.py
tests/core/actions/test_forms.py

Remove the duplication of valid SlotSet events in the tracker by FormAction

---

.github/workflows/automatic-release-to-main-merger.yml

- https://github.com/RasaHQ/rasa/pull/10460 for `2.8.x` branch

Don't merge 2.8.x into main

---

docs/docs/connectors/slack.mdx

- Add note about inviting Rasa bot to channel 
This came up after talking with @sebwarnke  

Add note about inviting Rasa bot to channel

---

CHANGELOG.mdx
changelog/10448.bugfix.md
changelog/7645.bugfix.md
changelog/9945.misc.md
pyproject.toml
rasa/version.py

prepared release of version 3.0.3

---

docs/README.md
docs/docs/actively-maintained-versions.mdx
docs/netlify.toml

- Update https://rasa.com/docs/rasa/actively-maintained-versions
- Update netlify redirects
(apparently we forgot to do this when releasing 3.0, cc @joejuzl)

update documentation about version support

---

rasa/core/migrate.py

- Handle ignored intents when migrating only if intents are actually ignored (fixes #10133 )

Split out ignored intents logic in `rasa data migrate`

---

changelog/10741.bugfix.md
docs/docs/how-to-deploy.mdx
rasa/nlu/featurizers/sparse_featurizer/lexical_syntactic_featurizer.py

Make LexicalSyntacticFeaturizer inheritable

---

CHANGELOG.mdx
changelog/10741.bugfix.md
changelog/7645.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.17

---

CHANGELOG.mdx
changelog/10572.misc.md
pyproject.toml
rasa/version.py

- add a schema for single events

prepared release of version 3.0.4

---

CHANGELOG.mdx
changelog/10137.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.18

---

data/test_domains/test_domain_from_directory_tree/skill_1_domain/domain_pt2.yml
data/test_domains/test_domain_from_directory_tree/skill_2_domain/domain_pt3.yml
rasa/shared/core/domain.py

- Fixes a bug where mergeing domains from multiple files failed when the first domain file did not contain any - intents

fix domain dir merge when no intents in first file

---

changelog/10621.improvement.md
data/test_domains/test_domain_with_duplicates/domain1.yml
data/test_domains/test_domain_with_duplicates/domain2.yml
data/test_domains/test_domain_without_duplicates/domain1.yml
data/test_domains/test_domain_without_duplicates/domain2.yml
rasa/cli/data.py
rasa/shared/core/domain.py
rasa/validator.py
tests/shared/core/test_domain.py
tests/test_validator.py

This backports the changes made in [#10444](https://github.com/RasaHQ/rasa/pull/10444) to `2.8.x`

Backport 10444 changes into `2.8.x`

---

changelog/10623.bugfix.md
rasa/cli/arguments/test.py
rasa/cli/test.py
tests/cli/test_rasa_test.py

This backports changes in [PR #10466](https://github.com/RasaHQ/rasa/pull/10446) into `2.8.x`

Backport 10446 changes into 2.8.x

---

README.md

- Update README to reflect the current actively maintained versions

update README section

---

CHANGELOG.mdx
changelog/10634.bugfix.md
changelog/10643.misc.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.21

---

docs/docs/components.mdx

This PR fixes https://github.com/RasaHQ/rasa/issues/10683.

Fix CRFEntityExtractor docs example. 

---

changelog/10728.bugfix.md
rasa/utils/tensorflow/models.py

- Use tf.function in RasaModel to improve inference speed.

Use tf.function for model prediction in RasaModel.

---

changelog/10746.misc.md
rasa/cli/x.py
tests/cli/test_rasa_x.py

- Update of rasa `main` branch part of https://github.com/RasaHQ/rasa-x/issues/7214

Update rasa-x endpoint for getting a model by tag in rasa-oss `main`

---

changelog/10540.bugfix.md
rasa/core/actions/action.py
tests/core/test_actions.py

Fix setting of non-required form slot with from_entity mapping during active_loop

---

changelog/10673.bugfix.md
rasa/core/tracker_store.py
tests/core/test_tracker_stores.py

Validate port in the `SQLTrackerStore` constructor

---

poetry.lock
pyproject.toml

- addresses ongoing issue in rasa-sdk [#592](https://github.com/RasaHQ/rasa-sdk/issues/592)
- rasa-sdk has had similar dependency applied and new 3.0.4 version released

Use prompt_toolkit ^2.0

---

changelog/10590.removal.md
rasa/core/utils.py

* Fixes https://github.com/RasaHQ/rasa/issues/10632
* Remove CompositionView
CompositionView has been deprecated
Co-authored-by: Tayfun Sen <t.sen@rasa.com>
- Backports https://github.com/RasaHQ/rasa/pull/10590/files for 3.0.x

Remove CompositionView (#10590)

---

changelog/10740.misc.md
rasa/cli/x.py
tests/cli/test_rasa_x.py

- Closes https://github.com/RasaHQ/rasa-x/issues/7214

Update rasa-x endpoint for getting a model by tag in rasa-oss

---

CHANGELOG.mdx
changelog/10504.bugfix.md
changelog/10536.doc.md
changelog/10540.bugfix.md
changelog/10590.removal.md
changelog/10673.bugfix.md
changelog/10728.bugfix.md
changelog/10761.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.0.6

---

changelog/10767.bugfix.md
data/test_domains/test_domain_from_multiple_files/last_month.yml
rasa/shared/core/domain.py
tests/shared/core/test_domain.py

- Merge entities in domain as list of dicts not plain list
- fixes https://github.com/RasaHQ/rasa/issues/10766

Fix multidomain with entities with roles

---

changelog/10743.bugfix.md
rasa/core/test.py
tests/cli/test_rasa_test.py

Fix `rasa test core` error with story containing entity but no user utterance text

---

CHANGELOG.mdx
changelog/10516.bugfix.md
changelog/10782.bugfix.md
changelog/10840.bugfix.md
pyproject.toml
rasa/server.py
rasa/version.py

- release Rasa Open Source 3.0.7

prepared release of version 3.0.7

---

.github/tests/test_data/comment_body.json
.github/tests/test_data/comment_body_no_dataset_branch.json
.github/tests/test_model_regression_test_read_dataset_branch_tmpl.py

Add tests retroactively for [this PR](https://github.com/RasaHQ/rasa/pull/10786)

Add tests for read dataset branch from comment body

---

changelog/10394.improvement.md
docs/docs/testing-your-assistant.mdx
rasa/nlu/test.py
rasa/shared/nlu/training_data/entities_parser.py
rasa/shared/nlu/training_data/formats/readerwriter.py
tests/nlu/test_evaluation.py
tests/shared/nlu/training_data/formats/test_readerwriter.py
tests/shared/nlu/training_data/test_entities_parser.py

- Same as [here](https://github.com/RasaHQ/rasa/pull/10773) but ported to 3.0.x

Port PR 10773

---

CHANGELOG.mdx
changelog/10808.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.25

---

rasa/cli/initial_project/project.yml
tests/cli/test_rasa_init.py

`rasa init` adds default `project.yml`

---

.github/workflows/continous-integration.yml

- Use Windows Server 2019 for jobs run on Windows

Use Windows Server 2019 for jobs run on Windows

---

.github/configs/mr-test-example.yaml

- Add num_repetitions to helper comment

Regr Tests: Add num_repetitions to helper comment

---

CHANGELOG.mdx
changelog/10675.bugfix.md
pyproject.toml
rasa/version.py
tests/core/test_training.py

prepared release of version 3.0.10

---

examples/nlg_server/nlg_server.py
examples/reminderbot/callback_server.py
rasa/core/training/interactive.py

- Fixes https://rasahq.atlassian.net/browse/ATO-37

fix instanciation of Sanic app

---

rasa/engine/recipes/default_recipe.py
tests/engine/recipes/test_default_recipe.py

- fix https://rasahq.atlassian.net/browse/ROSS-502

fix epoch_fraction default handling

---

rasa/engine/recipes/default_components.py

- fixes https://rasahq.atlassian.net/browse/ROSS-502

add logistic regression to default components

---

Makefile
tests/core/test_broker.py

WIP Pika investigation/fix

---

CHANGELOG.mdx
changelog/11048.removal.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.27

---

changelog/11088.misc.md
rasa/core/tracker_store.py

- Refactor `TrackerStore.stream_events` method by extracting new event streaming for loop into separate `TrackerStore` method

Extract new event streaming for loop into separate `TrackerStore` method

---

changelog/11122.improvement.md
docs/docs/policies.mdx
rasa/core/policies/ted_policy.py
rasa/core/policies/unexpected_intent_policy.py
rasa/utils/tensorflow/constants.py

- 2.8 port of https://github.com/RasaHQ/rasa/pull/10944/files

Force CPU training on 2.8

---

changelog/11123.misc.md
rasa/core/actions/action.py
tests/core/test_actions.py

- Make the exception raised when the action server cannot be reached more descriptive

make action server connection error message more descriptive

---

docs/docs/command-line-interface.mdx
docs/docs/testing-your-assistant.mdx

- Add some clarifications to the CLI docs for `rasa train`, `test`, and `shell`

add some details to CLI docs

---

CHANGELOG.mdx
changelog/10482.improvement.md
changelog/11122.improvement.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.28

---

docs/docs/command-line-interface.mdx
docs/docs/connectors/your-own-website.mdx
docs/docs/contextual-conversations.mdx
docs/docs/conversation-driven-development.mdx
docs/docs/deploy/deploy-rasa-x.mdx
docs/docs/deploy/deploy-rasa.mdx
docs/docs/deploy/introduction.mdx
docs/docs/event-brokers.mdx
docs/docs/glossary.mdx
docs/docs/reaching-out-to-user.mdx
docs/docs/rei/deploy.mdx
docs/docs/setting-up-ci-cd.mdx
docs/docs/testing-your-assistant.mdx
docs/docs/writing-stories.mdx
docs/docusaurus.config.js
rasa/shared/constants.py

- Addresses https://rasahq.atlassian.net/browse/RS-8
- Update the links pointing at /docs/rasa-x to /docs/rasa-enterprise in the docs

update /docs/rasa-x links

---

CHANGELOG.mdx
changelog/10480.bugfix.md
changelog/10908.bugfix.md
changelog/11149.bugfix.md
pyproject.toml
rasa/version.py

- [FIX](https://github.com/RasaHQ/rasa/pull/11149) is being release in 3.1.1 minor release

prepared release of version 3.1.1

---

.github/poetry_version.txt
docker/docker-bake.hcl

- Bump poetry to latest version

upgrade poetry

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml

add devcontainer content from main

---

CHANGELOG.mdx
changelog/11129.bugfix.md
changelog/11197.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.1.3

---

CHANGELOG.mdx
changelog/10430.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.2.1

---

CHANGELOG.mdx
pyproject.toml
rasa/version.py

- Micro release with updated dependencies.

prepared release of version 3.0.11

---

changelog/11207.doc.md
docs/docs/event-brokers.mdx
docs/docs/lock-stores.mdx
docs/docs/tracker-stores.mdx

- Update docs about tracker stores, event brokers and lock stores.

Update customizable classes docs

---

CHANGELOG.mdx
changelog/11131.bugfix.md
changelog/11292.misc.md
changelog/11293.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.30

---

changelog/11296.misc.md
poetry.lock
pyproject.toml

- Replace pinned pytest-sanic git branch with the rasa one, update `httpx` and `pyjwt` vulnerabilities.

Update vulnerable dependencies in repo default branch.

---

CHANGELOG.mdx
changelog/11302.misc.md
pyproject.toml
rasa/version.py

prepared release of version 3.0.12

---

CHANGELOG.mdx
changelog/11322.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.31

---

CHANGELOG.mdx
changelog/11333.bugfix.md
pyproject.toml
rasa/version.py

Prepare release 3.1.5

---

CHANGELOG.mdx
changelog/11305.bugfix.md
changelog/11326.bugfix.md
changelog/11333.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.2.3

---

docs/plugins/program_output.js

- Port of https://github.com/RasaHQ/rasa/pull/11339

update plugin for program output in docs

---

docs/plugins/program_output.js

- Port of https://github.com/RasaHQ/rasa/pull/11339

Update docs program output plugin 3.0.x

---

changelog/11061.bugfix.md
data/test_domains/test_domain_with_separate_session_config/configuration.yml
data/test_domains/test_domain_with_separate_session_config/intents.yml
data/test_domains/test_domain_with_separate_session_config/responses.yml
rasa/shared/core/domain.py
tests/shared/core/test_domain.py

Fix domain loading when session_config is in a separate yml file

---

changelog/11342.doc.md
docs/docs/lock-stores.mdx
docs/docs/migration-guide.mdx

- Write docs for the new `ConcurrentRedisLockStore`.

Add docs for `ConcurrentRedisLockStore`

---

CHANGELOG.mdx
changelog/11362.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.1.6

---

changelog/11362.bugfix.md
data/test_custom_action_triggers_action_extract_slots/config.yml
data/test_custom_action_triggers_action_extract_slots/domain.yml
data/test_custom_action_triggers_action_extract_slots/nlu.yml
data/test_custom_action_triggers_action_extract_slots/stories.yml
rasa/core/processor.py
tests/core/test_processor.py

- Ports #11362 to `3.2.x` (+ adds missing `await` keyword in unit test)

Port #11362 PR fix to `3.2.x`

---

CHANGELOG.mdx
changelog/11061.bugfix.md
changelog/11362.bugfix.md
changelog/11368.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.2.4

---

.github/workflows/security-scans.yml

- Adds Trufflehog secret scanning as a replacement for Gitleaks

Add Trufflehog Secret Scanning

---

.github/workflows/security-scans.yml

- Make Trufflehog non-blocking of the build until we've evaluated past findings in git commit history

Soft Fail For Trufflehog

---

changelog/11294.bugfix.md
rasa/shared/core/slot_mappings.py
tests/regressions/test_action_two_stage_fallback_11294.py

Fix `KeyError` error when using a domain with slots and triggering `action_two_stage_fallback`

---

CHANGELOG.mdx
changelog/11294.bugfix.md
changelog/11390.bugfix.md
changelog/11394.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.2.5

---

changelog/11256.improvement.md
rasa/core/lock.py
rasa/core/lock_store.py
tests/core/test_lock_store.py
tests/integration_tests/core/conftest.py
tests/integration_tests/core/test_lock_store.py

Revert "Add concurrent Redis lock store option"

---

changelog/11342.doc.md
docs/docs/lock-stores.mdx
docs/docs/migration-guide.mdx

Revert "Add docs for `ConcurrentRedisLockStore`"

---

CHANGELOG.mdx
changelog/11426.misc.md
changelog/11433.bugfix.md
changelog/11434.misc.md
pyproject.toml
rasa/version.py

prepared release of version 3.2.6

---

.github/workflows/documentation.yml
scripts/evaluate_release_tag.py

- - Cherry pick changes from https://github.com/RasaHQ/rasa/pull/11431 to prevent future patches on 3.1.x overwriting latest docs

Ato 254 fix rasa docs workflow 3.1.x

---

.github/workflows/documentation.yml
scripts/evaluate_release_tag.py

- Cherry pick changes from https://github.com/RasaHQ/rasa/pull/11431 to prevent future patches on 3.0.x overwriting latest docs

Ato 254 fix rasa docs workflow 3.0.x

---

CHANGELOG.mdx
pyproject.toml
rasa/version.py

OS vulnerability patch release.

prepared release of version 2.8.32

---

docs/docs/connectors/your-own-website.mdx

- Provide more information related to errors resulting from the incompability between the socketio server used by Rasa and the socketio client in the user's code base.
https://github.com/RasaHQ/rasa/issues/11084

add information about socketio client-server compatibility

---

poetry.lock
pyproject.toml

- Rasa installation via `pip` installs a version of `tensorflow-text` (2.9.0) that is incompatible with rasa TF dependency.
- Fixed the constraint in `pyproject.toml`.

Fix tensorflow-text constraint

---

changelog/11429.bugfix.md
docs/docs/components.mdx
rasa/nlu/classifiers/logistic_regression_classifier.py
tests/nlu/classifiers/test_logistic_regression_classifier.py

- Fixes #11429
- makes ranking length configurable

Logistic regression proper ranking

---

poetry.lock
pyproject.toml

- Bumped tensorflow to 2.8, 
- bumped tensorflow addons
- excluded tensorflow-text on arm64

Tensorflow 2.8

---

changelog/11395.bugfix.md
data/test_domains/initial_slot_values_greet_and_goodbye.yml
data/test_yaml_stories/rules_greet_and_goodbye.yml
rasa/shared/core/generator.py
tests/core/policies/test_rule_policy.py
tests/core/training/test_cached_trackers.py

- fixes #11395 on 2.8.x
- analog PR to #11480 
- supersedes #11465 

Ported rule policy initial value fix to 2.8.x

---

CHANGELOG.mdx
changelog/11395.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 2.8.33

---

changelog/11522.misc.md
poetry.lock

- Part of fix required for [ATO-299](https://rasahq.atlassian.net/browse/ATO-299)

Update sanic, ujson, rasa-sdk to latest security patches on 3.1.x

---

poetry.lock

- Part of fix required for ATO-299

Update sanic to latest security patch on 3.0.x

---

CHANGELOG.mdx
pyproject.toml
rasa/version.py

prepared release of version 3.0.13

---

poetry.lock

Update dependencies on 3.2.x (mainly rasa-sdk to the latest security patch)

---

CHANGELOG.mdx
changelog/11311.bugfix.md
changelog/11448.improvement.md
pyproject.toml
rasa/version.py

prepared release of version 3.2.7

---

changelog/11540.bugfix.md
rasa/nlu/classifiers/keyword_intent_classifier.py
tests/nlu/classifiers/test_keyword_classifier.py

- fix https://github.com/RasaHQ/rasa/issues/11540

fix: keyword classifier overrides

---

CHANGELOG.mdx
changelog/11540.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.2.8

---

CHANGELOG.mdx
pyproject.toml
rasa/version.py

prepared release of version 3.2.9

---

changelog/ato-161.bugfix.md
rasa/nlu/classifiers/diet_classifier.py
tests/nlu/classifiers/test_diet_classifier.py

- Fixes a bug where DIET crashed in evaluation steps during training when using masked language modelling

Fixed MLM + eval crash in DIET

---

.github/workflows/continous-integration.yml

- Previous condition to determine if a repo was a fork did not actually work.

Fix Condition to Detect Forks when Running CI

---

.github/workflows/continous-integration.yml

- These changes will impact the build time. We should keep a close eye and see if it's the right solution for this case-scenario

Disable cache for outsiders

---

.github/workflows/continous-integration.yml

I see the same error message.
Reverts RasaHQ/rasa#11606

Revert "Disable cache for outsiders"

---

docs/docs/components.mdx

- supersedes #11184 by fixing the doc

Fixed docs for crf features

---

Makefile
changelog/11561.improvement.md
changelog/11578.improvement.md
changelog/11596.improvement.md
changelog/11598.improvement.md
changelog/11623.improvement.md
rasa/core/exporter.py
tests/cli/test_rasa_export.py
tests/core/test_exporter.py

- Merged commits 332746d & f5379703 from main to fix issues with failing cli tests on rasa-plus. This will not be available with the current alpha 3.3.0a1 but will be available with the main release of 3.3.0.

Merge main into 3.3.x

---

docs/docs/compatibility-matrix.mdx
docs/docs/installation/rasa-pro/installation.mdx
docs/sidebars.js

- Add compatibility matrix (from decision on [this Notion page](https://www.notion.so/rasa/Rasa-Pro-Services-Versioning-01133b6faba143248541a1dfa75e20da))

add compatibility matrix to the docs

---

docs/docs/action-server/deploy-action-server.mdx
docs/docs/chitchat-faqs.mdx
docs/docs/command-line-interface.mdx
docs/docs/contextual-conversations.mdx
docs/docs/conversation-driven-development.mdx
docs/docs/deploy/deploy-rasa-plus.mdx
docs/docs/glossary.mdx
docs/docs/monitoring/analytics/example-queries.mdx
docs/docs/monitoring/analytics/getting-started-with-analytics.mdx
docs/docs/setting-up-ci-cd.mdx
docs/docusaurus.config.js

- Rename "Rasa Enterprise" to "Rasa X/Enterprise"
- Update SQL queries
- Update recommendation for data lakes

Docs leftovers

---

docs/docs/monitoring/analytics/getting-started-with-analytics.mdx

added paragraph on connecting the assistant

---

docs/docs/monitoring/analytics/example-queries.mdx
docs/docs/monitoring/analytics/getting-started-with-analytics.mdx

- Added types of analytics
- Table for supported metrics

Added metrics table and categories

---

README.md

Updated links on readme for launch

---

changelog/11575.bugfix.md
rasa/core/training/interactive.py

- Fixes [ATO-410](https://rasahq.atlassian.net/browse/ATO-410) (Jira ticket of #11575 )

Fix rasa interactive bug

---

CHANGELOG.mdx
changelog/11561.improvement.md
changelog/11571.doc.md
changelog/11575.bugfix.md
changelog/11578.improvement.md
changelog/11596.improvement.md
changelog/11598.improvement.md
changelog/11623.improvement.md
pyproject.toml
rasa/version.py

prepared release of version 3.3.0

---

.github/workflows/continous-integration.yml

- Update workflows to be able to run on PRs from forks if label `security-review:done` is assigned to the PR
- Simplify docker build/push step
- Add checkout only from request HEAD commit if is fork

Add pull_request_target for fork PRs

---

.github/workflows/continous-integration.yml
Makefile
changelog/11517.improvement.md
docker/Dockerfile.pretrained_embeddings_spacy_it
docker/configs/config_pretrained_embeddings_spacy_it.yml
docker/docker-bake.hcl
docs/docs/docker/building-in-docker.mdx

- Add italian spacy model docker image 

Add Spacy Italian pre-trained model into Rasa Docker image

---

CHANGELOG.mdx

- fixes #8842
- `make livedocs` will show you it works!

remove double line in codeblock of changelog

---

.github/workflows/continous-integration.yml

- Remove pull_request_target event

Remove pull_request_target

---

changelog/11721.doc.md
docs/docs/monitoring/analytics/getting-started-with-analytics.mdx

- Completes [ATO-461](https://rasahq.atlassian.net/browse/ATO-461)

Document how to set-up additional data lakes for rasa-pro-analytics

---

docs/docs/deploy/deploy-rasa-plus.mdx

- use `variables.release` in helm chart docs

Update helm chart docs to reference latest Rasa Plus release

---

CHANGELOG.mdx
changelog/11721.doc.md
changelog/11724.doc.md
pyproject.toml
rasa/version.py

- updated numpy and scikit learn dependencies to fix some vulnerabilities https://rasahq.atlassian.net/browse/CORE-31

prepared release of version 3.3.1

---

changelog/11799.doc.md
docs/docs/deploy/deploy-rasa-pro-services.mdx

- Actions [ATO-434](https://rasahq.atlassian.net/browse/ATO-434).

Add upgrading docs for Rasa Pro Services

---

.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/continous-integration.yml

- Fix CLOUDSK_PYTHON missing variable for google setup.

Fix CLOUDSDK_PYTHON error

---

CHANGELOG.mdx
changelog/11792.bugfix.md
pyproject.toml
rasa/version.py

Prepared release of version 3.3.3

---

.github/workflows/continous-integration.yml
changelog/11792.bugfix.md
rasa/engine/storage/local_model_storage.py
tests/engine/storage/test_local_model_storage.py

Backport windows fix

---

.github/workflows/automatic-pr-update.yml
.github/workflows/automatic-release-to-main-merger.yml
.github/workflows/ci-docs-tests.yml
.github/workflows/ci-github-actions.yml
.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml
.github/workflows/continous-integration.yml
.github/workflows/dependabot-batch-updater.yml
.github/workflows/documentation.yml
.github/workflows/nightly_release.yml
.github/workflows/rasa-install-cron-check.yml
.github/workflows/security-scans.yml
.github/workflows/spellcheck.yml

- Replaced `ubuntu-latest` with `ubuntu-22.04` because Github is moving `latest` to `22.04`.

Replace ubuntu-latest with ubuntu-22.04

---

.github/workflows/automatic-pr-update.yml
.github/workflows/ci-docs-tests.yml
.github/workflows/ci-github-actions.yml
.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml
.github/workflows/continous-integration.yml
.github/workflows/documentation.yml
.github/workflows/nightly_release.yml
.github/workflows/security-scans.yml
.github/workflows/spellcheck.yml

- Replaced ubuntu-latest with ubuntu-20.04 because Github is moving latest to 22.04.

Replace ubuntu-latest with ubuntu-20.04

---

CHANGELOG.mdx
changelog/11596.improvement.md
changelog/11829.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.2.11

---

docs/docs/action-server/events.mdx
docs/docs/action-server/validation-action.mdx
docs/docs/command-line-interface.mdx
docs/docs/connectors/hangouts.mdx
docs/docs/installation/installing-rasa-open-source.mdx
docs/docs/installation/rasa-pro/installation.mdx
docs/docs/language-support.mdx
docs/docs/messaging-and-voice-channels.mdx
docs/docs/setting-up-ci-cd.mdx
docs/docs/testing-your-assistant.mdx

Co-authored-by: IanFPFerreira <ianfillipe@gmail.com>
Co-Authored-by: vitordiniz25 <vitordiniz25@gmail.com>
- Fixed one case of speeling that was incorrect and mentioned in the issue, and fixed several cases of grammatical errors #10954
-  [X] updated the documentation

Grammatical and some spelling errors #10954

---

.github/workflows/assign-default-project.yml
.github/workflows/automatic-pr-update.yml
.github/workflows/automatic-release-to-main-merger.yml
.github/workflows/cancel-stale-workflows.yml
.github/workflows/ci-docs-tests.yml
.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml
.github/workflows/continous-integration.yml
.github/workflows/dependabot-batch-updater.yml
.github/workflows/documentation.yml
.github/workflows/security-scans.yml
.github/workflows/spellcheck.yml
.github/workflows/vulnerability-scan.yml
Makefile
rasa/core/actions/action.py
rasa/utils/endpoints.py
tests/core/test_actions.py

- compressing remote action payloads by default
- addresses  https://rasahq.atlassian.net/browse/ENG-123

compressing remote action payloads by default

---

changelog/11899.docs.md
docs/docs/compatibility-matrix.mdx

Updating compatibility matrix between Rasa Plus and Rasa Pro Services

[ATO-611] Update rasa pro services compatibility

---

.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml

- Replace deprecated GKE auth method with new recommended method.

Fix GKE Auth for Model Regression Tests

---

.github/workflows/semgrep-check.yml

- Add Semgrep GitHub action to scan repository for code vulnerabilities and other issues in our Workflow files

Add semgrep github action

---

CHANGELOG.mdx
changelog/11899.doc.md
changelog/11923.bugfix.md
changelog/11929.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.4.1

---

.github/workflows/continous-integration.yml
Makefile
changelog/11924.misc.md
poetry.lock
pytest.ini
tests/core/test_actions.py
tests/core/test_processor.py
tests/engine/test_caching.py
tests/engine/training/test_graph_trainer.py
tests/examples/test_example_bots_training_data.py
tests/nlu/classifiers/test_diet_classifier.py
tests/nlu/classifiers/test_mitie_intent_classifier.py
tests/regressions/test_action_extract_slots_11333.py
tests/test_server.py

Port ATO-495 to 3.4.x

---

CHANGELOG.mdx
changelog/11924.misc.md
changelog/11926.bugfix.md
changelog/11968.bugfix.md
changelog/11971.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.4.2

---

changelog/11976.doc.md
docs/docs/tracker-stores.mdx

Document fall back tracker store mechanism

---

.github/dependabot.yml

- Remove dependabot configuration for docs altogether

Remove dependabot configuration for docs altogether

---

changelog/12001.improvement.md
rasa/graph_components/validators/default_recipe_validator.py
tests/graph_components/validators/test_default_recipe_validator.py

- Add support for custom RulePolicy.
- Fixes https://rasahq.atlassian.net/browse/ENG-3

Add support for RulePolicy requirement - [ENG 3]

---

.github/configs/tf-cuda.json

Update cuda version for latest TF version

---

.github/workflows/automatic-release-to-main-merger.yml
.github/workflows/ci-model-regression-on-schedule.yml
.github/workflows/ci-model-regression.yml
.github/workflows/continous-integration.yml
.github/workflows/documentation.yml
.github/workflows/nightly_release.yml

- Removed `set-output` deprecated Github command

Replace `set-output` deprecated command

---

docs/docs/deploy/deploy-rasa.mdx

- Add docs for the use of the auto-patched images with OS security patches applied.

Security Patch Release Docs

---

rasa/core/processor.py
rasa/engine/graph.py
rasa/engine/recipes/default_recipe.py
rasa/engine/recipes/graph_recipe.py
rasa/engine/storage/local_model_storage.py
rasa/engine/storage/storage.py
rasa/shared/core/trackers.py
rasa/shared/utils/schemas/model_config.yml
tests/conftest.py
tests/core/test_agent.py
tests/core/test_processor.py
tests/engine/recipes/test_default_recipe.py
tests/engine/recipes/test_graph_recipe.py
tests/engine/storage/test_local_model_storage.py
tests/engine/storage/test_storage.py
tests/engine/test_loader.py
tests/engine/test_validation.py
tests/engine/training/test_graph_trainer.py
tests/shared/core/test_trackers.py
tests/test_server.py

- Implements [ATO-682 subtask](https://rasahq.atlassian.net/browse/ATO-682)

Propagate assistant_id to all events' metadata

---

rasa/engine/graph.py
rasa/engine/recipes/default_recipe.py
rasa/engine/validation.py
tests/engine/recipes/test_default_recipe.py
tests/test_model_training.py

- error if arguments are not met
- rather than fixed needs, needs are based on the arguments of the graph function

select graph needs based on method args for more flexibility

---

docs/docs/command-line-interface.mdx
docs/docs/model-configuration.mdx

Adds docs for `assistant_id`

---

CHANGELOG.mdx
changelog/11997.improvement.md
changelog/12052.bugfix.md
pyproject.toml
rasa/version.py

- Patch release for https://rasahq.atlassian.net/browse/ATO-767 fix

prepared release of version 3.4.4

---

changelog/12062.doc.md
docs/docs/connectors/audioodes-voiceai-connect.mdx

Add a link to ngrok section in the voice channel docs

---

docker/docker-bake.hcl

Update poetry version in docker-bake hcl file

---

rasa/engine/recipes/default_recipe.py
tests/engine/recipes/test_default_recipe.py

- expose nlu training data through variable needs generation

Allow policies to get nlu training data

---

CHANGELOG.mdx
changelog/11087.feature.md
changelog/11926.bugfix.md
changelog/11995.improvement.md
poetry.lock
pyproject.toml
rasa/version.py

- update rasa-sdk dependency to 3.2.3 in lockfile
- Release 3.2.12
- https://rasahq.atlassian.net/browse/ATO-731

ATO-731 Prepare release 3.2.12

---

CHANGELOG.mdx
poetry.lock
pyproject.toml
rasa/version.py

- Prepare 3.3.5 release
- https://rasahq.atlassian.net/browse/ATO-732

ATO-732 Prepare release 3.3.5

---

CODEOWNERS

Add dev-tribe-engineers as owner of rasa/

---

poetry.lock

- Updated future, setuptools, Werkzeug and cryptography to the versions listed [here](https://rasahq.atlassian.net/browse/ATO-814)

Update high severity vulnerabilities

---

changelog/12099.bugfix.md
rasa/utils/tensorflow/temp_keras_modules.py

Fix skipping evaluation when batch_size is dynamic

---

CHANGELOG.mdx
changelog/12099.bugfix.md
changelog/12102.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.2.13

---

CHANGELOG.mdx
changelog/12103.bugfix.md
changelog/12117.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.3.6

---

rasa/core/policies/ensemble.py
rasa/plugin.py

- Implements https://rasahq.atlassian.net/browse/ENG-87
- Adds a hook to get filtered and reranked policy predictions.

Implement FilterAndRerank for policy prediction

---

docs/docs/installation/environment-set-up.mdx

- As part of this task, it is decided not to do any dependency upgrades but update the docs.
- Fixes: https://rasahq.atlassian.net/browse/ENG-199

Update docs related to supported python version [ENG 199]

---

changelog/12098.bugfix.md
rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py
tests/nlu/featurizers/test_count_vectors_featurizer.py

- Restrict min_df value to 1 for all attributes except TEXT.
- Fixes: https://rasahq.atlassian.net/browse/ENG-149

Fix CountVectorFeaturizer to train when min_df != 1

---

CHANGELOG.mdx
changelog/12098.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.4.6

---

pyproject.toml
rasa/core/brokers/kafka.py
rasa/core/channels/__init__.py
rasa/core/channels/hangouts.py
rasa/core/channels/mattermost.py
rasa/engine/recipes/default_recipe.py
rasa/nlu/persistor.py
rasa/nlu/utils/hugging_face/registry.py
rasa/nlu/utils/spacy_utils.py
rasa/server.py
rasa/shared/core/training_data/structures.py
rasa/shared/nlu/training_data/entities_parser.py
rasa/shared/nlu/training_data/formats/luis.py
rasa/utils/plotting.py
tests/cli/test_rasa_evaluate_markers.py
tests/cli/test_rasa_export.py
tests/cli/test_rasa_interactive.py
tests/cli/test_rasa_run.py
tests/cli/test_rasa_test.py
tests/cli/test_rasa_train.py
tests/cli/test_rasa_visualize.py
tests/core/channels/test_hangouts.py
tests/core/policies/test_rule_policy.py
tests/nlu/tokenizers/test_whitespace_tokenizer.py

- Based of https://github.com/RasaHQ/rasa/pull/12135
- Enable more checks
- Relates to https://github.com/RasaHQ/rasa/pull/12136

enable RUF checks

---

changelog/12136.bugfix.md

- Add missing changelog entry for ATO-758

Add missing changelog entry for ATO-758

---

data/test_endpoints/endpoints_redis.yml
data/test_endpoints/endpoints_sql.yml
docs/docs/connectors/rocketchat.mdx
rasa/__main__.py
rasa/core/tracker_store.py
rasa/plugin.py
tests/core/test_tracker_stores.py

- Add more plugin hook specs to support epic [ATO-696](https://rasahq.atlassian.net/browse/ATO-696)
[ATO-696]: https://rasahq.atlassian.net/browse/ATO-696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-696] Add hook specs for tracker store

---

changelog/12155.bugfix.md
rasa/utils/common.py
rasa/utils/tensorflow/models.py

Set random seed

---

changelog/12169.doc.md
docs/docs/compatibility-matrix.mdx

- Fixes [ATO-822](https://rasahq.atlassian.net/browse/ATO-822)
[ATO-822]: https://rasahq.atlassian.net/browse/ATO-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Compatibility Matrix

---

changelog/12168.doc.md
docs/docs/deploy/deploy-rasa-pro-services.mdx

- Fixes [ATO-846](https://rasahq.atlassian.net/browse/ATO-846)
[ATO-846]: https://rasahq.atlassian.net/browse/ATO-846?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix docker image name in docs

---

CHANGELOG.mdx
changelog/12127.doc.md
changelog/12169.doc.md
changelog/12174.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.5.1

---

changelog/12189.bugfix.md
docs/docs/domain.mdx
rasa/shared/core/domain.py
tests/shared/core/test_domain.py

- Fixes [ATO-785](https://rasahq.atlassian.net/browse/ATO-785)
[ATO-785]: https://rasahq.atlassian.net/browse/ATO-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Except validate_form_action from selective_domain

---

changelog/12189.bugfix.md
docs/docs/domain.mdx
rasa/shared/core/domain.py
tests/shared/core/test_domain.py

Cherrypicks commits that fixes [ATO-785](https://rasahq.atlassian.net/browse/ATO-785) to 3.4.x
[ATO-785]: https://rasahq.atlassian.net/browse/ATO-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Port #12189 to  3.4.x

---

docs/docs/installation/rasa-pro/installation.mdx
docs/docs/installation/rasa-pro/rasa-pro-artifacts.mdx
docs/docs/introduction.mdx
docs/docs/monitoring/analytics/getting-started-with-analytics.mdx
docs/docs/rasa-pro.mdx
docs/sidebars.js

- New Rasa Pro page in docs, new sidebar entry
- Rename Architecture overview page
- small reword on Analytics page

New Rasa Pro page in docs

---

CHANGELOG.mdx
changelog/12209.doc.md
pyproject.toml
rasa/version.py

prepared release of version 3.5.3

---

CHANGELOG.mdx
changelog/12139.bugfix.md
changelog/12144.improvement.md
changelog/12189.bugfix.md
pyproject.toml
rasa/version.py

- Rasa- plus needs a patch release 3.4.7 to fix issues https://rasa-hq.slack.com/archives/C01M5TAHDHA/p1679904410287369
- Rasa 3.4.7 is being released to maintain version lockstep between rasa and rasa-plus

prepared release of version 3.4.7

---

CHANGELOG.mdx
changelog/12144.improvement.md
changelog/12187.bugfix.md
changelog/12192.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.3.7

---

.github/workflows/automatic-release-to-main-merger.yml
.github/workflows/ci-github-actions.yml
.github/workflows/documentation.yml

- Fix warning - Github Actions Node 12.x Deprecation by Summer 2023

Bump Github Actions dependencies

---

CHANGELOG.mdx
changelog/12186.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.4.8

---

README.md

- Remove outdated information from Maintenance Section of readme

Update maintenance section in Readme

---

CHANGELOG.mdx
changelog/12234.misc.md
pyproject.toml
rasa/version.py

prepared release of version 3.4.9

---

.github/workflows/automatic-pr-update.yml
.github/workflows/ci-docs-tests.yml
.github/workflows/ci-model-regression.yml
.github/workflows/continous-integration.yml
.github/workflows/documentation.yml
.github/workflows/security-scans.yml

- Bump versions of rasaHQ/create-comment and  rasaHQ/update-pr-branch github actions
- Replace rasaHQ/pr-change-paths-filter with dorny/paths-filter github action since version bump is not possible

INFRA-175 - Fix node 12 deprications in Github Actions

---

changelog/12272.doc.md
docs/docs/model-storage.mdx
tests/integration_tests/core/test_agent.py

- Fixes [ATO-884](https://rasahq.atlassian.net/browse/ATO-884)
[ATO-884]: https://rasahq.atlassian.net/browse/ATO-884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update AWS model loading docs and add integration testing

---

Makefile

- This download was missing and causing main's test to crash. Must have been a caching issue that it didn't come up in the original PR

Added model downloads to full model training

---

CHANGELOG.mdx
changelog/12255.misc.md
pyproject.toml
rasa/version.py

- New release for version 3.4.x

prepared release of version 3.4.10

---

changelog/12291.misc.md
pyproject.toml
tests/conftest.py
tests/core/conftest.py

- Fixes [ATO-859](https://rasahq.atlassian.net/browse/ATO-859)
[ATO-859]: https://rasahq.atlassian.net/browse/ATO-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable asyncio pytest mode in tests

---

changelog/12286.bugfix.md
data/test_config/config_no_assistant_id_with_comments.yml
rasa/cli/utils.py
rasa/shared/utils/io.py
tests/cli/test_utils.py

- Fixes [ATO-882](https://rasahq.atlassian.net/browse/ATO-882)
[ATO-882]: https://rasahq.atlassian.net/browse/ATO-882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATO-882 Appending assistant id truncates comments

---

CHANGELOG.mdx
changelog/12253.misc.md
pyproject.toml
rasa/version.py

- This https://github.com/RasaHQ/rasa/pull/12298 needs to be released in a version so rasa-plus 3.3.x can be upgraded to poetry 1.4.2

prepared release of version 3.3.9

---

CHANGELOG.mdx
changelog/12267.misc.md
changelog/12268.bugfix.md
changelog/12271.bugfix.md
changelog/12272.doc.md
changelog/12279.doc.md
changelog/12286.bugfix.md
changelog/12290.doc.md
changelog/12295.bugfix.md
poetry.lock
pyproject.toml
rasa/version.py

prepared release of version 3.5.5

---

README.md

- As per the last DoD in https://rasahq.atlassian.net/browse/ATO-929
- Updated README.md

Update readme with instruction to update version in rasax

---

rasa/core/actions/action.py
rasa/plugin.py

- Reverts changes introduced in https://github.com/RasaHQ/rasa/pull/12066

Remove action activation/deactivation generation code - [ENG 255] 

---

changelog/12332.misc.md
rasa/core/tracker_store.py
rasa/shared/core/trackers.py
tests/core/test_tracker_stores.py

- Fixes [ATO-634](https://rasahq.atlassian.net/browse/ATO-634)
[ATO-634]: https://rasahq.atlassian.net/browse/ATO-634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extract TrackerEventDiffEngine into a separate component

---

Makefile
changelog/12325.bugfix.md
rasa/core/brokers/pika.py
tests/core/test_broker.py
tests/integration_tests/core/brokers/test_pika.py

- (cherry picked from commit b6268c3a2610f87e23746b8e8c2056ae8a8804c5)

Fix RabbitMQ url parsing in `3.3.x`

---

CHANGELOG.mdx
changelog/12280.bugfix.md
changelog/12325.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.5.6

---

Makefile
changelog/12325.bugfix.md
rasa/core/brokers/pika.py
tests/core/test_broker.py
tests/integration_tests/core/brokers/test_pika.py

- (cherry picked from commit b6268c3a2610f87e23746b8e8c2056ae8a8804c5)

Fix RabbitMQ url parsing in `3.4.x`

---

CHANGELOG.mdx
changelog/12325.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.3.10

---

changelog/12361.bugfix.md
rasa/core/brokers/kafka.py
tests/integration_tests/core/brokers/test_kafka.py

- Fixes [ATO-1034](https://rasahq.atlassian.net/browse/ATO-1034)
[ATO-1034]: https://rasahq.atlassian.net/browse/ATO-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle Kafka Queue Full BufferError 

---

CHANGELOG.mdx
changelog/12361.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.4.12

---

changelog/12361.bugfix.md
rasa/core/brokers/kafka.py
tests/integration_tests/core/brokers/test_kafka.py

- Cherry picked commits from [12361](https://github.com/RasaHQ/rasa/pull/12361)

Port Kafka BufferError Exception fix to 3.5.x

---

CHANGELOG.mdx
changelog/12361.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.5.8

---

rasa/core/policies/ensemble.py
rasa/plugin.py

Revert "Implement FilterAndRerank for policy prediction"

---

changelog/12372.misc.md
rasa/core/agent.py
rasa/core/processor.py
rasa/core/utils.py
rasa/plugin.py
tests/test_plugin.py

- Implements [ATO-1021](https://rasahq.atlassian.net/browse/ATO-1021)
[ATO-1021]: https://rasahq.atlassian.net/browse/ATO-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implements hookspecs for anonymization pipeline

---

pyproject.toml

- use pypi package instead of git for tensorflow-addons

use pypi package instead of git for tensorflow-addons

---

CHANGELOG.mdx
pyproject.toml
rasa/version.py

Prepare release 3.5.9

---

.github/workflows/ci-github-actions.yml
.github/workflows/continous-integration.yml
.github/workflows/security-scans.yml

- Address installation issues [that prevented the 3.3.11 release](https://github.com/RasaHQ/rasa/actions/runs/5025305785)

pin urllib3 version

---

.github/workflows/continous-integration.yml

- Discussed [here](https://rasa-hq.slack.com/archives/C047U7ZBKM1/p1684746750902749)

Temporarily modify condition to release all docker images

---

.github/workflows/nightly_release.yml

- Issue https://github.com/RasaHQ/rasa/actions/runs/5019858949/jobs/9000781823

Fix ruamel.yaml issue

---

CHANGELOG.mdx
changelog/12437.doc.md
docs/docs/glossary.mdx
docs/docs/spaces.mdx
pyproject.toml
rasa/version.py

prepared release of version 3.5.10

---

.github/workflows/continous-integration.yml
changelog/12467.bugfix.md
rasa/core/actions/forms.py
tests/core/actions/test_forms.py
tests/core/test_broker.py

* run custom form validation on form activation
* add changelog entry
* update tests, rename var
(cherry picked from commit db0f81d6d009f17a715f56972da45537d25d35ee)
- ...

Implement bugfix for custom form validation during form activation in `3.5.x`

---

CHANGELOG.mdx
changelog/12467.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.5.11

---

.github/workflows/continous-integration.yml

- Backport [changes](https://github.com/RasaHQ/rasa/pull/12156) to 3.4.x

3.4.x-Add condition to skip tests when tag is pushed

---

CHANGELOG.mdx
changelog/12467.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.4.14

---

.github/workflows/continous-integration.yml
tests/core/test_broker.py

Revert docker change in pypi release workflow

---

.github/workflows/continous-integration.yml

- Backport https://github.com/RasaHQ/rasa/pull/12156 to 3.3.x

3.3.x-Add condition to skip tests when tag is pushed

---

docs/docs/deploy/deploy-rasa-pro-services.mdx

- Should be merged after https://github.com/RasaHQ/rasa-pro-services/pull/136

Add log level envar to rasa-pro-services

---

changelog/12504.doc.md
docs/docs/monitoring/analytics/example-queries.mdx
docs/docs/monitoring/analytics/getting-started-with-analytics.mdx

- add missing `.mdx` file (not sure why this is not picked-up by our linting system)

Fix deadlinks in analytics docs

---

rasa/shared/core/events.py
rasa/shared/core/training_data/story_reader/yaml_story_reader.py

Use structlog in shared package

---

docs/docs/llms/large-language-models.mdx
docs/docs/llms/llm-custom.mdx
docs/docs/llms/llm-intent.mdx
docs/docs/llms/llm-intentless.mdx
docs/docs/llms/llm-nlg.mdx
docs/docs/llms/llm-setup.mdx
docs/netlify.toml
docs/package.json
docs/sidebars.js
docs/themes/theme-custom/theme/RasaLabsBanner/index.jsx
docs/themes/theme-custom/theme/RasaLabsBanner/styles.module.css
docs/themes/theme-custom/theme/RasaLabsLabel/index.jsx
docs/themes/theme-custom/theme/RasaLabsLabel/styles.module.css

- add new Rasa Labs banner and label
- remove from sidebar and add links between pages
- fix typos / reword some sentences
- add redirect from `docs/rasa/llms`

Llms docs updates

---

changelog/12371.doc.md
docs/docs/installation/rasa-pro/installation.mdx
docs/docs/installation/rasa-pro/rasa-pro-artifacts.mdx

Docs; ATO-1063 Rasa Pro install doc update

---

changelog/12512.misc.md
docs/docs/telemetry/telemetry.mdx
rasa/plugin.py
rasa/telemetry.py
tests/test_telemetry.py

- Fix [ATO-1152](https://rasahq.atlassian.net/browse/ATO-1152)
- hook implementation in [PR](https://github.com/RasaHQ/rasa-plus/pull/628)
[ATO-1152]: https://rasahq.atlassian.net/browse/ATO-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-1152] Add license hashes to telemetry 

---

docs/docs/llms/llm-intent.mdx
docs/docs/llms/unhappy-paths.mdx

Wrote docs for unhappy paths

---

docs/docs/flows.mdx

Review business logic with flows [ENG-354]

---

docs/docs/spaces.mdx

- Mention customer support instead of forum in Spaces callout

Update spaces docs

---

rasa/nlu/classifiers/flow_prompt_template.jinja2
rasa/nlu/classifiers/llm_flow_classifier.py
rasa/shared/core/flows/flow.py

- improving prediction by allowing description for question to be integrated into the prompt

Validation hallucination

---

CHANGELOG.mdx
changelog/12512.misc.md
changelog/12534.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.5.12

---

docs/docs/llms/flow-policy.mdx
docs/docs/llms/unhappy-paths.mdx

cancellation docs

---

docs/themes/theme-custom/theme/RasaProBanner/index.jsx

- Remove free trial link.
- Change copy to 'Talk with Sales'

Remove free trial link. Change copy to 'Talk with Sales'

---

.github/workflows/continous-integration.yml

Fix version of actions with sha (security)

---

.github/workflows/continous-integration.yml
pyproject.toml
rasa/version.py

prepared release of version 3.6.1a1

---

CHANGELOG.mdx
changelog/12371.doc.md
changelog/12505.doc.md
changelog/12516.bugfix.md
changelog/12521.bugfix.md
changelog/12527.doc.md
changelog/12533.improvement.md
changelog/12543.improvement.md
changelog/12556.bugfix.md
changelog/12560.improvement.md
changelog/12579.doc.md
changelog/12581.doc.md
changelog/12597.doc.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.1

---

.github/workflows/continous-integration.yml

- Discussed here https://rasa-hq.slack.com/archives/C01H2UCNP2T/p1688458013078029
- Ignoring the 3.6.1 docker image to be tagged as latest to override this problem. 
- Ticket for fixing the issue created [here](https://rasahq.atlassian.net/browse/ATO-1234)

Ignore docker tag latest

---

CHANGELOG.mdx
changelog/12566.bugfix.md
changelog/12567.misc.md
changelog/12568.bugfix.md
pyproject.toml
rasa/version.py

Prepared release of version 3.4.15

---

CHANGELOG.mdx
changelog/12549.bugfix.md
pyproject.toml
rasa/version.py

Prepared release of version 3.5.13

---

docs/docs/rasa-pro-changelog.mdx

add blurb about OSS changelog

---

CHANGELOG.mdx
changelog/12602.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.2

---

rasa/core/actions/flows.py
rasa/core/policies/flow_policy.py
rasa/nlu/classifiers/llm_flow_classifier.py

- correction stacks where never pushed to the frame, it was always interrupt. Now correction works and the back jumps are executed
- allowing to correct multiple slots at once in the llm flow classifier

implemented fixes for corrections

---

changelog/12637.improvement.md
rasa/core/actions/forms.py
rasa/core/channels/facebook.py
rasa/core/channels/hangouts.py
rasa/core/channels/rest.py
rasa/core/http_interpreter.py
rasa/core/nlg/interpolator.py
rasa/utils/log_utils.py

- Fixes [ATO-1189](https://rasahq.atlassian.net/browse/ATO-1189)
[ATO-1189]: https://rasahq.atlassian.net/browse/ATO-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Natural Language info to structlog

---

CHANGELOG.mdx
changelog/12462.misc.md
changelog/12650.misc.md
pyproject.toml
rasa/version.py

prepared release of version 3.3.12

---

changelog/12648.misc.md
poetry.lock
pyproject.toml

Update requests to 2.31.0 on 3.4.x

---

CHANGELOG.mdx
changelog/12640.bugfix.md
changelog/12648.misc.md
pyproject.toml
rasa/version.py

prepared release of version 3.4.16

---

CHANGELOG.mdx
changelog/12639.bugfix.md
changelog/12649.misc.md
pyproject.toml
rasa/version.py

prepared release of version 3.5.14

---

docs/docs/flows.mdx
docs/docs/llms/llm-flow-classifier.mdx
docs/docs/llms/llm-setup.mdx
poetry.lock
pyproject.toml
rasa/core/policies/flow_policy.py
rasa/engine/caching.py
rasa/nlu/classifiers/llm_flow_classifier.py
rasa/shared/core/flows/flow.py
rasa/shared/core/trackers.py
rasa/utils/llm.py

- configurable llm connection
- simple caching for llm calls to improve testing and development speed

Use langchain rather than openai to allow for configuration

---

.github/workflows/documentation.yml
trivy-secret.yaml

- Fix [ATO-1236](https://rasahq.atlassian.net/browse/ATO-1236)
[ATO-1236]: https://rasahq.atlassian.net/browse/ATO-1236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-1236] Change slack notification for docs

---

pyproject.toml
rasa/version.py

prepared release of version 3.7.0b2

---

CHANGELOG.mdx
changelog/12637.improvement.md
changelog/12638.bugfix.md
changelog/12659.doc.md
changelog/12661.bugfix.md
changelog/12663.doc.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.3

---

changelog/12685.doc.md
docs/docs/custom-actions.mdx

- Fixes [ATO-977](https://rasahq.atlassian.net/browse/ATO-977?atlOrigin=eyJpIjoiYzRlOWQxMzkyOTJiNDNjNDkyMTQ3ZDI2Zjc2OGJjY2YiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[ATO-977]: https://rasahq.atlassian.net/browse/ATO-977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Correct action server api sample in docs

---

CHANGELOG.mdx
changelog/12575.bugfix.md
changelog/12663.doc.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.4

---

changelog/12704.improvement.md
rasa/core/channels/channel.py
rasa/core/channels/rest.py

- For [ATO-782](https://rasahq.atlassian.net/browse/ATO-782)
[ATO-782]: https://rasahq.atlassian.net/browse/ATO-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pass request Headers 

---

rasa/cdu/command_generator/command_prompt_template.jinja2
rasa/cdu/command_generator/llm_command_generator.py

- adds allowed values of bool and categorical slots to the prompt to improve slot filling performance

Allowed slot vals in prompt

---

docs/docs/flows.mdx
docs/docs/start-here.mdx
rasa/cdu/command_generator/llm_command_generator.py
rasa/cli/initial_project_dm2/data/flows.yml
rasa/shared/core/flows/flow.py

- skip if filled should default to `true` according to the spec: https://www.notion.so/rasa/PRD-Flow-spec-Studio-034f6810b3254ed09fe4e3a2c6a4519c?pvs=4#76149e32758242c1af41857214bb46d4

have skip if filled default to true

---

docs/docs/installation/rasa-pro/installation.mdx
docs/docs/installation/rasa-pro/rasa-pro-artifacts.mdx

- Improve the authentication docs to outline the exact steps instead of referring users to a lengthy GCP docs page

Improve GCP Artifact Registry Authentication Docs

---

changelog/12721.doc.md
docs/docs/monitoring/tracing.mdx

- Fixes [ATO-1374](https://rasahq.atlassian.net/browse/ATO-1374)
[ATO-1374]: https://rasahq.atlassian.net/browse/ATO-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update tracing documentation

---

Makefile
rasa/model_training.py
tests/README.md
tests/acceptance_tests/test_training.py
tests/conftest.py
tests/test_model_training.py

Some training e2e tests are testing logic which deduces if retraining should happen.
We can replace those e2e tests with unit tests which will target crucial components of the system.

[ATO-838][ATO-1048] Replace retraining e2e tests with unit tests

---

rasa/cdu/command_generator/llm_command_generator.py
rasa/core/policies/flow_policy.py

- resetting values instead of dropping abstract values
- not printing interrupt return message when no flow is left on stack

Eng 368 taking stock

---

changelog/12735.bugfix.md
poetry.lock
pyproject.toml

- Fixes [ATO-1419](https://rasahq.atlassian.net/browse/ATO-1419)
[ATO-1419]: https://rasahq.atlassian.net/browse/ATO-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Pin dnspython to avoid dependency incompatibility

---

docs/docs/llms/llm-setup.mdx

- additional docs for azure openai instance and configuration
- [x ] updated the documentation

docs: add azure llm docs

---

data/test_evaluations/test_end_to_end_trips_circuit_breaker.yml
rasa/cdu/command_processor.py
rasa/cdu/flow_stack.py
rasa/core/actions/flows.py
rasa/core/channels/chat.html
rasa/core/policies/default_flows.yml
rasa/core/policies/flow_policy.py
rasa/core/processor.py
rasa/shared/core/flows/flow.py
tests/core/test_evaluation.py

- introduced new stack frame type
- introduced `CLEANUP` step at the end of every flow 
- increased circuit breaker threshold to better support corrections
- removed unecessary `RESUME` flow stack type
- added pattern that gets triggered when the stack runs empty
Fixes https://rasahq.atlassian.net/browse/ENG-476
Fixes https://rasahq.atlassian.net/browse/ENG-462
Fixes https://rasahq.atlassian.net/browse/ENG-468

improved cancel and empty stack behaviour

---

docs/docs/flows.mdx
rasa/core/policies/flow_policy.py

- Add documentation for writing conditions in dm2 flows
- `p.evaluate(text_slots)` is faster than `p.analyze(text_slots)` in failure cases (source: [pypred readme](https://github.com/armon/pypred#api)). The latter also returns context which isn't being used. I have replaced the usage of analyze() with evaluate()

Pypred-docs

---

changelog/12755.bugfix.md
poetry.lock
pyproject.toml

- Fixes[ ATO-1371](https://rasahq.atlassian.net/browse/ATO-1371)

Address security vulnerabilities with setuptools and wheel

---

changelog/12768.bugfix.md
poetry.lock
pyproject.toml

- Fixes [ATO-1497](https://rasahq.atlassian.net/browse/ATO-1497)
[ATO-1497]: https://rasahq.atlassian.net/browse/ATO-1497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Address security vulnerabilities

---

examples/moodbot/domain.yml

updating baby tiger image

---

CHANGELOG.mdx
changelog/12768.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.7

---

.github/workflows/continous-integration.yml
rasa/core/lock_store.py

Add SSL cert parameters to Redis lock store.

[ATO-1367] Add SSL cert parameters to Redis lock store on 3.5.x

---

CHANGELOG.mdx
pyproject.toml
rasa/version.py

prepared release of version 3.6.8

---

CHANGELOG.mdx
pyproject.toml
rasa/version.py

prepared release of version 3.5.16

---

.github/workflows/ci-github-actions.yml
.github/workflows/continous-integration.yml
.github/workflows/security-scans.yml
poetry.lock
rasa/core/lock_store.py

Add SSL cert parameters to Redis lock store.

[ATO-1367] Add SSL cert parameters to Redis lock store on 3.4.x

---

docs/docs/llms/llm-configuration.mdx

- fixed `model_name` key to `model` for embeddings
- added common `too many inputs` error that users will receive if they do not lower `chunk_size` parameter from default value of 1000

Modified azure config logs

---

CHANGELOG.mdx
pyproject.toml
rasa/version.py

- Release 3.4.17,  fixes https://github.com/RasaHQ/rasa/pull/12774

prepared release of version 3.4.17

---

rasa/cdu/commands/correct_slots_command.py
rasa/cdu/commands/start_flow_command.py
rasa/cdu/stack/frames/__init__.py
rasa/cdu/stack/frames/dialogue_stack_frame.py
rasa/cdu/stack/frames/flow_stack_frame.py
rasa/core/actions/flow_trigger_action.py
rasa/core/policies/flow_policy.py
tests/cdu/commands/test_cancel_flow_command.py
tests/cdu/commands/test_correct_slots_command.py
tests/cdu/stack/frames/test_chit_chat_frame.py
tests/cdu/stack/frames/test_dialogue_stack_frame.py
tests/cdu/stack/frames/test_flow_frame.py
tests/cdu/stack/frames/test_search_frame.py
tests/cdu/stack/test_dialogue_stack.py
tests/cdu/stack/test_utils.py

added tests for the rasa.cdu.stack module

---

CHANGELOG.mdx
changelog/12778.improvement.md
changelog/12790.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.9

---

docs/docs/concepts/llm-configuration.mdx
docs/docs/llms/contextual-response-rephraser.mdx
docs/docs/llms/llm-configuration.mdx
docs/docs/llms/llm-custom.mdx
docs/docs/llms/llm-next-gen.mdx
docs/docs/start-here.mdx
docs/docs/tutorial.mdx
docs/sidebars.js

- renamed response rephraser & cdu

renamed llmresponserephraser -> contextualresponserephraser

---

changelog/1493.improvement.md
rasa/telemetry.py
tests/test_telemetry.py

- fixes https://rasahq.atlassian.net/browse/ATO-1493

License only telemetry 3.4

---

changelog/1493.improvement.md
rasa/telemetry.py
tests/test_telemetry.py

- fixes https://rasahq.atlassian.net/browse/ATO-1493

[ATO-1493] Send telemetry only if there is License present 3.5

---

changelog/1493.improvement.md
rasa/telemetry.py
tests/test_telemetry.py

- fixes https://rasahq.atlassian.net/browse/ATO-1493

[ATO-1493] Send telemetry only if there is License present 3.6

---

CHANGELOG.mdx
changelog/12827.improvement.md
changelog/12835.improvement.md
changelog/1493.improvement.md
pyproject.toml
rasa/version.py

prepared release of version 3.4.18

---

docs/docs/concepts/flows.mdx

Update docs with slot predicate validation

---

rasa/cli/project_templates/tutorial/actions.py
rasa/cli/project_templates/tutorial/domain.yml

rename custom action in tutorial project

---

rasa/core/policies/flow_policy.py
rasa/dialogue_understanding/patterns/collect_information.py
rasa/dialogue_understanding/patterns/default_flows_for_patterns.yml
rasa/shared/core/flows/flow.py
tests/cdu/stack/test_dialogue_stack.py
tests/core/actions/test_action_run_slot_rejections.py

- Implements [ATO-1567](https://rasahq.atlassian.net/browse/ATO-1567)
[ATO-1567]: https://rasahq.atlassian.net/browse/ATO-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ability to optionally specify different response for a collect information step

---

3.7.0b1/main_plain/.config/rasa/global.yml

Remove junk which was committed by accident.

Remove junk

---

docs/docs/llms/large-language-models.mdx
docs/docs/llms/llm-custom.mdx
docs/docs/llms/llm-intent.mdx
docs/docs/llms/llm-intentless.mdx
docs/docs/llms/llm-nlg.mdx
docs/docs/llms/llm-setup.mdx
docs/themes/theme-custom/theme/RasaLabsBanner/index.jsx
docs/themes/theme-custom/theme/RasaLabsLabel/styles.module.css

- Add Pro label on Labs pages
- Update labs banner content

Eng 574 update rasa labs pages

---

CHANGELOG.mdx
changelog/12827.improvement.md
changelog/12852.improvement.md
changelog/12868.doc.md
changelog/1493.improvement.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.10

---

docs/docs/concepts/flows.mdx

- Updating docs for ATO-1550 + ATO-1567.

More collect information updating docs

---

.github/workflows/continous-integration.yml
CHANGELOG.mdx
changelog/12722.bugfix.md
changelog/12886.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.11

---

.typo-ci.yml
docs/docs/deploy/deploy-action-server.mdx
docs/docs/deploy/deploy-rasa-pro-services.mdx
docs/docs/deploy/deploy-rasa.mdx
docs/docs/deploy/environment-variables.mdx
docs/sidebars.js

- Add new docs page for environment variables
- Reference this new page in the various Deployment docs

ATO-1560 Documentation for environment variables

---

.dockerignore
.github/workflows/continous-integration.yml
docker/.dockerignore

Fix docker-full build failure 

---

.dockerignore
.github/workflows/continous-integration.yml
docker/.dockerignore

- Same changes as here https://github.com/RasaHQ/rasa/pull/12895

Free disk space

---

docs/docs/concepts/conversation-repair.mdx

- Addresses some concerns from [here](https://rasahq.atlassian.net/browse/ENG-573)

Update info on default behaviour of conversation repairs and how to modify it

---

.typo-ci.yml
docs/docs/command-line-interface.mdx

- updates [ATO-1644](https://rasahq.atlassian.net/browse/ATO-1644)
[ATO-1644]: https://rasahq.atlassian.net/browse/ATO-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update docs about `rasa data validate flows` checks

---

rasa/shared/core/domain.py
rasa/shared/core/slot_mappings.py
rasa/shared/utils/schemas/domain.yml
tests/shared/core/test_domain.py
tests/shared/core/test_slot_mappings.py

- Implements [ATO-1625](https://rasahq.atlassian.net/browse/ATO-1625)
[ATO-1625]: https://rasahq.atlassian.net/browse/ATO-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make slot mappings optional and default to empty list

---

pyproject.toml
rasa/version.py

prepared release of version 3.8.0a12

---

CHANGELOG.mdx
changelog/12927.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.13

---

scripts/release.py

- adjusted release script to use `public` remote for releases < 3.7.0

adjusted release script to work with public remote

---

CHANGELOG.mdx
changelog/12948.bugfix.md
pyproject.toml
rasa/version.py

Prepare release 3.6.14

---

docs/docusaurus.config.js

⚠️ This needs to be released when the Studio docs are live
- Add link to Studio docs in navbar

add link to Studio docs

---

CHANGELOG.mdx
Makefile
changelog/12851.improvement.md
changelog/1493.improvement.md
pyproject.toml
rasa/version.py

prepared release of version 3.5.17

---

poetry.lock

- Fixes [ATO-1959](https://rasahq.atlassian.net/browse/ATO-1959)
[ATO-1959]: https://rasahq.atlassian.net/browse/ATO-1959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-1959] Fix Improper Certificate Validation 3.5.X

---

.github/workflows/continous-integration.yml
Makefile
changelog/12983.bugfix.md
changelog/712.misc.md
poetry.lock
pyproject.toml

- Fixes [ATO-1959](https://rasahq.atlassian.net/browse/ATO-1959)
[ATO-1959]: https://rasahq.atlassian.net/browse/ATO-1959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ATO-1959] Fix Improper Certificate Validation 3.6.X

---

docs/versioned_docs/version-3.x/changelog.mdx

Update changelog in 3.x

---

changelog/12998.bugfix.md

- Add changelog for the PR #12998 

add changelog for #12998

---

CHANGELOG.mdx
changelog/12983.bugfix.md
changelog/12998.bugfix.md
changelog/712.misc.md
pyproject.toml
rasa/version.py

- Release 3.6.16 that fixes #12998 

prepared release of version 3.6.16

---

CHANGELOG.mdx
changelog/13017.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.18

---

CHANGELOG.mdx
changelog/13019.bugfix.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.19

---

CHANGELOG.mdx
changelog/13030.misc.md
changelog/13031.misc.md
pyproject.toml
rasa/version.py

prepared release of version 3.6.20

---

.github/workflows/continous-integration.yml

- Bump actions/upload-artifact and actions/download-artifact to v4

[INFRA-1124] Update deprecated dependencies

---

docs/netlify.toml

Add redirects for SEO updates.
@m-vdb My last PR was messed up so started a new one. I removed the "enterprise" redirects (will move to rasa-x) and the "rasa-website" ones as well.

Add docs redirects
